Repository googleapis/google-cloud-php, pull requests merged in 2018-10, with the labels that each got.

#1150 Introduce bucket retention policy and locks
  Storage/src/Bucket.php
  Storage/src/Connection/ConnectionInterface.php
  Storage/src/Connection/Rest.php
  Storage/src/Connection/ServiceDefinition/storage-v1.json
  Storage/src/StorageClient.php
  Storage/tests/Snippet/BucketTest.php
  Storage/tests/Unit/BucketTest.php
  Storage/tests/Unit/Connection/RestTest.php
  tests/system/Storage/BucketLockRetentionPolicyTest.php
  tests/system/Storage/HoldObjectsTest.php
Labels: api: storage, cla: yes

#1325 Prepare v0.81.0
  Logging/VERSION
  Logging/src/LoggingClient.php
  Storage/VERSION
  Storage/src/StorageClient.php
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: cla: yes

#1326 Remove debug information from build
  dev/sh/build-docs
Labels: cla: yes

#1316 Fix handling of empty sets in Firestore updates
  Firestore/src/WriteBatch.php
  Firestore/tests/Conformance/proto/firestore-test-suite.binproto
  Firestore/tests/Unit/ConformanceTest.php
Labels: api: firestore, cla: yes

#1327 Remove unnecessary ternary expression
  BigQuery/src/ValueMapper.php
Labels: cla: yes

#1328 Use combined assignment operators when possible
  Core/src/Lock/FlockLock.php
  Core/src/Retry.php
  Datastore/src/Key.php
  Datastore/tests/Unit/DatastoreClientTest.php
  Datastore/tests/Unit/TransactionTest.php
  Spanner/tests/System/pcntl/AbortedErrorCausesRetry.php
  Spanner/tests/System/pcntl/ConcurrentTransactionsIncrementValueWithExecute.php
  Spanner/tests/System/pcntl/ConcurrentTransactionsIncrementValueWithRead.php
  Spanner/tests/System/pcntl/forked-process-test.php
Labels: cla: yes

#1329 Remove auxiliary variables when they are return right away
  Firestore/tests/System/QueryTest.php
  Firestore/tests/Unit/QueryTest.php
Labels: cla: yes

#1330 Remove unused variables passed to closures
  Core/tests/Unit/ExponentialBackoffTest.php
  Debugger/tests/System/app/web/app.php
  Spanner/tests/Unit/DatabaseTest.php
  Spanner/tests/Unit/OperationTest.php
Labels: cla: yes

#1322 Readrows Filter and system test
  Bigtable/src/DataClient.php
  Bigtable/tests/System/DataClientMutateRowsTest.php
  Bigtable/tests/System/DataClientReadRowsTest.php
  Bigtable/tests/System/DataClientTest.php
  Bigtable/tests/System/FilterTest.php
  Bigtable/tests/System/data/data.json
  Bigtable/tests/Unit/DataClientTest.php
  Bigtable/tests/Unit/Filter/Builder/QualifierFilterTest.php
  Bigtable/tests/Unit/FilterTest.php
Labels: api: bigtable, cla: yes

#1331 Use dedicated PHPUnit assertions
  BigQuery/tests/System/LoadDataAndQueryTest.php
  Datastore/tests/Unit/EntityMapperTest.php
  Debugger/tests/Unit/AgentTest.php
  Debugger/tests/Unit/VariableTableTest.php
  Storage/tests/System/ManageBucketsTest.php
  Storage/tests/System/ManageNotificationsTest.php
  Storage/tests/System/UploadObjectsTest.php
  Vision/tests/System/AnnotationsTest.php
  Vision/tests/Unit/ImageTest.php
  Vision/tests/Unit/VisionHelpersTraitTest.php
Labels: cla: yes

#1332 Provide test name in message for conformance test
  Bigtable/tests/Conformance/ReadRowsTest.php
Labels: cla: yes

#1309 Add support for DML and Partitioned DML
  Spanner/src/Connection/Grpc.php
  Spanner/src/Database.php
  Spanner/src/Operation.php
  Spanner/src/Result.php
  Spanner/src/Transaction.php
  Spanner/src/TransactionConfigurationTrait.php
  Spanner/src/TransactionalReadTrait.php
  Spanner/tests/OperationRefreshTrait.php
  Spanner/tests/ResultGeneratorTrait.php
  Spanner/tests/Snippet/ArrayTypeTest.php
  Spanner/tests/Snippet/Batch/BatchClientTest.php
  Spanner/tests/Snippet/Batch/BatchSnapshotTest.php
  Spanner/tests/Snippet/DatabaseTest.php
  Spanner/tests/Snippet/SnapshotTest.php
  Spanner/tests/Snippet/StructTypeTest.php
  Spanner/tests/Snippet/StructValueTest.php
  Spanner/tests/Snippet/TransactionTest.php
  Spanner/tests/Snippet/TransactionalReadMethodsTest.php
  Spanner/tests/System/PartitionedDmlTest.php
  Spanner/tests/System/SpannerTestCase.php
  Spanner/tests/System/WriteTest.php
  Spanner/tests/Unit/Batch/BatchClientTest.php
  Spanner/tests/Unit/Batch/BatchSnapshotTest.php
  Spanner/tests/Unit/Connection/GrpcTest.php
  Spanner/tests/Unit/Connection/IamDatabaseTest.php
  Spanner/tests/Unit/Connection/IamInstanceTest.php
  Spanner/tests/Unit/Connection/LongRunningConnectionTest.php
  Spanner/tests/Unit/DatabaseTest.php
  Spanner/tests/Unit/InstanceConfigurationTest.php
  Spanner/tests/Unit/InstanceTest.php
  Spanner/tests/Unit/SpannerClientTest.php
  Spanner/tests/Unit/TransactionTest.php
Labels: api: spanner, cla: yes

#1337 Prepare v0.82.0
  BigQuery/VERSION
  BigQuery/src/BigQueryClient.php
  Core/VERSION
  Datastore/VERSION
  Datastore/src/DatastoreClient.php
  Debugger/VERSION
  Debugger/src/DebuggerClient.php
  Firestore/VERSION
  Firestore/src/FirestoreClient.php
  Spanner/VERSION
  Spanner/src/SpannerClient.php
  Storage/VERSION
  Storage/src/StorageClient.php
  Vision/VERSION
  Vision/src/VisionClient.php
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: cla: yes

#1339 Adding kokoro config for windows
  .kokoro/presubmit/windows/common.cfg
  .kokoro/presubmit/windows/php56.cfg
  .kokoro/presubmit/windows/php70.cfg
  .kokoro/presubmit/windows/php71.cfg
  .kokoro/presubmit/windows/php72.cfg
  .kokoro/presubmit/windows/php73.cfg
  .kokoro/presubmit/windows/test.bat
Labels: cla: yes, testing, windows

#1353 Add Tasks V2beta3 library
  README.md
  Tasks/README.md
  Tasks/metadata/V2Beta3/Cloudtasks.php
  Tasks/metadata/V2Beta3/Queue.php
  Tasks/metadata/V2Beta3/Target.php
  Tasks/metadata/V2Beta3/Task.php
  Tasks/src/V2beta3/AppEngineHttpQueue.php
  Tasks/src/V2beta3/AppEngineHttpRequest.php
  Tasks/src/V2beta3/AppEngineRouting.php
  Tasks/src/V2beta3/Attempt.php
  Tasks/src/V2beta3/CloudTasksClient.php
  Tasks/src/V2beta3/CloudTasksGrpcClient.php
  Tasks/src/V2beta3/CreateQueueRequest.php
  Tasks/src/V2beta3/CreateTaskRequest.php
  Tasks/src/V2beta3/DeleteQueueRequest.php
  Tasks/src/V2beta3/DeleteTaskRequest.php
  Tasks/src/V2beta3/Gapic/CloudTasksGapicClient.php
  Tasks/src/V2beta3/GetQueueRequest.php
  Tasks/src/V2beta3/GetTaskRequest.php
  Tasks/src/V2beta3/HttpMethod.php
  Tasks/src/V2beta3/ListQueuesRequest.php
  Tasks/src/V2beta3/ListQueuesResponse.php
  Tasks/src/V2beta3/ListTasksRequest.php
  Tasks/src/V2beta3/ListTasksResponse.php
  Tasks/src/V2beta3/PauseQueueRequest.php
  Tasks/src/V2beta3/PurgeQueueRequest.php
  Tasks/src/V2beta3/Queue.php
  Tasks/src/V2beta3/Queue/State.php
  Tasks/src/V2beta3/Queue_State.php
  Tasks/src/V2beta3/README.md
  Tasks/src/V2beta3/RateLimits.php
  Tasks/src/V2beta3/ResumeQueueRequest.php
  Tasks/src/V2beta3/RetryConfig.php
  Tasks/src/V2beta3/RunTaskRequest.php
  Tasks/src/V2beta3/Task.php
  Tasks/src/V2beta3/Task/View.php
  Tasks/src/V2beta3/Task_View.php
  Tasks/src/V2beta3/UpdateQueueRequest.php
  Tasks/src/V2beta3/resources/cloud_tasks_client_config.json
  Tasks/src/V2beta3/resources/cloud_tasks_descriptor_config.php
  Tasks/src/V2beta3/resources/cloud_tasks_rest_client_config.php
  Tasks/synth.py
  Tasks/tests/System/V2beta3/TasksServiceSmokeTest.php
  Tasks/tests/Unit/V2beta3/CloudTasksClientTest.php
  docs/contents/cloud-tasks.json
Labels: cla: yes

#1356 Fix style in the code sample in the README
  README.md
  Tasks/README.md
Labels: cla: yes

#1355 Prepare v0.83.0
  Asset/VERSION
  Dialogflow/VERSION
  Dlp/VERSION
  Logging/VERSION
  Logging/src/LoggingClient.php
  Monitoring/VERSION
  PubSub/VERSION
  PubSub/src/PubSubClient.php
  Redis/VERSION
  Tasks/VERSION
  TextToSpeech/VERSION
  Trace/VERSION
  Trace/src/TraceClient.php
  VideoIntelligence/VERSION
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: cla: yes

#1334 Bigtable: Read modify write row model
  Bigtable/src/DataClient.php
  Bigtable/src/DataUtil.php
  Bigtable/src/ReadModifyWriteRowRules.php
  Bigtable/tests/Snippet/DataClientTest.php
  Bigtable/tests/System/DataClientReadModifyWriteRowTest.php
  Bigtable/tests/Unit/DataClientTest.php
  Bigtable/tests/Unit/DataUtilTest.php
  Bigtable/tests/Unit/ReadModifyWriteRowRulesTest.php
Labels: api: bigtable, cla: yes, kokoro:force-run

#1357 Remove appveyor artifacts
  appveyor.yml
  dev/appveyor-grpc.ps1
Labels: cla: yes

#1338 Bigtable: Sample row keys api
  Bigtable/src/DataClient.php
  Bigtable/tests/Snippet/DataClientTest.php
  Bigtable/tests/System/DataClientSampleRowKeysTest.php
  Bigtable/tests/Unit/DataClientTest.php
Labels: api: bigtable, cla: yes, kokoro:force-run

#1360 Storage system test fixes
  Storage/tests/System/BucketLockRetentionPolicyTest.php
  Storage/tests/System/HoldObjectsTest.php
  Storage/tests/System/ManageBucketsTest.php
Labels: api: storage, cla: yes

#1361 Translate system test fixes
  Translate/tests/System/TranslateTest.php
Labels: api: translation, cla: yes

#1333 Bigtable: checkAndMutateRow api implementation
  Bigtable/src/DataClient.php
  Bigtable/src/Mutations.php
  Bigtable/src/RowMutation.php
  Bigtable/tests/Snippet/DataClientTest.php
  Bigtable/tests/System/DataClientCheckAndMutateRowTest.php
  Bigtable/tests/Unit/DataClientTest.php
  Bigtable/tests/Unit/MutationsTest.php
  Bigtable/tests/Unit/RowMutationTest.php
Labels: api: bigtable, cla: yes, kokoro:force-run

#1366 Update firestore conformance tests
  Firestore/tests/Conformance/proto/firestore-test-suite.binproto
  Firestore/tests/Unit/ConformanceTest.php
Labels: api: firestore, cla: yes

#1359 Add kokoro configs for continuous build
  .kokoro/continuous/php72.cfg
  .kokoro/continuous/run-tests.sh
  .kokoro/trampoline.sh
  .travis.yml
  Asset/tests/System/V1beta1/AssetServiceSmokeTest.php
  CONTRIBUTING.md
  Core/src/Batch/BatchJob.php
  Core/src/Batch/Retry.php
  Core/src/Testing/System/DeletionQueue.php
  Core/src/Testing/System/SystemTestCase.php
  Core/tests/Unit/Batch/RetryTest.php
  README.md
  Redis/tests/System/V1/CloudRedisClientTest.php
  Redis/tests/System/V1beta1/CloudRedisClientTest.php
  Spanner/tests/System/bootstrap.php
  Storage/tests/System/RequesterPaysTest.php
  Storage/tests/System/UploadObjectsTest.php
  Storage/tests/System/bootstrap.php
  Tasks/tests/System/V2beta2/TasksServiceSmokeTest.php
  Tasks/tests/System/V2beta3/TasksServiceSmokeTest.php
  tests/System/ServiceWhitelist/WhitelistTest.php
Labels: cla: yes, testing

#1368 Presubmit docgen
  .kokoro/presubmit/run-tests.sh
Labels: cla: yes

#1369 Only test with hhvm on travis
  .travis.yml
Labels: cla: yes

#1367 Bigtable: refactor mutation model
  Bigtable/src/DataClient.php
  Bigtable/src/RowMutation.php
  Bigtable/tests/System/DataClientMutateRowsTest.php
  Bigtable/tests/System/DataClientReadRowsTest.php
  Bigtable/tests/System/DataClientTest.php
  Bigtable/tests/System/FilterTest.php
  Bigtable/tests/Unit/DataClientTest.php
  Bigtable/tests/Unit/RowMutationTest.php
Labels: api: bigtable, cla: yes

#1370 Run codecov.sh for php72
  .kokoro/presubmit/php72.cfg
  .kokoro/presubmit/run-tests.sh
  codecov.yml
Labels: cla: yes, testing

#1376 Exit when phpunit fails
  .kokoro/presubmit/windows/test.bat
Labels: cla: yes

#1375 Fix bigquery readme
  BigQuery/README.md
  README.md
Labels: cla: yes

#1377 Fix Firestore null value handling
  Firestore/src/ValueMapper.php
  Firestore/tests/Unit/ValueMapperTest.php
Labels: cla: yes

#1378 Prepare v0.84.0
  Asset/VERSION
  BigQuery/VERSION
  BigQuery/src/BigQueryClient.php
  Core/VERSION
  Dlp/VERSION
  Firestore/VERSION
  Firestore/src/FirestoreClient.php
  Redis/VERSION
  Spanner/VERSION
  Spanner/src/SpannerClient.php
  Storage/VERSION
  Storage/src/StorageClient.php
  Tasks/VERSION
  Translate/VERSION
  Translate/src/TranslateClient.php
  VideoIntelligence/VERSION
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: cla: yes

#1379 Fix Firestore array offset exists check
  Firestore/src/DocumentSnapshot.php
  Firestore/tests/System/ValueMapperTest.php
Labels: api: firestore, cla: yes

#1381 Prepare v0.84.1
  Firestore/VERSION
  Firestore/src/FirestoreClient.php
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: cla: yes

#1382 Bigtable: mutateRow api
  Bigtable/src/DataClient.php
  Bigtable/src/Mutations.php
  Bigtable/tests/Snippet/DataClientTest.php
  Bigtable/tests/System/DataClientMutateRowsTest.php
  Bigtable/tests/Unit/DataClientTest.php
Labels: cla: yes
