Repository googleapis/google-cloud-php, pull requests merged in 2018-03, with the labels that each got.

#919 Install gRPC on Windows CI when available
  appveyor.yml
  dev/appveyor-grpc.ps1
Labels: cla: yes

#922 Update Core with changes to support restructure
  src/Core/Testing/Snippet/Coverage/ExcludeFilter.php
  src/Core/Testing/Snippet/Coverage/Scanner.php
  src/Core/Testing/Snippet/Fixtures.php
  src/Core/Testing/Snippet/Parser/Parser.php
  src/Core/Testing/Snippet/keyfile-stub.json
  tests/snippets/Vision/Annotation/FaceTest.php
Labels: cla: yes

#927 Update speech config
  src/Speech/V1/resources/speech_client_config.json
Labels: cla: yes

#935 Add dlp v2
  composer.json
  docs/contents/cloud-dlp.json
  src/Bigtable/composer.json
  src/Container/composer.json
  src/Dataproc/composer.json
  src/Dlp/V2/DlpServiceClient.php
  src/Dlp/V2/Gapic/DlpServiceGapicClient.php
  src/Dlp/V2/README.md
  src/Dlp/V2/resources/dlp_service_client_config.json
  src/Dlp/V2/resources/dlp_service_descriptor_config.php
  src/Dlp/V2/resources/dlp_service_rest_client_config.php
  src/Dlp/composer.json
  src/ErrorReporting/composer.json
  src/Firestore/composer.json
  src/Language/composer.json
  src/Logging/composer.json
  src/Monitoring/composer.json
  src/OsLogin/composer.json
  src/PubSub/composer.json
  src/Spanner/composer.json
  src/Speech/composer.json
  src/Trace/composer.json
  src/VideoIntelligence/composer.json
  src/Vision/composer.json
Labels: cla: yes

#936 Prepare v0.57.0
  composer.json
  docs/manifest.json
  src/Bigtable/VERSION
  src/Container/VERSION
  src/Core/VERSION
  src/Dataproc/VERSION
  src/Dlp/VERSION
  src/ErrorReporting/VERSION
  src/Firestore/FirestoreClient.php
  src/Firestore/VERSION
  src/Language/LanguageClient.php
  src/Language/VERSION
  src/Logging/LoggingClient.php
  src/Logging/VERSION
  src/Monitoring/VERSION
  src/OsLogin/VERSION
  src/PubSub/PubSubClient.php
  src/PubSub/VERSION
  src/Spanner/SpannerClient.php
  src/Spanner/VERSION
  src/Speech/SpeechClient.php
  src/Speech/VERSION
  src/Trace/TraceClient.php
  src/Trace/VERSION
  src/VideoIntelligence/VERSION
  src/Vision/VERSION
  src/Vision/VisionClient.php
  tests/unit/Debugger/AgentTest.php
Labels: cla: yes

#941 Prepare v0.57.1
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: cla: yes

#945 Update paths for CODEOWNERS files
  docs/CODEOWNERS
Labels: cla: yes

#955 Add a static function for the location of the prepend file
  ErrorReporting/src/Bootstrap.php
  ErrorReporting/tests/Unit/BootstrapTest.php
Labels: cla: yes

#953 Fix composer integration test
  tests/Component/TestComposerInstall.php
Labels: cla: yes

#947 Add support for Spanner Commit Timestamps
  Spanner/src/CommitTimestamp.php
  Spanner/src/SpannerClient.php
  Spanner/tests/Snippet/CommitTimestampTest.php
  Spanner/tests/Snippet/SpannerClientTest.php
  Spanner/tests/System/WriteTest.php
  Spanner/tests/Unit/CommitTimestampTest.php
  Spanner/tests/Unit/SpannerClientTest.php
Labels: api: spanner, cla: yes

#952 Add big query data transfer
  BigQueryDataTransfer/.github/pull_request_template.md
  BigQueryDataTransfer/CONTRIBUTING.md
  BigQueryDataTransfer/LICENSE
  BigQueryDataTransfer/README.md
  BigQueryDataTransfer/VERSION
  BigQueryDataTransfer/composer.json
  BigQueryDataTransfer/phpunit-snippets.xml.dist
  BigQueryDataTransfer/phpunit-system.xml.dist
  BigQueryDataTransfer/phpunit.xml.dist
  BigQueryDataTransfer/src/V1/DataTransferServiceClient.php
  BigQueryDataTransfer/src/V1/Gapic/DataTransferServiceGapicClient.php
  BigQueryDataTransfer/src/V1/README.md
  BigQueryDataTransfer/src/V1/resources/data_transfer_service_client_config.json
  BigQueryDataTransfer/src/V1/resources/data_transfer_service_descriptor_config.php
  BigQueryDataTransfer/src/V1/resources/data_transfer_service_rest_client_config.php
  README.md
  composer.json
  docs/contents/cloud-bigquerydatatransfer.json
  docs/contents/google-cloud.json
  docs/manifest.json
Labels: cla: yes

#951 Add links to subpackages from README
  README.md
Labels: cla: yes

#959 Look for correct autoloader paths in daemons
  Core/bin/google-cloud-batch
  Debugger/bin/google-cloud-debugger
Labels: api: core, api: debugger, cla: yes

#961 Update debugger system test for new structure
  Debugger/tests/System/BasicTest.php
Labels: api: debugger, cla: yes

#960 Prepare v0.58.0
  BigQuery/VERSION
  BigQuery/src/BigQueryClient.php
  BigQueryDataTransfer/VERSION
  Bigtable/VERSION
  Container/VERSION
  Core/VERSION
  Dataproc/VERSION
  Datastore/VERSION
  Datastore/src/DatastoreClient.php
  Debugger/VERSION
  Debugger/src/DebuggerClient.php
  Dlp/VERSION
  ErrorReporting/VERSION
  Firestore/VERSION
  Firestore/src/FirestoreClient.php
  Language/VERSION
  Language/src/LanguageClient.php
  Logging/VERSION
  Logging/src/LoggingClient.php
  Monitoring/VERSION
  OsLogin/VERSION
  PubSub/VERSION
  PubSub/src/PubSubClient.php
  Spanner/VERSION
  Spanner/src/SpannerClient.php
  Speech/VERSION
  Speech/src/SpeechClient.php
  Storage/VERSION
  Storage/src/StorageClient.php
  Trace/VERSION
  Trace/src/TraceClient.php
  Translate/VERSION
  Translate/src/TranslateClient.php
  VideoIntelligence/VERSION
  Vision/VERSION
  Vision/src/VisionClient.php
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: cla: yes

#962 Fix BQDT composer file for restructure.
  BigQueryDataTransfer/composer.json
Labels: cla: yes

#965 Fix prepend include path
  ErrorReporting/src/prepend.php
Labels: cla: yes

#966 Fix docs for restructure
  dev/src/DocGenerator/DocGenerator.php
  docs/manifest.json
Labels: cla: yes

#964 Prepare v0.58.1
  BigQueryDataTransfer/VERSION
  ErrorReporting/VERSION
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: cla: yes

#967 Check that umbrella version has been bumped
  composer.json
  dev/src/ComponentIntegration/Command/ComponentIntegration.php
  dev/src/GetComponentsTrait.php
Labels: cla: yes

#969 Move Google Bigtable back to alpha
  README.md
Labels: api: bigtable, cla: yes

#956 Add support \DateTimeInterface
  .gitignore
  Firestore/src/ValueMapper.php
  Firestore/tests/Unit/ValueMapperTest.php
Labels: cla: yes
