Repository googleapis/google-cloud-php, pull requests merged in 2018-11, with the labels that each got.

#1386 Fix container system test and update protobuf metadata
  Container/metadata/V1/ClusterService.php
  Container/synth.py
  Container/tests/System/ClusterManagerClientTest.php
Labels: cla: yes

#1387 Rename DataClient -> Table and add BigtableClient
  Bigtable/src/BigtableClient.php
  Bigtable/src/ChunkFormatter.php
  Bigtable/src/Filter.php
  Bigtable/src/ReadModifyWriteRowRules.php
  Bigtable/src/Table.php
  Bigtable/tests/Snippet/BigtableClientTest.php
  Bigtable/tests/Snippet/ChunkFormatterTest.php
  Bigtable/tests/Snippet/FilterTest.php
  Bigtable/tests/Snippet/TableTest.php
  Bigtable/tests/System/BigtableTestCase.php
  Bigtable/tests/System/CheckAndMutateRowTest.php
  Bigtable/tests/System/FilterTest.php
  Bigtable/tests/System/MutateRowsTest.php
  Bigtable/tests/System/ReadModifyWriteRowTest.php
  Bigtable/tests/System/ReadRowsTest.php
  Bigtable/tests/System/SampleRowKeysTest.php
  Bigtable/tests/Unit/BigtableClientTest.php
  Bigtable/tests/Unit/TableTest.php
Labels: api: bigtable, cla: yes

#1388 Prep Bigtable handwritten client for release
  Bigtable/README.md
  README.md
  docs/contents/cloud-bigtable.json
Labels: api: bigtable, cla: yes

#1391 Update readme/projectID detection
  Bigtable/README.md
  Bigtable/src/BigtableClient.php
Labels: api: bigtable, cla: yes

#1393 Add 64 or 32 bit test
  Bigtable/src/DataUtil.php
  Bigtable/tests/Unit/DataUtilTest.php
Labels: api: bigtable, cla: yes

#1394 Prepare v0.85.0
  Bigtable/VERSION
  Bigtable/composer.json
  Bigtable/src/BigtableClient.php
  Container/VERSION
  Debugger/VERSION
  Debugger/src/DebuggerClient.php
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: cla: yes

#1404 Update Container config path
  Container/synth.py
Labels: cla: yes

#1405 Use pull request title for autosynth PRs
  dev/src/ReleaseBuilder/ReleaseBuilder.php
Labels: cla: yes

#1408 Comment update, add several helper methods
  Container/metadata/V1/ClusterService.php
  Container/src/V1/CancelOperationRequest.php
  Container/src/V1/Cluster.php
  Container/src/V1/Cluster/Status.php
  Container/src/V1/ClusterManagerGrpcClient.php
  Container/src/V1/ClusterUpdate.php
  Container/src/V1/CompleteIPRotationRequest.php
  Container/src/V1/CreateClusterRequest.php
  Container/src/V1/CreateNodePoolRequest.php
  Container/src/V1/DeleteClusterRequest.php
  Container/src/V1/DeleteNodePoolRequest.php
  Container/src/V1/Gapic/ClusterManagerGapicClient.php
  Container/src/V1/GetClusterRequest.php
  Container/src/V1/GetNodePoolRequest.php
  Container/src/V1/GetOperationRequest.php
  Container/src/V1/GetServerConfigRequest.php
  Container/src/V1/IPAllocationPolicy.php
  Container/src/V1/ListClustersRequest.php
  Container/src/V1/ListNodePoolsRequest.php
  Container/src/V1/ListOperationsRequest.php
  Container/src/V1/MasterAuth.php
  Container/src/V1/MasterAuthorizedNetworksConfig.php
  Container/src/V1/NodeConfig.php
  Container/src/V1/Operation.php
  Container/src/V1/PrivateClusterConfig.php
  Container/src/V1/RollbackNodePoolUpgradeRequest.php
  Container/src/V1/ServerConfig.php
  Container/src/V1/SetAddonsConfigRequest.php
  Container/src/V1/SetLabelsRequest.php
  Container/src/V1/SetLegacyAbacRequest.php
  Container/src/V1/SetLocationsRequest.php
  Container/src/V1/SetLoggingServiceRequest.php
  Container/src/V1/SetMaintenancePolicyRequest.php
  Container/src/V1/SetMasterAuthRequest.php
  Container/src/V1/SetMonitoringServiceRequest.php
  Container/src/V1/SetNetworkPolicyRequest.php
  Container/src/V1/SetNodePoolAutoscalingRequest.php
  Container/src/V1/SetNodePoolManagementRequest.php
  Container/src/V1/SetNodePoolSizeRequest.php
  Container/src/V1/StartIPRotationRequest.php
  Container/src/V1/UpdateClusterRequest.php
  Container/src/V1/UpdateMasterRequest.php
  Container/src/V1/UpdateNodePoolRequest.php
  Container/src/V1/resources/cluster_manager_client_config.json
  Container/src/V1/resources/cluster_manager_rest_client_config.php
  Container/tests/Unit/V1/ClusterManagerClientTest.php
Labels: cla: yes

#1414 Add a helper for product search
  Vision/src/V1/ImageAnnotatorClient.php
  Vision/tests/Snippet/V1/ImageAnnotatorClientTest.php
  Vision/tests/Unit/V1/ImageAnnotatorClientExtensionTest.php
Labels: api: vision, cla: yes

#1406 Update GitHub issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/support_request.md
  CONTRIBUTING.md
Labels: cla: yes

#1417 Add erusev/parsedown to require-dev.
  .kokoro/continuous/run-tests.sh
  Bigtable/composer.json
Labels: cla: yes

#1419 storage: use correct path with signed url cname
  Storage/src/StorageObject.php
  Storage/tests/Unit/StorageObjectTest.php
Labels: cla: yes

#1421 Revert "[Breaking Change] Updated documentation and modified InternalChecker message parameters."
  Monitoring/metadata/V3/NotificationService.php
  Monitoring/metadata/V3/Uptime.php
  Monitoring/src/V3/AlertPolicyServiceGrpcClient.php
  Monitoring/src/V3/Gapic/NotificationChannelServiceGapicClient.php
  Monitoring/src/V3/GroupServiceGrpcClient.php
  Monitoring/src/V3/InternalChecker.php
  Monitoring/src/V3/MetricServiceGrpcClient.php
  Monitoring/src/V3/NotificationChannelServiceGrpcClient.php
  Monitoring/src/V3/ServiceTier.php
  Monitoring/src/V3/UptimeCheckConfig.php
  Monitoring/src/V3/UptimeCheckConfig/ContentMatcher.php
  Monitoring/src/V3/UptimeCheckServiceGrpcClient.php
Labels: cla: yes

#1413 Prepare v0.86.0
  Bigtable/VERSION
  Bigtable/src/BigtableClient.php
  Container/VERSION
  Core/VERSION
  Debugger/VERSION
  Debugger/src/DebuggerClient.php
  Dialogflow/VERSION
  Monitoring/VERSION
  PubSub/VERSION
  PubSub/src/PubSubClient.php
  Speech/VERSION
  Speech/src/SpeechClient.php
  Storage/VERSION
  Storage/src/StorageClient.php
  Tasks/VERSION
  Trace/VERSION
  Trace/src/TraceClient.php
  VideoIntelligence/VERSION
  Vision/VERSION
  Vision/src/VisionClient.php
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: cla: yes

#1424 Update dataproc REST config.
  Dataproc/src/V1/resources/cluster_controller_rest_client_config.php
  Dataproc/src/V1/resources/job_controller_rest_client_config.php
Labels: cla: yes

#1425 Update Firestore REST config.
  Firestore/src/V1beta1/resources/firestore_rest_client_config.php
Labels: cla: yes

#1426 [Breaking Change] Renamed `imageName` to `referenceImageName` in Product Search generated client.
  Vision/src/V1/Gapic/ProductSearchGapicClient.php
  Vision/tests/Unit/V1/ProductSearchClientTest.php
Labels: cla: yes

#1428 Avoid rate limit error in the system test
  Storage/tests/System/ManageNotificationsTest.php
Labels: api: storage, cla: yes, testing

#1452 Add Vision Generation Metadata
  Vision/synth.metadata
Labels: cla: yes

#1451 Add VideoIntelligence Generation Metadata
  VideoIntelligence/synth.metadata
Labels: cla: yes

#1450 Add Trace Generation Metadata
  Trace/synth.metadata
Labels: cla: yes

#1449 Add Text-To-Speech Generation Metadata
  TextToSpeech/synth.metadata
Labels: cla: yes

#1448 Add Tasks Generation Metadata
  Tasks/synth.metadata
Labels: cla: yes

#1447 Add Speech Generation Metadata
  Speech/synth.metadata
Labels: cla: yes

#1446 Add Spanner Generation Metadata
  Spanner/synth.metadata
Labels: cla: yes

#1445 Add Redis Generation Metadata
  Redis/synth.metadata
Labels: cla: yes

#1444 Add PubSub Generation Metadata
  PubSub/synth.metadata
Labels: cla: yes

#1443 Add OsLogin Generation Metadata
  OsLogin/synth.metadata
Labels: cla: yes

#1442 Add Logging Generation Metadata
  Logging/synth.metadata
Labels: cla: yes

#1441 Add Language Generation Metadata
  Language/synth.metadata
Labels: cla: yes

#1440 Add KMS Generation Metadata
  Kms/synth.metadata
Labels: cla: yes

#1439 Add IOT Generation Metadata
  Iot/synth.metadata
Labels: cla: yes

#1438 Add Firestore Generation Metadata
  Firestore/synth.metadata
Labels: cla: yes

#1437 Add Error Reporting Generation Metadata
  ErrorReporting/synth.metadata
Labels: cla: yes

#1436 Add DLP Generation Metadata
  Dlp/synth.metadata
Labels: cla: yes

#1435 Add Dialogflow Generation Metadata
  Dialogflow/synth.metadata
Labels: cla: yes

#1434 Add Debugger Generation Metadata
  Debugger/synth.metadata
Labels: cla: yes

#1433 Add Dataproc Generation Metadata
  Dataproc/synth.metadata
Labels: cla: yes

#1432 Add Bigtable Generation Metadata
  Bigtable/synth.metadata
Labels: cla: yes

#1431 Add BigQuery Data Transfer Generation Metadata
  BigQueryDataTransfer/synth.metadata
Labels: cla: yes

#1430 Add Asset Generation Metadata
  Asset/synth.metadata
Labels: cla: yes

#1453 Handle malformed PR/commit messages
  dev/src/ReleaseBuilder/ReleaseBuilder.php
Labels: cla: yes

#1477 Add 3 new methods to the API surface.
  Iot/metadata/V1/DeviceManager.php
  Iot/metadata/V1/Resources.php
  Iot/src/V1/BindDeviceToGatewayRequest.php
  Iot/src/V1/BindDeviceToGatewayResponse.php
  Iot/src/V1/CreateDeviceRequest.php
  Iot/src/V1/Device.php
  Iot/src/V1/DeviceManagerGrpcClient.php
  Iot/src/V1/DeviceRegistry.php
  Iot/src/V1/Gapic/DeviceManagerGapicClient.php
  Iot/src/V1/GatewayAuthMethod.php
  Iot/src/V1/GatewayConfig.php
  Iot/src/V1/GatewayListOptions.php
  Iot/src/V1/GatewayType.php
  Iot/src/V1/ListDeviceRegistriesRequest.php
  Iot/src/V1/ListDevicesRequest.php
  Iot/src/V1/LogLevel.php
  Iot/src/V1/SendCommandToDeviceRequest.php
  Iot/src/V1/SendCommandToDeviceResponse.php
  Iot/src/V1/UnbindDeviceFromGatewayRequest.php
  Iot/src/V1/UnbindDeviceFromGatewayResponse.php
  Iot/src/V1/UpdateDeviceRequest.php
  Iot/src/V1/resources/device_manager_client_config.json
  Iot/src/V1/resources/device_manager_rest_client_config.php
  Iot/tests/Unit/V1/DeviceManagerClientTest.php
Labels: api: cloudiot, cla: yes

#1479 Documentation updates.
  Vision/metadata/V1/ImageAnnotator.php
  Vision/src/V1/Block.php
  Vision/src/V1/Gapic/ProductSearchGapicClient.php
  Vision/src/V1/Paragraph.php
  Vision/src/V1/ProductSearchGrpcClient.php
  Vision/src/V1/Word.php
Labels: cla: yes

#1478 Update Spanner generated client streaming configuration
  Spanner/src/V1/resources/spanner_client_config.json
Labels: cla: yes

#1502 Deprecate resource identity fields, add name field.
  Container/metadata/V1/ClusterService.php
  Container/src/V1/CancelOperationRequest.php
  Container/src/V1/Cluster.php
  Container/src/V1/Cluster/Status.php
  Container/src/V1/ClusterManagerGrpcClient.php
  Container/src/V1/ClusterUpdate.php
  Container/src/V1/CompleteIPRotationRequest.php
  Container/src/V1/CreateClusterRequest.php
  Container/src/V1/CreateNodePoolRequest.php
  Container/src/V1/DeleteClusterRequest.php
  Container/src/V1/DeleteNodePoolRequest.php
  Container/src/V1/Gapic/ClusterManagerGapicClient.php
  Container/src/V1/GetClusterRequest.php
  Container/src/V1/GetNodePoolRequest.php
  Container/src/V1/GetOperationRequest.php
  Container/src/V1/GetServerConfigRequest.php
  Container/src/V1/IPAllocationPolicy.php
  Container/src/V1/ListClustersRequest.php
  Container/src/V1/ListNodePoolsRequest.php
  Container/src/V1/ListOperationsRequest.php
  Container/src/V1/MasterAuth.php
  Container/src/V1/MasterAuthorizedNetworksConfig.php
  Container/src/V1/NodeConfig.php
  Container/src/V1/Operation.php
  Container/src/V1/PrivateClusterConfig.php
  Container/src/V1/RollbackNodePoolUpgradeRequest.php
  Container/src/V1/ServerConfig.php
  Container/src/V1/SetAddonsConfigRequest.php
  Container/src/V1/SetLabelsRequest.php
  Container/src/V1/SetLegacyAbacRequest.php
  Container/src/V1/SetLocationsRequest.php
  Container/src/V1/SetLoggingServiceRequest.php
  Container/src/V1/SetMaintenancePolicyRequest.php
  Container/src/V1/SetMasterAuthRequest.php
  Container/src/V1/SetMonitoringServiceRequest.php
  Container/src/V1/SetNetworkPolicyRequest.php
  Container/src/V1/SetNodePoolAutoscalingRequest.php
  Container/src/V1/SetNodePoolManagementRequest.php
  Container/src/V1/SetNodePoolSizeRequest.php
  Container/src/V1/StartIPRotationRequest.php
  Container/src/V1/UpdateClusterRequest.php
  Container/src/V1/UpdateMasterRequest.php
  Container/src/V1/UpdateNodePoolRequest.php
  Container/src/V1/resources/cluster_manager_client_config.json
  Container/src/V1/resources/cluster_manager_rest_client_config.php
  Container/tests/Unit/V1/ClusterManagerClientTest.php
Labels: cla: yes

#1506 Prepare v0.87.0
  Asset/VERSION
  BigQueryDataTransfer/VERSION
  Bigtable/VERSION
  Bigtable/src/BigtableClient.php
  Container/VERSION
  Dataproc/VERSION
  Debugger/VERSION
  Debugger/src/DebuggerClient.php
  Dialogflow/VERSION
  Dlp/VERSION
  ErrorReporting/VERSION
  Firestore/VERSION
  Firestore/src/FirestoreClient.php
  Iot/VERSION
  Kms/VERSION
  Language/VERSION
  Language/src/LanguageClient.php
  Logging/VERSION
  Logging/src/LoggingClient.php
  OsLogin/VERSION
  PubSub/VERSION
  PubSub/src/PubSubClient.php
  Redis/VERSION
  Spanner/VERSION
  Spanner/src/SpannerClient.php
  Speech/VERSION
  Speech/src/SpeechClient.php
  Storage/VERSION
  Storage/src/StorageClient.php
  Tasks/VERSION
  TextToSpeech/VERSION
  Trace/VERSION
  Trace/src/TraceClient.php
  VideoIntelligence/VERSION
  Vision/VERSION
  Vision/src/VisionClient.php
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: cla: yes

#1507 Update Dataproc retry and timeout configuration.
  Dataproc/src/V1/resources/cluster_controller_client_config.json
  Dataproc/src/V1/resources/cluster_controller_descriptor_config.php
  Dataproc/src/V1/resources/job_controller_client_config.json
  Dataproc/src/V1/resources/workflow_template_service_client_config.json
Labels: cla: yes
