Repository googleapis/google-cloud-php, pull requests merged in 2018-04, with the labels that each got.

#977 Revert "Add iot"
  BigQueryDataTransfer/composer.json
  Bigtable/composer.json
  Container/composer.json
  Core/composer.json
  Dataproc/composer.json
  Dlp/composer.json
  ErrorReporting/composer.json
  Firestore/composer.json
  Iot/.github/pull_request_template.md
  Iot/CONTRIBUTING.md
  Iot/LICENSE
  Iot/README.md
  Iot/VERSION
  Iot/composer.json
  Iot/phpunit-snippets.xml.dist
  Iot/phpunit-system.xml.dist
  Iot/phpunit.xml.dist
  Iot/src/V1/DeviceManagerClient.php
  Iot/src/V1/Gapic/DeviceManagerGapicClient.php
  Iot/src/V1/README.md
  Iot/src/V1/resources/device_manager_client_config.json
  Iot/src/V1/resources/device_manager_descriptor_config.php
  Iot/src/V1/resources/device_manager_rest_client_config.php
  Language/composer.json
  Logging/composer.json
  Monitoring/composer.json
  OsLogin/composer.json
  PubSub/composer.json
  Spanner/composer.json
  Speech/composer.json
  Trace/composer.json
  VideoIntelligence/composer.json
  Vision/composer.json
  composer.json
  docs/contents/cloud-iot.json
  docs/contents/google-cloud.json
  docs/manifest.json
Labels: cla: yes

#978 Bump GAX to ^.31
  BigQueryDataTransfer/composer.json
  Bigtable/composer.json
  Container/composer.json
  Core/composer.json
  Dataproc/composer.json
  Dlp/composer.json
  ErrorReporting/composer.json
  Firestore/composer.json
  Language/composer.json
  Logging/composer.json
  Monitoring/composer.json
  OsLogin/composer.json
  PubSub/composer.json
  Spanner/composer.json
  Speech/composer.json
  Trace/composer.json
  VideoIntelligence/composer.json
  Vision/composer.json
  composer.json
Labels: cla: yes

#974 Serialize empty objects in arrays as entities
  Datastore/src/EntityMapper.php
  Datastore/tests/System/SaveAndModifyTest.php
  Datastore/tests/Unit/EntityMapperTest.php
Labels: cla: yes

#971 Introduce BigQuery Regionalization Support
  BigQuery/src/BigQueryClient.php
  BigQuery/src/Connection/ServiceDefinition/bigquery-v2.json
  BigQuery/src/CopyJobConfiguration.php
  BigQuery/src/Dataset.php
  BigQuery/src/ExtractJobConfiguration.php
  BigQuery/src/Job.php
  BigQuery/src/JobConfigurationTrait.php
  BigQuery/src/LoadJobConfiguration.php
  BigQuery/src/QueryJobConfiguration.php
  BigQuery/src/QueryResults.php
  BigQuery/src/Table.php
  BigQuery/tests/Snippet/BigQueryClientTest.php
  BigQuery/tests/Snippet/CopyJobConfigurationTest.php
  BigQuery/tests/Snippet/ExtractJobConfigurationTest.php
  BigQuery/tests/Snippet/LoadJobConfigurationTest.php
  BigQuery/tests/Snippet/QueryJobConfigurationTest.php
  BigQuery/tests/System/BigQueryTestCase.php
  BigQuery/tests/System/RegionalizationTest.php
  BigQuery/tests/Unit/BigQueryClientTest.php
  BigQuery/tests/Unit/CopyJobConfigurationTest.php
  BigQuery/tests/Unit/ExtractJobConfigurationTest.php
  BigQuery/tests/Unit/JobConfigurationTraitTest.php
  BigQuery/tests/Unit/JobTest.php
  BigQuery/tests/Unit/LoadJobConfigurationTest.php
  BigQuery/tests/Unit/QueryJobConfigurationTest.php
  Core/src/ServiceBuilder.php
  phpunit-snippets.xml.dist
Labels: api: bigquery, cla: yes

#976 Update CONTRIBUTING
  .travis.yml
  AUTHENTICATION.md
  CONTRIBUTING.md
  composer.json
  dev/sh/style
  dev/sh/tests
Labels: cla: yes

#888 Add documents() method to Firestore Transaction
  Firestore/src/FirestoreClient.php
  Firestore/src/PathTrait.php
  Firestore/src/SnapshotTrait.php
  Firestore/src/Transaction.php
  Firestore/tests/Snippet/TransactionTest.php
  Firestore/tests/System/GetAllDocumentsTest.php
  Firestore/tests/Unit/FirestoreClientTest.php
  Firestore/tests/Unit/TransactionTest.php
Labels: api: firestore, cla: yes

#979 Fix links to API docs in READMEs
  BigQueryDataTransfer/src/V1/README.md
  Container/README.md
  Container/src/V1/README.md
  Dataproc/README.md
  Dataproc/src/V1/README.md
  OsLogin/README.md
  OsLogin/src/V1beta/README.md
  VideoIntelligence/README.md
  dev/src/AddComponent/Readmes.php
  dev/src/AddComponent/templates/template-README.md.txt
Labels: cla: yes

#987 Remove bqdt from suggests, as it is now included in the package
  composer.json
Labels: cla: yes

#944 Debugger: Agent no longer needs to clear opcache.
  Debugger/src/Agent.php
Labels: cla: yes

#946 Debugger: De-dup arrays and string in VariableTable
  Debugger/src/Breakpoint.php
  Debugger/src/VariableTable.php
  Debugger/tests/Unit/VariableTableTest.php
Labels: cla: yes

#988 Prepare v0.59.0
  BigQuery/VERSION
  BigQuery/src/BigQueryClient.php
  BigQueryDataTransfer/VERSION
  Bigtable/VERSION
  Container/VERSION
  Core/VERSION
  Dataproc/VERSION
  Datastore/VERSION
  Datastore/src/DatastoreClient.php
  Debugger/VERSION
  Debugger/src/DebuggerClient.php
  Dlp/VERSION
  ErrorReporting/VERSION
  Firestore/VERSION
  Firestore/src/FirestoreClient.php
  Iot/VERSION
  Language/VERSION
  Language/src/LanguageClient.php
  Logging/VERSION
  Logging/src/LoggingClient.php
  Monitoring/VERSION
  OsLogin/VERSION
  PubSub/VERSION
  PubSub/src/PubSubClient.php
  Spanner/VERSION
  Spanner/src/SpannerClient.php
  Speech/VERSION
  Speech/src/SpeechClient.php
  Trace/VERSION
  Trace/src/TraceClient.php
  VideoIntelligence/VERSION
  Vision/VERSION
  Vision/src/VisionClient.php
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: cla: yes

#994 Remove unused proto class prophesy
  Spanner/tests/Unit/Connection/GrpcTest.php
Labels: api: spanner, cla: yes

#993 Clone key objects when filling to a number
  Datastore/src/Operation.php
  Datastore/tests/Unit/OperationTest.php
Labels: api: datastore, cla: yes

#991 [Breaking Change] Rename DocumentSnapshot::fields() to data().
  Firestore/src/DocumentSnapshot.php
  Firestore/tests/Snippet/DocumentSnapshotTest.php
  Firestore/tests/System/DocumentAndCollectionTest.php
  Firestore/tests/System/QueryTest.php
  Firestore/tests/System/TransactionTest.php
  Firestore/tests/Unit/DocumentSnapshotTest.php
Labels: api: firestore, cla: yes

#995 Added documentation for SysVCacheItemPool
  README.md
  Spanner/README.md
  Spanner/src/Session/CacheSessionPool.php
Labels: cla: yes

#998 Add Monitoring alert service
  BigQueryDataTransfer/composer.json
  Bigtable/composer.json
  Container/composer.json
  Dataproc/composer.json
  Dlp/composer.json
  ErrorReporting/composer.json
  Firestore/composer.json
  Iot/composer.json
  Language/composer.json
  Logging/composer.json
  Monitoring/composer.json
  Monitoring/src/V3/AlertPolicyServiceClient.php
  Monitoring/src/V3/Gapic/AlertPolicyServiceGapicClient.php
  Monitoring/src/V3/Gapic/NotificationChannelServiceGapicClient.php
  Monitoring/src/V3/NotificationChannelServiceClient.php
  Monitoring/src/V3/resources/alert_policy_service_client_config.json
  Monitoring/src/V3/resources/alert_policy_service_descriptor_config.php
  Monitoring/src/V3/resources/alert_policy_service_rest_client_config.php
  Monitoring/src/V3/resources/notification_channel_service_client_config.json
  Monitoring/src/V3/resources/notification_channel_service_descriptor_config.php
  Monitoring/src/V3/resources/notification_channel_service_rest_client_config.php
  OsLogin/composer.json
  PubSub/composer.json
  Spanner/composer.json
  Speech/composer.json
  Trace/composer.json
  VideoIntelligence/composer.json
  Vision/composer.json
  composer.json
Labels: cla: yes

#1003 Encode empty arrays as firestore arrays
  Firestore/src/ValueMapper.php
  Firestore/tests/Unit/ValueMapperTest.php
Labels: api: firestore, cla: yes

#1006 Debugger: Fix variable name for integer keyed arrays
  Debugger/src/Agent.php
  Debugger/src/VariableTable.php
  Debugger/tests/Unit/VariableTableTest.php
Labels: cla: yes

#1001 Refresh Dlp
  Dlp/src/V2/Gapic/DlpServiceGapicClient.php
  Dlp/src/V2/resources/dlp_service_rest_client_config.php
Labels: cla: yes

#1007 Prepare v0.60.0
  BigQueryDataTransfer/VERSION
  Bigtable/VERSION
  Container/VERSION
  Dataproc/VERSION
  Datastore/VERSION
  Datastore/src/DatastoreClient.php
  Debugger/VERSION
  Debugger/src/DebuggerClient.php
  Dlp/VERSION
  ErrorReporting/VERSION
  Firestore/VERSION
  Firestore/src/FirestoreClient.php
  Iot/VERSION
  Iot/composer.json
  Language/VERSION
  Language/src/LanguageClient.php
  Logging/VERSION
  Logging/src/LoggingClient.php
  Monitoring/VERSION
  OsLogin/VERSION
  PubSub/VERSION
  PubSub/src/PubSubClient.php
  Spanner/VERSION
  Spanner/src/SpannerClient.php
  Speech/VERSION
  Speech/src/SpeechClient.php
  Trace/VERSION
  Trace/src/TraceClient.php
  VideoIntelligence/VERSION
  Vision/VERSION
  Vision/src/VisionClient.php
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: cla: yes

#1011 Added default values for the shemaphore and the shared memory
  Core/src/Batch/SysvConfigStorage.php
  Core/tests/Unit/Batch/SysvConfigStorageTest.php
Labels: cla: yes

#1012 [Appveyor] Retry composer download on failure
  appveyor.yml
Labels: cla: yes

#1010 Add dialogflow
  BigQueryDataTransfer/composer.json
  Bigtable/composer.json
  Container/composer.json
  Dataproc/composer.json
  Dialogflow/.github/pull_request_template.md
  Dialogflow/CONTRIBUTING.md
  Dialogflow/LICENSE
  Dialogflow/README.md
  Dialogflow/composer.json
  Dialogflow/src/V2/AgentsClient.php
  Dialogflow/src/V2/ContextsClient.php
  Dialogflow/src/V2/EntityTypesClient.php
  Dialogflow/src/V2/Gapic/AgentsGapicClient.php
  Dialogflow/src/V2/Gapic/ContextsGapicClient.php
  Dialogflow/src/V2/Gapic/EntityTypesGapicClient.php
  Dialogflow/src/V2/Gapic/IntentsGapicClient.php
  Dialogflow/src/V2/Gapic/SessionEntityTypesGapicClient.php
  Dialogflow/src/V2/Gapic/SessionsGapicClient.php
  Dialogflow/src/V2/IntentsClient.php
  Dialogflow/src/V2/README.md
  Dialogflow/src/V2/SessionEntityTypesClient.php
  Dialogflow/src/V2/SessionsClient.php
  Dialogflow/src/V2/resources/agents_client_config.json
  Dialogflow/src/V2/resources/agents_descriptor_config.php
  Dialogflow/src/V2/resources/agents_rest_client_config.php
  Dialogflow/src/V2/resources/contexts_client_config.json
  Dialogflow/src/V2/resources/contexts_descriptor_config.php
  Dialogflow/src/V2/resources/contexts_rest_client_config.php
  Dialogflow/src/V2/resources/entity_types_client_config.json
  Dialogflow/src/V2/resources/entity_types_descriptor_config.php
  Dialogflow/src/V2/resources/entity_types_rest_client_config.php
  Dialogflow/src/V2/resources/intents_client_config.json
  Dialogflow/src/V2/resources/intents_descriptor_config.php
  Dialogflow/src/V2/resources/intents_rest_client_config.php
  Dialogflow/src/V2/resources/session_entity_types_client_config.json
  Dialogflow/src/V2/resources/session_entity_types_descriptor_config.php
  Dialogflow/src/V2/resources/session_entity_types_rest_client_config.php
  Dialogflow/src/V2/resources/sessions_client_config.json
  Dialogflow/src/V2/resources/sessions_descriptor_config.php
  Dialogflow/src/V2/resources/sessions_rest_client_config.php
  Dlp/composer.json
  ErrorReporting/composer.json
  Firestore/composer.json
  Iot/composer.json
  Language/composer.json
  Logging/composer.json
  Monitoring/composer.json
  OsLogin/composer.json
  PubSub/composer.json
  Spanner/composer.json
  Speech/composer.json
  Trace/composer.json
  VideoIntelligence/composer.json
  Vision/composer.json
  composer.json
  docs/contents/cloud-dialogflow.json
  docs/contents/google-cloud.json
  docs/manifest.json
Labels: cla: yes

#1016 [Debugger] Add Daemon options to Agent
  Debugger/src/Agent.php
  Debugger/tests/Unit/AgentTest.php
Labels: api: debugger, cla: yes

#1018 Prepare v0.61.0
  BigQueryDataTransfer/VERSION
  Bigtable/VERSION
  Container/VERSION
  Core/VERSION
  Dataproc/VERSION
  Debugger/VERSION
  Debugger/src/DebuggerClient.php
  Debugger/tests/Unit/AgentTest.php
  Dialogflow/VERSION
  Dialogflow/composer.json
  Dialogflow/phpunit-snippets.xml.dist
  Dialogflow/phpunit-system.xml.dist
  Dialogflow/phpunit.xml.dist
  Dialogflow/tests/System/bootstrap.php
  Dlp/VERSION
  ErrorReporting/VERSION
  Firestore/VERSION
  Firestore/src/FirestoreClient.php
  Iot/VERSION
  Language/VERSION
  Language/src/LanguageClient.php
  Logging/VERSION
  Logging/src/LoggingClient.php
  Monitoring/VERSION
  OsLogin/VERSION
  PubSub/VERSION
  PubSub/src/PubSubClient.php
  Spanner/VERSION
  Spanner/src/SpannerClient.php
  Speech/VERSION
  Speech/src/SpeechClient.php
  Trace/VERSION
  Trace/src/TraceClient.php
  VideoIntelligence/VERSION
  Vision/VERSION
  Vision/src/VisionClient.php
  composer.json
  dev/src/ComponentIntegration/Command/ComponentIntegration.php
  docs/manifest.json
  src/ServiceBuilder.php
  src/VERSION
  src/Version.php
Labels: cla: yes

#1022 Update README to list all APIs
  README.md
Labels: api: dialogflow, api: iot, cla: yes, documentation

#1023 Update DLP example
  README.md
Labels: api: dlp, cla: yes, documentation

#913 Improve support for datastore custom entity types
  Datastore/src/DatastoreClient.php
  Datastore/src/Entity.php
  Datastore/src/EntityInterface.php
  Datastore/src/EntityMapper.php
  Datastore/src/EntityOptionsTrait.php
  Datastore/src/EntityTrait.php
  Datastore/src/Key.php
  Datastore/src/Operation.php
  Datastore/src/Transaction.php
  Datastore/src/TransactionTrait.php
  Datastore/tests/Snippet/DatastoreClientTest.php
  Datastore/tests/Snippet/EntityTest.php
  Datastore/tests/System/CustomEntityTypeTest.php
  Datastore/tests/System/Entities/Kingdom.php
  Datastore/tests/System/Entities/Person.php
  Datastore/tests/System/Entities/Pet.php
  Datastore/tests/System/Entities/Species.php
  Datastore/tests/Unit/EntityMapperTest.php
  Datastore/tests/Unit/EntityTest.php
Labels: api: datastore, cla: yes

#1020 Bigtable connection interface
  src/Bigtable/Connection/ConnectionInterface.php
Labels: cla: yes

#1021 Debugger: Set default stackframe variable depth limit
  Debugger/composer.json
  Debugger/src/Agent.php
  Debugger/src/Breakpoint.php
  Debugger/src/StackFrame.php
  Debugger/tests/Snippet/StackFrameTest.php
  Debugger/tests/Unit/AgentTest.php
Labels: api: debugger, cla: yes

#1024 move Bigtable connection to match new directory structure
  Bigtable/src/Connection/ConnectionInterface.php
Labels: api: bigtable, cla: yes

#1026 Add parens around invocations
  README.md
Labels: api: dlp, cla: yes, documentation

#1002 Fix Timestamp subsecond handling.
  Core/src/GrpcTrait.php
  Core/src/TimeTrait.php
  Core/src/Timestamp.php
  Core/src/ValueMapperTrait.php
  Core/tests/Unit/TimestampTest.php
  Firestore/src/Connection/Grpc.php
  Firestore/src/SnapshotTrait.php
  Firestore/src/ValueMapper.php
  Firestore/src/WriteBatch.php
  Firestore/tests/Snippet/DocumentReferenceTest.php
  Firestore/tests/Snippet/FirestoreClientTest.php
  Firestore/tests/Snippet/TransactionTest.php
  Firestore/tests/System/ValueMapperTest.php
  Firestore/tests/System/WriteTest.php
  Firestore/tests/Unit/DocumentReferenceTest.php
  Firestore/tests/Unit/FirestoreClientTest.php
  Firestore/tests/Unit/QueryTest.php
  Firestore/tests/Unit/SnapshotTraitTest.php
  Firestore/tests/Unit/TransactionTest.php
  Firestore/tests/Unit/ValueMapperTest.php
  Firestore/tests/Unit/WriteBatchTest.php
  Spanner/src/Batch/BatchClient.php
  Spanner/src/Operation.php
  Spanner/src/ValueMapper.php
  Spanner/tests/Snippet/Batch/BatchClientTest.php
  Spanner/tests/Snippet/Batch/BatchSnapshotTest.php
  Spanner/tests/Snippet/Batch/QueryPartitionTest.php
  Spanner/tests/Snippet/Batch/ReadPartitionTest.php
  Spanner/tests/Snippet/CommitTimestampTest.php
  Spanner/tests/System/WriteTest.php
  Spanner/tests/Unit/Batch/BatchClientTest.php
  Spanner/tests/Unit/TimestampTest.php
  Spanner/tests/Unit/TransactionConfigurationTraitTest.php
  Spanner/tests/Unit/TransactionTypeTest.php
  Spanner/tests/Unit/ValueMapperTest.php
Labels: api: core, api: firestore, api: spanner, cla: yes

#1028 Remove stray operator from system test
  Logging/tests/System/ManageSinksTest.php
Labels: cla: yes

#1030 Fix snippet coverage
  Core/src/Testing/Snippet/Parser/Parser.php
  Core/tests/Snippet/TimestampTest.php
  dev/sh/tests
Labels: cla: yes

#1035 Add parquet format to load job configuration docs
  BigQuery/src/LoadJobConfiguration.php
Labels: api: bigquery, cla: yes, documentation

#1036 Prepare v0.62.0
  BigQuery/VERSION
  BigQuery/src/BigQueryClient.php
  Core/VERSION
  Datastore/VERSION
  Datastore/src/DatastoreClient.php
  Debugger/VERSION
  Debugger/src/DebuggerClient.php
  Firestore/VERSION
  Firestore/src/FirestoreClient.php
  Logging/VERSION
  Logging/src/LoggingClient.php
  Spanner/VERSION
  Spanner/src/SpannerClient.php
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: cla: yes
