Repository googleapis/google-cloud-php, pull requests merged in 2018-02, with the labels that each got.

#894 Debugger: Windows compatibility
  composer.json
  src/Debugger/Agent.php
  src/Debugger/CliDaemon.php
  src/Debugger/Daemon.php
  src/Debugger/README.md
  src/Debugger/bin/google-cloud-debugger
  src/Debugger/composer.json
  tests/unit/Debugger/CliDaemonTest.php
  tests/unit/Debugger/data/daemon_config.php
  tests/unit/Debugger/data/daemon_config_wrong_return.php
Labels: cla: yes

#896 Debugger: Logpoint name
  src/Debugger/Agent.php
Labels: cla: yes

#895 Fix previous transaction protobuf error
  src/Firestore/Connection/Grpc.php
  tests/unit/Firestore/Connection/GrpcTest.php
Labels: api: firestore, cla: yes

#897 Debugger: Re-register debuggee and handle debuggeeId changes
  src/Debugger/Agent.php
  src/Debugger/Daemon.php
  tests/snippets/Debugger/DaemonTest.php
  tests/unit/Debugger/DaemonTest.php
Labels: cla: yes

#873 Vision partial
  src/Vision/V1/ImageAnnotatorClient.php
  src/Vision/VisionHelpersTrait.php
  tests/snippets/Vision/V1/ImageAnnotatorClientTest.php
  tests/unit/Vision/V1/ImageAnnotatorClientTest.php
  tests/unit/Vision/VisionHelpersTraitTest.php
Labels: api: vision, cla: yes

#900 Prepare v0.54.0
  composer.json
  docs/manifest.json
  src/Core/VERSION
  src/Debugger/DebuggerClient.php
  src/Debugger/VERSION
  src/ErrorReporting/VERSION
  src/Firestore/FirestoreClient.php
  src/Firestore/VERSION
  src/Logging/LoggingClient.php
  src/Logging/VERSION
  src/PubSub/PubSubClient.php
  src/PubSub/VERSION
  src/ServiceBuilder.php
  src/Version.php
  src/Vision/VERSION
  src/Vision/VisionClient.php
Labels: cla: yes

#902 Allow DocumentReference in WriteBatch
  src/Firestore/WriteBatch.php
  tests/unit/Firestore/WriteBatchTest.php
Labels: api: firestore, cla: yes

#905 Add allocate ID to upsert methods, refactor tests
  appveyor.yml
  appveyor_install_php.ps1
  src/Core/Testing/DatastoreOperationRefreshTrait.php
  src/Datastore/DatastoreClient.php
  src/Datastore/EntityMapper.php
  src/Datastore/Key.php
  src/Datastore/Operation.php
  src/Datastore/Transaction.php
  tests/snippets/Datastore/DatastoreClientTest.php
  tests/snippets/Datastore/ReadOnlyTransactionTest.php
  tests/snippets/Datastore/TransactionTest.php
  tests/unit/Datastore/DatastoreClientTest.php
  tests/unit/Datastore/EntityMapperTest.php
  tests/unit/Datastore/OperationTest.php
  tests/unit/Datastore/TransactionTest.php
Labels: api: datastore, cla: yes

#912 Pub/Sub 1.0.0
  README.md
Labels: api: pubsub, cla: yes

#914 Remove Appveyor configuration artifacts
  appveyor.yml
  appveyor_install_php.ps1
Labels: cla: yes

#915 Prepare v0.55.0
  composer.json
  docs/manifest.json
  src/Datastore/DatastoreClient.php
  src/Datastore/VERSION
  src/Firestore/FirestoreClient.php
  src/Firestore/VERSION
  src/PubSub/PubSubClient.php
  src/PubSub/VERSION
  src/ServiceBuilder.php
  src/Version.php
Labels: cla: yes

#917 Correctly handle nested structs when unpacking gRPC values
  src/Core/GrpcTrait.php
  tests/unit/Core/GrpcTraitTest.php
Labels: api: core, cla: yes

#918 Prepare v0.56.0
  composer.json
  docs/manifest.json
  src/Bigtable/VERSION
  src/Container/VERSION
  src/Core/VERSION
  src/Dataproc/VERSION
  src/Dlp/VERSION
  src/ErrorReporting/VERSION
  src/Firestore/FirestoreClient.php
  src/Firestore/VERSION
  src/Language/LanguageClient.php
  src/Language/VERSION
  src/Logging/LoggingClient.php
  src/Logging/VERSION
  src/Monitoring/VERSION
  src/OsLogin/VERSION
  src/PubSub/PubSubClient.php
  src/PubSub/VERSION
  src/ServiceBuilder.php
  src/Spanner/SpannerClient.php
  src/Spanner/VERSION
  src/Speech/SpeechClient.php
  src/Speech/VERSION
  src/Trace/TraceClient.php
  src/Trace/VERSION
  src/Version.php
  src/VideoIntelligence/VERSION
  src/Vision/VERSION
  src/Vision/VisionClient.php
Labels: cla: yes
