Repository googleapis/google-cloud-php, pull requests merged in 2018-06, with the labels that each got.

#1080 Fixes prepend.php auto_prepend_file path
  ErrorReporting/src/prepend.php
Labels: api: error reporting, cla: yes

#1081 adds context to exception handler
  ErrorReporting/src/Bootstrap.php
  ErrorReporting/tests/Unit/BootstrapTest.php
Labels: api: error reporting, cla: yes

#1091 Fix documentation links
  dev/src/DocGenerator/Parser/CodeParser.php
  docs/external-classes.json
Labels: cla: yes, documentation

#1033 Add support for Spanner Struct Parameters
  Spanner/src/ArrayType.php
  Spanner/src/Connection/Grpc.php
  Spanner/src/Database.php
  Spanner/src/Snapshot.php
  Spanner/src/StructType.php
  Spanner/src/StructValue.php
  Spanner/src/Transaction.php
  Spanner/src/TransactionalReadTrait.php
  Spanner/src/ValueMapper.php
  Spanner/tests/Snippet/ArrayTypeTest.php
  Spanner/tests/Snippet/Batch/BatchSnapshotTest.php
  Spanner/tests/Snippet/DatabaseTest.php
  Spanner/tests/Snippet/SnapshotTest.php
  Spanner/tests/Snippet/StructTypeTest.php
  Spanner/tests/Snippet/StructValueTest.php
  Spanner/tests/Snippet/TransactionTest.php
  Spanner/tests/Snippet/TransactionalReadMethodsTest.php
  Spanner/tests/System/QueryTest.php
  Spanner/tests/System/SnapshotTest.php
  Spanner/tests/Unit/ArrayTypeTest.php
  Spanner/tests/Unit/StructTypeTest.php
  Spanner/tests/Unit/StructValueTest.php
  Spanner/tests/Unit/ValueMapperTest.php
Labels: api: spanner, cla: yes

#1093 Update generated clients with array type hints
  BigQueryDataTransfer/src/V1/Gapic/DataTransferServiceGapicClient.php
  Bigtable/metadata/Admin/V2/BigtableInstanceAdmin.php
  Bigtable/src/Admin/V2/Gapic/BigtableInstanceAdminGapicClient.php
  Bigtable/src/Admin/V2/Gapic/BigtableTableAdminGapicClient.php
  Bigtable/src/V2/Gapic/BigtableGapicClient.php
  Container/src/V1/Gapic/ClusterManagerGapicClient.php
  Dataproc/src/V1/Gapic/ClusterControllerGapicClient.php
  Dataproc/src/V1/Gapic/JobControllerGapicClient.php
  Debugger/src/V2/Gapic/Controller2GapicClient.php
  Debugger/src/V2/Gapic/Debugger2GapicClient.php
  Dialogflow/src/V2/Gapic/AgentsGapicClient.php
  Dialogflow/src/V2/Gapic/ContextsGapicClient.php
  Dialogflow/src/V2/Gapic/EntityTypesGapicClient.php
  Dialogflow/src/V2/Gapic/IntentsGapicClient.php
  Dialogflow/src/V2/Gapic/SessionEntityTypesGapicClient.php
  Dialogflow/src/V2/Gapic/SessionsGapicClient.php
  Dlp/metadata/V2/Dlp.php
  Dlp/metadata/V2/Storage.php
  Dlp/src/V2/Gapic/DlpServiceGapicClient.php
  ErrorReporting/src/V1beta1/Gapic/ErrorGroupServiceGapicClient.php
  ErrorReporting/src/V1beta1/Gapic/ErrorStatsServiceGapicClient.php
  ErrorReporting/src/V1beta1/Gapic/ReportErrorsServiceGapicClient.php
  Firestore/src/V1beta1/Gapic/FirestoreGapicClient.php
  Iot/metadata/V1/DeviceManager.php
  Iot/metadata/V1/Resources.php
  Iot/src/V1/Gapic/DeviceManagerGapicClient.php
  Language/src/V1beta2/Gapic/LanguageServiceGapicClient.php
  Logging/src/V2/Gapic/ConfigServiceV2GapicClient.php
  Logging/src/V2/Gapic/LoggingServiceV2GapicClient.php
  Logging/src/V2/Gapic/MetricsServiceV2GapicClient.php
  Monitoring/src/V3/Gapic/AlertPolicyServiceGapicClient.php
  Monitoring/src/V3/Gapic/GroupServiceGapicClient.php
  Monitoring/src/V3/Gapic/MetricServiceGapicClient.php
  Monitoring/src/V3/Gapic/NotificationChannelServiceGapicClient.php
  Monitoring/src/V3/Gapic/UptimeCheckServiceGapicClient.php
  OsLogin/src/V1beta/Gapic/OsLoginServiceGapicClient.php
  PubSub/src/V1/Gapic/PublisherGapicClient.php
  PubSub/src/V1/Gapic/SubscriberGapicClient.php
  Redis/src/V1beta1/Gapic/CloudRedisGapicClient.php
  Spanner/src/Admin/Database/V1/Gapic/DatabaseAdminGapicClient.php
  Spanner/src/Admin/Instance/V1/Gapic/InstanceAdminGapicClient.php
  Spanner/src/V1/Gapic/SpannerGapicClient.php
  Speech/metadata/V1P1Beta1/CloudSpeech.php
  Speech/src/V1/Gapic/SpeechGapicClient.php
  Speech/src/V1beta1/Gapic/SpeechGapicClient.php
  Speech/src/V1p1beta1/Gapic/SpeechGapicClient.php
  Speech/src/V1p1beta1/RecognitionConfig.php
  Speech/src/V1p1beta1/SpeechRecognitionResult.php
  Speech/src/V1p1beta1/StreamingRecognitionResult.php
  Speech/src/V1p1beta1/WordInfo.php
  Trace/src/V2/Gapic/TraceServiceGapicClient.php
  VideoIntelligence/src/V1/Gapic/VideoIntelligenceServiceGapicClient.php
  VideoIntelligence/src/V1beta2/Gapic/VideoIntelligenceServiceGapicClient.php
  Vision/metadata/V1/Geometry.php
  Vision/metadata/V1/ImageAnnotator.php
  Vision/src/V1/Gapic/ImageAnnotatorGapicClient.php
Labels: cla: yes

#1095 Update partial veneers for gax changes
  Iot/src/V1/DeviceManagerClient.php
  Redis/src/V1beta1/CloudRedisClient.php
  Spanner/src/V1/SpannerClient.php
Labels: cla: yes

#1094 Prepare v0.68.0
  BigQuery/VERSION
  BigQuery/src/BigQueryClient.php
  BigQueryDataTransfer/VERSION
  Bigtable/VERSION
  Container/VERSION
  Core/VERSION
  Dataproc/VERSION
  Datastore/VERSION
  Datastore/src/DatastoreClient.php
  Debugger/VERSION
  Debugger/src/DebuggerClient.php
  Dialogflow/VERSION
  Dlp/VERSION
  ErrorReporting/VERSION
  Firestore/VERSION
  Firestore/src/FirestoreClient.php
  Iot/VERSION
  Language/VERSION
  Language/src/LanguageClient.php
  Logging/VERSION
  Logging/src/LoggingClient.php
  Monitoring/VERSION
  OsLogin/VERSION
  PubSub/VERSION
  PubSub/src/PubSubClient.php
  Redis/VERSION
  Spanner/VERSION
  Spanner/src/SpannerClient.php
  Speech/VERSION
  Speech/src/SpeechClient.php
  Storage/VERSION
  Storage/src/StorageClient.php
  Trace/VERSION
  Trace/src/TraceClient.php
  Translate/VERSION
  Translate/src/TranslateClient.php
  VideoIntelligence/VERSION
  Vision/VERSION
  Vision/src/VisionClient.php
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: cla: yes, do not merge

#1102 Debugger: Fix loading source context as array from source-contexts.json
  Debugger/src/Debuggee.php
  Debugger/tests/Unit/DebuggeeTest.php
Labels: cla: yes

#1104 Removing $optind variable
  Debugger/bin/google-cloud-debugger
Labels: cla: yes

#1099 Debugger: Limit captured bytes
  Debugger/src/Agent.php
  Debugger/src/Breakpoint.php
  Debugger/src/BufferFullException.php
  Debugger/src/Variable.php
  Debugger/src/VariableTable.php
  Debugger/tests/Unit/AgentTest.php
  Debugger/tests/Unit/VariableTableTest.php
  Debugger/tests/Unit/VariableTest.php
Labels: cla: yes

#1110 Ensure all batch related options can be passed through to PSR logger
  Logging/src/LoggingClient.php
  Logging/src/PsrLogger.php
  Logging/tests/Unit/LoggingClientTest.php
  Logging/tests/Unit/PsrLoggerTest.php
Labels: api: logging, cla: yes

#1114 Prepare v0.69.0
  Debugger/VERSION
  Debugger/src/DebuggerClient.php
  Logging/VERSION
  Logging/src/LoggingClient.php
  VideoIntelligence/VERSION
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: cla: yes, do not merge

#1118 Fixed the code example in the README
  README.md
  VideoIntelligence/README.md
Labels: cla: yes

#1116 Fix return type for ItemIteratorTrait->current
  Core/src/Iterator/ItemIteratorTrait.php
Labels: cla: yes

#1106 Add synthtool config for Vision API
  Vision/metadata/V1/Geometry.php
  Vision/metadata/V1/ImageAnnotator.php
  Vision/metadata/V1/TextAnnotation.php
  Vision/metadata/V1/WebDetection.php
  Vision/src/V1/Gapic/ImageAnnotatorGapicClient.php
  Vision/synth.py
Labels: api: vision, cla: yes

#1112 [Bigtable] Added missing methods in ConnectionInterface.
  Bigtable/src/Connection/ConnectionInterface.php
  Bigtable/src/Connection/Grpc.php
Labels: api: bigtable, cla: yes

#1117 Cleanup Firestore system test artifacts
  Firestore/tests/System/DocumentAndCollectionTest.php
  Firestore/tests/System/FirestoreTestCase.php
  Firestore/tests/System/GetAllDocumentsTest.php
  Firestore/tests/System/QueryTest.php
  Firestore/tests/System/README.md
  Firestore/tests/System/TransactionTest.php
  Firestore/tests/System/ValueMapperTest.php
  Firestore/tests/System/bootstrap.php
Labels: api: firestore, cla: yes

#1122 Support special characters in Firestore document paths
  Firestore/src/SnapshotTrait.php
  Firestore/tests/Unit/FirestoreClientTest.php
Labels: api: firestore, cla: yes

#1123 Add Tasks client lib
  README.md
  Tasks/.gitattributes
  Tasks/.github/pull_request_template.md
  Tasks/CONTRIBUTING.md
  Tasks/LICENSE
  Tasks/README.md
  Tasks/composer.json
  Tasks/metadata/V2Beta2/Cloudtasks.php
  Tasks/metadata/V2Beta2/Queue.php
  Tasks/metadata/V2Beta2/Target.php
  Tasks/metadata/V2Beta2/Task.php
  Tasks/src/V2beta2/AcknowledgeTaskRequest.php
  Tasks/src/V2beta2/AppEngineHttpRequest.php
  Tasks/src/V2beta2/AppEngineHttpTarget.php
  Tasks/src/V2beta2/AppEngineRouting.php
  Tasks/src/V2beta2/AttemptStatus.php
  Tasks/src/V2beta2/CancelLeaseRequest.php
  Tasks/src/V2beta2/CloudTasksClient.php
  Tasks/src/V2beta2/CloudTasksGrpcClient.php
  Tasks/src/V2beta2/CreateQueueRequest.php
  Tasks/src/V2beta2/CreateTaskRequest.php
  Tasks/src/V2beta2/DeleteQueueRequest.php
  Tasks/src/V2beta2/DeleteTaskRequest.php
  Tasks/src/V2beta2/Gapic/CloudTasksGapicClient.php
  Tasks/src/V2beta2/GetQueueRequest.php
  Tasks/src/V2beta2/GetTaskRequest.php
  Tasks/src/V2beta2/HttpMethod.php
  Tasks/src/V2beta2/LeaseTasksRequest.php
  Tasks/src/V2beta2/LeaseTasksResponse.php
  Tasks/src/V2beta2/ListQueuesRequest.php
  Tasks/src/V2beta2/ListQueuesResponse.php
  Tasks/src/V2beta2/ListTasksRequest.php
  Tasks/src/V2beta2/ListTasksResponse.php
  Tasks/src/V2beta2/PauseQueueRequest.php
  Tasks/src/V2beta2/PullMessage.php
  Tasks/src/V2beta2/PullTarget.php
  Tasks/src/V2beta2/PurgeQueueRequest.php
  Tasks/src/V2beta2/Queue.php
  Tasks/src/V2beta2/Queue_State.php
  Tasks/src/V2beta2/README.md
  Tasks/src/V2beta2/RateLimits.php
  Tasks/src/V2beta2/RenewLeaseRequest.php
  Tasks/src/V2beta2/ResumeQueueRequest.php
  Tasks/src/V2beta2/RetryConfig.php
  Tasks/src/V2beta2/RunTaskRequest.php
  Tasks/src/V2beta2/Task.php
  Tasks/src/V2beta2/TaskStatus.php
  Tasks/src/V2beta2/Task_View.php
  Tasks/src/V2beta2/UpdateQueueRequest.php
  Tasks/src/V2beta2/resources/cloud_tasks_client_config.json
  Tasks/src/V2beta2/resources/cloud_tasks_descriptor_config.php
  Tasks/src/V2beta2/resources/cloud_tasks_rest_client_config.php
  Tasks/synth.py
  Tasks/tests/System/V2beta2/TasksServiceSmokeTest.php
  Tasks/tests/System/bootstrap.php
  Tasks/tests/Unit/V2beta2/CloudTasksClientTest.php
  composer.json
  docs/contents/cloud-tasks.json
  docs/contents/google-cloud.json
  docs/manifest.json
Labels: api: tasks, cla: yes

#1129 [Bigtable] Added methods for manipulating IAM permissions to Grpc.php
  Bigtable/src/Connection/Grpc.php
  Bigtable/tests/Unit/Connection/GrpcTest.php
Labels: cla: yes

#1131 Revert "Add Tasks client lib"
  README.md
  Tasks/.gitattributes
  Tasks/.github/pull_request_template.md
  Tasks/CONTRIBUTING.md
  Tasks/LICENSE
  Tasks/README.md
  Tasks/composer.json
  Tasks/metadata/V2Beta2/Cloudtasks.php
  Tasks/metadata/V2Beta2/Queue.php
  Tasks/metadata/V2Beta2/Target.php
  Tasks/metadata/V2Beta2/Task.php
  Tasks/src/V2beta2/AcknowledgeTaskRequest.php
  Tasks/src/V2beta2/AppEngineHttpRequest.php
  Tasks/src/V2beta2/AppEngineHttpTarget.php
  Tasks/src/V2beta2/AppEngineRouting.php
  Tasks/src/V2beta2/AttemptStatus.php
  Tasks/src/V2beta2/CancelLeaseRequest.php
  Tasks/src/V2beta2/CloudTasksClient.php
  Tasks/src/V2beta2/CloudTasksGrpcClient.php
  Tasks/src/V2beta2/CreateQueueRequest.php
  Tasks/src/V2beta2/CreateTaskRequest.php
  Tasks/src/V2beta2/DeleteQueueRequest.php
  Tasks/src/V2beta2/DeleteTaskRequest.php
  Tasks/src/V2beta2/Gapic/CloudTasksGapicClient.php
  Tasks/src/V2beta2/GetQueueRequest.php
  Tasks/src/V2beta2/GetTaskRequest.php
  Tasks/src/V2beta2/HttpMethod.php
  Tasks/src/V2beta2/LeaseTasksRequest.php
  Tasks/src/V2beta2/LeaseTasksResponse.php
  Tasks/src/V2beta2/ListQueuesRequest.php
  Tasks/src/V2beta2/ListQueuesResponse.php
  Tasks/src/V2beta2/ListTasksRequest.php
  Tasks/src/V2beta2/ListTasksResponse.php
  Tasks/src/V2beta2/PauseQueueRequest.php
  Tasks/src/V2beta2/PullMessage.php
  Tasks/src/V2beta2/PullTarget.php
  Tasks/src/V2beta2/PurgeQueueRequest.php
  Tasks/src/V2beta2/Queue.php
  Tasks/src/V2beta2/Queue_State.php
  Tasks/src/V2beta2/README.md
  Tasks/src/V2beta2/RateLimits.php
  Tasks/src/V2beta2/RenewLeaseRequest.php
  Tasks/src/V2beta2/ResumeQueueRequest.php
  Tasks/src/V2beta2/RetryConfig.php
  Tasks/src/V2beta2/RunTaskRequest.php
  Tasks/src/V2beta2/Task.php
  Tasks/src/V2beta2/TaskStatus.php
  Tasks/src/V2beta2/Task_View.php
  Tasks/src/V2beta2/UpdateQueueRequest.php
  Tasks/src/V2beta2/resources/cloud_tasks_client_config.json
  Tasks/src/V2beta2/resources/cloud_tasks_descriptor_config.php
  Tasks/src/V2beta2/resources/cloud_tasks_rest_client_config.php
  Tasks/synth.py
  Tasks/tests/System/V2beta2/TasksServiceSmokeTest.php
  Tasks/tests/System/bootstrap.php
  Tasks/tests/Unit/V2beta2/CloudTasksClientTest.php
  composer.json
  docs/contents/cloud-tasks.json
  docs/contents/google-cloud.json
  docs/manifest.json
Labels: cla: yes

#1132 Prepare v0.69.1
  Core/VERSION
  Firestore/VERSION
  Firestore/src/FirestoreClient.php
  Logging/VERSION
  Logging/composer.json
  Logging/src/LoggingClient.php
  VideoIntelligence/VERSION
  Vision/VERSION
  Vision/src/VisionClient.php
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: cla: yes

#1135 Fix package name
  Translate/README.md
Labels: api: translation, cla: yes

#1138 Regenerate DLP client lib
  Dlp/metadata/V2/Dlp.php
  Dlp/src/V2/Action.php
  Dlp/src/V2/Action_SaveFindings.php
  Dlp/src/V2/AnalyzeDataSourceRiskDetails.php
  Dlp/src/V2/AnalyzeDataSourceRiskDetails_DeltaPresenceEstimationResult.php
  Dlp/src/V2/AnalyzeDataSourceRiskDetails_DeltaPresenceEstimationResult_DeltaPresenceEstimationHistogramBucket.php
  Dlp/src/V2/AnalyzeDataSourceRiskDetails_DeltaPresenceEstimationResult_DeltaPresenceEstimationQuasiIdValues.php
  Dlp/src/V2/BucketingConfig.php
  Dlp/src/V2/ContentItem.php
  Dlp/src/V2/CryptoReplaceFfxFpeConfig.php
  Dlp/src/V2/CustomInfoType.php
  Dlp/src/V2/CustomInfoType_DetectionRule.php
  Dlp/src/V2/CustomInfoType_DetectionRule_HotwordRule.php
  Dlp/src/V2/CustomInfoType_SurrogateType.php
  Dlp/src/V2/DateShiftConfig.php
  Dlp/src/V2/DeidentifyTemplate.php
  Dlp/src/V2/DlpServiceClient.php
  Dlp/src/V2/DlpServiceGrpcClient.php
  Dlp/src/V2/Finding.php
  Dlp/src/V2/FixedSizeBucketingConfig.php
  Dlp/src/V2/Gapic/DlpServiceGapicClient.php
  Dlp/src/V2/InfoType.php
  Dlp/src/V2/InfoTypeTransformations_InfoTypeTransformation.php
  Dlp/src/V2/InspectConfig.php
  Dlp/src/V2/InspectTemplate.php
  Dlp/src/V2/JobTrigger.php
  Dlp/src/V2/Likelihood.php
  Dlp/src/V2/ListJobTriggersRequest.php
  Dlp/src/V2/OutputStorageConfig.php
  Dlp/src/V2/PrivacyMetric.php
  Dlp/src/V2/PrivacyMetric_DeltaPresenceEstimationConfig.php
  Dlp/src/V2/QuasiId.php
  Dlp/src/V2/RedactImageRequest.php
  Dlp/src/V2/RedactImageRequest_ImageRedactionConfig.php
  Dlp/src/V2/RedactImageResponse.php
  Dlp/src/V2/RiskAnalysisJobConfig.php
  Dlp/src/V2/Schedule.php
  Dlp/src/V2/StatisticalTable.php
  Dlp/src/V2/StatisticalTable_QuasiIdentifierField.php
  Dlp/src/V2/Table.php
Labels: cla: yes

#1113 Add tts client lib
  README.md
  TextToSpeech/.gitattributes
  TextToSpeech/.github/pull_request_template.md
  TextToSpeech/CONTRIBUTING.md
  TextToSpeech/LICENSE
  TextToSpeech/README.md
  TextToSpeech/composer.json
  TextToSpeech/metadata/V1/CloudTts.php
  TextToSpeech/src/V1/AudioConfig.php
  TextToSpeech/src/V1/AudioEncoding.php
  TextToSpeech/src/V1/Gapic/TextToSpeechGapicClient.php
  TextToSpeech/src/V1/ListVoicesRequest.php
  TextToSpeech/src/V1/ListVoicesResponse.php
  TextToSpeech/src/V1/README.md
  TextToSpeech/src/V1/SsmlVoiceGender.php
  TextToSpeech/src/V1/SynthesisInput.php
  TextToSpeech/src/V1/SynthesizeSpeechRequest.php
  TextToSpeech/src/V1/SynthesizeSpeechResponse.php
  TextToSpeech/src/V1/TextToSpeechClient.php
  TextToSpeech/src/V1/TextToSpeechGrpcClient.php
  TextToSpeech/src/V1/Voice.php
  TextToSpeech/src/V1/VoiceSelectionParams.php
  TextToSpeech/src/V1/resources/text_to_speech_client_config.json
  TextToSpeech/src/V1/resources/text_to_speech_descriptor_config.php
  TextToSpeech/src/V1/resources/text_to_speech_rest_client_config.php
  TextToSpeech/synth.py
  TextToSpeech/tests/System/V1/TextToSpeechSmokeTest.php
  TextToSpeech/tests/System/bootstrap.php
  TextToSpeech/tests/Unit/V1/TextToSpeechClientTest.php
  composer.json
  docs/contents/cloud-text-to-speech.json
  docs/contents/google-cloud.json
  docs/manifest.json
Labels: api: text to speech, cla: yes

#1133 Add Tasks client lib
  README.md
  Tasks/.gitattributes
  Tasks/.github/pull_request_template.md
  Tasks/CONTRIBUTING.md
  Tasks/LICENSE
  Tasks/README.md
  Tasks/composer.json
  Tasks/metadata/V2Beta2/Cloudtasks.php
  Tasks/metadata/V2Beta2/Queue.php
  Tasks/metadata/V2Beta2/Target.php
  Tasks/metadata/V2Beta2/Task.php
  Tasks/src/V2beta2/AcknowledgeTaskRequest.php
  Tasks/src/V2beta2/AppEngineHttpRequest.php
  Tasks/src/V2beta2/AppEngineHttpTarget.php
  Tasks/src/V2beta2/AppEngineRouting.php
  Tasks/src/V2beta2/AttemptStatus.php
  Tasks/src/V2beta2/CancelLeaseRequest.php
  Tasks/src/V2beta2/CloudTasksClient.php
  Tasks/src/V2beta2/CloudTasksGrpcClient.php
  Tasks/src/V2beta2/CreateQueueRequest.php
  Tasks/src/V2beta2/CreateTaskRequest.php
  Tasks/src/V2beta2/DeleteQueueRequest.php
  Tasks/src/V2beta2/DeleteTaskRequest.php
  Tasks/src/V2beta2/Gapic/CloudTasksGapicClient.php
  Tasks/src/V2beta2/GetQueueRequest.php
  Tasks/src/V2beta2/GetTaskRequest.php
  Tasks/src/V2beta2/HttpMethod.php
  Tasks/src/V2beta2/LeaseTasksRequest.php
  Tasks/src/V2beta2/LeaseTasksResponse.php
  Tasks/src/V2beta2/ListQueuesRequest.php
  Tasks/src/V2beta2/ListQueuesResponse.php
  Tasks/src/V2beta2/ListTasksRequest.php
  Tasks/src/V2beta2/ListTasksResponse.php
  Tasks/src/V2beta2/PauseQueueRequest.php
  Tasks/src/V2beta2/PullMessage.php
  Tasks/src/V2beta2/PullTarget.php
  Tasks/src/V2beta2/PurgeQueueRequest.php
  Tasks/src/V2beta2/Queue.php
  Tasks/src/V2beta2/Queue_State.php
  Tasks/src/V2beta2/README.md
  Tasks/src/V2beta2/RateLimits.php
  Tasks/src/V2beta2/RenewLeaseRequest.php
  Tasks/src/V2beta2/ResumeQueueRequest.php
  Tasks/src/V2beta2/RetryConfig.php
  Tasks/src/V2beta2/RunTaskRequest.php
  Tasks/src/V2beta2/Task.php
  Tasks/src/V2beta2/TaskStatus.php
  Tasks/src/V2beta2/Task_View.php
  Tasks/src/V2beta2/UpdateQueueRequest.php
  Tasks/src/V2beta2/resources/cloud_tasks_client_config.json
  Tasks/src/V2beta2/resources/cloud_tasks_descriptor_config.php
  Tasks/src/V2beta2/resources/cloud_tasks_rest_client_config.php
  Tasks/synth.py
  Tasks/tests/System/V2beta2/TasksServiceSmokeTest.php
  Tasks/tests/System/bootstrap.php
  Tasks/tests/Unit/V2beta2/CloudTasksClientTest.php
  composer.json
  docs/contents/cloud-tasks.json
  docs/contents/google-cloud.json
  docs/manifest.json
Labels: api: tasks, cla: yes

#1139 Update example verbiage
  README.md
  TextToSpeech/README.md
  TextToSpeech/src/V1/README.md
  TextToSpeech/tests/System/V1/TextToSpeechSmokeTest.php
Labels: api: text to speech, cla: yes

#1141 Add missing autoloader config for Tasks and tts tests
  composer.json
Labels: cla: yes

#1144 Remove extra newline in README template
  dev/src/AddComponent/templates/template-README.md.txt
Labels: cla: yes, documentation

#1145 Exclude vendor dir for components too
  dev/src/DocGenerator/Command/Docs.php
Labels: cla: yes, documentation

#1140 Output the stacktrace as well when catching exceptions
  Core/src/Batch/BatchTrait.php
Labels: cla: yes

#1143 Add KMS client lib
  Kms/.gitattributes
  Kms/.github/pull_request_template.md
  Kms/CONTRIBUTING.md
  Kms/LICENSE
  Kms/README.md
  Kms/composer.json
  Kms/metadata/V1/Resources.php
  Kms/metadata/V1/Service.php
  Kms/src/V1/CreateCryptoKeyRequest.php
  Kms/src/V1/CreateCryptoKeyVersionRequest.php
  Kms/src/V1/CreateKeyRingRequest.php
  Kms/src/V1/CryptoKey.php
  Kms/src/V1/CryptoKeyVersion.php
  Kms/src/V1/CryptoKeyVersion_CryptoKeyVersionState.php
  Kms/src/V1/CryptoKey_CryptoKeyPurpose.php
  Kms/src/V1/DecryptRequest.php
  Kms/src/V1/DecryptResponse.php
  Kms/src/V1/DestroyCryptoKeyVersionRequest.php
  Kms/src/V1/EncryptRequest.php
  Kms/src/V1/EncryptResponse.php
  Kms/src/V1/Gapic/KeyManagementServiceGapicClient.php
  Kms/src/V1/GetCryptoKeyRequest.php
  Kms/src/V1/GetCryptoKeyVersionRequest.php
  Kms/src/V1/GetKeyRingRequest.php
  Kms/src/V1/KeyManagementServiceClient.php
  Kms/src/V1/KeyManagementServiceGrpcClient.php
  Kms/src/V1/KeyRing.php
  Kms/src/V1/ListCryptoKeyVersionsRequest.php
  Kms/src/V1/ListCryptoKeyVersionsResponse.php
  Kms/src/V1/ListCryptoKeysRequest.php
  Kms/src/V1/ListCryptoKeysResponse.php
  Kms/src/V1/ListKeyRingsRequest.php
  Kms/src/V1/ListKeyRingsResponse.php
  Kms/src/V1/README.md
  Kms/src/V1/RestoreCryptoKeyVersionRequest.php
  Kms/src/V1/UpdateCryptoKeyPrimaryVersionRequest.php
  Kms/src/V1/UpdateCryptoKeyRequest.php
  Kms/src/V1/UpdateCryptoKeyVersionRequest.php
  Kms/src/V1/resources/key_management_service_client_config.json
  Kms/src/V1/resources/key_management_service_descriptor_config.php
  Kms/src/V1/resources/key_management_service_rest_client_config.php
  Kms/synth.py
  Kms/tests/System/V1/KeyManagementServiceClientSmokeTest.php
  Kms/tests/System/bootstrap.php
  Kms/tests/Unit/V1/KeyManagementServiceClientTest.php
  README.md
  composer.json
  docs/contents/cloud-kms.json
  docs/contents/google-cloud.json
  docs/manifest.json
Labels: api: kms, cla: yes

#1147 Fixes for the replace version for the new components
  composer.json
Labels: cla: yes
