Repository googleapis/google-cloud-php, pull requests merged in 2018-12, with the labels that each got.

#1511 move google/cloud-core package from a development dependency to a production dependency in google/cloud-bigtable package
  Bigtable/composer.json
Labels: api: bigtable, cla: yes

#1514 Prepare v0.88.0
  Bigtable/VERSION
  Bigtable/src/BigtableClient.php
  Dataproc/VERSION
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: cla: yes

#1513 Update storage bucket notification sample
  Storage/src/Bucket.php
  Storage/src/StorageClient.php
  Storage/tests/Snippet/BucketTest.php
Labels: api: storage, cla: yes

#1542 Allow retries for initial valid call
  Spanner/src/Result.php
Labels: api: spanner, cla: yes

#1543 Add Container generation metadata.
  Container/synth.metadata
Labels: cla: yes

#1510 Storage async object downloads
  Core/composer.json
  Core/src/ExponentialBackoff.php
  Core/src/RequestWrapper.php
  Core/src/RequestWrapperTrait.php
  Core/src/ServiceBuilder.php
  Core/tests/Unit/ExponentialBackoffTest.php
  Core/tests/Unit/RequestWrapperTest.php
  Storage/composer.json
  Storage/src/Connection/Rest.php
  Storage/src/StorageObject.php
  Storage/tests/Snippet/StorageObjectTest.php
  Storage/tests/System/ManageObjectsTest.php
  Storage/tests/Unit/Connection/RestTest.php
  Storage/tests/Unit/StorageObjectTest.php
Labels: api: storage, cla: yes

#1544 Prepare v0.89.0
  Container/VERSION
  Core/VERSION
  Spanner/VERSION
  Spanner/src/SpannerClient.php
  Storage/VERSION
  Storage/src/StorageClient.php
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: cla: yes

#1546 Add PHP7.3 kokoro config
  .kokoro/presubmit/php73.cfg
Labels: cla: yes

#1509 Link to installed dependency version in generated docs
  dev/src/DocGenerator/Parser/CodeParser.php
  dev/src/ReleaseBuilder/ReleaseBuilder.php
  docs/external-classes.json
Labels: cla: yes, type: docs

#1545 Add unit test coverage to partial veneer methods
  Iot/src/V1/DeviceManagerClient.php
  Iot/tests/Unit/V1/DeviceManagerClientPartialVeneerTest.php
  Redis/src/V1/CloudRedisClient.php
  Redis/src/V1beta1/CloudRedisClient.php
  Redis/tests/Unit/V1/CloudRedisClientPartialVeneerTest.php
  Redis/tests/Unit/V1beta1/CloudRedisClientPartialVeneerTest.php
  Spanner/tests/Unit/V1/SpannerClientPartialVeneerTest.php
Labels: cla: yes

#1503 [Breaking Change] Replace InternalChecker `project_id` with `peer_project_id`.
  Monitoring/metadata/V3/NotificationService.php
  Monitoring/metadata/V3/Uptime.php
  Monitoring/src/V3/AlertPolicyServiceGrpcClient.php
  Monitoring/src/V3/Gapic/NotificationChannelServiceGapicClient.php
  Monitoring/src/V3/GroupServiceGrpcClient.php
  Monitoring/src/V3/InternalChecker.php
  Monitoring/src/V3/MetricServiceGrpcClient.php
  Monitoring/src/V3/NotificationChannelServiceGrpcClient.php
  Monitoring/src/V3/ServiceTier.php
  Monitoring/src/V3/UptimeCheckConfig.php
  Monitoring/src/V3/UptimeCheckConfig/ContentMatcher.php
  Monitoring/src/V3/UptimeCheckServiceGrpcClient.php
Labels: cla: yes, do not merge

#1550 Require GAX in google/cloud-datastore
  Datastore/composer.json
Labels: cla: yes

#1517 Add cloud common protos directory
  Asset/composer.json
  BigQueryDataTransfer/composer.json
  Bigtable/composer.json
  CommonProtos/.gitignore
  CommonProtos/CONTRIBUTING.md
  CommonProtos/LICENSE
  CommonProtos/README.md
  CommonProtos/composer.json
  CommonProtos/dev/regenerate.sh
  CommonProtos/metadata/Cloud/Audit/AuditLog.php
  CommonProtos/metadata/Devtools/Source/V1/SourceContext.php
  CommonProtos/phpunit.xml.dist
  CommonProtos/src/Audit/AuditLog.php
  CommonProtos/src/Audit/AuthenticationInfo.php
  CommonProtos/src/Audit/AuthorizationInfo.php
  CommonProtos/src/Audit/RequestMetadata.php
  CommonProtos/src/DevTools/Source/V1/AliasContext.php
  CommonProtos/src/DevTools/Source/V1/AliasContext/Kind.php
  CommonProtos/src/DevTools/Source/V1/AliasContext_Kind.php
  CommonProtos/src/DevTools/Source/V1/CloudRepoSourceContext.php
  CommonProtos/src/DevTools/Source/V1/CloudWorkspaceId.php
  CommonProtos/src/DevTools/Source/V1/CloudWorkspaceSourceContext.php
  CommonProtos/src/DevTools/Source/V1/ExtendedSourceContext.php
  CommonProtos/src/DevTools/Source/V1/GerritSourceContext.php
  CommonProtos/src/DevTools/Source/V1/GitSourceContext.php
  CommonProtos/src/DevTools/Source/V1/ProjectRepoId.php
  CommonProtos/src/DevTools/Source/V1/RepoId.php
  CommonProtos/src/DevTools/Source/V1/SourceContext.php
  CommonProtos/tests/Unit/InstantiateClassesTest.php
  CommonProtos/tests/bootstrap.php
  Container/composer.json
  Core/composer.json
  Dataproc/composer.json
  Debugger/composer.json
  Dialogflow/composer.json
  Dlp/composer.json
  ErrorReporting/composer.json
  Firestore/composer.json
  Iot/composer.json
  Kms/composer.json
  Language/composer.json
  Logging/composer.json
  Monitoring/composer.json
  OsLogin/composer.json
  PubSub/composer.json
  Redis/composer.json
  Spanner/composer.json
  Speech/composer.json
  Tasks/composer.json
  TextToSpeech/composer.json
  Trace/composer.json
  VideoIntelligence/composer.json
  Vision/composer.json
  composer.json
  docs/contents/cloud-common-protos.json
  docs/manifest.json
  phpcs-ruleset.xml
Labels: cla: yes

#1551 Use consistent name for the test runner image
  .kokoro/presubmit/php55.cfg
Labels: cla: yes, testing

#1576 Fix incorrect classname in GAPIC Documentation.
  VideoIntelligence/src/V1/Gapic/VideoIntelligenceServiceGapicClient.php
  VideoIntelligence/src/V1beta2/Gapic/VideoIntelligenceServiceGapicClient.php
  VideoIntelligence/synth.metadata
Labels: cla: yes

#1577 Fix incorrect classname in GAPIC Documentation.
  Vision/src/V1/Gapic/ImageAnnotatorGapicClient.php
  Vision/src/V1/Gapic/ProductSearchGapicClient.php
  Vision/synth.metadata
Labels: cla: yes

#1575 Fix incorrect classname in GAPIC Documentation.
  Trace/src/V2/Gapic/TraceServiceGapicClient.php
  Trace/synth.metadata
Labels: cla: yes

#1574 Fix incorrect classname in Text-To-Speech Generated Client Documentation.
  TextToSpeech/src/V1/Gapic/TextToSpeechGapicClient.php
  TextToSpeech/synth.metadata
Labels: cla: yes

#1573 Fix incorrect classname in Tasks Generated Client Documentation.
  Tasks/src/V2beta2/Gapic/CloudTasksGapicClient.php
  Tasks/src/V2beta3/Gapic/CloudTasksGapicClient.php
  Tasks/synth.metadata
Labels: cla: yes

#1572 Fix incorrect classname in Speech Generated Client Documentation.
  Speech/src/V1/Gapic/SpeechGapicClient.php
  Speech/src/V1p1beta1/Gapic/SpeechGapicClient.php
  Speech/synth.metadata
Labels: cla: yes

#1571 Fix incorrect classname in Spanner Generated Client Documentation.
  Spanner/src/Admin/Database/V1/Gapic/DatabaseAdminGapicClient.php
  Spanner/src/Admin/Instance/V1/Gapic/InstanceAdminGapicClient.php
  Spanner/src/V1/Gapic/SpannerGapicClient.php
  Spanner/synth.metadata
Labels: cla: yes

#1570 Fix incorrect classname in Redis Generated Client Documentation.
  Redis/src/V1/Gapic/CloudRedisGapicClient.php
  Redis/src/V1beta1/Gapic/CloudRedisGapicClient.php
  Redis/synth.metadata
Labels: cla: yes

#1569 Fix incorrect classname in PubSub Generated Client Documentation.
  PubSub/src/V1/Gapic/PublisherGapicClient.php
  PubSub/src/V1/Gapic/SubscriberGapicClient.php
  PubSub/synth.metadata
Labels: cla: yes

#1568 Fix incorrect classname in OsLogin Generated Client Documentation.
  OsLogin/src/V1/Gapic/OsLoginServiceGapicClient.php
  OsLogin/src/V1beta/Gapic/OsLoginServiceGapicClient.php
  OsLogin/synth.metadata
Labels: cla: yes

#1567 Fix incorrect classname in Monitoring Generated Client Documentation.
  Monitoring/src/V3/Gapic/AlertPolicyServiceGapicClient.php
  Monitoring/src/V3/Gapic/GroupServiceGapicClient.php
  Monitoring/src/V3/Gapic/MetricServiceGapicClient.php
  Monitoring/src/V3/Gapic/NotificationChannelServiceGapicClient.php
  Monitoring/src/V3/Gapic/UptimeCheckServiceGapicClient.php
  Monitoring/synth.metadata
Labels: cla: yes

#1566 Fix incorrect classname in Logging Generated Client Documentation.
  Logging/src/V2/Gapic/ConfigServiceV2GapicClient.php
  Logging/src/V2/Gapic/LoggingServiceV2GapicClient.php
  Logging/src/V2/Gapic/MetricsServiceV2GapicClient.php
  Logging/synth.metadata
Labels: cla: yes

#1565 Fix incorrect classname in Language Generated Client Documentation.
  Language/src/V1beta2/Gapic/LanguageServiceGapicClient.php
  Language/synth.metadata
Labels: cla: yes

#1564 Fix incorrect classname in KMS Generated Client Documentation.
  Kms/src/V1/Gapic/KeyManagementServiceGapicClient.php
  Kms/synth.metadata
Labels: cla: yes

#1563 Fix incorrect classname in IOT Generated Client Documentation.
  Iot/src/V1/Gapic/DeviceManagerGapicClient.php
  Iot/synth.metadata
Labels: cla: yes

#1562 Fix incorrect classname in Firestore Generated Client Documentation.
  Firestore/src/V1beta1/Gapic/FirestoreGapicClient.php
  Firestore/synth.metadata
Labels: cla: yes

#1560 Fix incorrect classname in DLP Generated Client Documentation.
  Dlp/src/V2/Gapic/DlpServiceGapicClient.php
  Dlp/synth.metadata
Labels: cla: yes

#1559 Fix incorrect classname in Dialogflow Generated Client Documentation.
  Dialogflow/src/V2/Gapic/AgentsGapicClient.php
  Dialogflow/src/V2/Gapic/ContextsGapicClient.php
  Dialogflow/src/V2/Gapic/EntityTypesGapicClient.php
  Dialogflow/src/V2/Gapic/IntentsGapicClient.php
  Dialogflow/src/V2/Gapic/SessionEntityTypesGapicClient.php
  Dialogflow/src/V2/Gapic/SessionsGapicClient.php
  Dialogflow/synth.metadata
Labels: cla: yes

#1558 Fix incorrect classname in Debugger Generated Client Documentation.
  Debugger/src/V2/Gapic/Controller2GapicClient.php
  Debugger/src/V2/Gapic/Debugger2GapicClient.php
  Debugger/synth.metadata
Labels: cla: yes

#1557 Fix incorrect classname in Dataproc Generated Client Documentation.
  Dataproc/src/V1/Gapic/ClusterControllerGapicClient.php
  Dataproc/src/V1/Gapic/JobControllerGapicClient.php
  Dataproc/src/V1/Gapic/WorkflowTemplateServiceGapicClient.php
  Dataproc/synth.metadata
Labels: cla: yes

#1556 Fix incorrect classname in Container Generated Client Documentation.
  Container/src/V1/Gapic/ClusterManagerGapicClient.php
  Container/synth.metadata
Labels: cla: yes

#1555 Fix incorrect classname in Bigtable Generated Client Documentation.
  Bigtable/src/Admin/V2/Gapic/BigtableInstanceAdminGapicClient.php
  Bigtable/src/Admin/V2/Gapic/BigtableTableAdminGapicClient.php
  Bigtable/src/V2/Gapic/BigtableGapicClient.php
  Bigtable/synth.metadata
Labels: cla: yes

#1554 Fix incorrect classname in BigQuery Data Transfer Generated Client Documentation.
  BigQueryDataTransfer/src/V1/Gapic/DataTransferServiceGapicClient.php
  BigQueryDataTransfer/synth.metadata
Labels: cla: yes

#1553 Fix incorrect classname in Asset Generated Client Documentation.
  Asset/src/V1beta1/Gapic/AssetServiceGapicClient.php
  Asset/synth.metadata
Labels: cla: yes

#1561 Fix incorrect classname in Error Reporting Generated Client Documentation.
  ErrorReporting/src/V1beta1/Gapic/ErrorGroupServiceGapicClient.php
  ErrorReporting/src/V1beta1/Gapic/ErrorStatsServiceGapicClient.php
  ErrorReporting/src/V1beta1/Gapic/ReportErrorsServiceGapicClient.php
  ErrorReporting/synth.metadata
Labels: cla: yes

#1578 Preapre v0.90.0
  Asset/VERSION
  BigQueryDataTransfer/VERSION
  Bigtable/VERSION
  Bigtable/src/BigtableClient.php
  CommonProtos/VERSION
  Container/VERSION
  Core/VERSION
  Dataproc/VERSION
  Datastore/VERSION
  Datastore/src/DatastoreClient.php
  Datastore/src/V1/Gapic/DatastoreGapicClient.php
  Debugger/VERSION
  Debugger/src/DebuggerClient.php
  Dialogflow/VERSION
  Dlp/VERSION
  ErrorReporting/VERSION
  Firestore/VERSION
  Firestore/src/FirestoreClient.php
  Iot/VERSION
  Kms/VERSION
  Language/VERSION
  Language/src/LanguageClient.php
  Logging/VERSION
  Logging/src/LoggingClient.php
  Monitoring/VERSION
  OsLogin/VERSION
  PubSub/VERSION
  PubSub/src/PubSubClient.php
  Redis/VERSION
  Spanner/VERSION
  Spanner/src/SpannerClient.php
  Speech/VERSION
  Speech/src/SpeechClient.php
  Tasks/VERSION
  TextToSpeech/VERSION
  Trace/VERSION
  Trace/src/TraceClient.php
  VideoIntelligence/VERSION
  Vision/VERSION
  Vision/src/VisionClient.php
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: cla: yes

#1580 Update Trace README
  Trace/README.md
Labels: cla: yes
