Repository googleapis/google-cloud-php, pull requests merged in 2018-05, with the labels that each got.

#875 Initial implementation of speech partial
  Speech/src/SpeechHelpersTrait.php
  Speech/src/V1/SpeechClient.php
  Speech/src/V1beta1/SpeechClient.php
  Speech/tests/Snippet/V1/SpeechClientTest.php
  Speech/tests/Snippet/V1beta1/SpeechClientTest.php
  Speech/tests/Unit/SpeechHelpersTraitTest.php
  Speech/tests/Unit/V1/SpeechClientTest.php
  Speech/tests/Unit/V1beta1/SpeechClientTest.php
Labels: api: speech, cla: yes

#1038 Prepare v0.63.0
  Speech/VERSION
  Speech/src/SpeechClient.php
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: cla: yes

#1044 Corrected comment typo in Transaction.php
  Datastore/src/Transaction.php
Labels: api: datastore, cla: yes

#1050 Prepare v0.64.0
  BigQueryDataTransfer/VERSION
  Bigtable/VERSION
  Container/VERSION
  Core/VERSION
  Dataproc/VERSION
  Datastore/VERSION
  Datastore/src/DatastoreClient.php
  Dialogflow/VERSION
  Dlp/VERSION
  ErrorReporting/VERSION
  Firestore/VERSION
  Firestore/src/FirestoreClient.php
  Iot/VERSION
  Language/VERSION
  Language/src/LanguageClient.php
  Logging/VERSION
  Logging/src/LoggingClient.php
  Monitoring/VERSION
  OsLogin/VERSION
  PubSub/VERSION
  PubSub/src/PubSubClient.php
  README.md
  Redis/VERSION
  Spanner/VERSION
  Spanner/src/SpannerClient.php
  Speech/VERSION
  Speech/src/SpeechClient.php
  Trace/VERSION
  Trace/src/TraceClient.php
  VideoIntelligence/VERSION
  Vision/VERSION
  Vision/src/VisionClient.php
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: cla: yes

#1019 Introduce Cloud KMS key name support
  Storage/src/Bucket.php
  Storage/src/StorageClient.php
  Storage/src/StorageObject.php
  Storage/tests/Snippet/BucketTest.php
  Storage/tests/System/KmsTest.php
  Storage/tests/System/ManageNotificationsTest.php
  Storage/tests/System/StorageTestCase.php
Labels: api: storage, cla: yes, do not merge

#1054 Support reading and writing empty geopoint values
  Core/src/GeoPoint.php
  Core/tests/Unit/GeoPointTest.php
  Datastore/src/EntityMapper.php
  Datastore/tests/System/SaveAndModifyTest.php
  Datastore/tests/Unit/EntityMapperTest.php
Labels: api: datastore, cla: yes

#1058 Prepare v0.65.0
  Core/VERSION
  Datastore/VERSION
  Datastore/src/DatastoreClient.php
  Redis/VERSION
  Storage/VERSION
  Storage/src/StorageClient.php
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: cla: yes

#1064 Replace abandoned dev dependency in unit test
  composer.json
  tests/Unit/JsonFileTest.php
Labels: cla: yes

#1065 Remove default version arg, pick up latest proto changes
  BigQueryDataTransfer/src/V1/Gapic/DataTransferServiceGapicClient.php
  Bigtable/src/Admin/V2/Gapic/BigtableInstanceAdminGapicClient.php
  Bigtable/src/Admin/V2/Gapic/BigtableTableAdminGapicClient.php
  Bigtable/src/V2/Gapic/BigtableGapicClient.php
  Container/src/V1/Gapic/ClusterManagerGapicClient.php
  Dataproc/src/V1/Gapic/ClusterControllerGapicClient.php
  Dataproc/src/V1/Gapic/JobControllerGapicClient.php
  Debugger/src/V2/Gapic/Controller2GapicClient.php
  Debugger/src/V2/Gapic/Debugger2GapicClient.php
  Dialogflow/src/V2/Gapic/AgentsGapicClient.php
  Dialogflow/src/V2/Gapic/ContextsGapicClient.php
  Dialogflow/src/V2/Gapic/EntityTypesGapicClient.php
  Dialogflow/src/V2/Gapic/IntentsGapicClient.php
  Dialogflow/src/V2/Gapic/SessionEntityTypesGapicClient.php
  Dialogflow/src/V2/Gapic/SessionsGapicClient.php
  Dlp/src/V2/Gapic/DlpServiceGapicClient.php
  Dlp/src/V2/resources/dlp_service_rest_client_config.php
  ErrorReporting/src/V1beta1/Gapic/ErrorGroupServiceGapicClient.php
  ErrorReporting/src/V1beta1/Gapic/ErrorStatsServiceGapicClient.php
  ErrorReporting/src/V1beta1/Gapic/ReportErrorsServiceGapicClient.php
  Firestore/src/V1beta1/Gapic/FirestoreGapicClient.php
  Iot/src/V1/Gapic/DeviceManagerGapicClient.php
  Language/src/V1beta2/Gapic/LanguageServiceGapicClient.php
  Logging/src/V2/Gapic/ConfigServiceV2GapicClient.php
  Logging/src/V2/Gapic/LoggingServiceV2GapicClient.php
  Logging/src/V2/Gapic/MetricsServiceV2GapicClient.php
  Monitoring/src/V3/Gapic/AlertPolicyServiceGapicClient.php
  Monitoring/src/V3/Gapic/GroupServiceGapicClient.php
  Monitoring/src/V3/Gapic/MetricServiceGapicClient.php
  Monitoring/src/V3/Gapic/NotificationChannelServiceGapicClient.php
  Monitoring/src/V3/Gapic/UptimeCheckServiceGapicClient.php
  OsLogin/src/V1beta/Gapic/OsLoginServiceGapicClient.php
  PubSub/src/V1/Gapic/PublisherGapicClient.php
  PubSub/src/V1/Gapic/SubscriberGapicClient.php
  Redis/src/V1beta1/Gapic/CloudRedisGapicClient.php
  Spanner/src/Admin/Database/V1/Gapic/DatabaseAdminGapicClient.php
  Spanner/src/Admin/Instance/V1/Gapic/InstanceAdminGapicClient.php
  Spanner/src/V1/Gapic/SpannerGapicClient.php
  Speech/src/V1/Gapic/SpeechGapicClient.php
  Speech/src/V1beta1/Gapic/SpeechGapicClient.php
  Trace/src/V2/Gapic/TraceServiceGapicClient.php
  VideoIntelligence/src/V1/Gapic/VideoIntelligenceServiceGapicClient.php
  VideoIntelligence/src/V1beta2/Gapic/VideoIntelligenceServiceGapicClient.php
  Vision/src/V1/Gapic/ImageAnnotatorGapicClient.php
Labels: cla: yes

#1067 Remove code coverage from unit tests
  dev/sh/tests
Labels: cla: yes

#1066 Add speech v1p1beta1 API
  Speech/src/V1p1beta1/Gapic/SpeechGapicClient.php
  Speech/src/V1p1beta1/README.md
  Speech/src/V1p1beta1/SpeechClient.php
  Speech/src/V1p1beta1/resources/speech_client_config.json
  Speech/src/V1p1beta1/resources/speech_descriptor_config.php
  Speech/src/V1p1beta1/resources/speech_rest_client_config.php
  docs/contents/cloud-speech.json
Labels: cla: yes

#1068 Bump versions of gax and proto-client
  BigQueryDataTransfer/composer.json
  Bigtable/composer.json
  Container/composer.json
  Core/composer.json
  Dataproc/composer.json
  Dialogflow/composer.json
  Dlp/composer.json
  ErrorReporting/composer.json
  Firestore/composer.json
  Iot/composer.json
  Language/composer.json
  Logging/composer.json
  Monitoring/composer.json
  OsLogin/composer.json
  PubSub/composer.json
  Redis/composer.json
  Spanner/composer.json
  Speech/composer.json
  Trace/composer.json
  VideoIntelligence/composer.json
  Vision/composer.json
  composer.json
Labels: cla: yes

#1071 Ensure releasing a session after pool has been cleared does not error
  Spanner/src/Session/CacheSessionPool.php
  Spanner/tests/Unit/Session/CacheSessionPoolTest.php
Labels: api: spanner, cla: yes

#1072 Prepare v0.66.1
  Spanner/VERSION
  Spanner/src/SpannerClient.php
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: cla: yes

#1027 Trace: Add Grpc connection interface
  Trace/composer.json
  Trace/src/Annotation.php
  Trace/src/Attributes.php
  Trace/src/Connection/ConnectionInterface.php
  Trace/src/Connection/Grpc.php
  Trace/src/Connection/Rest.php
  Trace/src/Link.php
  Trace/src/MessageEvent.php
  Trace/src/Span.php
  Trace/src/StackTrace.php
  Trace/src/Status.php
  Trace/src/TimeEvent.php
  Trace/src/Trace.php
  Trace/src/TraceClient.php
  Trace/tests/System/BasicTest.php
  Trace/tests/Unit/AnnotationTest.php
  Trace/tests/Unit/AttributesTest.php
  Trace/tests/Unit/Connection/GrpcTest.php
  Trace/tests/Unit/LinkTest.php
  Trace/tests/Unit/MessageEventTest.php
  Trace/tests/Unit/SpanTest.php
  Trace/tests/Unit/StackTraceTest.php
  Trace/tests/Unit/StatusTest.php
Labels: api: trace, cla: yes

#1037 Debugger: Add Grpc connection
  Debugger/composer.json
  Debugger/src/AliasContext.php
  Debugger/src/Breakpoint.php
  Debugger/src/CloudRepoSourceContext.php
  Debugger/src/CloudWorkspaceId.php
  Debugger/src/CloudWorkspaceSourceContext.php
  Debugger/src/Connection/Grpc.php
  Debugger/src/Connection/Rest.php
  Debugger/src/Debuggee.php
  Debugger/src/DebuggerClient.php
  Debugger/src/ExtendedSourceContext.php
  Debugger/src/FormatMessage.php
  Debugger/src/GerritSourceContext.php
  Debugger/src/GitSourceContext.php
  Debugger/src/ProjectRepoId.php
  Debugger/src/RepoId.php
  Debugger/src/SourceContext.php
  Debugger/src/SourceLocation.php
  Debugger/src/StackFrame.php
  Debugger/src/StatusMessage.php
  Debugger/src/Variable.php
  Debugger/src/VariableTable.php
  Debugger/tests/Snippet/ExtendedSourceContextTest.php
  Debugger/tests/System/BasicTest.php
  Debugger/tests/Unit/AliasContextTest.php
  Debugger/tests/Unit/BreakpointTest.php
  Debugger/tests/Unit/BreakpointValidationTest.php
  Debugger/tests/Unit/CloudRepoSourceContextTest.php
  Debugger/tests/Unit/CloudWorkspaceIdTest.php
  Debugger/tests/Unit/CloudWorkspaceSourceContextTest.php
  Debugger/tests/Unit/Connection/GrpcTest.php
  Debugger/tests/Unit/DebuggeeTest.php
  Debugger/tests/Unit/ExtendedSourceContextTest.php
  Debugger/tests/Unit/FormatMessageTest.php
  Debugger/tests/Unit/GerritSourceContextTest.php
  Debugger/tests/Unit/GitSourceContextTest.php
  Debugger/tests/Unit/JsonTestTrait.php
  Debugger/tests/Unit/ProjectRepoIdTest.php
  Debugger/tests/Unit/RepoIdTest.php
  Debugger/tests/Unit/SourceLocationTest.php
  Debugger/tests/Unit/StackFrameTest.php
  Debugger/tests/Unit/StatusMessageTest.php
  Debugger/tests/Unit/VariableTableTest.php
  Debugger/tests/Unit/VariableTest.php
Labels: api: debugger, cla: yes

#1074 Add .gitattributes
  .gitattributes
  BigQuery/.gitattributes
  BigQueryDataTransfer/.gitattributes
  Bigtable/.gitattributes
  Container/.gitattributes
  Core/.gitattributes
  Dataproc/.gitattributes
  Datastore/.gitattributes
  Debugger/.gitattributes
  Dialogflow/.gitattributes
  ErrorReporting/.gitattributes
  Firestore/.gitattributes
  Iot/.gitattributes
  Language/.gitattributes
  Logging/.gitattributes
  Monitoring/.gitattributes
  OsLogin/.gitattributes
  PubSub/.gitattributes
  Redis/.gitattributes
  Spanner/.gitattributes
  Speech/.gitattributes
  Storage/.gitattributes
  Trace/.gitattributes
  Translate/.gitattributes
  VideoIntelligence/.gitattributes
  Vision/.gitattributes
  dev/src/AddComponent/Command/AddComponent.php
  dev/src/AddComponent/GitAttributes.php
  dev/src/AddComponent/templates/template-gitattributes.txt
Labels: cla: yes

#1075 Regenerate Vision V1
  BigQueryDataTransfer/composer.json
  Bigtable/composer.json
  Container/composer.json
  Dataproc/composer.json
  Debugger/composer.json
  Dialogflow/composer.json
  Dlp/composer.json
  ErrorReporting/composer.json
  Firestore/composer.json
  Iot/composer.json
  Language/composer.json
  Logging/composer.json
  Monitoring/composer.json
  OsLogin/composer.json
  PubSub/composer.json
  Redis/composer.json
  Spanner/composer.json
  Speech/composer.json
  Trace/composer.json
  VideoIntelligence/composer.json
  Vision/composer.json
  Vision/src/V1/Gapic/ImageAnnotatorGapicClient.php
  Vision/src/V1/resources/image_annotator_client_config.json
  Vision/src/V1/resources/image_annotator_descriptor_config.php
  Vision/src/V1/resources/image_annotator_rest_client_config.php
  composer.json
Labels: api: vision, cla: yes

#1077 Prepare v0.67.0
  BigQuery/VERSION
  BigQuery/src/BigQueryClient.php
  BigQueryDataTransfer/VERSION
  Bigtable/VERSION
  Container/VERSION
  Core/VERSION
  Dataproc/VERSION
  Datastore/VERSION
  Datastore/src/DatastoreClient.php
  Debugger/VERSION
  Debugger/src/DebuggerClient.php
  Dialogflow/VERSION
  Dlp/VERSION
  ErrorReporting/VERSION
  Firestore/VERSION
  Firestore/src/FirestoreClient.php
  Iot/VERSION
  Language/VERSION
  Language/src/LanguageClient.php
  Logging/VERSION
  Logging/src/LoggingClient.php
  Monitoring/VERSION
  OsLogin/VERSION
  PubSub/VERSION
  PubSub/src/PubSubClient.php
  Redis/VERSION
  Spanner/VERSION
  Spanner/src/SpannerClient.php
  Speech/VERSION
  Speech/src/SpeechClient.php
  Storage/VERSION
  Storage/src/StorageClient.php
  Trace/VERSION
  Trace/src/TraceClient.php
  Translate/VERSION
  Translate/src/TranslateClient.php
  VideoIntelligence/VERSION
  Vision/VERSION
  Vision/src/VisionClient.php
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: cla: yes
