Repository googleapis/google-cloud-php, pull requests merged in 2020-11, with the labels that each got.

#3539 chore: update grpc dependency to v1.33.1
  Translate/src/V3/TranslationServiceGrpcClient.php
  Translate/synth.metadata
Labels: cla: yes, context: partial

#3536 chore: update grpc dependency to v1.33.1
  Gaming/src/V1/GameServerClustersServiceGrpcClient.php
  Gaming/src/V1/GameServerConfigsServiceGrpcClient.php
  Gaming/src/V1/GameServerDeploymentsServiceGrpcClient.php
  Gaming/src/V1/RealmsServiceGrpcClient.php
  Gaming/synth.metadata
Labels: cla: yes, context: partial

#3540 test: run PubSub system tests against emulator
  .github/emulator/pubsub.sh
  .github/workflows/pubsub-emulator-system-tests.yaml
  .github/workflows/spanner-emulator-system-tests.yaml
Labels: api: pubsub, cla: yes

#3407 feat: [breaking v1beta1] createSecret method signature change
  SecretManager/metadata/V1/Resources.php
  SecretManager/metadata/V1/Service.php
  SecretManager/metadata/V1Beta1/Resources.php
  SecretManager/metadata/V1Beta1/Service.php
  SecretManager/src/V1/AccessSecretVersionResponse.php
  SecretManager/src/V1/AddSecretVersionRequest.php
  SecretManager/src/V1/CreateSecretRequest.php
  SecretManager/src/V1/Replication.php
  SecretManager/src/V1/Secret.php
  SecretManager/src/V1/SecretManagerServiceGrpcClient.php
  SecretManager/src/V1/SecretPayload.php
  SecretManager/src/V1/SecretVersion.php
  SecretManager/src/V1/UpdateSecretRequest.php
  SecretManager/src/V1/resources/secret_manager_service_client_config.json
  SecretManager/src/V1beta1/AccessSecretVersionResponse.php
  SecretManager/src/V1beta1/AddSecretVersionRequest.php
  SecretManager/src/V1beta1/CreateSecretRequest.php
  SecretManager/src/V1beta1/Gapic/SecretManagerServiceGapicClient.php
  SecretManager/src/V1beta1/Replication.php
  SecretManager/src/V1beta1/Secret.php
  SecretManager/src/V1beta1/SecretManagerServiceGrpcClient.php
  SecretManager/src/V1beta1/SecretVersion.php
  SecretManager/src/V1beta1/UpdateSecretRequest.php
  SecretManager/src/V1beta1/resources/secret_manager_service_client_config.json
  SecretManager/synth.metadata
  SecretManager/tests/Unit/V1beta1/SecretManagerServiceClientTest.php
Labels: cla: yes, context: full

#3544 chore: release 0.144.0
  CHANGELOG.md
  Gaming/VERSION
  RecommendationEngine/VERSION
  SecretManager/VERSION
  Translate/VERSION
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: autorelease: pending, cla: yes

#3548 feat: add customer managed encryption
  SecretManager/metadata/V1/Resources.php
  SecretManager/src/V1/CustomerManagedEncryption.php
  SecretManager/src/V1/CustomerManagedEncryptionStatus.php
  SecretManager/src/V1/Replication.php
  SecretManager/src/V1/Replication/Automatic.php
  SecretManager/src/V1/Replication/UserManaged/Replica.php
  SecretManager/src/V1/ReplicationStatus.php
  SecretManager/src/V1/ReplicationStatus/AutomaticStatus.php
  SecretManager/src/V1/ReplicationStatus/UserManagedStatus.php
  SecretManager/src/V1/ReplicationStatus/UserManagedStatus/ReplicaStatus.php
  SecretManager/src/V1/ReplicationStatus_AutomaticStatus.php
  SecretManager/src/V1/ReplicationStatus_UserManagedStatus.php
  SecretManager/src/V1/ReplicationStatus_UserManagedStatus_ReplicaStatus.php
  SecretManager/src/V1/SecretManagerServiceGrpcClient.php
  SecretManager/src/V1/SecretVersion.php
  SecretManager/src/V1beta1/SecretManagerServiceGrpcClient.php
  SecretManager/synth.metadata
Labels: cla: yes, context: full

#3552 chore: update metadata
  WebSecurityScanner/metadata/V1Beta/CrawledUrl.php
  WebSecurityScanner/metadata/V1Beta/Finding.php
  WebSecurityScanner/metadata/V1Beta/FindingAddon.php
  WebSecurityScanner/metadata/V1Beta/FindingTypeStats.php
  WebSecurityScanner/metadata/V1Beta/ScanConfig.php
  WebSecurityScanner/metadata/V1Beta/ScanConfigError.php
  WebSecurityScanner/metadata/V1Beta/ScanRun.php
  WebSecurityScanner/metadata/V1Beta/ScanRunErrorTrace.php
  WebSecurityScanner/metadata/V1Beta/ScanRunWarningTrace.php
  WebSecurityScanner/metadata/V1Beta/WebSecurityScanner.php
  WebSecurityScanner/synth.metadata
Labels: cla: yes, context: full

#3555 feat: introduce workflows client
  README.md
  Workflows/.gitattributes
  Workflows/.github/pull_request_template.md
  Workflows/.repo-metadata.json
  Workflows/CONTRIBUTING.md
  Workflows/LICENSE
  Workflows/README.md
  Workflows/VERSION
  Workflows/composer.json
  Workflows/metadata/Executions/V1Beta/Executions.php
  Workflows/metadata/V1Beta/Workflows.php
  Workflows/phpunit-snippets.xml.dist
  Workflows/phpunit-system.xml.dist
  Workflows/phpunit.xml.dist
  Workflows/src/Executions/V1beta/CancelExecutionRequest.php
  Workflows/src/Executions/V1beta/CreateExecutionRequest.php
  Workflows/src/Executions/V1beta/Execution.php
  Workflows/src/Executions/V1beta/Execution/Error.php
  Workflows/src/Executions/V1beta/Execution/State.php
  Workflows/src/Executions/V1beta/ExecutionView.php
  Workflows/src/Executions/V1beta/Execution_Error.php
  Workflows/src/Executions/V1beta/Execution_State.php
  Workflows/src/Executions/V1beta/ExecutionsClient.php
  Workflows/src/Executions/V1beta/ExecutionsGrpcClient.php
  Workflows/src/Executions/V1beta/Gapic/ExecutionsGapicClient.php
  Workflows/src/Executions/V1beta/GetExecutionRequest.php
  Workflows/src/Executions/V1beta/ListExecutionsRequest.php
  Workflows/src/Executions/V1beta/ListExecutionsResponse.php
  Workflows/src/Executions/V1beta/README.md
  Workflows/src/Executions/V1beta/resources/executions_client_config.json
  Workflows/src/Executions/V1beta/resources/executions_descriptor_config.php
  Workflows/src/Executions/V1beta/resources/executions_rest_client_config.php
  Workflows/src/V1beta/CreateWorkflowRequest.php
  Workflows/src/V1beta/DeleteWorkflowRequest.php
  Workflows/src/V1beta/Gapic/WorkflowsGapicClient.php
  Workflows/src/V1beta/GetWorkflowRequest.php
  Workflows/src/V1beta/ListWorkflowsRequest.php
  Workflows/src/V1beta/ListWorkflowsResponse.php
  Workflows/src/V1beta/OperationMetadata.php
  Workflows/src/V1beta/README.md
  Workflows/src/V1beta/UpdateWorkflowRequest.php
  Workflows/src/V1beta/Workflow.php
  Workflows/src/V1beta/Workflow/State.php
  Workflows/src/V1beta/Workflow_State.php
  Workflows/src/V1beta/WorkflowsClient.php
  Workflows/src/V1beta/WorkflowsGrpcClient.php
  Workflows/src/V1beta/resources/workflows_client_config.json
  Workflows/src/V1beta/resources/workflows_descriptor_config.php
  Workflows/src/V1beta/resources/workflows_rest_client_config.php
  Workflows/synth.metadata
  Workflows/synth.py
  Workflows/tests/Unit/Executions/V1beta/ExecutionsClientTest.php
  Workflows/tests/Unit/V1beta/WorkflowsClientTest.php
  composer.json
  docs/contents/cloud-workflows.json
  docs/contents/google-cloud.json
  docs/manifest.json
Labels: cla: yes

#3556 chore: release 0.145.0
  CHANGELOG.md
  SecretManager/VERSION
  WebSecurityScanner/VERSION
  Workflows/VERSION
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: autorelease: pending, cla: yes

#3553 ci: fix Bigtable testing
  .github/workflows/bigtable-emulator-system-tests.yaml
Labels: cla: yes

#3559 fix: correct metadata namespace for datastore admin
  DatastoreAdmin/composer.json
  composer.json
Labels: cla: yes

#3563 chore: update metadata
  RecommendationEngine/metadata/V1Beta1/RecommendationengineResources.php
  RecommendationEngine/synth.metadata
Labels: cla: yes, context: full

#3608 chore: update gapic-generator to v2.8.0
  Vision/src/V1/Gapic/ImageAnnotatorGapicClient.php
  Vision/src/V1/Gapic/ProductSearchGapicClient.php
  Vision/synth.metadata
Labels: cla: yes, context: full

#3613 feat: introduce assured workloads
  AssuredWorkloads/.gitattributes
  AssuredWorkloads/.github/pull_request_template.md
  AssuredWorkloads/.repo-metadata.json
  AssuredWorkloads/CONTRIBUTING.md
  AssuredWorkloads/LICENSE
  AssuredWorkloads/README.md
  AssuredWorkloads/VERSION
  AssuredWorkloads/composer.json
  AssuredWorkloads/metadata/V1Beta1/AssuredworkloadsV1Beta1.php
  AssuredWorkloads/phpunit-snippets.xml.dist
  AssuredWorkloads/phpunit-system.xml.dist
  AssuredWorkloads/phpunit.xml.dist
  AssuredWorkloads/src/V1beta1/AssuredWorkloadsServiceClient.php
  AssuredWorkloads/src/V1beta1/AssuredWorkloadsServiceGrpcClient.php
  AssuredWorkloads/src/V1beta1/CreateWorkloadOperationMetadata.php
  AssuredWorkloads/src/V1beta1/CreateWorkloadRequest.php
  AssuredWorkloads/src/V1beta1/DeleteWorkloadRequest.php
  AssuredWorkloads/src/V1beta1/Gapic/AssuredWorkloadsServiceGapicClient.php
  AssuredWorkloads/src/V1beta1/GetWorkloadRequest.php
  AssuredWorkloads/src/V1beta1/ListWorkloadsRequest.php
  AssuredWorkloads/src/V1beta1/ListWorkloadsResponse.php
  AssuredWorkloads/src/V1beta1/README.md
  AssuredWorkloads/src/V1beta1/UpdateWorkloadRequest.php
  AssuredWorkloads/src/V1beta1/Workload.php
  AssuredWorkloads/src/V1beta1/Workload/CJISSettings.php
  AssuredWorkloads/src/V1beta1/Workload/ComplianceRegime.php
  AssuredWorkloads/src/V1beta1/Workload/FedrampHighSettings.php
  AssuredWorkloads/src/V1beta1/Workload/FedrampModerateSettings.php
  AssuredWorkloads/src/V1beta1/Workload/IL4Settings.php
  AssuredWorkloads/src/V1beta1/Workload/KMSSettings.php
  AssuredWorkloads/src/V1beta1/Workload/ResourceInfo.php
  AssuredWorkloads/src/V1beta1/Workload/ResourceInfo/ResourceType.php
  AssuredWorkloads/src/V1beta1/Workload_CJISSettings.php
  AssuredWorkloads/src/V1beta1/Workload_ComplianceRegime.php
  AssuredWorkloads/src/V1beta1/Workload_FedrampHighSettings.php
  AssuredWorkloads/src/V1beta1/Workload_FedrampModerateSettings.php
  AssuredWorkloads/src/V1beta1/Workload_IL4Settings.php
  AssuredWorkloads/src/V1beta1/Workload_KMSSettings.php
  AssuredWorkloads/src/V1beta1/Workload_ResourceInfo.php
  AssuredWorkloads/src/V1beta1/Workload_ResourceInfo_ResourceType.php
  AssuredWorkloads/src/V1beta1/resources/assured_workloads_service_client_config.json
  AssuredWorkloads/src/V1beta1/resources/assured_workloads_service_descriptor_config.php
  AssuredWorkloads/src/V1beta1/resources/assured_workloads_service_rest_client_config.php
  AssuredWorkloads/synth.metadata
  AssuredWorkloads/synth.py
  AssuredWorkloads/tests/Unit/V1beta1/AssuredWorkloadsServiceClientTest.php
  README.md
  composer.json
  docs/contents/cloud-assured-workloads.json
  docs/contents/google-cloud.json
  docs/manifest.json
Labels: cla: yes

#3614 chore: release 0.146.0
  AnalyticsAdmin/VERSION
  AnalyticsData/VERSION
  AssuredWorkloads/VERSION
  CHANGELOG.md
  DatastoreAdmin/VERSION
  RecommendationEngine/VERSION
  Vision/VERSION
  Vision/src/VisionClient.php
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: autorelease: pending, cla: yes

#3570 feat: add support for the not equal (!=) operator
  Firestore/src/Query.php
  Firestore/tests/Unit/QueryTest.php
  Firestore/tests/Unit/conformance/v1/query-invalid-operator.json
Labels: cla: yes

#3617 chore: fix docs generation
  .github/workflows/docs.yml
Labels: cla: yes
