Repository googleapis/google-cloud-php, pull requests merged in 2020-04, with the labels that each got.

#2819 chore: remove experimental flag
  Speech/src/V1/Gapic/SpeechGapicClient.php
  Speech/src/V1/SpeechClient.php
  Speech/synth.metadata
Labels: api: speech, cla: yes

#2818 docs: update documentation
  SecretManager/src/V1/CreateSecretRequest.php
  SecretManager/src/V1/Gapic/SecretManagerServiceGapicClient.php
  SecretManager/src/V1beta1/CreateSecretRequest.php
  SecretManager/src/V1beta1/Gapic/SecretManagerServiceGapicClient.php
  SecretManager/synth.metadata
Labels: api: secretmanager, cla: yes

#2817 chore: remove experimental flag
  OsLogin/src/V1/Gapic/OsLoginServiceGapicClient.php
  OsLogin/src/V1/OsLoginServiceClient.php
  OsLogin/synth.metadata
Labels: api: oslogin, cla: yes

#2821 chore: update synth script to include iot client
  Iot/synth.py
Labels: api: cloudiot, cla: yes

#2822 chore: replace deprecated constant reference
  Logging/src/Connection/Grpc.php
Labels: api: logging, cla: yes

#2823 feat: add new entry options
  Logging/src/Logger.php
Labels: api: logging, cla: yes

#2833 feat: add formatting method
  PubSub/src/V1/Gapic/PublisherGapicClient.php
  PubSub/src/V1/Gapic/SubscriberGapicClient.php
  PubSub/synth.metadata
  PubSub/tests/Unit/V1/PublisherClientTest.php
  PubSub/tests/Unit/V1/SubscriberClientTest.php
Labels: api: pubsub, cla: yes

#2827 feat: add first party oauth authorization type
  BigQueryDataTransfer/metadata/V1/Datatransfer.php
  BigQueryDataTransfer/src/V1/DataSource/AuthorizationType.php
  BigQueryDataTransfer/src/V1/DataTransferServiceGrpcClient.php
  BigQueryDataTransfer/src/V1/Gapic/DataTransferServiceGapicClient.php
  BigQueryDataTransfer/synth.metadata
Labels: api: bigquerydatatransfer, cla: yes

#2835 feat: add formatting methods
  Talent/src/V4beta1/Gapic/ApplicationServiceGapicClient.php
  Talent/src/V4beta1/Gapic/CompanyServiceGapicClient.php
  Talent/src/V4beta1/Gapic/CompletionGapicClient.php
  Talent/src/V4beta1/Gapic/JobServiceGapicClient.php
  Talent/synth.metadata
  Talent/tests/Unit/V4beta1/CompanyServiceClientTest.php
  Talent/tests/Unit/V4beta1/JobServiceClientTest.php
Labels: api: talent, cla: yes

#2834 feat: add formatting methods
  SecurityCenter/src/V1/Gapic/SecurityCenterGapicClient.php
  SecurityCenter/src/V1p1beta1/Gapic/SecurityCenterGapicClient.php
  SecurityCenter/synth.metadata
Labels: api: securitycenter, cla: yes

#2831 docs: fix copyright year
  Iot/src/V1/DeviceManagerGrpcClient.php
  Iot/synth.metadata
Labels: api: cloudiot, cla: yes

#2828 feat: add formatting methods
  Dataproc/metadata/V1/AutoscalingPolicies.php
  Dataproc/metadata/V1Beta2/AutoscalingPolicies.php
  Dataproc/metadata/V1Beta2/WorkflowTemplates.php
  Dataproc/src/V1/CreateAutoscalingPolicyRequest.php
  Dataproc/src/V1/Gapic/AutoscalingPolicyServiceGapicClient.php
  Dataproc/src/V1/Gapic/WorkflowTemplateServiceGapicClient.php
  Dataproc/src/V1/resources/autoscaling_policy_service_client_config.json
  Dataproc/src/V1/resources/autoscaling_policy_service_rest_client_config.php
  Dataproc/src/V1/resources/cluster_controller_client_config.json
  Dataproc/src/V1/resources/cluster_controller_descriptor_config.php
  Dataproc/src/V1/resources/job_controller_client_config.json
  Dataproc/src/V1/resources/workflow_template_service_client_config.json
  Dataproc/src/V1/resources/workflow_template_service_descriptor_config.php
  Dataproc/src/V1beta2/Gapic/AutoscalingPolicyServiceGapicClient.php
  Dataproc/src/V1beta2/Gapic/WorkflowTemplateServiceGapicClient.php
  Dataproc/src/V1beta2/ListWorkflowTemplatesRequest.php
  Dataproc/src/V1beta2/OrderedJob.php
  Dataproc/src/V1beta2/TemplateParameter.php
  Dataproc/src/V1beta2/UpdateAutoscalingPolicyRequest.php
  Dataproc/src/V1beta2/WorkflowTemplateServiceGrpcClient.php
  Dataproc/src/V1beta2/resources/autoscaling_policy_service_client_config.json
  Dataproc/src/V1beta2/resources/cluster_controller_client_config.json
  Dataproc/src/V1beta2/resources/cluster_controller_descriptor_config.php
  Dataproc/src/V1beta2/resources/job_controller_client_config.json
  Dataproc/src/V1beta2/resources/workflow_template_service_client_config.json
  Dataproc/src/V1beta2/resources/workflow_template_service_descriptor_config.php
  Dataproc/synth.metadata
  Dataproc/tests/Unit/V1/AutoscalingPolicyServiceClientTest.php
  Dataproc/tests/Unit/V1/WorkflowTemplateServiceClientTest.php
  Dataproc/tests/Unit/V1beta2/AutoscalingPolicyServiceClientTest.php
  Dataproc/tests/Unit/V1beta2/WorkflowTemplateServiceClientTest.php
Labels: api: dataproc, cla: yes

#2826 feat: update clients
  Asset/metadata/V1/AssetService.php
  Asset/metadata/V1/Assets.php
  Asset/src/V1/Asset.php
  Asset/src/V1/AssetServiceGrpcClient.php
  Asset/src/V1/BatchGetAssetsHistoryRequest.php
  Asset/src/V1/BigQueryDestination.php
  Asset/src/V1/ExportAssetsRequest.php
  Asset/src/V1/Feed.php
  Asset/src/V1/FeedOutputConfig.php
  Asset/src/V1/Gapic/AssetServiceGapicClient.php
  Asset/src/V1/PubsubDestination.php
  Asset/src/V1/Resource.php
  Asset/src/V1/TemporalAsset.php
  Asset/src/V1/TimeWindow.php
  Asset/synth.metadata
Labels: api: cloudasset, cla: yes

#2845 chore: Migrate all synth.py scripts from artman to bazel
  Asset/synth.py
  AutoMl/synth.py
  BigQueryDataTransfer/synth.py
  Bigtable/synth.py
  Billing/synth.py
  Container/synth.py
  Dataproc/synth.py
  Datastore/synth.py
  Debugger/synth.py
  Dialogflow/synth.py
  Dlp/synth.py
  ErrorReporting/synth.py
  Firestore/synth.py
  Iot/synth.py
  Kms/synth.py
  Language/synth.py
  Logging/synth.py
  Monitoring/synth.py
  OsLogin/synth.py
  PubSub/synth.py
  Recommender/synth.py
  Redis/synth.py
  Scheduler/synth.py
  SecretManager/synth.py
  SecurityCenter/synth.py
  ServiceDirectory/synth.py
  Spanner/synth.py
  Speech/synth.py
  Talent/synth.py
  Tasks/synth.py
  TextToSpeech/synth.py
  Trace/synth.py
  Translate/synth.py
  VideoIntelligence/synth.py
  Vision/synth.py
  WebRisk/synth.py
  WebSecurityScanner/synth.py
Labels: cla: yes, kokoro:force-run

#2844 chore: update metadata
  OsLogin/metadata/V1/Oslogin.php
  OsLogin/metadata/V1Beta/Oslogin.php
  OsLogin/synth.metadata
Labels: cla: yes

#2860 chore: update metadata
  WebRisk/metadata/V1Beta1/Webrisk.php
  WebRisk/synth.metadata
Labels: cla: yes

#2859 chore: update docs to use new helper
  Talent/src/V4beta1/Gapic/CompanyServiceGapicClient.php
  Talent/src/V4beta1/Gapic/CompletionGapicClient.php
  Talent/src/V4beta1/Gapic/EventServiceGapicClient.php
  Talent/src/V4beta1/Gapic/JobServiceGapicClient.php
  Talent/synth.metadata
  Talent/tests/Unit/V4beta1/CompanyServiceClientTest.php
  Talent/tests/Unit/V4beta1/CompletionClientTest.php
  Talent/tests/Unit/V4beta1/EventServiceClientTest.php
  Talent/tests/Unit/V4beta1/JobServiceClientTest.php
Labels: api: talent, cla: yes

#2858 feat!: remove projectName helper and upate timeouts
  Scheduler/src/V1beta1/Gapic/CloudSchedulerGapicClient.php
  Scheduler/src/V1beta1/resources/cloud_scheduler_client_config.json
  Scheduler/synth.metadata
Labels: cla: yes

#2857 feat: add new snapshot methods
  PubSub/src/V1/Gapic/PublisherGapicClient.php
  PubSub/src/V1/Gapic/SubscriberGapicClient.php
  PubSub/src/V1/PushConfig.php
  PubSub/src/V1/resources/publisher_client_config.json
  PubSub/src/V1/resources/publisher_descriptor_config.php
  PubSub/src/V1/resources/publisher_rest_client_config.php
  PubSub/src/V1/resources/subscriber_client_config.json
  PubSub/src/V1/resources/subscriber_rest_client_config.php
  PubSub/synth.metadata
  PubSub/tests/Unit/V1/PublisherClientTest.php
  PubSub/tests/Unit/V1/SubscriberClientTest.php
Labels: cla: yes

#2856 feat!: remove readonly service scopes
  OsLogin/metadata/Common/Common.php
  OsLogin/src/V1beta/Gapic/OsLoginServiceGapicClient.php
  OsLogin/synth.metadata
Labels: cla: yes

#2855 feat: extend ListTimeSeries timeout and update documentation
  Monitoring/src/V3/Aggregation.php
  Monitoring/src/V3/AlertPolicy/Condition.php
  Monitoring/src/V3/AlertPolicy/Condition/TimeSeriesQueryLanguageCondition.php
  Monitoring/src/V3/QueryTimeSeriesRequest.php
  Monitoring/src/V3/resources/metric_service_client_config.json
  Monitoring/synth.metadata
Labels: cla: yes

#2850 feat: extend GetModelEvaluation timeout
  AutoMl/src/V1/resources/auto_ml_client_config.json
  AutoMl/synth.metadata
Labels: cla: yes

#2851 docs: update generated proto documentation
  Bigtable/src/V2/BigtableGrpcClient.php
  Bigtable/src/V2/CheckAndMutateRowRequest.php
  Bigtable/src/V2/MutateRowRequest.php
  Bigtable/src/V2/MutateRowsRequest.php
  Bigtable/src/V2/MutateRowsRequest/Entry.php
  Bigtable/src/V2/MutateRowsResponse/Entry.php
  Bigtable/src/V2/ReadModifyWriteRowRequest.php
  Bigtable/src/V2/ReadRowsRequest.php
  Bigtable/src/V2/ReadRowsResponse.php
  Bigtable/src/V2/ReadRowsResponse/CellChunk.php
  Bigtable/src/V2/SampleRowKeysRequest.php
  Bigtable/synth.metadata
Labels: cla: yes

#2854 docs: update generated proto documentation
  Language/src/V1/Document.php
  Language/src/V1beta2/AnnotateTextRequest/Features.php
  Language/src/V1beta2/Document.php
  Language/src/V1beta2/Gapic/LanguageServiceGapicClient.php
  Language/synth.metadata
Labels: cla: yes

#2862 chore: move security center to beta
  README.md
  SecurityCenter/README.md
  SecurityCenter/src/V1/Gapic/SecurityCenterGapicClient.php
  SecurityCenter/src/V1/SecurityCenterClient.php
  SecurityCenter/synth.py
Labels: api: securitycenter, cla: yes

#2866 chore: update recommendation-engine -> recommendations-ai
  composer.json
Labels: cla: yes

#2865 chore: update recommendations-ai id/name in manifest
  docs/manifest.json
Labels: cla: yes

#2867 chore: update default VERSION
  RecommendationEngine/VERSION
Labels: cla: yes

#2868 chore: release 0.131.0
  Asset/VERSION
  AutoMl/VERSION
  BigQuery/VERSION
  BigQuery/src/BigQueryClient.php
  BigQueryDataTransfer/VERSION
  Bigtable/VERSION
  Bigtable/src/BigtableClient.php
  Billing/VERSION
  CHANGELOG.md
  CommonProtos/VERSION
  Container/VERSION
  Core/VERSION
  Dataproc/VERSION
  Datastore/VERSION
  Datastore/src/DatastoreClient.php
  Debugger/VERSION
  Debugger/src/DebuggerClient.php
  Dialogflow/VERSION
  Dlp/VERSION
  ErrorReporting/VERSION
  Firestore/VERSION
  Firestore/src/FirestoreClient.php
  Iot/VERSION
  Kms/VERSION
  Language/VERSION
  Language/src/LanguageClient.php
  Logging/VERSION
  Logging/src/LoggingClient.php
  Monitoring/VERSION
  OsLogin/VERSION
  PubSub/VERSION
  PubSub/src/PubSubClient.php
  RecommendationEngine/VERSION
  Recommender/VERSION
  Redis/VERSION
  Scheduler/VERSION
  SecretManager/VERSION
  SecurityCenter/VERSION
  ServiceDirectory/VERSION
  Spanner/VERSION
  Spanner/src/SpannerClient.php
  Speech/VERSION
  Speech/src/SpeechClient.php
  Storage/VERSION
  Storage/src/StorageClient.php
  Talent/VERSION
  Tasks/VERSION
  TextToSpeech/VERSION
  Trace/VERSION
  Trace/src/TraceClient.php
  Translate/VERSION
  VideoIntelligence/VERSION
  Vision/VERSION
  Vision/src/VisionClient.php
  WebRisk/VERSION
  WebSecurityScanner/VERSION
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: autorelease: pending, cla: yes

#2871 chore: update metadata
  BigQueryDataTransfer/metadata/V1/Datatransfer.php
  BigQueryDataTransfer/metadata/V1/Transfer.php
  BigQueryDataTransfer/synth.metadata
Labels: cla: yes

#2872 chore: update metadata
  Container/metadata/V1/ClusterService.php
  Container/synth.metadata
Labels: cla: yes

#2873 docs: update documentation
  Dataproc/src/V1/AcceleratorConfig.php
  Dataproc/src/V1/GceClusterConfig.php
  Dataproc/src/V1/InstanceGroupConfig.php
  Dataproc/src/V1/SoftwareConfig.php
  Dataproc/src/V1beta2/AcceleratorConfig.php
  Dataproc/src/V1beta2/GceClusterConfig.php
  Dataproc/src/V1beta2/InstanceGroupConfig.php
  Dataproc/src/V1beta2/SoftwareConfig.php
  Dataproc/synth.metadata
Labels: cla: yes

#2874 docs: update documentation
  SecurityCenter/src/V1p1beta1/Asset/IamPolicy.php
  SecurityCenter/synth.metadata
Labels: cla: yes

#2876 chore: update metadata
  WebRisk/metadata/V1Beta1/Webrisk.php
  WebRisk/synth.metadata
Labels: cla: yes

#2883 chore: update metadata
  TextToSpeech/metadata/V1/CloudTts.php
  TextToSpeech/synth.metadata
Labels: cla: yes

#2881 chore: update metadata
  Monitoring/metadata/V3/Alert.php
  Monitoring/metadata/V3/AlertService.php
  Monitoring/metadata/V3/Common.php
  Monitoring/metadata/V3/DroppedLabels.php
  Monitoring/metadata/V3/Group.php
  Monitoring/metadata/V3/GroupService.php
  Monitoring/metadata/V3/Metric.php
  Monitoring/metadata/V3/MetricService.php
  Monitoring/metadata/V3/MutationRecord.php
  Monitoring/metadata/V3/Notification.php
  Monitoring/metadata/V3/NotificationService.php
  Monitoring/metadata/V3/Service.php
  Monitoring/metadata/V3/ServiceService.php
  Monitoring/metadata/V3/SpanContext.php
  Monitoring/metadata/V3/Uptime.php
  Monitoring/metadata/V3/UptimeService.php
  Monitoring/synth.metadata
Labels: cla: yes

#2880 docs: update documentation
  Container/src/V1/CancelOperationRequest.php
  Container/src/V1/CompleteIPRotationRequest.php
  Container/src/V1/CreateClusterRequest.php
  Container/src/V1/CreateNodePoolRequest.php
  Container/src/V1/DeleteClusterRequest.php
  Container/src/V1/DeleteNodePoolRequest.php
  Container/src/V1/Gapic/ClusterManagerGapicClient.php
  Container/src/V1/GetClusterRequest.php
  Container/src/V1/GetNodePoolRequest.php
  Container/src/V1/GetOperationRequest.php
  Container/src/V1/GetServerConfigRequest.php
  Container/src/V1/ListClustersRequest.php
  Container/src/V1/ListNodePoolsRequest.php
  Container/src/V1/ListOperationsRequest.php
  Container/src/V1/ListUsableSubnetworksRequest.php
  Container/src/V1/RollbackNodePoolUpgradeRequest.php
  Container/src/V1/SetAddonsConfigRequest.php
  Container/src/V1/SetLabelsRequest.php
  Container/src/V1/SetLegacyAbacRequest.php
  Container/src/V1/SetLocationsRequest.php
  Container/src/V1/SetLoggingServiceRequest.php
  Container/src/V1/SetMaintenancePolicyRequest.php
  Container/src/V1/SetMasterAuthRequest.php
  Container/src/V1/SetMonitoringServiceRequest.php
  Container/src/V1/SetNetworkPolicyRequest.php
  Container/src/V1/SetNodePoolAutoscalingRequest.php
  Container/src/V1/SetNodePoolManagementRequest.php
  Container/src/V1/SetNodePoolSizeRequest.php
  Container/src/V1/StartIPRotationRequest.php
  Container/src/V1/UpdateClusterRequest.php
  Container/src/V1/UpdateMasterRequest.php
  Container/src/V1/UpdateNodePoolRequest.php
  Container/synth.metadata
Labels: cla: yes

#2885 chore: update timeouts and system test
  Language/src/V1beta2/resources/language_service_client_config.json
  Language/synth.metadata
  Language/tests/System/V1beta2/LanguageServiceSmokeTest.php
Labels: cla: yes

#2889 chore: update documentation
  Spanner/metadata/Admin/Database/V1/Backup.php
  Spanner/src/Admin/Database/V1/Backup.php
  Spanner/synth.metadata
Labels: cla: yes

#2888 docs: update documentation
  Monitoring/src/V3/TimeInterval.php
  Monitoring/synth.metadata
Labels: cla: yes

#2906 chore: disable updating v1beta1 client
  Firestore/synth.py
Labels: api: firestore

#2536 fix: encode LRO operation metadata properly
  Core/src/LongRunning/OperationResponseTrait.php
  Core/tests/Unit/LongRunning/OperationResponseTraitTest.php
Labels: api: core, cla: yes

#2837 fix: update spanner lroResponseMappers to map types for `metadata` and `response` separately
  Spanner/src/Connection/Grpc.php
  Spanner/tests/System/BackupTest.php
Labels: api: spanner, cla: yes

#2909 feat(spanner): deserialize response & metadata in operation lists
  Spanner/src/Connection/Grpc.php
  Spanner/tests/System/BackupTest.php
Labels: cla: yes

#2905 feat: add custom classes, phrase sets, long running uri, adaptation configuration, speaker tags
  Speech/metadata/V1P1Beta1/CloudSpeech.php
  Speech/metadata/V1P1Beta1/Resource.php
  Speech/src/V1p1beta1/CustomClass.php
  Speech/src/V1p1beta1/CustomClass/ClassItem.php
  Speech/src/V1p1beta1/CustomClass_ClassItem.php
  Speech/src/V1p1beta1/LongRunningRecognizeMetadata.php
  Speech/src/V1p1beta1/PhraseSet.php
  Speech/src/V1p1beta1/PhraseSet/Phrase.php
  Speech/src/V1p1beta1/PhraseSet_Phrase.php
  Speech/src/V1p1beta1/RecognitionAudio.php
  Speech/src/V1p1beta1/RecognitionConfig.php
  Speech/src/V1p1beta1/RecognitionConfig/AudioEncoding.php
  Speech/src/V1p1beta1/SpeakerDiarizationConfig.php
  Speech/src/V1p1beta1/SpeechAdaptation.php
  Speech/src/V1p1beta1/SpeechGrpcClient.php
  Speech/src/V1p1beta1/SpeechRecognitionResult.php
  Speech/src/V1p1beta1/StreamingRecognitionResult.php
  Speech/src/V1p1beta1/WordInfo.php
  Speech/synth.metadata
Labels: cla: yes

#2904 feat: update backup and restore timeouts
  Spanner/src/Admin/Database/V1/resources/database_admin_client_config.json
  Spanner/synth.metadata
Labels: cla: yes

#2903 docs: update documentation
  PubSub/src/V1/Gapic/PublisherGapicClient.php
  PubSub/src/V1/Gapic/SubscriberGapicClient.php
  PubSub/src/V1/Subscription.php
  PubSub/src/V1/UpdateTopicRequest.php
  PubSub/synth.metadata
Labels: cla: yes

#2902 feat: add external protection level options
  Kms/metadata/V1/Resources.php
  Kms/metadata/V1/Service.php
  Kms/src/V1/CryptoKeyVersion.php
  Kms/src/V1/CryptoKeyVersion/CryptoKeyVersionAlgorithm.php
  Kms/src/V1/ExternalProtectionLevelOptions.php
  Kms/src/V1/KeyManagementServiceGrpcClient.php
  Kms/src/V1/LocationMetadata.php
  Kms/synth.metadata
Labels: cla: yes

#2899 docs: update documentation
  Bigtable/metadata/Admin/V2/Common.php
  Bigtable/metadata/Admin/V2/Instance.php
  Bigtable/metadata/Admin/V2/Table.php
  Bigtable/src/Admin/V2/Cluster.php
  Bigtable/src/Admin/V2/Gapic/BigtableInstanceAdminGapicClient.php
  Bigtable/synth.metadata
Labels: cla: yes

#2898 feat: update timeouts and retry, and documentation
  AutoMl/src/V1/Gapic/AutoMlGapicClient.php
  AutoMl/src/V1/resources/auto_ml_client_config.json
  AutoMl/src/V1/resources/auto_ml_descriptor_config.php
  AutoMl/src/V1/resources/auto_ml_rest_client_config.php
  AutoMl/src/V1/resources/prediction_service_descriptor_config.php
  AutoMl/src/V1beta1/Gapic/AutoMlGapicClient.php
  AutoMl/src/V1beta1/Gapic/PredictionServiceGapicClient.php
  AutoMl/src/V1beta1/resources/auto_ml_client_config.json
  AutoMl/src/V1beta1/resources/auto_ml_descriptor_config.php
  AutoMl/src/V1beta1/resources/auto_ml_rest_client_config.php
  AutoMl/src/V1beta1/resources/prediction_service_descriptor_config.php
  AutoMl/synth.metadata
  AutoMl/tests/Unit/V1/AutoMlClientTest.php
  AutoMl/tests/Unit/V1beta1/AutoMlClientTest.php
  AutoMl/tests/Unit/V1beta1/PredictionServiceClientTest.php
Labels: cla: yes

#2893 feat: add integer range partitioning
  BigQuery/src/Connection/ServiceDefinition/bigquery-v2.json
  BigQuery/src/LoadJobConfiguration.php
  BigQuery/src/QueryJobConfiguration.php
  BigQuery/tests/Snippet/LoadJobConfigurationTest.php
  BigQuery/tests/Snippet/QueryJobConfigurationTest.php
  BigQuery/tests/System/LoadDataAndQueryTest.php
  BigQuery/tests/System/ManageTablesTest.php
  BigQuery/tests/Unit/LoadJobConfigurationTest.php
  BigQuery/tests/Unit/QueryJobConfigurationTest.php
Labels: api: bigquery, cla: yes

#2882 feat!: update formatting method signatures to add tenant id
  Talent/metadata/V4Beta1/Company.php
  Talent/metadata/V4Beta1/Job.php
  Talent/src/V4beta1/Gapic/ApplicationServiceGapicClient.php
  Talent/src/V4beta1/Gapic/CompanyServiceGapicClient.php
  Talent/src/V4beta1/Gapic/CompletionGapicClient.php
  Talent/src/V4beta1/Gapic/JobServiceGapicClient.php
  Talent/synth.metadata
  Talent/tests/Unit/V4beta1/CompanyServiceClientTest.php
  Talent/tests/Unit/V4beta1/JobServiceClientTest.php
Labels: cla: yes

#2915 feat: introduce memorystore for memcached client
  Memcache/.gitattributes
  Memcache/.github/pull_request_template.md
  Memcache/.repo-metadata.json
  Memcache/CONTRIBUTING.md
  Memcache/LICENSE
  Memcache/README.md
  Memcache/VERSION
  Memcache/composer.json
  Memcache/metadata/V1Beta2/CloudMemcache.php
  Memcache/phpunit-snippets.xml.dist
  Memcache/phpunit-system.xml.dist
  Memcache/phpunit.xml.dist
  Memcache/src/V1beta2/ApplyParametersRequest.php
  Memcache/src/V1beta2/CloudMemcacheClient.php
  Memcache/src/V1beta2/CloudMemcacheGrpcClient.php
  Memcache/src/V1beta2/CreateInstanceRequest.php
  Memcache/src/V1beta2/DeleteInstanceRequest.php
  Memcache/src/V1beta2/Gapic/CloudMemcacheGapicClient.php
  Memcache/src/V1beta2/GetInstanceRequest.php
  Memcache/src/V1beta2/Instance.php
  Memcache/src/V1beta2/Instance/InstanceMessage.php
  Memcache/src/V1beta2/Instance/InstanceMessage/Code.php
  Memcache/src/V1beta2/Instance/Node.php
  Memcache/src/V1beta2/Instance/Node/State.php
  Memcache/src/V1beta2/Instance/NodeConfig.php
  Memcache/src/V1beta2/Instance/State.php
  Memcache/src/V1beta2/Instance_InstanceMessage.php
  Memcache/src/V1beta2/Instance_InstanceMessage_Code.php
  Memcache/src/V1beta2/Instance_Node.php
  Memcache/src/V1beta2/Instance_NodeConfig.php
  Memcache/src/V1beta2/Instance_Node_State.php
  Memcache/src/V1beta2/Instance_State.php
  Memcache/src/V1beta2/ListInstancesRequest.php
  Memcache/src/V1beta2/ListInstancesResponse.php
  Memcache/src/V1beta2/LocationMetadata.php
  Memcache/src/V1beta2/MemcacheParameters.php
  Memcache/src/V1beta2/MemcacheVersion.php
  Memcache/src/V1beta2/OperationMetadata.php
  Memcache/src/V1beta2/README.md
  Memcache/src/V1beta2/UpdateInstanceRequest.php
  Memcache/src/V1beta2/UpdateParametersRequest.php
  Memcache/src/V1beta2/ZoneMetadata.php
  Memcache/src/V1beta2/resources/cloud_memcache_client_config.json
  Memcache/src/V1beta2/resources/cloud_memcache_descriptor_config.php
  Memcache/src/V1beta2/resources/cloud_memcache_rest_client_config.php
  Memcache/synth.metadata
  Memcache/synth.py
  Memcache/tests/Unit/V1beta2/CloudMemcacheClientTest.php
  composer.json
  docs/contents/cloud-memcache.json
  docs/contents/google-cloud.json
  docs/manifest.json
Labels: cla: yes

#2916 feat: introduce bigquery storage client
  BigQueryStorage/.gitattributes
  BigQueryStorage/.github/pull_request_template.md
  BigQueryStorage/.repo-metadata.json
  BigQueryStorage/CONTRIBUTING.md
  BigQueryStorage/LICENSE
  BigQueryStorage/README.md
  BigQueryStorage/VERSION
  BigQueryStorage/composer.json
  BigQueryStorage/metadata/V1/Arrow.php
  BigQueryStorage/metadata/V1/Avro.php
  BigQueryStorage/metadata/V1/Storage.php
  BigQueryStorage/metadata/V1/Stream.php
  BigQueryStorage/phpunit-snippets.xml.dist
  BigQueryStorage/phpunit-system.xml.dist
  BigQueryStorage/phpunit.xml.dist
  BigQueryStorage/src/V1/ArrowRecordBatch.php
  BigQueryStorage/src/V1/ArrowSchema.php
  BigQueryStorage/src/V1/AvroRows.php
  BigQueryStorage/src/V1/AvroSchema.php
  BigQueryStorage/src/V1/BigQueryReadClient.php
  BigQueryStorage/src/V1/BigQueryReadGrpcClient.php
  BigQueryStorage/src/V1/CreateReadSessionRequest.php
  BigQueryStorage/src/V1/DataFormat.php
  BigQueryStorage/src/V1/Gapic/BigQueryReadGapicClient.php
  BigQueryStorage/src/V1/README.md
  BigQueryStorage/src/V1/ReadRowsRequest.php
  BigQueryStorage/src/V1/ReadRowsResponse.php
  BigQueryStorage/src/V1/ReadSession.php
  BigQueryStorage/src/V1/ReadSession/TableModifiers.php
  BigQueryStorage/src/V1/ReadSession/TableReadOptions.php
  BigQueryStorage/src/V1/ReadSession_TableModifiers.php
  BigQueryStorage/src/V1/ReadSession_TableReadOptions.php
  BigQueryStorage/src/V1/ReadStream.php
  BigQueryStorage/src/V1/SplitReadStreamRequest.php
  BigQueryStorage/src/V1/SplitReadStreamResponse.php
  BigQueryStorage/src/V1/StreamStats.php
  BigQueryStorage/src/V1/StreamStats/Progress.php
  BigQueryStorage/src/V1/StreamStats_Progress.php
  BigQueryStorage/src/V1/ThrottleState.php
  BigQueryStorage/src/V1/resources/big_query_read_client_config.json
  BigQueryStorage/src/V1/resources/big_query_read_descriptor_config.php
  BigQueryStorage/src/V1/resources/big_query_read_rest_client_config.php
  BigQueryStorage/synth.metadata
  BigQueryStorage/synth.py
  BigQueryStorage/tests/Unit/V1/BigQueryReadClientTest.php
  composer.json
  docs/contents/cloud-bigquery-storage.json
  docs/contents/google-cloud.json
  docs/manifest.json
Labels: cla: yes

#2919 feat: make dead letter policies available to rest transport
  PubSub/src/Connection/ServiceDefinition/pubsub-v1.json
  PubSub/src/Subscription.php
  PubSub/tests/System/ManageSubscriptionsTest.php
Labels: api: pubsub, cla: yes

#2913 feat!: update formatting method names
  SecurityCenter/src/V1/Gapic/SecurityCenterGapicClient.php
  SecurityCenter/src/V1p1beta1/Gapic/SecurityCenterGapicClient.php
  SecurityCenter/synth.metadata
Labels: cla: yes

#2918 feat: introduce recaptcha enterprise client
  RecaptchaEnterprise/.gitattributes
  RecaptchaEnterprise/.github/pull_request_template.md
  RecaptchaEnterprise/.repo-metadata.json
  RecaptchaEnterprise/CONTRIBUTING.md
  RecaptchaEnterprise/LICENSE
  RecaptchaEnterprise/README.md
  RecaptchaEnterprise/VERSION
  RecaptchaEnterprise/composer.json
  RecaptchaEnterprise/metadata/V1/Recaptchaenterprise.php
  RecaptchaEnterprise/phpunit-snippets.xml.dist
  RecaptchaEnterprise/phpunit-system.xml.dist
  RecaptchaEnterprise/phpunit.xml.dist
  RecaptchaEnterprise/src/V1/AndroidKeySettings.php
  RecaptchaEnterprise/src/V1/AnnotateAssessmentRequest.php
  RecaptchaEnterprise/src/V1/AnnotateAssessmentRequest/Annotation.php
  RecaptchaEnterprise/src/V1/AnnotateAssessmentRequest_Annotation.php
  RecaptchaEnterprise/src/V1/AnnotateAssessmentResponse.php
  RecaptchaEnterprise/src/V1/Assessment.php
  RecaptchaEnterprise/src/V1/CreateAssessmentRequest.php
  RecaptchaEnterprise/src/V1/CreateKeyRequest.php
  RecaptchaEnterprise/src/V1/DeleteKeyRequest.php
  RecaptchaEnterprise/src/V1/Event.php
  RecaptchaEnterprise/src/V1/Gapic/RecaptchaEnterpriseServiceGapicClient.php
  RecaptchaEnterprise/src/V1/GetKeyRequest.php
  RecaptchaEnterprise/src/V1/IOSKeySettings.php
  RecaptchaEnterprise/src/V1/Key.php
  RecaptchaEnterprise/src/V1/ListKeysRequest.php
  RecaptchaEnterprise/src/V1/ListKeysResponse.php
  RecaptchaEnterprise/src/V1/README.md
  RecaptchaEnterprise/src/V1/RecaptchaEnterpriseServiceClient.php
  RecaptchaEnterprise/src/V1/RecaptchaEnterpriseServiceGrpcClient.php
  RecaptchaEnterprise/src/V1/RiskAnalysis.php
  RecaptchaEnterprise/src/V1/RiskAnalysis/ClassificationReason.php
  RecaptchaEnterprise/src/V1/RiskAnalysis_ClassificationReason.php
  RecaptchaEnterprise/src/V1/TokenProperties.php
  RecaptchaEnterprise/src/V1/TokenProperties/InvalidReason.php
  RecaptchaEnterprise/src/V1/TokenProperties_InvalidReason.php
  RecaptchaEnterprise/src/V1/UpdateKeyRequest.php
  RecaptchaEnterprise/src/V1/WebKeySettings.php
  RecaptchaEnterprise/src/V1/WebKeySettings/ChallengeSecurityPreference.php
  RecaptchaEnterprise/src/V1/WebKeySettings/IntegrationType.php
  RecaptchaEnterprise/src/V1/WebKeySettings_ChallengeSecurityPreference.php
  RecaptchaEnterprise/src/V1/WebKeySettings_IntegrationType.php
  RecaptchaEnterprise/src/V1/resources/recaptcha_enterprise_service_client_config.json
  RecaptchaEnterprise/src/V1/resources/recaptcha_enterprise_service_descriptor_config.php
  RecaptchaEnterprise/src/V1/resources/recaptcha_enterprise_service_rest_client_config.php
  RecaptchaEnterprise/synth.py
  RecaptchaEnterprise/tests/Unit/V1/RecaptchaEnterpriseServiceClientTest.php
  composer.json
  docs/contents/cloud-recaptcha-enterprise.json
  docs/contents/google-cloud.json
  docs/manifest.json
Labels: cla: yes

#2908 chore: update require version for google/cloud-core
  Spanner/composer.json
Labels: cla: yes

#2920 feat: add webrisk v1 client
  WebRisk/README.md
  WebRisk/metadata/V1/Webrisk.php
  WebRisk/src/V1/CompressionType.php
  WebRisk/src/V1/ComputeThreatListDiffRequest.php
  WebRisk/src/V1/ComputeThreatListDiffRequest/Constraints.php
  WebRisk/src/V1/ComputeThreatListDiffRequest_Constraints.php
  WebRisk/src/V1/ComputeThreatListDiffResponse.php
  WebRisk/src/V1/ComputeThreatListDiffResponse/Checksum.php
  WebRisk/src/V1/ComputeThreatListDiffResponse/ResponseType.php
  WebRisk/src/V1/ComputeThreatListDiffResponse_Checksum.php
  WebRisk/src/V1/ComputeThreatListDiffResponse_ResponseType.php
  WebRisk/src/V1/CreateSubmissionRequest.php
  WebRisk/src/V1/Gapic/WebRiskServiceGapicClient.php
  WebRisk/src/V1/README.md
  WebRisk/src/V1/RawHashes.php
  WebRisk/src/V1/RawIndices.php
  WebRisk/src/V1/RiceDeltaEncoding.php
  WebRisk/src/V1/SearchHashesRequest.php
  WebRisk/src/V1/SearchHashesResponse.php
  WebRisk/src/V1/SearchHashesResponse/ThreatHash.php
  WebRisk/src/V1/SearchHashesResponse_ThreatHash.php
  WebRisk/src/V1/SearchUrisRequest.php
  WebRisk/src/V1/SearchUrisResponse.php
  WebRisk/src/V1/SearchUrisResponse/ThreatUri.php
  WebRisk/src/V1/SearchUrisResponse_ThreatUri.php
  WebRisk/src/V1/Submission.php
  WebRisk/src/V1/ThreatEntryAdditions.php
  WebRisk/src/V1/ThreatEntryRemovals.php
  WebRisk/src/V1/ThreatType.php
  WebRisk/src/V1/WebRiskServiceClient.php
  WebRisk/src/V1/WebRiskServiceGrpcClient.php
  WebRisk/src/V1/resources/web_risk_service_client_config.json
  WebRisk/src/V1/resources/web_risk_service_descriptor_config.php
  WebRisk/src/V1/resources/web_risk_service_rest_client_config.php
  WebRisk/synth.metadata
  WebRisk/synth.py
  WebRisk/tests/Unit/V1/WebRiskServiceClientTest.php
  docs/contents/cloud-web-risk.json
Labels: cla: yes

#2921 chore: update README to include new clients
  README.md
Labels: cla: yes

#2911 chore: release 0.132.0
  AutoMl/VERSION
  BigQuery/VERSION
  BigQuery/src/BigQueryClient.php
  BigQueryDataTransfer/VERSION
  BigQueryStorage/VERSION
  Bigtable/VERSION
  Bigtable/src/BigtableClient.php
  CHANGELOG.md
  Container/VERSION
  Core/VERSION
  DataCatalog/VERSION
  Dataproc/VERSION
  Firestore/VERSION
  Firestore/src/FirestoreClient.php
  Kms/VERSION
  Language/VERSION
  Language/src/LanguageClient.php
  Memcache/VERSION
  Monitoring/VERSION
  PubSub/VERSION
  PubSub/src/PubSubClient.php
  RecaptchaEnterprise/VERSION
  SecurityCenter/VERSION
  Spanner/VERSION
  Spanner/src/SpannerClient.php
  Speech/VERSION
  Speech/src/SpeechClient.php
  Talent/VERSION
  TextToSpeech/VERSION
  WebRisk/VERSION
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: autorelease: pending, cla: yes

#2924 chore: add synth metadata file
  RecaptchaEnterprise/synth.metadata
Labels: cla: yes

#2931 docs: update documentation formatting
  AutoMl/src/V1/BatchPredictRequest.php
  AutoMl/src/V1/BatchPredictResult.php
  AutoMl/src/V1/Gapic/PredictionServiceGapicClient.php
  AutoMl/src/V1/PredictRequest.php
  AutoMl/src/V1/PredictResponse.php
  AutoMl/src/V1/PredictionServiceGrpcClient.php
  AutoMl/synth.metadata
Labels: cla: yes

#2932 chore: sample context aware commits for a broader base of services
  AutoMl/synth.py
  BigQueryStorage/synth.py
  DataCatalog/synth.py
  Dialogflow/synth.py
  Memcache/synth.py
  Recommender/synth.py
  ServiceDirectory/synth.py
  Talent/synth.py
  TextToSpeech/synth.py
  Vision/synth.py
Labels: cla: yes

#2970 fix: fix check for user provided MD5 hash
  Storage/src/Connection/Rest.php
  Storage/tests/Unit/Connection/RestTest.php
Labels: cla: yes

#2968 chore: update metadata
  Bigtable/metadata/Admin/V2/BigtableTableAdmin.php
  Bigtable/synth.metadata
Labels: cla: yes

#2927 feat: allow array-of-arrays value for "in" query filter
  Firestore/src/Query.php
  Firestore/src/ValueMapper.php
  Firestore/tests/System/QueryTest.php
  Firestore/tests/Unit/ValueMapperTest.php
Labels: api: firestore, cla: yes

#2974 fix: correctly serialize evaluated expressions
  Debugger/src/Breakpoint.php
Labels: cla: yes
