Repository googleapis/google-cloud-php, pull requests merged in 2020-05, with the labels that each got.

#2976 chore: reorder methods and update samples
  RecommendationEngine/metadata/V1Beta1/CatalogService.php
  RecommendationEngine/metadata/V1Beta1/Import.php
  RecommendationEngine/metadata/V1Beta1/PredictionApikeyRegistryService.php
  RecommendationEngine/metadata/V1Beta1/PredictionService.php
  RecommendationEngine/metadata/V1Beta1/RecommendationengineResources.php
  RecommendationEngine/metadata/V1Beta1/UserEventService.php
  RecommendationEngine/src/V1beta1/Gapic/CatalogServiceGapicClient.php
  RecommendationEngine/src/V1beta1/Gapic/PredictionApiKeyRegistryGapicClient.php
  RecommendationEngine/src/V1beta1/Gapic/UserEventServiceGapicClient.php
  RecommendationEngine/src/V1beta1/resources/catalog_service_client_config.json
  RecommendationEngine/src/V1beta1/resources/catalog_service_rest_client_config.php
  RecommendationEngine/src/V1beta1/resources/prediction_api_key_registry_client_config.json
  RecommendationEngine/src/V1beta1/resources/prediction_api_key_registry_rest_client_config.php
  RecommendationEngine/src/V1beta1/resources/user_event_service_client_config.json
  RecommendationEngine/src/V1beta1/resources/user_event_service_rest_client_config.php
  RecommendationEngine/synth.metadata
  RecommendationEngine/tests/Unit/V1beta1/CatalogServiceClientTest.php
  RecommendationEngine/tests/Unit/V1beta1/PredictionApiKeyRegistryClientTest.php
  RecommendationEngine/tests/Unit/V1beta1/UserEventServiceClientTest.php
Labels: cla: yes

#2929 fix: add bucket to v4 post policy conditions
  Storage/src/SigningHelper.php
  Storage/tests/Unit/data/signed-url-v4-testdata.json
Labels: api: storage, cla: yes

#2977 docs: update value documentation
  Datastore/src/V1/Value.php
  Datastore/synth.metadata
Labels: cla: yes

#2701 feat(spanner): Option to use GAPIC backoff strategy (#2062)
  Spanner/src/SpannerClient.php
  Spanner/tests/Unit/GapicBackoff/GapicBackoffTest.php
  Spanner/tests/Unit/GapicBackoff/MockOperationResponse.php
Labels: api: spanner, cla: yes

#2997 chore: create CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes

#3000 docs: update documentation formatting
  DataCatalog/metadata/V1/Datacatalog.php
  DataCatalog/src/V1/CreateTagRequest.php
  DataCatalog/src/V1/Entry.php
  DataCatalog/src/V1/EntryGroup.php
  DataCatalog/src/V1/Gapic/DataCatalogGapicClient.php
  DataCatalog/src/V1/ListEntryGroupsRequest.php
  DataCatalog/src/V1/ListTagsRequest.php
  DataCatalog/src/V1/RenameTagTemplateFieldRequest.php
  DataCatalog/src/V1/SearchCatalogRequest.php
  DataCatalog/synth.metadata
Labels: cla: yes, context: full

#3028 docs: update received message documentation
  PubSub/src/V1/ReceivedMessage.php
  PubSub/synth.metadata
Labels: cla: yes

#2849 feat: introduce support for org/access context policies
  Asset/composer.json
  Asset/external/metadata/Cloud/Orgpolicy/V1/Orgpolicy.php
  Asset/external/metadata/Identity/Accesscontextmanager/Type/DeviceResources.php
  Asset/external/metadata/Identity/Accesscontextmanager/V1/AccessLevel.php
  Asset/external/metadata/Identity/Accesscontextmanager/V1/AccessPolicy.php
  Asset/external/metadata/Identity/Accesscontextmanager/V1/ServicePerimeter.php
  Asset/external/protos/Cloud/OrgPolicy/V1/Policy.php
  Asset/external/protos/Cloud/OrgPolicy/V1/Policy/BooleanPolicy.php
  Asset/external/protos/Cloud/OrgPolicy/V1/Policy/ListPolicy.php
  Asset/external/protos/Cloud/OrgPolicy/V1/Policy/ListPolicy/AllValues.php
  Asset/external/protos/Cloud/OrgPolicy/V1/Policy/RestoreDefault.php
  Asset/external/protos/Cloud/OrgPolicy/V1/Policy_BooleanPolicy.php
  Asset/external/protos/Cloud/OrgPolicy/V1/Policy_ListPolicy.php
  Asset/external/protos/Cloud/OrgPolicy/V1/Policy_ListPolicy_AllValues.php
  Asset/external/protos/Cloud/OrgPolicy/V1/Policy_RestoreDefault.php
  Asset/external/protos/Identity/AccessContextManager/Type/DeviceEncryptionStatus.php
  Asset/external/protos/Identity/AccessContextManager/Type/DeviceManagementLevel.php
  Asset/external/protos/Identity/AccessContextManager/Type/OsType.php
  Asset/external/protos/Identity/AccessContextManager/V1/AccessLevel.php
  Asset/external/protos/Identity/AccessContextManager/V1/AccessPolicy.php
  Asset/external/protos/Identity/AccessContextManager/V1/BasicLevel.php
  Asset/external/protos/Identity/AccessContextManager/V1/BasicLevel/ConditionCombiningFunction.php
  Asset/external/protos/Identity/AccessContextManager/V1/BasicLevel_ConditionCombiningFunction.php
  Asset/external/protos/Identity/AccessContextManager/V1/Condition.php
  Asset/external/protos/Identity/AccessContextManager/V1/CustomLevel.php
  Asset/external/protos/Identity/AccessContextManager/V1/DevicePolicy.php
  Asset/external/protos/Identity/AccessContextManager/V1/OsConstraint.php
  Asset/external/protos/Identity/AccessContextManager/V1/ServicePerimeter.php
  Asset/external/protos/Identity/AccessContextManager/V1/ServicePerimeter/PerimeterType.php
  Asset/external/protos/Identity/AccessContextManager/V1/ServicePerimeterConfig.php
  Asset/external/protos/Identity/AccessContextManager/V1/ServicePerimeterConfig/VpcAccessibleServices.php
  Asset/external/protos/Identity/AccessContextManager/V1/ServicePerimeterConfig_VpcAccessibleServices.php
  Asset/external/protos/Identity/AccessContextManager/V1/ServicePerimeter_PerimeterType.php
  Asset/metadata/V1/AssetService.php
  Asset/metadata/V1/Assets.php
  Asset/src/V1/Asset.php
  Asset/src/V1/AssetServiceGrpcClient.php
  Asset/src/V1/BatchGetAssetsHistoryRequest.php
  Asset/src/V1/BigQueryDestination.php
  Asset/src/V1/ExportAssetsRequest.php
  Asset/src/V1/Feed.php
  Asset/src/V1/FeedOutputConfig.php
  Asset/src/V1/Gapic/AssetServiceGapicClient.php
  Asset/src/V1/PubsubDestination.php
  Asset/src/V1/Resource.php
  Asset/src/V1/TemporalAsset.php
  Asset/src/V1/TimeWindow.php
  Asset/src/V1beta1/resources/asset_service_rest_client_config.php
  Asset/synth.metadata
  composer.json
  phpcs-ruleset.xml
Labels: cla: yes

#3029 feat: update timeout configuration
  Spanner/src/Admin/Database/V1/resources/database_admin_client_config.json
  Spanner/synth.metadata
Labels: api: spanner, cla: yes

#2930 tests: skip unsupported tests when using emulator
  Spanner/tests/System/AdminTest.php
  Spanner/tests/System/BackupTest.php
  Spanner/tests/System/PartitionedDmlTest.php
  Spanner/tests/System/ReadTest.php
  Spanner/tests/System/SpannerTestCase.php
  Spanner/tests/System/WriteTest.php
Labels: api: spanner, cla: yes

#3051 chore: reorder methods
  WebSecurityScanner/src/V1beta/Gapic/WebSecurityScannerGapicClient.php
  WebSecurityScanner/src/V1beta/resources/web_security_scanner_client_config.json
  WebSecurityScanner/src/V1beta/resources/web_security_scanner_rest_client_config.php
  WebSecurityScanner/synth.metadata
  WebSecurityScanner/tests/Unit/V1beta/WebSecurityScannerClientTest.php
Labels: cla: yes, context: full

#2878 feat: async upload for storage buckets
  Core/src/Upload/MultipartUploader.php
  Core/src/Upload/ResumableUploader.php
  Core/src/Upload/StreamableUploader.php
  Core/tests/Unit/Upload/MultipartUploaderTest.php
  Core/tests/Unit/Upload/ResumableUploaderTest.php
  Core/tests/Unit/Upload/StreamableUploaderTest.php
  Storage/src/Bucket.php
  Storage/tests/Snippet/BucketTest.php
  Storage/tests/System/ManageObjectsTest.php
  Storage/tests/Unit/BucketTest.php
Labels: cla: yes

#3049 feat: update retry and timeout config
  Trace/src/V2/Gapic/TraceServiceGapicClient.php
  Trace/src/V2/resources/trace_service_client_config.json
  Trace/src/V2/resources/trace_service_rest_client_config.php
  Trace/synth.metadata
  Trace/tests/Unit/V2/TraceServiceClientTest.php
Labels: cla: yes, context: full

#3052 feat: update timeouts
  Bigtable/src/V2/resources/bigtable_client_config.json
  Bigtable/synth.metadata
Labels: cla: yes, context: full

#3050 chore: reorder methods
  Translate/src/V3/Gapic/TranslationServiceGapicClient.php
  Translate/src/V3/resources/translation_service_client_config.json
  Translate/src/V3/resources/translation_service_descriptor_config.php
  Translate/src/V3/resources/translation_service_rest_client_config.php
  Translate/synth.metadata
  Translate/tests/Unit/V3/TranslationServiceClientTest.php
Labels: cla: yes, context: full

#3048 chore: reorder methods
  TextToSpeech/src/V1/Gapic/TextToSpeechGapicClient.php
  TextToSpeech/src/V1/resources/text_to_speech_client_config.json
  TextToSpeech/src/V1/resources/text_to_speech_rest_client_config.php
  TextToSpeech/synth.metadata
  TextToSpeech/tests/Unit/V1/TextToSpeechClientTest.php
Labels: cla: yes, context: full

#3047 fix: update retry codes
  Tasks/src/V2beta2/resources/cloud_tasks_client_config.json
  Tasks/src/V2beta3/resources/cloud_tasks_client_config.json
  Tasks/synth.metadata
Labels: cla: yes, context: full

#3046 fix: update retry code for recognize
  Speech/src/V1p1beta1/resources/speech_client_config.json
  Speech/synth.metadata
Labels: cla: yes, context: full

#3045 chore: reorder methods
  Scheduler/src/V1/Gapic/CloudSchedulerGapicClient.php
  Scheduler/src/V1/resources/cloud_scheduler_client_config.json
  Scheduler/src/V1/resources/cloud_scheduler_rest_client_config.php
  Scheduler/src/V1beta1/Gapic/CloudSchedulerGapicClient.php
  Scheduler/src/V1beta1/resources/cloud_scheduler_client_config.json
  Scheduler/src/V1beta1/resources/cloud_scheduler_rest_client_config.php
  Scheduler/synth.metadata
  Scheduler/tests/Unit/V1/CloudSchedulerClientTest.php
  Scheduler/tests/Unit/V1beta1/CloudSchedulerClientTest.php
Labels: cla: yes, context: full

#3043 feat: update retry and timeout config
  Iot/src/V1/Gapic/DeviceManagerGapicClient.php
  Iot/src/V1/resources/device_manager_client_config.json
  Iot/src/V1/resources/device_manager_rest_client_config.php
  Iot/synth.metadata
  Iot/tests/Unit/V1/DeviceManagerClientTest.php
Labels: cla: yes, context: full

#3044 chore: reorder methods
  OsLogin/src/V1/Gapic/OsLoginServiceGapicClient.php
  OsLogin/src/V1/resources/os_login_service_client_config.json
  OsLogin/src/V1/resources/os_login_service_rest_client_config.php
  OsLogin/synth.metadata
  OsLogin/tests/Unit/V1/OsLoginServiceClientTest.php
Labels: cla: yes, context: full

#3042 chore: reorder methods
  ErrorReporting/src/V1beta1/Gapic/ErrorGroupServiceGapicClient.php
  ErrorReporting/src/V1beta1/Gapic/ErrorStatsServiceGapicClient.php
  ErrorReporting/src/V1beta1/resources/error_group_service_client_config.json
  ErrorReporting/src/V1beta1/resources/error_group_service_rest_client_config.php
  ErrorReporting/src/V1beta1/resources/error_stats_service_client_config.json
  ErrorReporting/src/V1beta1/resources/error_stats_service_rest_client_config.php
  ErrorReporting/synth.metadata
  ErrorReporting/tests/Unit/V1beta1/ErrorGroupServiceClientTest.php
  ErrorReporting/tests/Unit/V1beta1/ErrorStatsServiceClientTest.php
Labels: cla: yes, context: full

#3040 fix: update retry configuration, reorder methods
  Container/src/V1/Gapic/ClusterManagerGapicClient.php
  Container/src/V1/resources/cluster_manager_client_config.json
  Container/src/V1/resources/cluster_manager_rest_client_config.php
  Container/synth.metadata
  Container/tests/Unit/V1/ClusterManagerClientTest.php
Labels: cla: yes, context: full

#3039 fix: update retry config, reorder methods
  BigQueryDataTransfer/src/V1/Gapic/DataTransferServiceGapicClient.php
  BigQueryDataTransfer/src/V1/resources/data_transfer_service_client_config.json
  BigQueryDataTransfer/src/V1/resources/data_transfer_service_rest_client_config.php
  BigQueryDataTransfer/synth.metadata
  BigQueryDataTransfer/tests/Unit/V1/DataTransferServiceClientTest.php
Labels: cla: yes, context: full

#3053 chore: update timeouts
  Spanner/src/Admin/Database/V1/Gapic/DatabaseAdminGapicClient.php
  Spanner/src/Admin/Database/V1/resources/database_admin_client_config.json
  Spanner/src/Admin/Database/V1/resources/database_admin_descriptor_config.php
  Spanner/src/Admin/Database/V1/resources/database_admin_rest_client_config.php
  Spanner/src/Admin/Instance/V1/resources/instance_admin_client_config.json
  Spanner/synth.metadata
  Spanner/tests/Unit/Admin/Database/V1/DatabaseAdminClientTest.php
Labels: cla: yes, context: full

#3041 feat: update timeout config
  Debugger/src/V2/resources/controller2_client_config.json
  Debugger/src/V2/resources/debugger2_client_config.json
  Debugger/synth.metadata
Labels: cla: yes, context: full

#3056 feat!: update createReadSession, readRows, splitReadStream
  BigQueryStorage/src/V1/Gapic/BigQueryReadGapicClient.php
  BigQueryStorage/synth.metadata
  BigQueryStorage/tests/Unit/V1/BigQueryReadClientTest.php
Labels: cla: yes, context: full

#3065 chore: update minimum google/cloud-core dependency
  Storage/composer.json
Labels: api: storage, cla: yes

#3064 chore: release 0.133.0
  Asset/VERSION
  AutoMl/VERSION
  BigQueryDataTransfer/VERSION
  BigQueryStorage/VERSION
  Bigtable/VERSION
  Bigtable/src/BigtableClient.php
  CHANGELOG.md
  Container/VERSION
  Core/VERSION
  DataCatalog/VERSION
  Datastore/VERSION
  Datastore/src/DatastoreClient.php
  Debugger/VERSION
  Debugger/src/DebuggerClient.php
  Dialogflow/VERSION
  ErrorReporting/VERSION
  Firestore/VERSION
  Firestore/src/FirestoreClient.php
  Iot/VERSION
  Memcache/VERSION
  OsLogin/VERSION
  PubSub/VERSION
  PubSub/src/PubSubClient.php
  RecaptchaEnterprise/VERSION
  RecommendationEngine/VERSION
  Recommender/VERSION
  Scheduler/VERSION
  ServiceDirectory/VERSION
  Spanner/VERSION
  Spanner/src/SpannerClient.php
  Speech/VERSION
  Speech/src/SpeechClient.php
  Storage/VERSION
  Storage/src/StorageClient.php
  Talent/VERSION
  Tasks/VERSION
  TextToSpeech/VERSION
  Trace/VERSION
  Trace/src/TraceClient.php
  Translate/VERSION
  Vision/VERSION
  Vision/src/VisionClient.php
  WebSecurityScanner/VERSION
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: autorelease: pending, cla: yes
