Repository googleapis/google-cloud-php, pull requests merged in 2020-08, with the labels that each got.

#3274 feat: add UpgradeInstance request
  Redis/metadata/V1/CloudRedis.php
  Redis/src/V1/CloudRedisGrpcClient.php
  Redis/src/V1/Gapic/CloudRedisGapicClient.php
  Redis/src/V1/Instance.php
  Redis/src/V1/Instance/ConnectMode.php
  Redis/src/V1/UpgradeInstanceRequest.php
  Redis/src/V1/resources/cloud_redis_client_config.json
  Redis/src/V1/resources/cloud_redis_descriptor_config.php
  Redis/src/V1/resources/cloud_redis_rest_client_config.php
  Redis/synth.metadata
  Redis/tests/Unit/V1/CloudRedisClientTest.php
Labels: cla: yes, context: full

#3270 feat: update retry and timeout configuration
  BigQueryStorage/src/V1/resources/big_query_read_client_config.json
  BigQueryStorage/synth.metadata
Labels: cla: yes, context: full

#3275 feat: update retry and timeout configuration
  SecurityCenter/src/V1/Gapic/SecurityCenterGapicClient.php
  SecurityCenter/src/V1/resources/security_center_client_config.json
  SecurityCenter/src/V1/resources/security_center_rest_client_config.php
  SecurityCenter/src/V1p1beta1/resources/security_center_client_config.json
  SecurityCenter/synth.metadata
  SecurityCenter/tests/Unit/V1/SecurityCenterClientTest.php
Labels: cla: yes, context: full

#3273 feat: update retry and timeout configuration
  RecommendationEngine/metadata/V1Beta1/Catalog.php
  RecommendationEngine/metadata/V1Beta1/CatalogService.php
  RecommendationEngine/metadata/V1Beta1/Common.php
  RecommendationEngine/metadata/V1Beta1/Import.php
  RecommendationEngine/metadata/V1Beta1/PredictionApikeyRegistryService.php
  RecommendationEngine/metadata/V1Beta1/PredictionService.php
  RecommendationEngine/metadata/V1Beta1/RecommendationengineResources.php
  RecommendationEngine/metadata/V1Beta1/UserEvent.php
  RecommendationEngine/metadata/V1Beta1/UserEventService.php
  RecommendationEngine/src/V1beta1/resources/catalog_service_client_config.json
  RecommendationEngine/src/V1beta1/resources/prediction_api_key_registry_client_config.json
  RecommendationEngine/src/V1beta1/resources/prediction_service_client_config.json
  RecommendationEngine/src/V1beta1/resources/user_event_service_client_config.json
  RecommendationEngine/synth.metadata
Labels: cla: yes, context: partial

#3272 feat: update retry and timeout configuration
  Iot/src/V1/Gapic/DeviceManagerGapicClient.php
  Iot/src/V1/resources/device_manager_client_config.json
  Iot/src/V1/resources/device_manager_rest_client_config.php
  Iot/synth.metadata
  Iot/tests/Unit/V1/DeviceManagerClientTest.php
Labels: cla: yes, context: full

#3277 chore: release 0.137.0
  BigQueryConnection/VERSION
  BigQueryReservation/VERSION
  BigQueryStorage/VERSION
  CHANGELOG.md
  Iot/VERSION
  Language/VERSION
  Language/src/LanguageClient.php
  PubSub/VERSION
  PubSub/src/PubSubClient.php
  RecommendationEngine/VERSION
  Recommender/VERSION
  Redis/VERSION
  SecurityCenter/VERSION
  ServiceDirectory/VERSION
  Spanner/VERSION
  Spanner/src/SpannerClient.php
  Trace/VERSION
  Trace/src/TraceClient.php
  Translate/VERSION
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: autorelease: pending, cla: yes

#3280 feat!: add support for new data types and reorganize signatures
  Dlp/metadata/V2/Dlp.php
  Dlp/metadata/V2/Storage.php
  Dlp/src/V2/BucketingConfig/Bucket.php
  Dlp/src/V2/ByteContentItem/BytesType.php
  Dlp/src/V2/CloudStorageOptions.php
  Dlp/src/V2/ContentLocation.php
  Dlp/src/V2/CreateDeidentifyTemplateRequest.php
  Dlp/src/V2/CreateDlpJobRequest.php
  Dlp/src/V2/CreateInspectTemplateRequest.php
  Dlp/src/V2/CreateJobTriggerRequest.php
  Dlp/src/V2/CreateStoredInfoTypeRequest.php
  Dlp/src/V2/CryptoReplaceFfxFpeConfig/FfxCommonNativeAlphabet.php
  Dlp/src/V2/DateShiftConfig.php
  Dlp/src/V2/DeidentifyContentRequest.php
  Dlp/src/V2/DeleteDeidentifyTemplateRequest.php
  Dlp/src/V2/DeleteInspectTemplateRequest.php
  Dlp/src/V2/DeleteStoredInfoTypeRequest.php
  Dlp/src/V2/DlpServiceGrpcClient.php
  Dlp/src/V2/FileType.php
  Dlp/src/V2/Finding.php
  Dlp/src/V2/FixedSizeBucketingConfig.php
  Dlp/src/V2/Gapic/DlpServiceGapicClient.php
  Dlp/src/V2/GetDeidentifyTemplateRequest.php
  Dlp/src/V2/GetInspectTemplateRequest.php
  Dlp/src/V2/GetStoredInfoTypeRequest.php
  Dlp/src/V2/HybridFindingDetails.php
  Dlp/src/V2/HybridInspectDlpJobRequest.php
  Dlp/src/V2/HybridInspectJobTriggerRequest.php
  Dlp/src/V2/HybridInspectStatistics.php
  Dlp/src/V2/HybridOptions.php
  Dlp/src/V2/InfoType.php
  Dlp/src/V2/InspectContentRequest.php
  Dlp/src/V2/JobTrigger.php
  Dlp/src/V2/ListDeidentifyTemplatesRequest.php
  Dlp/src/V2/ListDlpJobsRequest.php
  Dlp/src/V2/ListInfoTypesRequest.php
  Dlp/src/V2/ListInspectTemplatesRequest.php
  Dlp/src/V2/ListJobTriggersRequest.php
  Dlp/src/V2/ListStoredInfoTypesRequest.php
  Dlp/src/V2/MetadataLocation.php
  Dlp/src/V2/MetadataType.php
  Dlp/src/V2/PrivacyMetric/DeltaPresenceEstimationConfig.php
  Dlp/src/V2/PrivacyMetric/KMapEstimationConfig.php
  Dlp/src/V2/PrivacyMetric/KMapEstimationConfig/AuxiliaryTable.php
  Dlp/src/V2/RedactImageRequest.php
  Dlp/src/V2/ReidentifyContentRequest.php
  Dlp/src/V2/StatisticalTable.php
  Dlp/src/V2/StorageMetadataLabel.php
  Dlp/src/V2/TableLocation.php
  Dlp/src/V2/UpdateDeidentifyTemplateRequest.php
  Dlp/src/V2/UpdateInspectTemplateRequest.php
  Dlp/src/V2/UpdateStoredInfoTypeRequest.php
  Dlp/src/V2/resources/dlp_service_client_config.json
  Dlp/src/V2/resources/dlp_service_descriptor_config.php
  Dlp/src/V2/resources/dlp_service_rest_client_config.php
  Dlp/synth.metadata
  Dlp/synth.py
  Dlp/tests/Unit/V2/DlpServiceClientTest.php
Labels: api: dlp, cla: yes

#3271 feat: introduce new fields to ClusterConfig and InstanceGroupConfig
  Dataproc/metadata/V1/Clusters.php
  Dataproc/metadata/V1/Jobs.php
  Dataproc/metadata/V1/WorkflowTemplates.php
  Dataproc/src/V1/BasicYarnAutoscalingConfig.php
  Dataproc/src/V1/ClusterConfig.php
  Dataproc/src/V1/Component.php
  Dataproc/src/V1/EndpointConfig.php
  Dataproc/src/V1/Gapic/AutoscalingPolicyServiceGapicClient.php
  Dataproc/src/V1/Gapic/ClusterControllerGapicClient.php
  Dataproc/src/V1/Gapic/JobControllerGapicClient.php
  Dataproc/src/V1/Gapic/WorkflowTemplateServiceGapicClient.php
  Dataproc/src/V1/GceClusterConfig.php
  Dataproc/src/V1/InstanceGroupConfig.php
  Dataproc/src/V1/InstanceGroupConfig/Preemptibility.php
  Dataproc/src/V1/InstanceGroupConfig_Preemptibility.php
  Dataproc/src/V1/JobReference.php
  Dataproc/src/V1/OrderedJob.php
  Dataproc/src/V1/PySparkJob.php
  Dataproc/src/V1/SoftwareConfig.php
  Dataproc/src/V1/SparkJob.php
  Dataproc/src/V1/SparkRJob.php
  Dataproc/src/V1/WorkflowTemplate.php
  Dataproc/src/V1/resources/autoscaling_policy_service_client_config.json
  Dataproc/src/V1/resources/autoscaling_policy_service_rest_client_config.php
  Dataproc/src/V1/resources/cluster_controller_client_config.json
  Dataproc/src/V1/resources/cluster_controller_descriptor_config.php
  Dataproc/src/V1/resources/cluster_controller_rest_client_config.php
  Dataproc/src/V1/resources/job_controller_client_config.json
  Dataproc/src/V1/resources/job_controller_rest_client_config.php
  Dataproc/src/V1/resources/workflow_template_service_client_config.json
  Dataproc/src/V1/resources/workflow_template_service_rest_client_config.php
  Dataproc/src/V1beta2/Gapic/ClusterControllerGapicClient.php
  Dataproc/src/V1beta2/Gapic/JobControllerGapicClient.php
  Dataproc/src/V1beta2/Gapic/WorkflowTemplateServiceGapicClient.php
  Dataproc/src/V1beta2/resources/autoscaling_policy_service_client_config.json
  Dataproc/src/V1beta2/resources/cluster_controller_client_config.json
  Dataproc/src/V1beta2/resources/cluster_controller_descriptor_config.php
  Dataproc/src/V1beta2/resources/cluster_controller_rest_client_config.php
  Dataproc/src/V1beta2/resources/job_controller_client_config.json
  Dataproc/src/V1beta2/resources/job_controller_rest_client_config.php
  Dataproc/src/V1beta2/resources/workflow_template_service_client_config.json
  Dataproc/src/V1beta2/resources/workflow_template_service_descriptor_config.php
  Dataproc/src/V1beta2/resources/workflow_template_service_rest_client_config.php
  Dataproc/synth.metadata
  Dataproc/tests/Unit/V1/AutoscalingPolicyServiceClientTest.php
  Dataproc/tests/Unit/V1/ClusterControllerClientTest.php
  Dataproc/tests/Unit/V1/JobControllerClientTest.php
  Dataproc/tests/Unit/V1/WorkflowTemplateServiceClientTest.php
  Dataproc/tests/Unit/V1beta2/ClusterControllerClientTest.php
  Dataproc/tests/Unit/V1beta2/JobControllerClientTest.php
  Dataproc/tests/Unit/V1beta2/WorkflowTemplateServiceClientTest.php
Labels: cla: yes, context: full

#3283 docs: add Gaming to README
  README.md
Labels: cla: yes

#3284 chore: release 0.138.0
  CHANGELOG.md
  Dataproc/VERSION
  Dlp/VERSION
  Gaming/VERSION
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: autorelease: pending, cla: yes

#3276 fix: correctly set google-cloud-resource-prefix headers
  Spanner/src/Connection/Grpc.php
  Spanner/src/Instance.php
  Spanner/src/InstanceConfiguration.php
  Spanner/src/Operation.php
  Spanner/src/Session/Session.php
  Spanner/src/SpannerClient.php
  Spanner/tests/Snippet/Batch/BatchSnapshotTest.php
  Spanner/tests/Snippet/BatchDmlResultTest.php
  Spanner/tests/Snippet/TransactionalReadMethodsTest.php
  Spanner/tests/Unit/Batch/BatchClientTest.php
  Spanner/tests/Unit/Batch/BatchSnapshotTest.php
  Spanner/tests/Unit/Connection/GrpcTest.php
  Spanner/tests/Unit/DatabaseTest.php
  Spanner/tests/Unit/InstanceConfigurationTest.php
  Spanner/tests/Unit/InstanceTest.php
  Spanner/tests/Unit/OperationTest.php
  Spanner/tests/Unit/SpannerClientTest.php
Labels: api: spanner, cla: yes

#3291 docs: add accurate description to job configuration methods
  BigQuery/src/JobConfigurationTrait.php
Labels: cla: yes

#3290 feat: pass retryAttempt to all retryFunction calls
  Core/src/ExponentialBackoff.php
  Core/src/Retry.php
Labels: cla: yes

#3294 chore: update manifest
  manifest.json
Labels: cla: yes

#3293 chore: add .repo-metadata.json to bigquery libraries
  BigQueryConnection/.repo-metadata.json
  BigQueryReservation/.repo-metadata.json
Labels: api: bigqueryconnection, api: bigqueryreservation, cla: yes

#3295 chore: update docs title for bigquery reservation
  docs/contents/cloud-bigquery-reservation.json
Labels: cla: yes

#3153 feat: add support for noncurrent and custom time lifecycle rules
  Storage/src/Connection/ServiceDefinition/storage-v1.json
  Storage/src/Lifecycle.php
  Storage/tests/Snippet/LifecycleTest.php
  Storage/tests/System/ManageBucketsTest.php
  Storage/tests/Unit/LifecycleTest.php
Labels: api: storage, cla: yes

#3301 feat: regenerate with proto v3.13.0
  BigQueryConnection/src/V1/CloudSqlProperties.php
  BigQueryConnection/src/V1/Connection.php
  BigQueryConnection/src/V1/CreateConnectionRequest.php
  BigQueryConnection/src/V1/UpdateConnectionRequest.php
  BigQueryConnection/synth.metadata
Labels: cla: yes, context: none

#3302 feat: regenerate with protoc v3.13.0
  BigQueryDataTransfer/src/V1/CreateTransferConfigRequest.php
  BigQueryDataTransfer/src/V1/DataSource.php
  BigQueryDataTransfer/src/V1/DataSourceParameter.php
  BigQueryDataTransfer/src/V1/ListTransferRunsRequest.php
  BigQueryDataTransfer/src/V1/ScheduleOptions.php
  BigQueryDataTransfer/src/V1/ScheduleTransferRunsRequest.php
  BigQueryDataTransfer/src/V1/StartManualTransferRunsRequest.php
  BigQueryDataTransfer/src/V1/StartManualTransferRunsRequest/TimeRange.php
  BigQueryDataTransfer/src/V1/TransferConfig.php
  BigQueryDataTransfer/src/V1/TransferMessage.php
  BigQueryDataTransfer/src/V1/TransferRun.php
  BigQueryDataTransfer/src/V1/UpdateTransferConfigRequest.php
  BigQueryDataTransfer/synth.metadata
Labels: cla: yes, context: full

#3292 feat: add client integrity verification fields to the KMS protos
  Kms/metadata/V1/Resources.php
  Kms/metadata/V1/Service.php
  Kms/src/V1/AsymmetricDecryptRequest.php
  Kms/src/V1/AsymmetricDecryptResponse.php
  Kms/src/V1/AsymmetricSignRequest.php
  Kms/src/V1/AsymmetricSignResponse.php
  Kms/src/V1/CryptoKey.php
  Kms/src/V1/DecryptRequest.php
  Kms/src/V1/DecryptResponse.php
  Kms/src/V1/EncryptRequest.php
  Kms/src/V1/EncryptResponse.php
  Kms/src/V1/Gapic/KeyManagementServiceGapicClient.php
  Kms/src/V1/PublicKey.php
  Kms/synth.metadata
  Kms/tests/Unit/V1/KeyManagementServiceClientTest.php
Labels: cla: yes, context: full

#3297 feat: added field severity to findings
  SecurityCenter/metadata/V1P1Beta1/Finding.php
  SecurityCenter/metadata/V1P1Beta1/SecuritycenterService.php
  SecurityCenter/src/V1p1beta1/CreateFindingRequest.php
  SecurityCenter/src/V1p1beta1/CreateNotificationConfigRequest.php
  SecurityCenter/src/V1p1beta1/CreateSourceRequest.php
  SecurityCenter/src/V1p1beta1/Finding.php
  SecurityCenter/src/V1p1beta1/Finding/Severity.php
  SecurityCenter/src/V1p1beta1/Finding_Severity.php
  SecurityCenter/src/V1p1beta1/Gapic/SecurityCenterGapicClient.php
  SecurityCenter/src/V1p1beta1/GetOrganizationSettingsRequest.php
  SecurityCenter/src/V1p1beta1/GroupAssetsRequest.php
  SecurityCenter/src/V1p1beta1/GroupFindingsRequest.php
  SecurityCenter/src/V1p1beta1/ListAssetsRequest.php
  SecurityCenter/src/V1p1beta1/ListFindingsRequest.php
  SecurityCenter/src/V1p1beta1/ListFindingsResponse/ListFindingsResult.php
  SecurityCenter/src/V1p1beta1/ListSourcesRequest.php
  SecurityCenter/src/V1p1beta1/RunAssetDiscoveryRequest.php
  SecurityCenter/src/V1p1beta1/SecurityCenterGrpcClient.php
  SecurityCenter/src/V1p1beta1/UpdateFindingRequest.php
  SecurityCenter/synth.metadata
Labels: cla: yes, context: full

#3333 feat: regenerate with protoc v3.13.0
  WebSecurityScanner/src/V1beta/CreateScanConfigRequest.php
  WebSecurityScanner/src/V1beta/Finding.php
  WebSecurityScanner/src/V1beta/ScanConfig.php
  WebSecurityScanner/src/V1beta/ScanConfig/Authentication.php
  WebSecurityScanner/src/V1beta/ScanConfig/Schedule.php
  WebSecurityScanner/src/V1beta/ScanConfigError.php
  WebSecurityScanner/src/V1beta/ScanRun.php
  WebSecurityScanner/src/V1beta/ScanRunErrorTrace.php
  WebSecurityScanner/src/V1beta/ScanRunWarningTrace.php
  WebSecurityScanner/src/V1beta/UpdateScanConfigRequest.php
  WebSecurityScanner/synth.metadata
Labels: cla: yes, context: full

#3332 feat: regenerate with protoc v3.13.0
  WebRisk/src/V1/ComputeThreatListDiffRequest.php
  WebRisk/src/V1/ComputeThreatListDiffResponse.php
  WebRisk/src/V1/CreateSubmissionRequest.php
  WebRisk/src/V1/SearchHashesResponse.php
  WebRisk/src/V1/SearchHashesResponse/ThreatHash.php
  WebRisk/src/V1/SearchUrisResponse.php
  WebRisk/src/V1/SearchUrisResponse/ThreatUri.php
  WebRisk/src/V1/ThreatEntryAdditions.php
  WebRisk/src/V1/ThreatEntryRemovals.php
  WebRisk/src/V1beta1/ComputeThreatListDiffRequest.php
  WebRisk/src/V1beta1/ComputeThreatListDiffResponse.php
  WebRisk/src/V1beta1/SearchHashesResponse.php
  WebRisk/src/V1beta1/SearchHashesResponse/ThreatHash.php
  WebRisk/src/V1beta1/SearchUrisResponse.php
  WebRisk/src/V1beta1/SearchUrisResponse/ThreatUri.php
  WebRisk/src/V1beta1/ThreatEntryAdditions.php
  WebRisk/src/V1beta1/ThreatEntryRemovals.php
  WebRisk/synth.metadata
Labels: cla: yes, context: full

#3303 feat: regenerate with protoc v3.13.0
  BigQueryReservation/src/V1/Assignment.php
  BigQueryReservation/src/V1/BiReservation.php
  BigQueryReservation/src/V1/CapacityCommitment.php
  BigQueryReservation/src/V1/CreateAssignmentRequest.php
  BigQueryReservation/src/V1/CreateCapacityCommitmentRequest.php
  BigQueryReservation/src/V1/CreateReservationRequest.php
  BigQueryReservation/src/V1/SplitCapacityCommitmentResponse.php
  BigQueryReservation/src/V1/UpdateBiReservationRequest.php
  BigQueryReservation/src/V1/UpdateCapacityCommitmentRequest.php
  BigQueryReservation/src/V1/UpdateReservationRequest.php
  BigQueryReservation/synth.metadata
Labels: cla: yes, context: none

#3331 feat: regenerate with protoc v3.13.0
  Vision/src/V1/AnnotateFileRequest.php
  Vision/src/V1/AnnotateFileResponse.php
  Vision/src/V1/AnnotateImageRequest.php
  Vision/src/V1/AnnotateImageResponse.php
  Vision/src/V1/AsyncAnnotateFileRequest.php
  Vision/src/V1/AsyncAnnotateFileResponse.php
  Vision/src/V1/AsyncBatchAnnotateImagesRequest.php
  Vision/src/V1/AsyncBatchAnnotateImagesResponse.php
  Vision/src/V1/BatchOperationMetadata.php
  Vision/src/V1/Block.php
  Vision/src/V1/ColorInfo.php
  Vision/src/V1/CreateProductRequest.php
  Vision/src/V1/CreateProductSetRequest.php
  Vision/src/V1/CreateReferenceImageRequest.php
  Vision/src/V1/CropHint.php
  Vision/src/V1/EntityAnnotation.php
  Vision/src/V1/FaceAnnotation.php
  Vision/src/V1/FaceAnnotation/Landmark.php
  Vision/src/V1/Feature.php
  Vision/src/V1/Image.php
  Vision/src/V1/ImageContext.php
  Vision/src/V1/ImageProperties.php
  Vision/src/V1/ImportProductSetsInputConfig.php
  Vision/src/V1/ImportProductSetsRequest.php
  Vision/src/V1/InputConfig.php
  Vision/src/V1/LatLongRect.php
  Vision/src/V1/LocalizedObjectAnnotation.php
  Vision/src/V1/LocationInfo.php
  Vision/src/V1/OperationMetadata.php
  Vision/src/V1/OutputConfig.php
  Vision/src/V1/Page.php
  Vision/src/V1/Paragraph.php
  Vision/src/V1/ProductSearchParams.php
  Vision/src/V1/ProductSearchResults.php
  Vision/src/V1/ProductSearchResults/GroupedResult.php
  Vision/src/V1/ProductSearchResults/Result.php
  Vision/src/V1/ProductSet.php
  Vision/src/V1/PurgeProductsRequest.php
  Vision/src/V1/Symbol.php
  Vision/src/V1/TextAnnotation/DetectedBreak.php
  Vision/src/V1/TextAnnotation/TextProperty.php
  Vision/src/V1/UpdateProductRequest.php
  Vision/src/V1/UpdateProductSetRequest.php
  Vision/src/V1/Word.php
  Vision/synth.metadata
Labels: cla: yes, context: full

#3329 feat: regenerate with protoc v3.13.0
  Translate/src/V3/BatchTranslateMetadata.php
  Translate/src/V3/BatchTranslateResponse.php
  Translate/src/V3/BatchTranslateTextRequest.php
  Translate/src/V3/CreateGlossaryMetadata.php
  Translate/src/V3/CreateGlossaryRequest.php
  Translate/src/V3/DeleteGlossaryMetadata.php
  Translate/src/V3/DeleteGlossaryResponse.php
  Translate/src/V3/DetectLanguageRequest.php
  Translate/src/V3/Glossary.php
  Translate/src/V3/GlossaryInputConfig.php
  Translate/src/V3/InputConfig.php
  Translate/src/V3/OutputConfig.php
  Translate/src/V3/TranslateTextRequest.php
  Translate/src/V3/Translation.php
  Translate/synth.metadata
Labels: cla: yes, context: full

#3342 feat: regenerate with protoc v3.13.0
  OsConfig/src/V1/AptSettings.php
  OsConfig/src/V1/CreatePatchDeploymentRequest.php
  OsConfig/src/V1/ExecStep.php
  OsConfig/src/V1/ExecStepConfig.php
  OsConfig/src/V1/ExecutePatchJobRequest.php
  OsConfig/src/V1/MonthlySchedule.php
  OsConfig/src/V1/OneTimeSchedule.php
  OsConfig/src/V1/PatchConfig.php
  OsConfig/src/V1/PatchDeployment.php
  OsConfig/src/V1/PatchJob.php
  OsConfig/src/V1/PatchJobInstanceDetails.php
  OsConfig/src/V1/RecurringSchedule.php
  OsConfig/synth.metadata
Labels: cla: yes, context: full

#3341 feat: regenerate with protoc v3.13.0
  Kms/src/V1/AsymmetricDecryptRequest.php
  Kms/src/V1/AsymmetricDecryptResponse.php
  Kms/src/V1/AsymmetricSignRequest.php
  Kms/src/V1/AsymmetricSignResponse.php
  Kms/src/V1/CreateCryptoKeyRequest.php
  Kms/src/V1/CreateCryptoKeyVersionRequest.php
  Kms/src/V1/CreateImportJobRequest.php
  Kms/src/V1/CreateKeyRingRequest.php
  Kms/src/V1/CryptoKey.php
  Kms/src/V1/CryptoKeyVersion.php
  Kms/src/V1/CryptoKeyVersionTemplate.php
  Kms/src/V1/DecryptRequest.php
  Kms/src/V1/DecryptResponse.php
  Kms/src/V1/Digest.php
  Kms/src/V1/EncryptRequest.php
  Kms/src/V1/EncryptResponse.php
  Kms/src/V1/ImportCryptoKeyVersionRequest.php
  Kms/src/V1/ImportJob.php
  Kms/src/V1/KeyOperationAttestation.php
  Kms/src/V1/KeyRing.php
  Kms/src/V1/ListCryptoKeyVersionsRequest.php
  Kms/src/V1/ListCryptoKeysRequest.php
  Kms/src/V1/PublicKey.php
  Kms/src/V1/UpdateCryptoKeyRequest.php
  Kms/src/V1/UpdateCryptoKeyVersionRequest.php
  Kms/synth.metadata
Labels: cla: yes, context: full

#3328 feat: regenerate with protoc v3.13.0
  Trace/src/V2/AttributeValue.php
  Trace/src/V2/Module.php
  Trace/src/V2/Span.php
  Trace/src/V2/Span/Link.php
  Trace/src/V2/Span/TimeEvent.php
  Trace/src/V2/Span/TimeEvent/Annotation.php
  Trace/src/V2/Span/TimeEvent/MessageEvent.php
  Trace/src/V2/StackTrace.php
  Trace/src/V2/StackTrace/StackFrame.php
  Trace/synth.metadata
Labels: cla: yes, context: full

#3327 feat: regenerate with protoc v3.13.0
  Tasks/src/V2/AppEngineHttpRequest.php
  Tasks/src/V2/Attempt.php
  Tasks/src/V2/CreateQueueRequest.php
  Tasks/src/V2/CreateTaskRequest.php
  Tasks/src/V2/GetTaskRequest.php
  Tasks/src/V2/HttpRequest.php
  Tasks/src/V2/ListTasksRequest.php
  Tasks/src/V2/Queue.php
  Tasks/src/V2/RetryConfig.php
  Tasks/src/V2/RunTaskRequest.php
  Tasks/src/V2/Task.php
  Tasks/src/V2/UpdateQueueRequest.php
  Tasks/src/V2beta2/AcknowledgeTaskRequest.php
  Tasks/src/V2beta2/AppEngineHttpRequest.php
  Tasks/src/V2beta2/AppEngineHttpTarget.php
  Tasks/src/V2beta2/AttemptStatus.php
  Tasks/src/V2beta2/CancelLeaseRequest.php
  Tasks/src/V2beta2/CreateQueueRequest.php
  Tasks/src/V2beta2/CreateTaskRequest.php
  Tasks/src/V2beta2/GetTaskRequest.php
  Tasks/src/V2beta2/LeaseTasksRequest.php
  Tasks/src/V2beta2/ListTasksRequest.php
  Tasks/src/V2beta2/Queue.php
  Tasks/src/V2beta2/RenewLeaseRequest.php
  Tasks/src/V2beta2/RetryConfig.php
  Tasks/src/V2beta2/RunTaskRequest.php
  Tasks/src/V2beta2/Task.php
  Tasks/src/V2beta2/TaskStatus.php
  Tasks/src/V2beta2/UpdateQueueRequest.php
  Tasks/src/V2beta3/AppEngineHttpQueue.php
  Tasks/src/V2beta3/AppEngineHttpRequest.php
  Tasks/src/V2beta3/Attempt.php
  Tasks/src/V2beta3/CreateQueueRequest.php
  Tasks/src/V2beta3/CreateTaskRequest.php
  Tasks/src/V2beta3/GetTaskRequest.php
  Tasks/src/V2beta3/HttpRequest.php
  Tasks/src/V2beta3/ListTasksRequest.php
  Tasks/src/V2beta3/Queue.php
  Tasks/src/V2beta3/RetryConfig.php
  Tasks/src/V2beta3/RunTaskRequest.php
  Tasks/src/V2beta3/Task.php
  Tasks/src/V2beta3/UpdateQueueRequest.php
  Tasks/synth.metadata
Labels: cla: yes, context: full

#3286 chore: escape `*` characters in comments
  TextToSpeech/src/V1/Gapic/TextToSpeechGapicClient.php
  TextToSpeech/src/V1/ListVoicesRequest.php
  TextToSpeech/synth.metadata
Labels: cla: yes, context: full

#3344 fix: preserve empty arrays when using set() with merge enabled
  Firestore/src/WriteBatch.php
  Firestore/tests/Unit/WriteBatchTest.php
Labels: api: firestore, cla: yes
