Repository googleapis/google-cloud-php, pull requests merged in 2020-10, with the labels that each got.

#3455 fix: restore LRO REST bindings
  Asset/src/V1/resources/asset_service_rest_client_config.php
Labels: cla: yes

#3453 chore: release 0.141.0
  Asset/VERSION
  Bigtable/VERSION
  Bigtable/src/BigtableClient.php
  CHANGELOG.md
  Debugger/VERSION
  Debugger/src/DebuggerClient.php
  Firestore/VERSION
  Firestore/src/FirestoreClient.php
  Language/VERSION
  Language/src/LanguageClient.php
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: autorelease: pending, cla: yes

#3460 docs: fix proto comments for language API
  Language/src/V1/Document.php
  Language/src/V1beta2/Document.php
  Language/synth.metadata
Labels: cla: yes, context: full

#3451 feat: create references to tables from other projects
  BigQuery/src/BigQueryClient.php
  BigQuery/src/Bytes.php
  BigQuery/src/CopyJobConfiguration.php
  BigQuery/src/Dataset.php
  BigQuery/src/Date.php
  BigQuery/src/ExtractJobConfiguration.php
  BigQuery/src/InsertResponse.php
  BigQuery/src/Job.php
  BigQuery/src/LoadJobConfiguration.php
  BigQuery/src/Model.php
  BigQuery/src/Numeric.php
  BigQuery/src/QueryJobConfiguration.php
  BigQuery/src/QueryResults.php
  BigQuery/src/Table.php
  BigQuery/src/Time.php
  BigQuery/src/Timestamp.php
  BigQuery/tests/Snippet/BigQueryClientTest.php
  BigQuery/tests/System/BigQueryTestCase.php
  BigQuery/tests/System/LoadDataAndQueryTest.php
  BigQuery/tests/System/ManageTablesTest.php
  BigQuery/tests/System/RegionalizationTest.php
  BigQuery/tests/Unit/BigQueryClientTest.php
Labels: api: bigquery, cla: yes

#3457 feat: add aws connection support
  BigQueryConnection/metadata/V1/Connection.php
  BigQueryConnection/src/V1/AwsCrossAccountRole.php
  BigQueryConnection/src/V1/AwsProperties.php
  BigQueryConnection/src/V1/Connection.php
  BigQueryConnection/synth.metadata
Labels: cla: yes, context: full

#3450 feat: introduce datastore admin client
  DatastoreAdmin/.gitattributes
  DatastoreAdmin/.github/pull_request_template.md
  DatastoreAdmin/.repo-metadata.json
  DatastoreAdmin/CONTRIBUTING.md
  DatastoreAdmin/LICENSE
  DatastoreAdmin/README.md
  DatastoreAdmin/composer.json
  DatastoreAdmin/metadata/V1/DatastoreAdmin.php
  DatastoreAdmin/metadata/V1/Index.php
  DatastoreAdmin/phpunit-snippets.xml.dist
  DatastoreAdmin/phpunit-system.xml.dist
  DatastoreAdmin/phpunit.xml.dist
  DatastoreAdmin/src/V1/CommonMetadata.php
  DatastoreAdmin/src/V1/CommonMetadata/State.php
  DatastoreAdmin/src/V1/CommonMetadata_State.php
  DatastoreAdmin/src/V1/DatastoreAdminClient.php
  DatastoreAdmin/src/V1/DatastoreAdminGrpcClient.php
  DatastoreAdmin/src/V1/EntityFilter.php
  DatastoreAdmin/src/V1/ExportEntitiesMetadata.php
  DatastoreAdmin/src/V1/ExportEntitiesRequest.php
  DatastoreAdmin/src/V1/ExportEntitiesResponse.php
  DatastoreAdmin/src/V1/Gapic/DatastoreAdminGapicClient.php
  DatastoreAdmin/src/V1/GetIndexRequest.php
  DatastoreAdmin/src/V1/ImportEntitiesMetadata.php
  DatastoreAdmin/src/V1/ImportEntitiesRequest.php
  DatastoreAdmin/src/V1/Index.php
  DatastoreAdmin/src/V1/Index/AncestorMode.php
  DatastoreAdmin/src/V1/Index/Direction.php
  DatastoreAdmin/src/V1/Index/IndexedProperty.php
  DatastoreAdmin/src/V1/Index/State.php
  DatastoreAdmin/src/V1/IndexOperationMetadata.php
  DatastoreAdmin/src/V1/Index_AncestorMode.php
  DatastoreAdmin/src/V1/Index_Direction.php
  DatastoreAdmin/src/V1/Index_IndexedProperty.php
  DatastoreAdmin/src/V1/Index_State.php
  DatastoreAdmin/src/V1/ListIndexesRequest.php
  DatastoreAdmin/src/V1/ListIndexesResponse.php
  DatastoreAdmin/src/V1/OperationType.php
  DatastoreAdmin/src/V1/Progress.php
  DatastoreAdmin/src/V1/resources/datastore_admin_client_config.json
  DatastoreAdmin/src/V1/resources/datastore_admin_descriptor_config.php
  DatastoreAdmin/src/V1/resources/datastore_admin_rest_client_config.php
  DatastoreAdmin/synth.metadata
  DatastoreAdmin/synth.py
  DatastoreAdmin/tests/Unit/V1/DatastoreAdminClientTest.php
  README.md
  composer.json
  docs/contents/cloud-datastore-admin.json
  docs/contents/google-cloud.json
  docs/manifest.json
Labels: api: datastore, cla: yes

#3464 chore: switch pubsub/v1 retry config to grpc_service_config
  PubSub/src/V1/resources/publisher_client_config.json
  PubSub/src/V1/resources/subscriber_client_config.json
  PubSub/synth.metadata
Labels: cla: yes, context: full

#3462 feat: add text extraction health care option in create model
  AutoMl/metadata/V1Beta1/Text.php
  AutoMl/src/V1beta1/ModelExportOutputConfig.php
  AutoMl/src/V1beta1/TextExtractionModelMetadata.php
  AutoMl/src/V1beta1/resources/auto_ml_client_config.json
  AutoMl/src/V1beta1/resources/auto_ml_rest_client_config.php
  AutoMl/src/V1beta1/resources/prediction_service_rest_client_config.php
  AutoMl/synth.metadata
Labels: cla: yes, context: full

#3456 feat: add support for GEOGRAPHY type
  BigQuery/src/BigQueryClient.php
  BigQuery/src/Geography.php
  BigQuery/src/ValueMapper.php
  BigQuery/tests/Snippet/BigQueryClientTest.php
  BigQuery/tests/Snippet/GeographyTest.php
  BigQuery/tests/System/LoadDataAndQueryTest.php
  BigQuery/tests/System/data/table-data.json
  BigQuery/tests/System/data/table-schema.json
  BigQuery/tests/Unit/BigQueryClientTest.php
  BigQuery/tests/Unit/GeographyTest.php
Labels: api: bigquery, cla: yes

#3467 docs: fixed link from SentimentAnalysisResult
  Dialogflow/src/V2/SentimentAnalysisResult.php
  Dialogflow/synth.metadata
Labels: cla: yes, context: full

#3469 chore: add VERSION file
  DatastoreAdmin/VERSION
Labels: cla: yes

#3468 chore: release 0.142.0
  AutoMl/VERSION
  BigQuery/VERSION
  BigQuery/src/BigQueryClient.php
  BigQueryConnection/VERSION
  CHANGELOG.md
  DatastoreAdmin/VERSION
  Dialogflow/VERSION
  Language/VERSION
  Language/src/LanguageClient.php
  PubSub/VERSION
  PubSub/src/PubSubClient.php
  VideoIntelligence/VERSION
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: autorelease: pending, cla: yes

#3471 feat: add risk analysis options
  Dlp/metadata/V2/Dlp.php
  Dlp/src/V2/AnalyzeDataSourceRiskDetails.php
  Dlp/src/V2/AnalyzeDataSourceRiskDetails/RequestedRiskAnalysisOptions.php
  Dlp/src/V2/AnalyzeDataSourceRiskDetails_RequestedRiskAnalysisOptions.php
  Dlp/src/V2/StorageConfig/TimespanConfig.php
  Dlp/synth.metadata
Labels: cla: yes, context: full

#3474 test: update signature test values
  Kms/synth.metadata
  Kms/tests/Unit/V1/KeyManagementServiceClientTest.php
Labels: cla: yes, context: full

#3472 feat: add support for IN queries with documents IDs
  Firestore/src/Query.php
  Firestore/tests/System/QueryTest.php
  Firestore/tests/Unit/QueryTest.php
Labels: cla: yes

#3476 test: fix Storage system tests
  Storage/tests/System/ManageObjectsTest.php
  Storage/tests/System/StreamWrapper/DirectoryTest.php
Labels: api: storage, cla: yes

#3519 chore: update grpc dependency to v1.33.1
  WebSecurityScanner/src/V1beta/WebSecurityScannerGrpcClient.php
  WebSecurityScanner/synth.metadata
Labels: cla: yes, context: full

#3518 chore: update grpc dependency to v1.33.1
  WebRisk/src/V1/WebRiskServiceGrpcClient.php
  WebRisk/src/V1beta1/WebRiskServiceV1Beta1GrpcClient.php
  WebRisk/synth.metadata
Labels: cla: yes, context: full

#3517 chore: update grpc dependency to v1.33.1
  Vision/src/V1/ImageAnnotatorGrpcClient.php
  Vision/src/V1/ProductSearchGrpcClient.php
  Vision/synth.metadata
Labels: cla: yes, context: full

#3515 chore: update grpc dependency to v1.33.1
  Trace/src/V2/TraceServiceGrpcClient.php
  Trace/synth.metadata
Labels: cla: yes, context: full

#3514 chore: update grpc dependency to v1.33.1
  TextToSpeech/src/V1/TextToSpeechGrpcClient.php
  TextToSpeech/synth.metadata
Labels: cla: yes, context: full

#3513 chore: update grpc dependency to v1.33.1
  Tasks/src/V2/CloudTasksGrpcClient.php
  Tasks/src/V2beta2/CloudTasksGrpcClient.php
  Tasks/src/V2beta3/CloudTasksGrpcClient.php
  Tasks/synth.metadata
Labels: cla: yes, context: full

#3512 chore: update grpc dependency to v1.33.1
  Talent/src/V4beta1/ApplicationServiceGrpcClient.php
  Talent/src/V4beta1/CompanyServiceGrpcClient.php
  Talent/src/V4beta1/CompletionGrpcClient.php
  Talent/src/V4beta1/EventServiceGrpcClient.php
  Talent/src/V4beta1/JobServiceGrpcClient.php
  Talent/src/V4beta1/ProfileServiceGrpcClient.php
  Talent/src/V4beta1/TenantServiceGrpcClient.php
  Talent/synth.metadata
Labels: cla: yes, context: full

#3176 fix: do not stall on Core\Batch\SysvProcessor#submit() when message queue overflows
  Core/src/Batch/QueueOverflowException.php
  Core/src/Batch/SysvProcessor.php
  Core/tests/System/Batch/BatchRunnerTest.php
  Core/tests/Unit/Batch/SysvProcessorTest.php
Labels: api: core, cla: yes

#3516 chore: update grpc dependency to v1.33.1
  VideoIntelligence/src/V1/VideoIntelligenceServiceGrpcClient.php
  VideoIntelligence/src/V1beta2/VideoIntelligenceServiceGrpcClient.php
  VideoIntelligence/synth.metadata
Labels: cla: yes, context: full

#3523 test: allow skipping system tests not supported by emulators
  Core/src/Testing/System/SystemTestCase.php
  Core/tests/Snippet/Testing/System/SystemTestCaseTest.php
Labels: api: core, cla: yes

#3510 chore: update grpc dependency to v1.33.1
  Spanner/src/Admin/Database/V1/DatabaseAdminGrpcClient.php
  Spanner/src/Admin/Instance/V1/InstanceAdminGrpcClient.php
  Spanner/src/V1/SpannerGrpcClient.php
  Spanner/synth.metadata
Labels: cla: yes, context: full

#3524 test: allow changing location for KeyManager
  Core/src/Testing/System/KeyManager.php
Labels: api: core, cla: yes

#3508 chore: update grpc dependency to v1.33.1
  SecurityCenter/src/V1/SecurityCenterGrpcClient.php
  SecurityCenter/src/V1p1beta1/SecurityCenterGrpcClient.php
  SecurityCenter/synth.metadata
Labels: cla: yes, context: full

#3507 chore: update grpc dependency to v1.33.1
  Scheduler/src/V1/CloudSchedulerGrpcClient.php
  Scheduler/src/V1beta1/CloudSchedulerGrpcClient.php
  Scheduler/synth.metadata
Labels: cla: yes, context: full

#3506 chore: update grpc dependency to v1.33.1
  Redis/src/V1/CloudRedisGrpcClient.php
  Redis/src/V1beta1/CloudRedisGrpcClient.php
  Redis/synth.metadata
Labels: cla: yes, context: full

#3505 chore: update grpc dependency to v1.33.1
  Recommender/src/V1/RecommenderGrpcClient.php
  Recommender/synth.metadata
Labels: cla: yes, context: full

#3504 chore: update grpc dependency to v1.33.1
  RecaptchaEnterprise/src/V1/RecaptchaEnterpriseServiceGrpcClient.php
  RecaptchaEnterprise/synth.metadata
Labels: cla: yes, context: full

#3503 chore: update grpc dependency to v1.33.1
  PubSub/src/V1/PublisherGrpcClient.php
  PubSub/src/V1/SubscriberGrpcClient.php
  PubSub/synth.metadata
Labels: cla: yes, context: full

#3501 chore: update grpc dependency to v1.33.1
  OsConfig/src/V1/OsConfigServiceGrpcClient.php
  OsConfig/synth.metadata
Labels: cla: yes, context: full

#3499 chore: update grpc dependency to v1.33.1
  Language/src/V1/LanguageServiceGrpcClient.php
  Language/src/V1beta2/LanguageServiceGrpcClient.php
  Language/synth.metadata
Labels: cla: yes, context: full

#3498 chore: update grpc dependency to v1.33.1
  Kms/src/V1/KeyManagementServiceGrpcClient.php
  Kms/synth.metadata
Labels: cla: yes, context: full

#3496 chore: update grpc dependency to v1.33.1
  Firestore/src/Admin/V1/FirestoreAdminGrpcClient.php
  Firestore/src/V1/FirestoreGrpcClient.php
  Firestore/synth.metadata
Labels: cla: yes, context: full

#3495 chore: update grpc dependency to v1.33.1
  ErrorReporting/src/V1beta1/ErrorGroupServiceGrpcClient.php
  ErrorReporting/src/V1beta1/ErrorStatsServiceGrpcClient.php
  ErrorReporting/src/V1beta1/ReportErrorsServiceGrpcClient.php
  ErrorReporting/synth.metadata
Labels: cla: yes, context: full

#3494 chore: update grpc dependency to v1.33.1
  Dlp/src/V2/DlpServiceGrpcClient.php
  Dlp/synth.metadata
Labels: cla: yes, context: full

#3492 chore: update grpc dependency to v1.33.1
  Debugger/src/V2/Controller2GrpcClient.php
  Debugger/src/V2/Debugger2GrpcClient.php
  Debugger/synth.metadata
Labels: cla: yes, context: full

#3491 chore: update grpc dependency to v1.33.1
  Datastore/src/V1/DatastoreGrpcClient.php
  Datastore/synth.metadata
Labels: cla: yes, context: full

#3490 chore: update grpc dependency to v1.33.1
  Dataproc/src/V1/AutoscalingPolicyServiceGrpcClient.php
  Dataproc/src/V1/ClusterControllerGrpcClient.php
  Dataproc/src/V1/JobControllerGrpcClient.php
  Dataproc/src/V1/WorkflowTemplateServiceGrpcClient.php
  Dataproc/src/V1beta2/AutoscalingPolicyServiceGrpcClient.php
  Dataproc/src/V1beta2/ClusterControllerGrpcClient.php
  Dataproc/src/V1beta2/JobControllerGrpcClient.php
  Dataproc/src/V1beta2/WorkflowTemplateServiceGrpcClient.php
  Dataproc/synth.metadata
Labels: cla: yes, context: full

#3489 chore: update grpc dependency to v1.33.1
  DataCatalog/src/V1/DataCatalogGrpcClient.php
  DataCatalog/synth.metadata
Labels: cla: yes, context: full

#3486 chore: update grpc dependency to v1.33.1
  Bigtable/src/Admin/V2/BigtableInstanceAdminGrpcClient.php
  Bigtable/src/Admin/V2/BigtableTableAdminGrpcClient.php
  Bigtable/src/V2/BigtableGrpcClient.php
  Bigtable/synth.metadata
Labels: cla: yes, context: full

#3483 chore: update grpc dependency to v1.33.1
  BigQueryDataTransfer/src/V1/DataTransferServiceGrpcClient.php
  BigQueryDataTransfer/synth.metadata
Labels: cla: yes, context: full

#3481 chore: update grpc dependency to v1.33.1
  AutoMl/src/V1/AutoMlGrpcClient.php
  AutoMl/src/V1/PredictionServiceGrpcClient.php
  AutoMl/src/V1beta1/AutoMlGrpcClient.php
  AutoMl/src/V1beta1/PredictionServiceGrpcClient.php
  AutoMl/synth.metadata
Labels: cla: yes, context: full

#3525 chore: retry composer update on fail
  .kokoro/presubmit/run-tests.sh
Labels: cla: yes

#3484 chore: update grpc dependency to v1.33.1
  BigQueryReservation/src/V1/ReservationServiceGrpcClient.php
  BigQueryReservation/synth.metadata
Labels: cla: yes, context: full

#3482 chore: update grpc dependency to v1.33.1
  BigQueryConnection/src/V1/ConnectionServiceGrpcClient.php
  BigQueryConnection/synth.metadata
Labels: cla: yes, context: full

#3488 chore: update grpc dependency to v1.33.1
  Container/src/V1/ClusterManagerGrpcClient.php
  Container/synth.metadata
Labels: cla: yes, context: full

#3509 chore: update grpc dependency to v1.33.1
  ServiceDirectory/src/V1beta1/LookupServiceGrpcClient.php
  ServiceDirectory/src/V1beta1/RegistrationServiceGrpcClient.php
  ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#3511 chore: update grpc dependency to v1.33.1
  Speech/src/V1/SpeechGrpcClient.php
  Speech/src/V1p1beta1/SpeechGrpcClient.php
  Speech/synth.metadata
Labels: cla: yes, context: full

#3493 chore: update grpc dependency to v1.33.1
  Dialogflow/src/V2/AgentsGrpcClient.php
  Dialogflow/src/V2/ContextsGrpcClient.php
  Dialogflow/src/V2/EntityTypesGrpcClient.php
  Dialogflow/src/V2/EnvironmentsGrpcClient.php
  Dialogflow/src/V2/IntentsGrpcClient.php
  Dialogflow/src/V2/SessionEntityTypesGrpcClient.php
  Dialogflow/src/V2/SessionsGrpcClient.php
  Dialogflow/synth.metadata
Labels: cla: yes, context: full

#3485 chore: update grpc dependency to v1.33.1
  BigQueryStorage/src/V1/BigQueryReadGrpcClient.php
  BigQueryStorage/synth.metadata
Labels: cla: yes, context: full

#3479 test: detect PubSub emulator and skip unsupported system tests
  PubSub/tests/System/ManageIAMPoliciesTest.php
  PubSub/tests/System/ManageSubscriptionsTest.php
  PubSub/tests/System/ManageTopicsTest.php
  PubSub/tests/System/PubSubTestCase.php
Labels: api: pubsub, cla: yes

#3528 feat: update table admin IAM to include the binding for backup
  Bigtable/metadata/Admin/V2/BigtableInstanceAdmin.php
  Bigtable/metadata/Admin/V2/BigtableTableAdmin.php
  Bigtable/src/Admin/V2/BigtableInstanceAdminGrpcClient.php
  Bigtable/src/Admin/V2/BigtableTableAdminGrpcClient.php
  Bigtable/src/Admin/V2/CheckConsistencyRequest.php
  Bigtable/src/Admin/V2/CreateBackupRequest.php
  Bigtable/src/Admin/V2/CreateTableFromSnapshotRequest.php
  Bigtable/src/Admin/V2/CreateTableRequest.php
  Bigtable/src/Admin/V2/DeleteAppProfileRequest.php
  Bigtable/src/Admin/V2/DeleteBackupRequest.php
  Bigtable/src/Admin/V2/Gapic/BigtableInstanceAdminGapicClient.php
  Bigtable/src/Admin/V2/Gapic/BigtableTableAdminGapicClient.php
  Bigtable/src/Admin/V2/GenerateConsistencyTokenRequest.php
  Bigtable/src/Admin/V2/GetBackupRequest.php
  Bigtable/src/Admin/V2/ListBackupsRequest.php
  Bigtable/src/Admin/V2/ListBackupsResponse.php
  Bigtable/src/Admin/V2/ListSnapshotsRequest.php
  Bigtable/src/Admin/V2/ListTablesRequest.php
  Bigtable/src/Admin/V2/ModifyColumnFamiliesRequest.php
  Bigtable/src/Admin/V2/RestoreTableMetadata.php
  Bigtable/src/Admin/V2/RestoreTableRequest.php
  Bigtable/src/Admin/V2/SnapshotTableRequest.php
  Bigtable/src/Admin/V2/UpdateBackupRequest.php
  Bigtable/src/Admin/V2/resources/bigtable_table_admin_rest_client_config.php
  Bigtable/synth.metadata
Labels: cla: yes, context: full

#3529 fix: update the v1 retry params for several methods
  Recommender/src/V1/resources/recommender_client_config.json
  Recommender/synth.metadata
Labels: cla: yes, context: full

#3487 chore: update grpc dependency to v1.33.1
  Billing/src/V1/CloudBillingGrpcClient.php
  Billing/src/V1/CloudCatalogGrpcClient.php
  Billing/synth.metadata
Labels: cla: yes, context: full

#3497 chore: update grpc dependency to v1.33.1
  Iot/src/V1/DeviceManagerGrpcClient.php
  Iot/synth.metadata
Labels: cla: yes, context: full

#3502 chore: update grpc dependency to v1.33.1
  OsLogin/src/V1/OsLoginServiceGrpcClient.php
  OsLogin/src/V1beta/OsLoginServiceGrpcClient.php
  OsLogin/synth.metadata
Labels: cla: yes, context: full

#3466 feat: add parameter prettyPrint=false to REST API requests
  Core/src/RestTrait.php
  Core/tests/Unit/RestTraitTest.php
Labels: api: core, cla: yes

#3478 feat: implement IAM for tables
  BigQuery/src/Connection/ConnectionInterface.php
  BigQuery/src/Connection/IamTable.php
  BigQuery/src/Connection/Rest.php
  BigQuery/src/Connection/ServiceDefinition/bigquery-v2.json
  BigQuery/src/Table.php
  BigQuery/tests/Snippet/TableTest.php
  BigQuery/tests/System/ManageTablesTest.php
  BigQuery/tests/Unit/Connection/RestTest.php
  BigQuery/tests/Unit/TableTest.php
Labels: api: bigquery, cla: yes

#3530 chore: release 0.143.0
  AutoMl/VERSION
  BigQuery/VERSION
  BigQuery/src/BigQueryClient.php
  BigQueryConnection/VERSION
  BigQueryDataTransfer/VERSION
  BigQueryReservation/VERSION
  BigQueryStorage/VERSION
  Bigtable/VERSION
  Bigtable/src/BigtableClient.php
  Billing/VERSION
  CHANGELOG.md
  Container/VERSION
  Core/VERSION
  DataCatalog/VERSION
  Dataproc/VERSION
  Datastore/VERSION
  Datastore/src/DatastoreClient.php
  Debugger/VERSION
  Debugger/src/DebuggerClient.php
  Dialogflow/VERSION
  Dlp/VERSION
  ErrorReporting/VERSION
  Firestore/VERSION
  Firestore/src/FirestoreClient.php
  Iot/VERSION
  Kms/VERSION
  Language/VERSION
  Language/src/LanguageClient.php
  Memcache/VERSION
  OsConfig/VERSION
  OsLogin/VERSION
  PubSub/VERSION
  PubSub/src/PubSubClient.php
  RecaptchaEnterprise/VERSION
  Recommender/VERSION
  Redis/VERSION
  Scheduler/VERSION
  SecurityCenter/VERSION
  SecurityPrivateCa/VERSION
  ServiceDirectory/VERSION
  Spanner/VERSION
  Spanner/src/SpannerClient.php
  Speech/VERSION
  Speech/src/SpeechClient.php
  Talent/VERSION
  Tasks/VERSION
  TextToSpeech/VERSION
  Trace/VERSION
  Trace/src/TraceClient.php
  VideoIntelligence/VERSION
  Vision/VERSION
  Vision/src/VisionClient.php
  WebRisk/VERSION
  WebSecurityScanner/VERSION
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: autorelease: pending, cla: yes

#3533 test: set correct location for KeyManager
  BigQuery/tests/System/ManageDatasetsTest.php
  BigQuery/tests/System/ManageModelsTest.php
Labels: api: bigquery, cla: yes
