Repository googleapis/google-cloud-php, pull requests merged in 2020-12, with the labels that each got.

#3626 docs: add note about preferring startQuery
  BigQuery/src/BigQueryClient.php
Labels: cla: yes

#3625 chore: fix snippet
  AssuredWorkloads/README.md
Labels: cla: yes

#3628 build: configure release-please bot
  .github/release-please.yml
  .kokoro/continuous/node10/release.sh
  .kokoro/continuous/node10/test.cfg
Labels: cla: yes

#3572 chore: update gapic-generator to v2.8.0
  BigQueryConnection/src/V1/Gapic/ConnectionServiceGapicClient.php
  BigQueryConnection/synth.metadata
Labels: cla: yes, context: full

#3571 chore: update gapic-generator to v2.8.0
  AutoMl/src/V1/Gapic/AutoMlGapicClient.php
  AutoMl/src/V1/Gapic/PredictionServiceGapicClient.php
  AutoMl/src/V1beta1/Gapic/AutoMlGapicClient.php
  AutoMl/src/V1beta1/Gapic/PredictionServiceGapicClient.php
  AutoMl/synth.metadata
Labels: cla: yes, context: full

#3573 chore: update gapic-generator to v2.8.0
  BigQueryDataTransfer/src/V1/Gapic/DataTransferServiceGapicClient.php
  BigQueryDataTransfer/synth.metadata
Labels: cla: yes, context: full

#3574 chore: update gapic-generator to v2.8.0
  BigQueryReservation/src/V1/Gapic/ReservationServiceGapicClient.php
  BigQueryReservation/synth.metadata
Labels: cla: yes, context: full

#3575 chore: update gapic-generator to v2.8.0
  BigQueryStorage/src/V1/Gapic/BigQueryReadGapicClient.php
  BigQueryStorage/synth.metadata
Labels: cla: yes, context: full

#3561 ci: add empty key file and env vars for emulator workflows
  .github/emulator/example-key.json
  .github/workflows/bigtable-emulator-system-tests.yaml
  .github/workflows/datastore-emulator-system-tests.yaml
  .github/workflows/firestore-emulator-system-tests.yaml
  .github/workflows/pubsub-emulator-system-tests.yaml
Labels: cla: yes

#3576 chore: update gapic-generator to v2.8.0
  Bigtable/src/Admin/V2/Gapic/BigtableInstanceAdminGapicClient.php
  Bigtable/src/Admin/V2/Gapic/BigtableTableAdminGapicClient.php
  Bigtable/src/V2/Gapic/BigtableGapicClient.php
  Bigtable/synth.metadata
Labels: cla: yes, context: full

#3579 chore: update gapic-generator to v2.8.0
  DataCatalog/src/V1/Gapic/DataCatalogGapicClient.php
  DataCatalog/synth.metadata
Labels: cla: yes, context: full

#3580 chore: update gapic-generator to v2.8.0
  Dataproc/src/V1/Gapic/AutoscalingPolicyServiceGapicClient.php
  Dataproc/src/V1/Gapic/ClusterControllerGapicClient.php
  Dataproc/src/V1/Gapic/JobControllerGapicClient.php
  Dataproc/src/V1/Gapic/WorkflowTemplateServiceGapicClient.php
  Dataproc/src/V1beta2/Gapic/AutoscalingPolicyServiceGapicClient.php
  Dataproc/src/V1beta2/Gapic/ClusterControllerGapicClient.php
  Dataproc/src/V1beta2/Gapic/JobControllerGapicClient.php
  Dataproc/src/V1beta2/Gapic/WorkflowTemplateServiceGapicClient.php
  Dataproc/synth.metadata
Labels: cla: yes, context: full

#3581 chore: update gapic-generator to v2.8.0
  Datastore/src/V1/Gapic/DatastoreGapicClient.php
  Datastore/synth.metadata
Labels: cla: yes, context: full

#3610 chore: update gapic-generator to v2.8.0
  WebSecurityScanner/src/V1beta/Gapic/WebSecurityScannerGapicClient.php
  WebSecurityScanner/synth.metadata
Labels: cla: yes, context: full

#3609 chore: update gapic-generator to v2.8.0
  WebRisk/src/V1/Gapic/WebRiskServiceGapicClient.php
  WebRisk/src/V1beta1/Gapic/WebRiskServiceV1Beta1GapicClient.php
  WebRisk/synth.metadata
Labels: cla: yes, context: full

#3607 chore: update gapic-generator to v2.8.0
  VideoIntelligence/src/V1/Gapic/VideoIntelligenceServiceGapicClient.php
  VideoIntelligence/src/V1beta2/Gapic/VideoIntelligenceServiceGapicClient.php
  VideoIntelligence/synth.metadata
Labels: cla: yes, context: full

#3606 chore: update gapic-generator to v2.8.0
  Trace/src/V2/Gapic/TraceServiceGapicClient.php
  Trace/synth.metadata
Labels: cla: yes, context: full

#3605 chore: update gapic-generator to v2.8.0
  TextToSpeech/src/V1/Gapic/TextToSpeechGapicClient.php
  TextToSpeech/synth.metadata
Labels: cla: yes, context: full

#3604 chore: update gapic-generator to v2.8.0
  Tasks/src/V2/Gapic/CloudTasksGapicClient.php
  Tasks/src/V2beta2/Gapic/CloudTasksGapicClient.php
  Tasks/src/V2beta3/Gapic/CloudTasksGapicClient.php
  Tasks/synth.metadata
Labels: cla: yes, context: full

#3603 chore: update gapic-generator to v2.8.0
  Talent/src/V4/Gapic/CompanyServiceGapicClient.php
  Talent/src/V4/Gapic/CompletionGapicClient.php
  Talent/src/V4/Gapic/EventServiceGapicClient.php
  Talent/src/V4/Gapic/JobServiceGapicClient.php
  Talent/src/V4/Gapic/TenantServiceGapicClient.php
  Talent/src/V4beta1/Gapic/ApplicationServiceGapicClient.php
  Talent/src/V4beta1/Gapic/CompanyServiceGapicClient.php
  Talent/src/V4beta1/Gapic/CompletionGapicClient.php
  Talent/src/V4beta1/Gapic/EventServiceGapicClient.php
  Talent/src/V4beta1/Gapic/JobServiceGapicClient.php
  Talent/src/V4beta1/Gapic/ProfileServiceGapicClient.php
  Talent/src/V4beta1/Gapic/TenantServiceGapicClient.php
  Talent/synth.metadata
Labels: cla: yes, context: full

#3602 chore: update gapic-generator to v2.8.0
  Speech/src/V1/Gapic/SpeechGapicClient.php
  Speech/src/V1p1beta1/Gapic/SpeechGapicClient.php
  Speech/synth.metadata
Labels: cla: yes, context: full

#3601 chore: update gapic-generator to v2.8.0
  Spanner/src/Admin/Database/V1/Gapic/DatabaseAdminGapicClient.php
  Spanner/src/Admin/Instance/V1/Gapic/InstanceAdminGapicClient.php
  Spanner/src/V1/Gapic/SpannerGapicClient.php
  Spanner/synth.metadata
Labels: cla: yes, context: full

#3600 chore: update gapic-generator to v2.8.0
  ServiceDirectory/src/V1beta1/Gapic/LookupServiceGapicClient.php
  ServiceDirectory/src/V1beta1/Gapic/RegistrationServiceGapicClient.php
  ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#3599 chore(SecurityCenter): update gapic-generator to v2.8.0
  SecurityCenter/src/V1/Gapic/SecurityCenterGapicClient.php
  SecurityCenter/src/V1p1beta1/Gapic/SecurityCenterGapicClient.php
  SecurityCenter/synth.metadata
Labels: cla: yes, context: full

#3598 chore: update gapic-generator to v2.8.0
  SecretManager/src/V1/Gapic/SecretManagerServiceGapicClient.php
  SecretManager/src/V1beta1/Gapic/SecretManagerServiceGapicClient.php
  SecretManager/synth.metadata
Labels: cla: yes, context: full

#3596 chore: update gapic-generator to v2.8.0
  Redis/src/V1/Gapic/CloudRedisGapicClient.php
  Redis/src/V1beta1/Gapic/CloudRedisGapicClient.php
  Redis/synth.metadata
Labels: cla: yes, context: full

#3595 chore: update gapic-generator to v2.8.0
  Recommender/src/V1/Gapic/RecommenderGapicClient.php
  Recommender/synth.metadata
Labels: cla: yes, context: full

#3594 chore: update gapic-generator to v2.8.0
  RecommendationEngine/src/V1beta1/Gapic/CatalogServiceGapicClient.php
  RecommendationEngine/src/V1beta1/Gapic/PredictionApiKeyRegistryGapicClient.php
  RecommendationEngine/src/V1beta1/Gapic/PredictionServiceGapicClient.php
  RecommendationEngine/src/V1beta1/Gapic/UserEventServiceGapicClient.php
  RecommendationEngine/synth.metadata
Labels: cla: yes, context: full

#3592 chore: update gapic-generator to v2.8.0
  PubSub/src/V1/Gapic/PublisherGapicClient.php
  PubSub/src/V1/Gapic/SubscriberGapicClient.php
  PubSub/synth.metadata
Labels: cla: yes, context: full

#3591 chore: update gapic-generator to v2.8.0
  OsLogin/src/V1/Gapic/OsLoginServiceGapicClient.php
  OsLogin/src/V1beta/Gapic/OsLoginServiceGapicClient.php
  OsLogin/synth.metadata
Labels: cla: yes, context: full

#3593 chore: update gapic-generator to v2.8.0
  RecaptchaEnterprise/src/V1/Gapic/RecaptchaEnterpriseServiceGapicClient.php
  RecaptchaEnterprise/synth.metadata
Labels: cla: yes, context: full

#3590 chore: update gapic-generator to v2.8.0
  Memcache/src/V1beta2/Gapic/CloudMemcacheGapicClient.php
  Memcache/synth.metadata
Labels: cla: yes, context: full

#3589 chore: update gapic-generator to v2.8.0
  Language/src/V1/Gapic/LanguageServiceGapicClient.php
  Language/src/V1beta2/Gapic/LanguageServiceGapicClient.php
  Language/synth.metadata
Labels: cla: yes, context: full

#3588 chore: update gapic-generator to v2.8.0
  Kms/src/V1/Gapic/KeyManagementServiceGapicClient.php
  Kms/synth.metadata
Labels: cla: yes, context: full

#3587 chore: update gapic-generator to v2.8.0
  Iot/src/V1/Gapic/DeviceManagerGapicClient.php
  Iot/synth.metadata
Labels: cla: yes, context: full

#3586 chore: update gapic-generator to v2.8.0
  Firestore/src/Admin/V1/Gapic/FirestoreAdminGapicClient.php
  Firestore/src/V1/Gapic/FirestoreGapicClient.php
  Firestore/synth.metadata
Labels: cla: yes, context: full

#3585 chore: update gapic-generator to v2.8.0
  ErrorReporting/src/V1beta1/Gapic/ErrorGroupServiceGapicClient.php
  ErrorReporting/src/V1beta1/Gapic/ErrorStatsServiceGapicClient.php
  ErrorReporting/src/V1beta1/Gapic/ReportErrorsServiceGapicClient.php
  ErrorReporting/synth.metadata
Labels: cla: yes, context: full

#3584 chore: update gapic-generator to v2.8.0
  Dlp/src/V2/Gapic/DlpServiceGapicClient.php
  Dlp/synth.metadata
Labels: cla: yes, context: full

#3583 chore: update gapic-generator to v2.8.0
  Dialogflow/src/V2/Gapic/AgentsGapicClient.php
  Dialogflow/src/V2/Gapic/ContextsGapicClient.php
  Dialogflow/src/V2/Gapic/EntityTypesGapicClient.php
  Dialogflow/src/V2/Gapic/EnvironmentsGapicClient.php
  Dialogflow/src/V2/Gapic/IntentsGapicClient.php
  Dialogflow/src/V2/Gapic/SessionEntityTypesGapicClient.php
  Dialogflow/src/V2/Gapic/SessionsGapicClient.php
  Dialogflow/synth.metadata
Labels: cla: yes, context: full

#3582 chore: update gapic-generator to v2.8.0
  Debugger/src/V2/Gapic/Controller2GapicClient.php
  Debugger/src/V2/Gapic/Debugger2GapicClient.php
  Debugger/synth.metadata
Labels: cla: yes, context: full

#3597 chore: update gapic-generator to v2.8.0
  Scheduler/src/V1/Gapic/CloudSchedulerGapicClient.php
  Scheduler/src/V1beta1/Gapic/CloudSchedulerGapicClient.php
  Scheduler/synth.metadata
Labels: cla: yes, context: full

#3554 chore: move release to github actions
  .github/workflows/release.yml
  .travis.yml
  dev/src/Split/Command.php
  dev/src/Split/GitHub.php
  dev/src/Split/ReleaseNotes.php
  dev/src/Split/SplitInstall.php
  dev/tests/Unit/Split/GitHubTest.php
  dev/tests/Unit/Split/ReleaseNotesTest.php
  dev/tests/fixtures/split/get-release.json
  dev/tests/fixtures/split/get-repo.json
  dev/tests/fixtures/split/release-notes.md
Labels: cla: yes

#3577 chore: update gapic-generator to v2.8.0
  Billing/src/V1/Gapic/CloudBillingGapicClient.php
  Billing/src/V1/Gapic/CloudCatalogGapicClient.php
  Billing/synth.metadata
Labels: cla: yes, context: full, kokoro:force-run

#3633 chore: adds throttled to UpdateDatabaseDdlMetadata
  Spanner/metadata/Admin/Database/V1/SpannerDatabaseAdmin.php
  Spanner/src/Admin/Database/V1/UpdateDatabaseDdlMetadata.php
  Spanner/synth.metadata
Labels: cla: yes, context: full

#3637 fix: add IAM to StorageClient by default
  Storage/src/StorageClient.php
Labels: cla: yes

#3641 chore: fix release action tag fetcher
  .github/workflows/release.yml
Labels: cla: yes

#3644 feat: add support for billingAccounts as a parent resource name
  Recommender/metadata/V1/Insight.php
  Recommender/metadata/V1/Recommendation.php
  Recommender/metadata/V1/RecommenderService.php
  Recommender/src/V1/Gapic/RecommenderGapicClient.php
  Recommender/src/V1/ListInsightsRequest.php
  Recommender/src/V1/ListRecommendationsRequest.php
  Recommender/src/V1/Operation.php
  Recommender/src/V1/resources/recommender_rest_client_config.php
  Recommender/synth.metadata
  Recommender/tests/Unit/V1/RecommenderClientTest.php
Labels: cla: yes, context: full

#3643 feat: added field severity to findings
  SecurityCenter/metadata/V1/Finding.php
  SecurityCenter/metadata/V1/SecuritycenterService.php
  SecurityCenter/src/V1/CreateFindingRequest.php
  SecurityCenter/src/V1/CreateNotificationConfigRequest.php
  SecurityCenter/src/V1/CreateSourceRequest.php
  SecurityCenter/src/V1/Finding.php
  SecurityCenter/src/V1/Finding/Severity.php
  SecurityCenter/src/V1/Finding_Severity.php
  SecurityCenter/src/V1/Gapic/SecurityCenterGapicClient.php
  SecurityCenter/src/V1/GetOrganizationSettingsRequest.php
  SecurityCenter/src/V1/GroupAssetsRequest.php
  SecurityCenter/src/V1/GroupFindingsRequest.php
  SecurityCenter/src/V1/ListAssetsRequest.php
  SecurityCenter/src/V1/ListFindingsRequest.php
  SecurityCenter/src/V1/ListFindingsResponse/ListFindingsResult.php
  SecurityCenter/src/V1/NotificationConfig.php
  SecurityCenter/src/V1/RunAssetDiscoveryRequest.php
  SecurityCenter/src/V1/UpdateFindingRequest.php
  SecurityCenter/src/V1/UpdateOrganizationSettingsRequest.php
  SecurityCenter/synth.metadata
Labels: cla: yes, context: full
