Repository googleapis/google-cloud-php, pull requests merged in 2020-07, with the labels that each got.

#3090 feat: add maintain() method for CacheSessionPool
  Spanner/src/Session/CacheSessionPool.php
  Spanner/tests/Unit/Session/CacheSessionPoolTest.php
Labels: api: spanner, cla: yes

#3233 feat: Surface to retryFunction for observation.
  Core/src/RequestWrapper.php
Labels: cla: yes

#3226 ci(spanner): add emulator system tests GitHub action
  .github/workflows/spanner-integration-tests-against-emulator.yaml
Labels: automerge, cla: yes

#3238 fix: use correct variable name for retry attempt argument
  Core/src/RequestWrapper.php
Labels: api: core, cla: yes

#3237 fix: exclude generated client from debug dump
  Firestore/src/Connection/Grpc.php
Labels: api: firestore, cla: yes

#3129 chore: migrate docs jobs from travis to github
  .github/workflows/docs.yml
  .travis.yml
  dev/sh/build-docs
  dev/sh/push-docs
Labels: cla: yes

#3241 feat: update retry and timeout configuration
  ErrorReporting/src/V1beta1/resources/error_group_service_client_config.json
  ErrorReporting/src/V1beta1/resources/error_stats_service_client_config.json
  ErrorReporting/src/V1beta1/resources/report_errors_service_client_config.json
  ErrorReporting/synth.metadata
Labels: cla: yes, context: full

#3240 feat: update retry and timeout configuration
  Debugger/src/V2/resources/controller2_client_config.json
  Debugger/src/V2/resources/debugger2_client_config.json
  Debugger/synth.metadata
Labels: cla: yes, context: full

#3230 feat: update retry and timeout configuration
  BigQueryDataTransfer/src/V1/Gapic/DataTransferServiceGapicClient.php
  BigQueryDataTransfer/src/V1/resources/data_transfer_service_client_config.json
  BigQueryDataTransfer/src/V1/resources/data_transfer_service_rest_client_config.php
  BigQueryDataTransfer/synth.metadata
  BigQueryDataTransfer/tests/Unit/V1/DataTransferServiceClientTest.php
Labels: cla: yes, context: full

#3217 Add support for Guzzle 7.x
  Core/composer.json
  composer.json
Labels: cla: yes

#3239 chore: release 0.136.0
  BigQueryDataTransfer/VERSION
  BigQueryStorage/VERSION
  Bigtable/VERSION
  Bigtable/src/BigtableClient.php
  Billing/VERSION
  CHANGELOG.md
  Container/VERSION
  Core/VERSION
  DataCatalog/VERSION
  Dataproc/VERSION
  Datastore/VERSION
  Datastore/src/DatastoreClient.php
  Debugger/VERSION
  Debugger/src/DebuggerClient.php
  Dialogflow/VERSION
  ErrorReporting/VERSION
  Firestore/VERSION
  Firestore/src/FirestoreClient.php
  Iot/VERSION
  Kms/VERSION
  Language/VERSION
  Language/src/LanguageClient.php
  Memcache/VERSION
  OsLogin/VERSION
  PubSub/VERSION
  PubSub/src/PubSubClient.php
  RecaptchaEnterprise/VERSION
  Recommender/VERSION
  Redis/VERSION
  Scheduler/VERSION
  SecurityCenter/VERSION
  ServiceDirectory/VERSION
  Spanner/VERSION
  Spanner/src/SpannerClient.php
  Speech/VERSION
  Speech/src/SpeechClient.php
  Storage/VERSION
  Storage/src/StorageClient.php
  Talent/VERSION
  Tasks/VERSION
  TextToSpeech/VERSION
  Trace/VERSION
  Trace/src/TraceClient.php
  Translate/VERSION
  VideoIntelligence/VERSION
  Vision/VERSION
  Vision/src/VisionClient.php
  WebRisk/VERSION
  WebSecurityScanner/VERSION
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: autorelease: pending, cla: yes

#3229 chore: update retry configurations
  Spanner/metadata/Admin/Database/V1/SpannerDatabaseAdmin.php
  Spanner/metadata/V1/Type.php
  Spanner/src/Admin/Database/V1/Gapic/DatabaseAdminGapicClient.php
  Spanner/src/Admin/Database/V1/resources/database_admin_client_config.json
  Spanner/src/Admin/Database/V1/resources/database_admin_rest_client_config.php
  Spanner/src/Admin/Instance/V1/Gapic/InstanceAdminGapicClient.php
  Spanner/src/Admin/Instance/V1/resources/instance_admin_client_config.json
  Spanner/src/Admin/Instance/V1/resources/instance_admin_rest_client_config.php
  Spanner/src/V1/Type.php
  Spanner/src/V1/TypeCode.php
  Spanner/src/V1/resources/spanner_client_config.json
  Spanner/synth.metadata
  Spanner/tests/Unit/Admin/Database/V1/DatabaseAdminClientTest.php
  Spanner/tests/Unit/Admin/Instance/V1/InstanceAdminClientTest.php
Labels: cla: yes, context: full

#3247 chore: migrate to bazel
  RecommendationEngine/synth.py
Labels: api: recommendationengine, cla: yes

#3223 feat: adds methods for interacting with insights
  Recommender/metadata/V1/Insight.php
  Recommender/metadata/V1/Recommendation.php
  Recommender/metadata/V1/RecommenderService.php
  Recommender/src/V1/Gapic/RecommenderGapicClient.php
  Recommender/src/V1/GetInsightRequest.php
  Recommender/src/V1/Insight.php
  Recommender/src/V1/Insight/Category.php
  Recommender/src/V1/Insight/RecommendationReference.php
  Recommender/src/V1/InsightStateInfo.php
  Recommender/src/V1/InsightStateInfo/State.php
  Recommender/src/V1/InsightStateInfo_State.php
  Recommender/src/V1/Insight_Category.php
  Recommender/src/V1/Insight_RecommendationReference.php
  Recommender/src/V1/ListInsightsRequest.php
  Recommender/src/V1/ListInsightsResponse.php
  Recommender/src/V1/MarkInsightAcceptedRequest.php
  Recommender/src/V1/Recommendation.php
  Recommender/src/V1/Recommendation/InsightReference.php
  Recommender/src/V1/RecommendationStateInfo/State.php
  Recommender/src/V1/Recommendation_InsightReference.php
  Recommender/src/V1/RecommenderGrpcClient.php
  Recommender/src/V1/resources/recommender_client_config.json
  Recommender/src/V1/resources/recommender_descriptor_config.php
  Recommender/src/V1/resources/recommender_rest_client_config.php
  Recommender/synth.metadata
  Recommender/tests/Unit/V1/RecommenderClientTest.php
Labels: cla: yes, context: full

#3260 docs: add backticks in docstring
  Translate/src/V3/OutputConfig.php
  Translate/synth.metadata
Labels: cla: yes, context: full

#3259 docs: remove experimental warning for ordering keys properties
  PubSub/src/V1/Gapic/PublisherGapicClient.php
  PubSub/src/V1/Gapic/SubscriberGapicClient.php
  PubSub/src/V1/PublisherGrpcClient.php
  PubSub/src/V1/PubsubMessage.php
  PubSub/src/V1/Snapshot.php
  PubSub/src/V1/SubscriberGrpcClient.php
  PubSub/src/V1/Subscription.php
  PubSub/src/V1/Topic.php
  PubSub/synth.metadata
Labels: cla: yes, context: full

#3227 feat: added support for span kind
  Trace/metadata/V2/Trace.php
  Trace/src/V2/Gapic/TraceServiceGapicClient.php
  Trace/src/V2/Span.php
  Trace/src/V2/Span/Attributes.php
  Trace/src/V2/Span/SpanKind.php
  Trace/src/V2/Span_SpanKind.php
  Trace/src/V2/TraceServiceGrpcClient.php
  Trace/src/V2/resources/trace_service_client_config.json
  Trace/synth.metadata
Labels: cla: yes, context: full

#3125 feat: add client support for detach subscription
  PubSub/src/Connection/ConnectionInterface.php
  PubSub/src/Connection/Grpc.php
  PubSub/src/Connection/Rest.php
  PubSub/src/Subscription.php
  PubSub/tests/Snippet/SubscriptionTest.php
  PubSub/tests/System/ManageSubscriptionsTest.php
  PubSub/tests/System/PubSubTestCase.php
  PubSub/tests/Unit/Connection/GrpcTest.php
  PubSub/tests/Unit/Connection/RestTest.php
  PubSub/tests/Unit/SubscriptionTest.php
Labels: api: pubsub, cla: yes

#3266 feat: update retry and timeout configuration
  Language/src/V1/resources/language_service_client_config.json
  Language/src/V1beta2/resources/language_service_client_config.json
  Language/synth.metadata
Labels: cla: yes, context: full

#3267 feat: update retry and timeout configuration
  ServiceDirectory/src/V1beta1/resources/lookup_service_client_config.json
  ServiceDirectory/src/V1beta1/resources/registration_service_client_config.json
  ServiceDirectory/synth.metadata
Labels: cla: yes, context: full
