Repository googleapis/google-cloud-php, pull requests merged in 2020-09, with the labels that each got.

#3325 feat: regenerate with protoc v3.13.0
  Speech/src/V1/LongRunningRecognizeMetadata.php
  Speech/src/V1/LongRunningRecognizeRequest.php
  Speech/src/V1/RecognitionAudio.php
  Speech/src/V1/RecognitionConfig.php
  Speech/src/V1/RecognitionMetadata.php
  Speech/src/V1/RecognizeRequest.php
  Speech/src/V1/StreamingRecognitionConfig.php
  Speech/src/V1/StreamingRecognitionResult.php
  Speech/src/V1/StreamingRecognizeRequest.php
  Speech/src/V1/StreamingRecognizeResponse.php
  Speech/src/V1/WordInfo.php
  Speech/src/V1p1beta1/LongRunningRecognizeMetadata.php
  Speech/src/V1p1beta1/LongRunningRecognizeRequest.php
  Speech/src/V1p1beta1/RecognitionAudio.php
  Speech/src/V1p1beta1/RecognitionConfig.php
  Speech/src/V1p1beta1/RecognitionMetadata.php
  Speech/src/V1p1beta1/RecognizeRequest.php
  Speech/src/V1p1beta1/StreamingRecognitionConfig.php
  Speech/src/V1p1beta1/StreamingRecognitionResult.php
  Speech/src/V1p1beta1/StreamingRecognizeRequest.php
  Speech/src/V1p1beta1/StreamingRecognizeResponse.php
  Speech/src/V1p1beta1/WordInfo.php
  Speech/synth.metadata
Labels: cla: yes, context: full

#3324 feat: regenerate with protoc v3.13.0
  Spanner/src/Admin/Database/V1/Backup.php
  Spanner/src/Admin/Database/V1/BackupInfo.php
  Spanner/src/Admin/Database/V1/CreateBackupMetadata.php
  Spanner/src/Admin/Database/V1/CreateBackupRequest.php
  Spanner/src/Admin/Database/V1/Database.php
  Spanner/src/Admin/Database/V1/OperationProgress.php
  Spanner/src/Admin/Database/V1/OptimizeRestoredDatabaseMetadata.php
  Spanner/src/Admin/Database/V1/RestoreDatabaseMetadata.php
  Spanner/src/Admin/Database/V1/RestoreDatabaseRequest.php
  Spanner/src/Admin/Database/V1/RestoreInfo.php
  Spanner/src/Admin/Database/V1/UpdateBackupRequest.php
  Spanner/src/Admin/Instance/V1/CreateInstanceMetadata.php
  Spanner/src/Admin/Instance/V1/CreateInstanceRequest.php
  Spanner/src/Admin/Instance/V1/GetInstanceRequest.php
  Spanner/src/Admin/Instance/V1/Instance.php
  Spanner/src/Admin/Instance/V1/ReplicaInfo.php
  Spanner/src/Admin/Instance/V1/UpdateInstanceMetadata.php
  Spanner/src/Admin/Instance/V1/UpdateInstanceRequest.php
  Spanner/src/V1/BatchCreateSessionsRequest.php
  Spanner/src/V1/BeginTransactionRequest.php
  Spanner/src/V1/CommitRequest.php
  Spanner/src/V1/CommitResponse.php
  Spanner/src/V1/CreateSessionRequest.php
  Spanner/src/V1/ExecuteBatchDmlRequest.php
  Spanner/src/V1/ExecuteBatchDmlRequest/Statement.php
  Spanner/src/V1/ExecuteBatchDmlResponse.php
  Spanner/src/V1/ExecuteSqlRequest.php
  Spanner/src/V1/KeyRange.php
  Spanner/src/V1/Mutation.php
  Spanner/src/V1/Mutation/Delete.php
  Spanner/src/V1/PartialResultSet.php
  Spanner/src/V1/PartitionQueryRequest.php
  Spanner/src/V1/PartitionReadRequest.php
  Spanner/src/V1/PartitionResponse.php
  Spanner/src/V1/PlanNode.php
  Spanner/src/V1/ReadRequest.php
  Spanner/src/V1/ResultSet.php
  Spanner/src/V1/ResultSetMetadata.php
  Spanner/src/V1/ResultSetStats.php
  Spanner/src/V1/Session.php
  Spanner/src/V1/StructType/Field.php
  Spanner/src/V1/Transaction.php
  Spanner/src/V1/TransactionOptions.php
  Spanner/src/V1/TransactionOptions/ReadOnly.php
  Spanner/src/V1/TransactionSelector.php
  Spanner/src/V1/Type.php
  Spanner/synth.metadata
Labels: cla: yes, context: full

#3323 feat: regenerate with protoc v3.13.0
  ServiceDirectory/src/V1beta1/CreateEndpointRequest.php
  ServiceDirectory/src/V1beta1/CreateNamespaceRequest.php
  ServiceDirectory/src/V1beta1/CreateServiceRequest.php
  ServiceDirectory/src/V1beta1/ResolveServiceResponse.php
  ServiceDirectory/src/V1beta1/UpdateEndpointRequest.php
  ServiceDirectory/src/V1beta1/UpdateNamespaceRequest.php
  ServiceDirectory/src/V1beta1/UpdateServiceRequest.php
  ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#3322 feat: regenerate with protoc v3.13.0
  Scheduler/src/V1/AppEngineHttpTarget.php
  Scheduler/src/V1/CreateJobRequest.php
  Scheduler/src/V1/HttpTarget.php
  Scheduler/src/V1/Job.php
  Scheduler/src/V1/RetryConfig.php
  Scheduler/src/V1/UpdateJobRequest.php
  Scheduler/src/V1beta1/AppEngineHttpTarget.php
  Scheduler/src/V1beta1/CreateJobRequest.php
  Scheduler/src/V1beta1/HttpTarget.php
  Scheduler/src/V1beta1/Job.php
  Scheduler/src/V1beta1/RetryConfig.php
  Scheduler/src/V1beta1/UpdateJobRequest.php
  Scheduler/synth.metadata
Labels: cla: yes, context: full

#3321 feat: regenerate with protoc v3.13.0
  Redis/src/V1/CreateInstanceRequest.php
  Redis/src/V1/ExportInstanceRequest.php
  Redis/src/V1/FailoverInstanceRequest.php
  Redis/src/V1/ImportInstanceRequest.php
  Redis/src/V1/InputConfig.php
  Redis/src/V1/Instance.php
  Redis/src/V1/OperationMetadata.php
  Redis/src/V1/OutputConfig.php
  Redis/src/V1/UpdateInstanceRequest.php
  Redis/src/V1beta1/CreateInstanceRequest.php
  Redis/src/V1beta1/ExportInstanceRequest.php
  Redis/src/V1beta1/FailoverInstanceRequest.php
  Redis/src/V1beta1/ImportInstanceRequest.php
  Redis/src/V1beta1/InputConfig.php
  Redis/src/V1beta1/Instance.php
  Redis/src/V1beta1/OutputConfig.php
  Redis/src/V1beta1/UpdateInstanceRequest.php
  Redis/synth.metadata
Labels: cla: yes, context: full

#3320 feat: regenerate with protoc v3.13.0
  Recommender/src/V1/CostProjection.php
  Recommender/src/V1/Impact.php
  Recommender/src/V1/Insight.php
  Recommender/src/V1/InsightStateInfo.php
  Recommender/src/V1/Operation.php
  Recommender/src/V1/Recommendation.php
  Recommender/src/V1/RecommendationStateInfo.php
  Recommender/src/V1/ValueMatcher.php
  Recommender/synth.metadata
Labels: cla: yes, context: full

#3319 feat: regenerate with protoc v3.13.0
  RecaptchaEnterprise/src/V1/AnnotateAssessmentRequest.php
  RecaptchaEnterprise/src/V1/Assessment.php
  RecaptchaEnterprise/src/V1/CreateAssessmentRequest.php
  RecaptchaEnterprise/src/V1/CreateKeyRequest.php
  RecaptchaEnterprise/src/V1/Key.php
  RecaptchaEnterprise/src/V1/TokenProperties.php
  RecaptchaEnterprise/src/V1/UpdateKeyRequest.php
  RecaptchaEnterprise/src/V1/WebKeySettings.php
  RecaptchaEnterprise/synth.metadata
Labels: cla: yes, context: full

#3318 feat: regenerate with protoc v3.13.0
  PubSub/src/V1/ExpirationPolicy.php
  PubSub/src/V1/ModifyPushConfigRequest.php
  PubSub/src/V1/PubsubMessage.php
  PubSub/src/V1/PushConfig.php
  PubSub/src/V1/ReceivedMessage.php
  PubSub/src/V1/RetryPolicy.php
  PubSub/src/V1/SeekRequest.php
  PubSub/src/V1/Snapshot.php
  PubSub/src/V1/Subscription.php
  PubSub/src/V1/Topic.php
  PubSub/src/V1/UpdateSnapshotRequest.php
  PubSub/src/V1/UpdateSubscriptionRequest.php
  PubSub/src/V1/UpdateTopicRequest.php
  PubSub/synth.metadata
Labels: cla: yes, context: full

#3317 feat: regenerate with protoc v3.13.0
  OsLogin/src/V1/ImportSshPublicKeyRequest.php
  OsLogin/src/V1/ImportSshPublicKeyResponse.php
  OsLogin/src/V1/UpdateSshPublicKeyRequest.php
  OsLogin/src/V1beta/ImportSshPublicKeyRequest.php
  OsLogin/src/V1beta/ImportSshPublicKeyResponse.php
  OsLogin/src/V1beta/UpdateSshPublicKeyRequest.php
  OsLogin/synth.metadata
Labels: cla: yes, context: full

#3316 feat: regenerate with protoc v3.13.0
  Memcache/src/V1beta2/CreateInstanceRequest.php
  Memcache/src/V1beta2/Instance.php
  Memcache/src/V1beta2/Instance/InstanceMessage.php
  Memcache/src/V1beta2/Instance/Node.php
  Memcache/src/V1beta2/OperationMetadata.php
  Memcache/src/V1beta2/UpdateInstanceRequest.php
  Memcache/src/V1beta2/UpdateParametersRequest.php
  Memcache/synth.metadata
Labels: cla: yes, context: full

#3315 feat: regenerate with protoc v3.13.0
  Language/src/V1/AnalyzeEntitiesRequest.php
  Language/src/V1/AnalyzeEntitySentimentRequest.php
  Language/src/V1/AnalyzeSentimentRequest.php
  Language/src/V1/AnalyzeSentimentResponse.php
  Language/src/V1/AnalyzeSyntaxRequest.php
  Language/src/V1/AnnotateTextRequest.php
  Language/src/V1/AnnotateTextResponse.php
  Language/src/V1/ClassifyTextRequest.php
  Language/src/V1/DependencyEdge.php
  Language/src/V1/Document.php
  Language/src/V1/Entity.php
  Language/src/V1/EntityMention.php
  Language/src/V1/PartOfSpeech.php
  Language/src/V1/Sentence.php
  Language/src/V1/Token.php
  Language/src/V1beta2/AnalyzeEntitiesRequest.php
  Language/src/V1beta2/AnalyzeEntitySentimentRequest.php
  Language/src/V1beta2/AnalyzeSentimentRequest.php
  Language/src/V1beta2/AnalyzeSentimentResponse.php
  Language/src/V1beta2/AnalyzeSyntaxRequest.php
  Language/src/V1beta2/AnnotateTextRequest.php
  Language/src/V1beta2/AnnotateTextResponse.php
  Language/src/V1beta2/ClassifyTextRequest.php
  Language/src/V1beta2/DependencyEdge.php
  Language/src/V1beta2/Document.php
  Language/src/V1beta2/Entity.php
  Language/src/V1beta2/EntityMention.php
  Language/src/V1beta2/PartOfSpeech.php
  Language/src/V1beta2/Sentence.php
  Language/src/V1beta2/Token.php
  Language/synth.metadata
Labels: cla: yes, context: full

#3314 feat: regenerate with protoc v3.13.0
  Iot/src/V1/CreateDeviceRegistryRequest.php
  Iot/src/V1/CreateDeviceRequest.php
  Iot/src/V1/Device.php
  Iot/src/V1/DeviceConfig.php
  Iot/src/V1/DeviceCredential.php
  Iot/src/V1/DeviceRegistry.php
  Iot/src/V1/DeviceState.php
  Iot/src/V1/GatewayConfig.php
  Iot/src/V1/GatewayListOptions.php
  Iot/src/V1/GetDeviceRequest.php
  Iot/src/V1/ListDevicesRequest.php
  Iot/src/V1/PublicKeyCertificate.php
  Iot/src/V1/RegistryCredential.php
  Iot/src/V1/UpdateDeviceRegistryRequest.php
  Iot/src/V1/UpdateDeviceRequest.php
  Iot/src/V1/X509CertificateDetails.php
  Iot/synth.metadata
Labels: cla: yes, context: full

#3313 feat: regenerate with protoc v3.13.0
  ErrorReporting/src/V1beta1/ErrorContext.php
  ErrorReporting/src/V1beta1/ErrorEvent.php
  ErrorReporting/src/V1beta1/ErrorGroupStats.php
  ErrorReporting/src/V1beta1/ListEventsRequest.php
  ErrorReporting/src/V1beta1/ListEventsResponse.php
  ErrorReporting/src/V1beta1/ListGroupStatsRequest.php
  ErrorReporting/src/V1beta1/ListGroupStatsResponse.php
  ErrorReporting/src/V1beta1/QueryTimeRange.php
  ErrorReporting/src/V1beta1/ReportErrorEventRequest.php
  ErrorReporting/src/V1beta1/ReportedErrorEvent.php
  ErrorReporting/src/V1beta1/TimedCount.php
  ErrorReporting/src/V1beta1/UpdateGroupRequest.php
  ErrorReporting/synth.metadata
Labels: cla: yes, context: full

#3310 feat: regenerate with protoc v3.13.0
  Datastore/src/V1/BeginTransactionRequest.php
  Datastore/src/V1/CommitRequest.php
  Datastore/src/V1/CompositeFilter.php
  Datastore/src/V1/Entity.php
  Datastore/src/V1/EntityResult.php
  Datastore/src/V1/Filter.php
  Datastore/src/V1/GqlQueryParameter.php
  Datastore/src/V1/Key.php
  Datastore/src/V1/Key/PathElement.php
  Datastore/src/V1/LookupRequest.php
  Datastore/src/V1/Mutation.php
  Datastore/src/V1/MutationResult.php
  Datastore/src/V1/Projection.php
  Datastore/src/V1/PropertyFilter.php
  Datastore/src/V1/PropertyOrder.php
  Datastore/src/V1/Query.php
  Datastore/src/V1/QueryResultBatch.php
  Datastore/src/V1/ReadOptions.php
  Datastore/src/V1/RunQueryRequest.php
  Datastore/src/V1/RunQueryResponse.php
  Datastore/src/V1/TransactionOptions.php
  Datastore/src/V1/Value.php
  Datastore/synth.metadata
Labels: cla: yes, context: full

#3308 feat: regenerate with protoc v3.13.0
  DataCatalog/src/V1/BigQueryTableSpec.php
  DataCatalog/src/V1/CreateEntryGroupRequest.php
  DataCatalog/src/V1/CreateEntryRequest.php
  DataCatalog/src/V1/CreateTagRequest.php
  DataCatalog/src/V1/CreateTagTemplateFieldRequest.php
  DataCatalog/src/V1/CreateTagTemplateRequest.php
  DataCatalog/src/V1/Entry.php
  DataCatalog/src/V1/EntryGroup.php
  DataCatalog/src/V1/FieldType.php
  DataCatalog/src/V1/GcsFileSpec.php
  DataCatalog/src/V1/GetEntryGroupRequest.php
  DataCatalog/src/V1/ListEntriesRequest.php
  DataCatalog/src/V1/LookupEntryRequest.php
  DataCatalog/src/V1/SearchCatalogRequest.php
  DataCatalog/src/V1/SearchCatalogResult.php
  DataCatalog/src/V1/SystemTimestamps.php
  DataCatalog/src/V1/Tag.php
  DataCatalog/src/V1/TagField.php
  DataCatalog/src/V1/TagTemplateField.php
  DataCatalog/src/V1/UpdateEntryGroupRequest.php
  DataCatalog/src/V1/UpdateEntryRequest.php
  DataCatalog/src/V1/UpdateTagRequest.php
  DataCatalog/src/V1/UpdateTagTemplateFieldRequest.php
  DataCatalog/src/V1/UpdateTagTemplateRequest.php
  DataCatalog/synth.metadata
Labels: cla: yes, context: full

#3307 feat: regenerate with protoc v3.13.0
  Container/src/V1/AddonsConfig.php
  Container/src/V1/Cluster.php
  Container/src/V1/ClusterAutoscaling.php
  Container/src/V1/ClusterUpdate.php
  Container/src/V1/CreateClusterRequest.php
  Container/src/V1/CreateNodePoolRequest.php
  Container/src/V1/DatabaseEncryption.php
  Container/src/V1/MaintenancePolicy.php
  Container/src/V1/MaintenanceWindow.php
  Container/src/V1/MasterAuth.php
  Container/src/V1/NetworkPolicy.php
  Container/src/V1/NodeConfig.php
  Container/src/V1/NodeManagement.php
  Container/src/V1/NodePool.php
  Container/src/V1/NodeTaint.php
  Container/src/V1/Operation.php
  Container/src/V1/RecurringTimeWindow.php
  Container/src/V1/ResourceUsageExportConfig.php
  Container/src/V1/SetAddonsConfigRequest.php
  Container/src/V1/SetMaintenancePolicyRequest.php
  Container/src/V1/SetMasterAuthRequest.php
  Container/src/V1/SetNetworkPolicyRequest.php
  Container/src/V1/SetNodePoolAutoscalingRequest.php
  Container/src/V1/SetNodePoolManagementRequest.php
  Container/src/V1/StatusCondition.php
  Container/src/V1/TimeWindow.php
  Container/src/V1/UpdateClusterRequest.php
  Container/src/V1/UsableSubnetworkSecondaryRange.php
  Container/synth.metadata
Labels: cla: yes, context: full

#3306 feat: regenerate with protoc v3.13.0
  Billing/src/V1/AggregationInfo.php
  Billing/src/V1/CreateBillingAccountRequest.php
  Billing/src/V1/ListSkusRequest.php
  Billing/src/V1/PricingExpression/TierRate.php
  Billing/src/V1/PricingInfo.php
  Billing/src/V1/Sku.php
  Billing/src/V1/UpdateBillingAccountRequest.php
  Billing/src/V1/UpdateProjectBillingInfoRequest.php
  Billing/synth.metadata
Labels: cla: yes, context: full

#3305 feat: regenerate with protoc v3.13.0
  Bigtable/src/Admin/V2/AppProfile.php
  Bigtable/src/Admin/V2/Backup.php
  Bigtable/src/Admin/V2/BackupInfo.php
  Bigtable/src/Admin/V2/Cluster.php
  Bigtable/src/Admin/V2/ColumnFamily.php
  Bigtable/src/Admin/V2/CreateAppProfileRequest.php
  Bigtable/src/Admin/V2/CreateBackupMetadata.php
  Bigtable/src/Admin/V2/CreateBackupRequest.php
  Bigtable/src/Admin/V2/CreateClusterMetadata.php
  Bigtable/src/Admin/V2/CreateClusterRequest.php
  Bigtable/src/Admin/V2/CreateInstanceMetadata.php
  Bigtable/src/Admin/V2/CreateInstanceRequest.php
  Bigtable/src/Admin/V2/CreateTableFromSnapshotMetadata.php
  Bigtable/src/Admin/V2/CreateTableRequest.php
  Bigtable/src/Admin/V2/DropRowRangeRequest.php
  Bigtable/src/Admin/V2/GcRule.php
  Bigtable/src/Admin/V2/GetTableRequest.php
  Bigtable/src/Admin/V2/Instance.php
  Bigtable/src/Admin/V2/ListTablesRequest.php
  Bigtable/src/Admin/V2/ModifyColumnFamiliesRequest/Modification.php
  Bigtable/src/Admin/V2/OperationProgress.php
  Bigtable/src/Admin/V2/OptimizeRestoredTableMetadata.php
  Bigtable/src/Admin/V2/PartialUpdateInstanceRequest.php
  Bigtable/src/Admin/V2/RestoreInfo.php
  Bigtable/src/Admin/V2/RestoreTableMetadata.php
  Bigtable/src/Admin/V2/RestoreTableRequest.php
  Bigtable/src/Admin/V2/Snapshot.php
  Bigtable/src/Admin/V2/SnapshotTableMetadata.php
  Bigtable/src/Admin/V2/SnapshotTableRequest.php
  Bigtable/src/Admin/V2/Table.php
  Bigtable/src/Admin/V2/Table/ClusterState.php
  Bigtable/src/Admin/V2/UpdateAppProfileRequest.php
  Bigtable/src/Admin/V2/UpdateBackupRequest.php
  Bigtable/src/Admin/V2/UpdateClusterMetadata.php
  Bigtable/src/Admin/V2/UpdateInstanceMetadata.php
  Bigtable/src/V2/CheckAndMutateRowRequest.php
  Bigtable/src/V2/ColumnRange.php
  Bigtable/src/V2/MutateRowsResponse/Entry.php
  Bigtable/src/V2/Mutation.php
  Bigtable/src/V2/Mutation/DeleteFromColumn.php
  Bigtable/src/V2/ReadModifyWriteRowResponse.php
  Bigtable/src/V2/ReadModifyWriteRule.php
  Bigtable/src/V2/ReadRowsRequest.php
  Bigtable/src/V2/ReadRowsResponse/CellChunk.php
  Bigtable/src/V2/RowFilter.php
  Bigtable/src/V2/RowFilter/Condition.php
  Bigtable/src/V2/RowRange.php
  Bigtable/src/V2/ValueRange.php
  Bigtable/synth.metadata
Labels: cla: yes, context: full

#3146 feat: retry CommitRequests that fail with UNAVAILABLE
  Firestore/metadata/V1/Query.php
  Firestore/synth.metadata
Labels: cla: yes, context: full

#3108 feat: support fflush() and append mode in StreamWrapper
  Storage/src/StreamWrapper.php
  Storage/tests/System/StreamWrapper/AppendTest.php
  Storage/tests/System/StreamWrapper/FlushTest.php
  Storage/tests/Unit/StreamWrapperTest.php
Labels: api: storage, cla: yes

#3364 feat!: move clients from beta to GA
  BigQueryStorage/.repo-metadata.json
  BigQueryStorage/README.md
  BigQueryStorage/synth.py
  DataCatalog/.repo-metadata.json
  DataCatalog/README.md
  DataCatalog/synth.py
  Dlp/.repo-metadata.json
  Dlp/README.md
  Dlp/synth.py
  README.md
  RecaptchaEnterprise/.repo-metadata.json
  RecaptchaEnterprise/README.md
  RecaptchaEnterprise/synth.py
  SecurityCenter/README.md
  SecurityCenter/synth.py
  WebRisk/.repo-metadata.json
  WebRisk/README.md
  WebRisk/synth.py
Labels: cla: yes

#3349 feat: regenerate with protoc v3.13.0
  TextToSpeech/src/V1/SynthesisInput.php
  TextToSpeech/src/V1/SynthesizeSpeechRequest.php
  TextToSpeech/synth.metadata
Labels: cla: yes, context: full

#3330 feat: regenerate with protoc v3.13.0
  VideoIntelligence/src/V1/AnnotateVideoRequest.php
  VideoIntelligence/src/V1/DetectedLandmark.php
  VideoIntelligence/src/V1/ExplicitContentFrame.php
  VideoIntelligence/src/V1/FaceFrame.php
  VideoIntelligence/src/V1/FaceSegment.php
  VideoIntelligence/src/V1/LabelAnnotation.php
  VideoIntelligence/src/V1/LabelFrame.php
  VideoIntelligence/src/V1/LabelSegment.php
  VideoIntelligence/src/V1/LogoRecognitionAnnotation.php
  VideoIntelligence/src/V1/ObjectTrackingAnnotation.php
  VideoIntelligence/src/V1/ObjectTrackingFrame.php
  VideoIntelligence/src/V1/TextFrame.php
  VideoIntelligence/src/V1/TextSegment.php
  VideoIntelligence/src/V1/TimestampedObject.php
  VideoIntelligence/src/V1/Track.php
  VideoIntelligence/src/V1/VideoAnnotationProgress.php
  VideoIntelligence/src/V1/VideoAnnotationResults.php
  VideoIntelligence/src/V1/VideoContext.php
  VideoIntelligence/src/V1/VideoSegment.php
  VideoIntelligence/src/V1/WordInfo.php
  VideoIntelligence/src/V1beta2/AnnotateVideoRequest.php
  VideoIntelligence/src/V1beta2/ExplicitContentFrame.php
  VideoIntelligence/src/V1beta2/FaceFrame.php
  VideoIntelligence/src/V1beta2/FaceSegment.php
  VideoIntelligence/src/V1beta2/LabelAnnotation.php
  VideoIntelligence/src/V1beta2/LabelFrame.php
  VideoIntelligence/src/V1beta2/LabelSegment.php
  VideoIntelligence/src/V1beta2/VideoAnnotationProgress.php
  VideoIntelligence/src/V1beta2/VideoAnnotationResults.php
  VideoIntelligence/src/V1beta2/VideoContext.php
  VideoIntelligence/src/V1beta2/VideoSegment.php
  VideoIntelligence/synth.metadata
Labels: cla: yes, context: full

#3343 feat: regenerate with protoc v3.13.0
  SecurityCenter/src/V1/Asset.php
  SecurityCenter/src/V1/CreateFindingRequest.php
  SecurityCenter/src/V1/CreateNotificationConfigRequest.php
  SecurityCenter/src/V1/CreateSourceRequest.php
  SecurityCenter/src/V1/Finding.php
  SecurityCenter/src/V1/GroupAssetsRequest.php
  SecurityCenter/src/V1/GroupAssetsResponse.php
  SecurityCenter/src/V1/GroupFindingsRequest.php
  SecurityCenter/src/V1/GroupFindingsResponse.php
  SecurityCenter/src/V1/ListAssetsRequest.php
  SecurityCenter/src/V1/ListAssetsResponse.php
  SecurityCenter/src/V1/ListAssetsResponse/ListAssetsResult.php
  SecurityCenter/src/V1/ListFindingsRequest.php
  SecurityCenter/src/V1/ListFindingsResponse.php
  SecurityCenter/src/V1/ListFindingsResponse/ListFindingsResult.php
  SecurityCenter/src/V1/NotificationConfig.php
  SecurityCenter/src/V1/NotificationMessage.php
  SecurityCenter/src/V1/OrganizationSettings.php
  SecurityCenter/src/V1/OrganizationSettings/AssetDiscoveryConfig.php
  SecurityCenter/src/V1/RunAssetDiscoveryResponse.php
  SecurityCenter/src/V1/SetFindingStateRequest.php
  SecurityCenter/src/V1/UpdateFindingRequest.php
  SecurityCenter/src/V1/UpdateNotificationConfigRequest.php
  SecurityCenter/src/V1/UpdateOrganizationSettingsRequest.php
  SecurityCenter/src/V1/UpdateSecurityMarksRequest.php
  SecurityCenter/src/V1/UpdateSourceRequest.php
  SecurityCenter/src/V1p1beta1/Asset.php
  SecurityCenter/src/V1p1beta1/CreateFindingRequest.php
  SecurityCenter/src/V1p1beta1/CreateNotificationConfigRequest.php
  SecurityCenter/src/V1p1beta1/CreateSourceRequest.php
  SecurityCenter/src/V1p1beta1/Finding.php
  SecurityCenter/src/V1p1beta1/GroupAssetsRequest.php
  SecurityCenter/src/V1p1beta1/GroupAssetsResponse.php
  SecurityCenter/src/V1p1beta1/GroupFindingsRequest.php
  SecurityCenter/src/V1p1beta1/GroupFindingsResponse.php
  SecurityCenter/src/V1p1beta1/ListAssetsRequest.php
  SecurityCenter/src/V1p1beta1/ListAssetsResponse.php
  SecurityCenter/src/V1p1beta1/ListAssetsResponse/ListAssetsResult.php
  SecurityCenter/src/V1p1beta1/ListFindingsRequest.php
  SecurityCenter/src/V1p1beta1/ListFindingsResponse.php
  SecurityCenter/src/V1p1beta1/ListFindingsResponse/ListFindingsResult.php
  SecurityCenter/src/V1p1beta1/NotificationConfig.php
  SecurityCenter/src/V1p1beta1/NotificationMessage.php
  SecurityCenter/src/V1p1beta1/OrganizationSettings.php
  SecurityCenter/src/V1p1beta1/OrganizationSettings/AssetDiscoveryConfig.php
  SecurityCenter/src/V1p1beta1/RunAssetDiscoveryResponse.php
  SecurityCenter/src/V1p1beta1/SetFindingStateRequest.php
  SecurityCenter/src/V1p1beta1/UpdateFindingRequest.php
  SecurityCenter/src/V1p1beta1/UpdateNotificationConfigRequest.php
  SecurityCenter/src/V1p1beta1/UpdateOrganizationSettingsRequest.php
  SecurityCenter/src/V1p1beta1/UpdateSecurityMarksRequest.php
  SecurityCenter/src/V1p1beta1/UpdateSourceRequest.php
  SecurityCenter/synth.metadata
Labels: cla: yes, context: full

#3311 feat: regenerate with protoc v3.13.0
  Debugger/src/V2/Breakpoint.php
  Debugger/src/V2/Debuggee.php
  Debugger/src/V2/GetBreakpointResponse.php
  Debugger/src/V2/ListBreakpointsRequest.php
  Debugger/src/V2/ListBreakpointsRequest/BreakpointActionValue.php
  Debugger/src/V2/RegisterDebuggeeRequest.php
  Debugger/src/V2/RegisterDebuggeeResponse.php
  Debugger/src/V2/SetBreakpointRequest.php
  Debugger/src/V2/SetBreakpointResponse.php
  Debugger/src/V2/StackFrame.php
  Debugger/src/V2/StatusMessage.php
  Debugger/src/V2/UpdateActiveBreakpointRequest.php
  Debugger/src/V2/Variable.php
  Debugger/synth.metadata
Labels: cla: yes, context: full

#3304 feat: regenerate with protoc v3.13.0
  BigQueryStorage/src/V1/CreateReadSessionRequest.php
  BigQueryStorage/src/V1/ReadRowsResponse.php
  BigQueryStorage/src/V1/ReadSession.php
  BigQueryStorage/src/V1/ReadSession/TableModifiers.php
  BigQueryStorage/src/V1/SplitReadStreamResponse.php
  BigQueryStorage/src/V1/StreamStats.php
  BigQueryStorage/synth.metadata
Labels: cla: yes, context: full

#3400 chore: remove experimental tag
  BigQueryStorage/src/V1/BigQueryReadClient.php
  BigQueryStorage/src/V1/Gapic/BigQueryReadGapicClient.php
  BigQueryStorage/synth.metadata
Labels: cla: yes, context: none

#3406 chore: remove experimental tag
  RecaptchaEnterprise/src/V1/Gapic/RecaptchaEnterpriseServiceGapicClient.php
  RecaptchaEnterprise/src/V1/RecaptchaEnterpriseServiceClient.php
  RecaptchaEnterprise/synth.metadata
Labels: cla: yes, context: none

#3409 chore: remove experimental tags
  WebRisk/src/V1/Gapic/WebRiskServiceGapicClient.php
  WebRisk/src/V1/WebRiskServiceClient.php
  WebRisk/synth.metadata
Labels: cla: yes, context: none

#3408 chore: remove experimental tags
  SecurityCenter/src/V1/Gapic/SecurityCenterGapicClient.php
  SecurityCenter/src/V1/SecurityCenterClient.php
  SecurityCenter/synth.metadata
Labels: cla: yes, context: none

#3403 docs: update documentation surrounding parent resource names
  Dlp/src/V2/BigQueryOptions/SampleMethod.php
  Dlp/src/V2/CreateDeidentifyTemplateRequest.php
  Dlp/src/V2/CreateDlpJobRequest.php
  Dlp/src/V2/CreateInspectTemplateRequest.php
  Dlp/src/V2/CreateJobTriggerRequest.php
  Dlp/src/V2/CreateStoredInfoTypeRequest.php
  Dlp/src/V2/CryptoReplaceFfxFpeConfig.php
  Dlp/src/V2/DeidentifyContentRequest.php
  Dlp/src/V2/DlpServiceClient.php
  Dlp/src/V2/Gapic/DlpServiceGapicClient.php
  Dlp/src/V2/InfoType.php
  Dlp/src/V2/InspectContentRequest.php
  Dlp/src/V2/ListDeidentifyTemplatesRequest.php
  Dlp/src/V2/ListDlpJobsRequest.php
  Dlp/src/V2/ListInfoTypesRequest.php
  Dlp/src/V2/ListInspectTemplatesRequest.php
  Dlp/src/V2/ListJobTriggersRequest.php
  Dlp/src/V2/ListStoredInfoTypesRequest.php
  Dlp/src/V2/RedactImageRequest.php
  Dlp/src/V2/ReidentifyContentRequest.php
  Dlp/synth.metadata
Labels: cla: yes, context: partial

#3413 fix: fix expiration time key in CacheSessionPool#maintain()
  Spanner/src/Session/CacheSessionPool.php
  Spanner/tests/Unit/Session/CacheSessionPoolTest.php
Labels: cla: yes

#3334 feat: add support for setting/detecting a quota project
  BigQuery/src/BigQueryClient.php
  Core/src/RequestWrapper.php
  Core/src/RequestWrapperTrait.php
  Core/tests/Unit/RequestWrapperTest.php
  Datastore/src/DatastoreClient.php
  Firestore/src/FirestoreClient.php
  Logging/src/LoggingClient.php
  PubSub/src/PubSubClient.php
  Spanner/src/SpannerClient.php
  Speech/src/SpeechClient.php
  Storage/src/StorageClient.php
  Trace/src/TraceClient.php
  Translate/src/V2/TranslateClient.php
  Vision/src/VisionClient.php
Labels: cla: yes

#3415 fix: add LRO bindings for rest configuration
  Translate/src/V3/resources/translation_service_rest_client_config.php
Labels: api: translate, cla: yes

#3417 chore: update google/cloud-core dependency version
  Asset/composer.json
  AutoMl/composer.json
  BigQuery/composer.json
  BigQueryConnection/composer.json
  BigQueryDataTransfer/composer.json
  BigQueryReservation/composer.json
  BigQueryStorage/composer.json
  Bigtable/composer.json
  Billing/composer.json
  Container/composer.json
  DataCatalog/composer.json
  Dataproc/composer.json
  Datastore/composer.json
  Debugger/composer.json
  Dialogflow/composer.json
  Dlp/composer.json
  ErrorReporting/composer.json
  Firestore/composer.json
  Gaming/composer.json
  Iot/composer.json
  Kms/composer.json
  Language/composer.json
  Logging/composer.json
  Memcache/composer.json
  Monitoring/composer.json
  OsLogin/composer.json
  PubSub/composer.json
  RecaptchaEnterprise/composer.json
  RecommendationEngine/composer.json
  Recommender/composer.json
  Redis/composer.json
  Scheduler/composer.json
  SecretManager/composer.json
  SecurityCenter/composer.json
  ServiceDirectory/composer.json
  Spanner/composer.json
  Speech/composer.json
  Storage/composer.json
  Talent/composer.json
  Tasks/composer.json
  TextToSpeech/composer.json
  Trace/composer.json
  Translate/composer.json
  VideoIntelligence/composer.json
  Vision/composer.json
  WebRisk/composer.json
  WebSecurityScanner/composer.json
Labels: cla: yes

#3424 docs: wording updates for tiers
  Dialogflow/src/V2/OriginalDetectIntentRequest.php
  Dialogflow/synth.metadata
Labels: cla: yes, context: full

#3061 feat(spanner): add support for NUMERIC type
  Spanner/composer.json
  Spanner/src/Database.php
  Spanner/src/Numeric.php
  Spanner/src/SpannerClient.php
  Spanner/src/ValueMapper.php
  Spanner/tests/Snippet/NumericTest.php
  Spanner/tests/Snippet/SpannerClientTest.php
  Spanner/tests/System/QueryTest.php
  Spanner/tests/System/WriteTest.php
  Spanner/tests/Unit/NumericTest.php
  Spanner/tests/Unit/SpannerClientTest.php
  Spanner/tests/Unit/ValueMapperTest.php
Labels: api: spanner, cla: yes

#3430 docs: correct the links for parent fields
  Dlp/src/V2/CreateDeidentifyTemplateRequest.php
  Dlp/src/V2/CreateDlpJobRequest.php
  Dlp/src/V2/CreateInspectTemplateRequest.php
  Dlp/src/V2/CreateJobTriggerRequest.php
  Dlp/src/V2/CreateStoredInfoTypeRequest.php
  Dlp/src/V2/DeidentifyContentRequest.php
  Dlp/src/V2/Gapic/DlpServiceGapicClient.php
  Dlp/src/V2/InspectContentRequest.php
  Dlp/src/V2/ListDlpJobsRequest.php
  Dlp/src/V2/ListJobTriggersRequest.php
  Dlp/src/V2/RedactImageRequest.php
  Dlp/src/V2/ReidentifyContentRequest.php
  Dlp/synth.metadata
Labels: cla: yes, context: full

#3404 feat: add new query operators
  Firestore/metadata/V1/Query.php
  Firestore/src/Admin/V1/CreateIndexRequest.php
  Firestore/src/Admin/V1/ExportDocumentsMetadata.php
  Firestore/src/Admin/V1/Field.php
  Firestore/src/Admin/V1/FieldOperationMetadata.php
  Firestore/src/Admin/V1/FieldOperationMetadata/IndexConfigDelta.php
  Firestore/src/Admin/V1/FirestoreAdminGrpcClient.php
  Firestore/src/Admin/V1/ImportDocumentsMetadata.php
  Firestore/src/Admin/V1/Index.php
  Firestore/src/Admin/V1/Index/IndexField.php
  Firestore/src/Admin/V1/IndexOperationMetadata.php
  Firestore/src/Admin/V1/UpdateFieldRequest.php
  Firestore/src/V1/BatchGetDocumentsRequest.php
  Firestore/src/V1/BatchGetDocumentsResponse.php
  Firestore/src/V1/BeginTransactionRequest.php
  Firestore/src/V1/CommitResponse.php
  Firestore/src/V1/CreateDocumentRequest.php
  Firestore/src/V1/DeleteDocumentRequest.php
  Firestore/src/V1/Document.php
  Firestore/src/V1/DocumentChange.php
  Firestore/src/V1/DocumentDelete.php
  Firestore/src/V1/DocumentRemove.php
  Firestore/src/V1/DocumentTransform/FieldTransform.php
  Firestore/src/V1/FirestoreGrpcClient.php
  Firestore/src/V1/Gapic/FirestoreGapicClient.php
  Firestore/src/V1/GetDocumentRequest.php
  Firestore/src/V1/ListDocumentsRequest.php
  Firestore/src/V1/ListenRequest.php
  Firestore/src/V1/ListenResponse.php
  Firestore/src/V1/PartitionQueryRequest.php
  Firestore/src/V1/PartitionQueryResponse.php
  Firestore/src/V1/Precondition.php
  Firestore/src/V1/RunQueryRequest.php
  Firestore/src/V1/RunQueryResponse.php
  Firestore/src/V1/StructuredQuery.php
  Firestore/src/V1/StructuredQuery/CompositeFilter.php
  Firestore/src/V1/StructuredQuery/FieldFilter.php
  Firestore/src/V1/StructuredQuery/FieldFilter/Operator.php
  Firestore/src/V1/StructuredQuery/Filter.php
  Firestore/src/V1/StructuredQuery/Order.php
  Firestore/src/V1/StructuredQuery/UnaryFilter.php
  Firestore/src/V1/StructuredQuery/UnaryFilter/Operator.php
  Firestore/src/V1/Target.php
  Firestore/src/V1/Target/QueryTarget.php
  Firestore/src/V1/TargetChange.php
  Firestore/src/V1/TransactionOptions.php
  Firestore/src/V1/TransactionOptions/ReadOnly.php
  Firestore/src/V1/UpdateDocumentRequest.php
  Firestore/src/V1/Value.php
  Firestore/src/V1/Write.php
  Firestore/src/V1/WriteResponse.php
  Firestore/src/V1/WriteResult.php
  Firestore/synth.metadata
Labels: cla: yes, context: full

#3346 feat: add emulator support
  Bigtable/src/Admin/V2/BigtableInstanceAdminClient.php
  Bigtable/src/Admin/V2/BigtableTableAdminClient.php
  Bigtable/src/EmulatorSupportTrait.php
  Bigtable/src/V2/BigtableClient.php
Labels: api: bigtable, cla: yes

#3427 chore: update CODEOWNERS for bigtable
  .github/CODEOWNERS
Labels: cla: yes

#3432 feat: regenerate with protoc v3.13.0
  Gaming/src/V1/CreateGameServerClusterRequest.php
  Gaming/src/V1/CreateGameServerConfigRequest.php
  Gaming/src/V1/CreateGameServerDeploymentRequest.php
  Gaming/src/V1/CreateRealmRequest.php
  Gaming/src/V1/DeployedFleetDetails.php
  Gaming/src/V1/DeployedFleetDetails/DeployedFleet.php
  Gaming/src/V1/DeployedFleetDetails/DeployedFleetAutoscaler.php
  Gaming/src/V1/GameServerCluster.php
  Gaming/src/V1/GameServerClusterConnectionInfo.php
  Gaming/src/V1/GameServerConfig.php
  Gaming/src/V1/GameServerConfigOverride.php
  Gaming/src/V1/GameServerDeployment.php
  Gaming/src/V1/GameServerDeploymentRollout.php
  Gaming/src/V1/OperationMetadata.php
  Gaming/src/V1/OperationStatus.php
  Gaming/src/V1/PreviewCreateGameServerClusterRequest.php
  Gaming/src/V1/PreviewCreateGameServerClusterResponse.php
  Gaming/src/V1/PreviewDeleteGameServerClusterRequest.php
  Gaming/src/V1/PreviewDeleteGameServerClusterResponse.php
  Gaming/src/V1/PreviewGameServerDeploymentRolloutRequest.php
  Gaming/src/V1/PreviewGameServerDeploymentRolloutResponse.php
  Gaming/src/V1/PreviewRealmUpdateRequest.php
  Gaming/src/V1/PreviewRealmUpdateResponse.php
  Gaming/src/V1/PreviewUpdateGameServerClusterRequest.php
  Gaming/src/V1/PreviewUpdateGameServerClusterResponse.php
  Gaming/src/V1/Realm.php
  Gaming/src/V1/Schedule.php
  Gaming/src/V1/TargetDetails/TargetFleetDetails.php
  Gaming/src/V1/TargetDetails/TargetFleetDetails/TargetFleet.php
  Gaming/src/V1/TargetDetails/TargetFleetDetails/TargetFleetAutoscaler.php
  Gaming/src/V1/UpdateGameServerClusterRequest.php
  Gaming/src/V1/UpdateGameServerDeploymentRequest.php
  Gaming/src/V1/UpdateGameServerDeploymentRolloutRequest.php
  Gaming/src/V1/UpdateRealmRequest.php
  Gaming/synth.metadata
Labels: cla: yes, context: none

#3433 chore: fix doc generation
  .github/workflows/docs.yml
Labels: cla: yes

#3426 chore: update CODEOWNERS file
  .github/CODEOWNERS
Labels: cla: yes

#3440 chore: add LICENSE to firestore
  Firestore/LICENSE
Labels: cla: yes

#3437 docs: updated description of finding severity field
  SecurityCenter/metadata/V1P1Beta1/SecuritycenterService.php
  SecurityCenter/src/V1p1beta1/CreateNotificationConfigRequest.php
  SecurityCenter/src/V1p1beta1/Finding.php
  SecurityCenter/src/V1p1beta1/Finding/Severity.php
  SecurityCenter/src/V1p1beta1/Gapic/SecurityCenterGapicClient.php
  SecurityCenter/src/V1p1beta1/GroupFindingsRequest.php
  SecurityCenter/src/V1p1beta1/ListFindingsRequest.php
  SecurityCenter/synth.metadata
Labels: cla: yes, context: full

#3340 feat: add model extract and move job methods to client
  BigQuery/src/BigQueryClient.php
  BigQuery/src/Connection/ServiceDefinition/bigquery-v2.json
  BigQuery/src/Dataset.php
  BigQuery/src/ExtractJobConfiguration.php
  BigQuery/src/Model.php
  BigQuery/src/Table.php
  BigQuery/tests/Snippet/BigQueryClientTest.php
  BigQuery/tests/Snippet/ExtractJobConfigurationTest.php
  BigQuery/tests/Snippet/ModelTest.php
  BigQuery/tests/System/ManageModelsTest.php
  BigQuery/tests/System/ManageTablesTest.php
  BigQuery/tests/Unit/BigQueryClientTest.php
  BigQuery/tests/Unit/ExtractJobConfigurationTest.php
  BigQuery/tests/Unit/ModelTest.php
  BigQuery/tests/Unit/TableTest.php
Labels: api: bigquery, cla: yes

#3441 feat: update pubsub service definition
  PubSub/src/Connection/ServiceDefinition/pubsub-v1.json
  PubSub/tests/System/ManageSubscriptionsTest.php
Labels: api: pubsub, cla: yes

#3442 chore: release 0.140.0
  AutoMl/VERSION
  BigQuery/VERSION
  BigQuery/src/BigQueryClient.php
  Bigtable/VERSION
  Bigtable/src/BigtableClient.php
  CHANGELOG.md
  Dialogflow/VERSION
  Dlp/VERSION
  Firestore/VERSION
  Firestore/src/FirestoreClient.php
  Gaming/VERSION
  PubSub/VERSION
  PubSub/src/PubSubClient.php
  SecurityCenter/VERSION
  Spanner/VERSION
  Spanner/src/SpannerClient.php
  composer.json
  docs/manifest.json
  src/ServiceBuilder.php
  src/Version.php
Labels: autorelease: pending, cla: yes

#3269 feat: add parent() method for CollectionReference
  Firestore/src/CollectionReference.php
  Firestore/src/Query.php
  Firestore/tests/Snippet/CollectionReferenceTest.php
  Firestore/tests/Unit/CollectionReferenceTest.php
Labels: cla: yes

#3443 chore: deploy full docs folder
  .github/workflows/docs.yml
Labels: cla: yes

#3435 fix: adds quota project doc to language, debugger and bigtable
  Bigtable/src/BigtableClient.php
  Debugger/src/DebuggerClient.php
  Language/src/LanguageClient.php
Labels: cla: yes

#3448 feat: add support for query limit-to-last
  Firestore/src/Query.php
  Firestore/tests/Snippet/QueryTest.php
  Firestore/tests/System/QueryTest.php
  Firestore/tests/Unit/QueryTest.php
Labels: api: firestore, cla: yes

#3398 feat: bigquery destination, output result, v1beta1 formatting
  Asset/metadata/V1/AssetService.php
  Asset/metadata/V1/Assets.php
  Asset/src/V1/AssetServiceGrpcClient.php
  Asset/src/V1/BigQueryDestination.php
  Asset/src/V1/ContentType.php
  Asset/src/V1/CreateFeedRequest.php
  Asset/src/V1/ExportAssetsRequest.php
  Asset/src/V1/ExportAssetsResponse.php
  Asset/src/V1/Feed.php
  Asset/src/V1/Gapic/AssetServiceGapicClient.php
  Asset/src/V1/GcsOutputResult.php
  Asset/src/V1/IamPolicySearchResult.php
  Asset/src/V1/IamPolicySearchResult/Explanation.php
  Asset/src/V1/OutputResult.php
  Asset/src/V1/PartitionSpec.php
  Asset/src/V1/PartitionSpec/PartitionKey.php
  Asset/src/V1/PartitionSpec_PartitionKey.php
  Asset/src/V1/ResourceSearchResult.php
  Asset/src/V1/SearchAllIamPoliciesRequest.php
  Asset/src/V1/SearchAllResourcesRequest.php
  Asset/src/V1/UpdateFeedRequest.php
  Asset/src/V1/resources/asset_service_client_config.json
  Asset/src/V1/resources/asset_service_rest_client_config.php
  Asset/src/V1beta1/AssetServiceGrpcClient.php
  Asset/src/V1beta1/Gapic/AssetServiceGapicClient.php
  Asset/synth.metadata
  Asset/synth.py
  Asset/tests/Unit/V1/AssetServiceClientTest.php
Labels: cla: yes, context: partial
