Repository googleapis/google-cloud-php, pull requests merged in 2021-05, with the labels that each got.

#4019 fix: datastore admin autoloader
  DatastoreAdmin/composer.json
Labels: cla: yes

#4032 chore: add readme
  Compute/src/V1/README.md
Labels: cla: yes

#4031 chore: update list sample
  Compute/README.md
Labels: cla: yes, samples

#4037 feat: add ZSTD compression as an option for Arrow
  BigQueryStorage/metadata/V1/Arrow.php
  BigQueryStorage/src/V1/ArrowSerializationOptions/CompressionCodec.php
  BigQueryStorage/src/V1/ReadSession.php
  BigQueryStorage/src/V1/ReadSession/TableReadOptions.php
  BigQueryStorage/synth.metadata
Labels: cla: yes, context: full

#3962 chore: make google/cloud-compute 7.0+ only
  .kokoro/continuous/run-tests.sh
  .kokoro/presubmit/run-tests.sh
  Compute/composer.json
  dev/src/DocGenerator/Command/Docs.php
  phpunit-php5-system.xml.dist
  phpunit-php5.xml.dist
Labels: automerge, cla: yes

#3974 tests: add more system tests for GCE
  Compute/tests/System/V1/AddressTest.php
  Compute/tests/System/V1/PaginationTest.php
  Compute/tests/System/V1/SmokeTest.php
Labels: cla: yes, kokoro:run

#4047 chore(tests): simplifies compute system test logic
  Compute/tests/System/V1/AddressTest.php
  Compute/tests/System/V1/SmokeTest.php
Labels: cla: yes

#4050 chore: fix unit test failure on windows
  .kokoro/presubmit/windows/test.bat
  Core/src/ClientTrait.php
  Core/tests/Unit/ClientTraitTest.php
Labels: cla: yes
