Repository googleapis/google-cloud-php, pull requests merged in 2021-06, with the labels that each got.

#4043 chore: add cicd team to codeowners
  .github/CODEOWNERS
  Container/.repo-metadata.json
Labels: cla: yes

#4029 chore: migrate devtools/trace to the PHP microgenerator
  Trace/src/V2/Gapic/TraceServiceGapicClient.php
  Trace/src/V2/TraceServiceClient.php
  Trace/src/V2/gapic_metadata.json
  Trace/src/V2/resources/trace_service_client_config.json
  Trace/src/V2/resources/trace_service_descriptor_config.php
  Trace/src/V2/resources/trace_service_rest_client_config.php
  Trace/synth.metadata
  Trace/synth.py
  Trace/tests/Unit/V2/TraceServiceClientTest.php
Labels: cla: yes, context: full

#4027 chore: migrate bigquery/connection to the PHP microgenerator
  BigQueryConnection/src/V1/ConnectionServiceClient.php
  BigQueryConnection/src/V1/Gapic/ConnectionServiceGapicClient.php
  BigQueryConnection/src/V1/gapic_metadata.json
  BigQueryConnection/src/V1/resources/connection_service_client_config.json
  BigQueryConnection/src/V1/resources/connection_service_rest_client_config.php
  BigQueryConnection/synth.metadata
  BigQueryConnection/synth.py
  BigQueryConnection/tests/Unit/V1/ConnectionServiceClientTest.php
Labels: cla: yes, context: full

#4022 chore: migrate dlp to the PHP microgenerator
  Dlp/src/V2/DlpServiceClient.php
  Dlp/src/V2/Gapic/DlpServiceGapicClient.php
  Dlp/src/V2/gapic_metadata.json
  Dlp/src/V2/resources/dlp_service_client_config.json
  Dlp/src/V2/resources/dlp_service_descriptor_config.php
  Dlp/src/V2/resources/dlp_service_rest_client_config.php
  Dlp/synth.metadata
  Dlp/synth.py
  Dlp/tests/Unit/V2/DlpServiceClientTest.php
Labels: cla: yes, context: full

#4026 [Bigtable] docs: update the comments in Cloud Bigtable RestoreTable API to reflect the new API capability
  Bigtable/src/Admin/V2/BigtableTableAdminGrpcClient.php
  Bigtable/src/Admin/V2/Gapic/BigtableTableAdminGapicClient.php
  Bigtable/src/Admin/V2/RestoreTableRequest.php
  Bigtable/synth.metadata
Labels: cla: yes, context: full

#4006 chore: migrate vision to the PHP microgenerator
  Vision/src/V1/Gapic/ImageAnnotatorGapicClient.php
  Vision/src/V1/Gapic/ProductSearchGapicClient.php
  Vision/src/V1/resources/image_annotator_client_config.json
  Vision/src/V1/resources/image_annotator_descriptor_config.php
  Vision/src/V1/resources/image_annotator_rest_client_config.php
  Vision/src/V1/resources/product_search_client_config.json
  Vision/src/V1/resources/product_search_descriptor_config.php
  Vision/src/V1/resources/product_search_rest_client_config.php
  Vision/synth.metadata
  Vision/synth.py
  Vision/tests/Unit/V1/ImageAnnotatorClientTest.php
  Vision/tests/Unit/V1/ProductSearchClientTest.php
Labels: cla: yes, context: full

#4020 [DatastoreAdmin] chore: Update to the latest gapic-generator-2.11.0 and gax-java-1.63.3
  DatastoreAdmin/src/V1/resources/datastore_admin_rest_client_config.php
  DatastoreAdmin/synth.metadata
Labels: cla: yes, context: full

#4061 chore: migrate datastore/admin to the PHP microgenerator
  DatastoreAdmin/src/V1/DatastoreAdminClient.php
  DatastoreAdmin/src/V1/Gapic/DatastoreAdminGapicClient.php
  DatastoreAdmin/src/V1/gapic_metadata.json
  DatastoreAdmin/src/V1/resources/datastore_admin_client_config.json
  DatastoreAdmin/src/V1/resources/datastore_admin_descriptor_config.php
  DatastoreAdmin/src/V1/resources/datastore_admin_rest_client_config.php
  DatastoreAdmin/synth.metadata
  DatastoreAdmin/synth.py
  DatastoreAdmin/tests/Unit/V1/DatastoreAdminClientTest.php
Labels: cla: yes, context: full

#4044 chore: migrate bigquery/storage to the PHP microgenerator
  BigQueryStorage/src/V1/BigQueryReadClient.php
  BigQueryStorage/src/V1/Gapic/BigQueryReadGapicClient.php
  BigQueryStorage/src/V1/gapic_metadata.json
  BigQueryStorage/src/V1/resources/big_query_read_client_config.json
  BigQueryStorage/synth.metadata
  BigQueryStorage/synth.py
  BigQueryStorage/tests/Unit/V1/BigQueryReadClientTest.php
Labels: cla: yes, context: full

#4021 chore: update to the latest gapic-generator-2.11.0 and gax-java-1.63.3 & use microgenerator
  Debugger/src/V2/Controller2Client.php
  Debugger/src/V2/Debugger2Client.php
  Debugger/src/V2/Gapic/Controller2GapicClient.php
  Debugger/src/V2/Gapic/Debugger2GapicClient.php
  Debugger/src/V2/gapic_metadata.json
  Debugger/src/V2/resources/controller2_client_config.json
  Debugger/src/V2/resources/controller2_descriptor_config.php
  Debugger/src/V2/resources/controller2_rest_client_config.php
  Debugger/src/V2/resources/debugger2_client_config.json
  Debugger/src/V2/resources/debugger2_descriptor_config.php
  Debugger/src/V2/resources/debugger2_rest_client_config.php
  Debugger/synth.metadata
  Debugger/synth.py
  Debugger/tests/Unit/V2/Controller2ClientTest.php
  Debugger/tests/Unit/V2/Debugger2ClientTest.php
Labels: cla: yes, context: full

#3977 chore: migrate billing/v1 to the PHP microgenerator
  Billing/src/V1/CloudBillingClient.php
  Billing/src/V1/CloudBillingGrpcClient.php
  Billing/src/V1/CloudCatalogClient.php
  Billing/src/V1/CloudCatalogGrpcClient.php
  Billing/src/V1/Gapic/CloudBillingGapicClient.php
  Billing/src/V1/Gapic/CloudCatalogGapicClient.php
  Billing/src/V1/gapic_metadata.json
  Billing/src/V1/resources/cloud_billing_client_config.json
  Billing/src/V1/resources/cloud_billing_rest_client_config.php
  Billing/src/V1/resources/cloud_catalog_client_config.json
  Billing/synth.metadata
  Billing/synth.py
  Billing/tests/Unit/V1/CloudBillingClientTest.php
  Billing/tests/Unit/V1/CloudCatalogClientTest.php
Labels: cla: yes, context: full

#3973 chore: migrate webrisk/{v1,v1beta} to the PHP microgenerator
  WebRisk/src/V1/Gapic/WebRiskServiceGapicClient.php
  WebRisk/src/V1/WebRiskServiceClient.php
  WebRisk/src/V1/gapic_metadata.json
  WebRisk/src/V1/resources/web_risk_service_client_config.json
  WebRisk/src/V1/resources/web_risk_service_descriptor_config.php
  WebRisk/src/V1/resources/web_risk_service_rest_client_config.php
  WebRisk/src/V1beta1/Gapic/WebRiskServiceV1Beta1GapicClient.php
  WebRisk/src/V1beta1/WebRiskServiceV1Beta1Client.php
  WebRisk/src/V1beta1/gapic_metadata.json
  WebRisk/src/V1beta1/resources/web_risk_service_v1_beta1_client_config.json
  WebRisk/src/V1beta1/resources/web_risk_service_v1_beta1_descriptor_config.php
  WebRisk/src/V1beta1/resources/web_risk_service_v1_beta1_rest_client_config.php
  WebRisk/synth.metadata
  WebRisk/synth.py
  WebRisk/tests/Unit/V1/WebRiskServiceClientTest.php
  WebRisk/tests/Unit/V1beta1/WebRiskServiceV1Beta1ClientTest.php
Labels: cla: yes, context: full

#3939 [Firestore] fix: retry RESOURCE_EXHAUSTED errors docs: various documentation improvements
  Firestore/src/V1/DocumentTransform/FieldTransform/ServerValue.php
  Firestore/synth.metadata
Labels: cla: yes, context: full

#3935 [RecommendationEngine] docs: place paths in code spans
  RecommendationEngine/src/V1beta1/Gapic/CatalogServiceGapicClient.php
  RecommendationEngine/src/V1beta1/Gapic/PredictionApiKeyRegistryGapicClient.php
  RecommendationEngine/src/V1beta1/Gapic/PredictionServiceGapicClient.php
  RecommendationEngine/src/V1beta1/Gapic/UserEventServiceGapicClient.php
  RecommendationEngine/synth.metadata
Labels: cla: yes, context: full

#3971 chore: migrate servicedirectory to the PHP microgenerator
  ServiceDirectory/src/V1/Gapic/LookupServiceGapicClient.php
  ServiceDirectory/src/V1/Gapic/RegistrationServiceGapicClient.php
  ServiceDirectory/src/V1/LookupServiceClient.php
  ServiceDirectory/src/V1/RegistrationServiceClient.php
  ServiceDirectory/src/V1/gapic_metadata.json
  ServiceDirectory/src/V1/resources/lookup_service_client_config.json
  ServiceDirectory/src/V1/resources/lookup_service_descriptor_config.php
  ServiceDirectory/src/V1/resources/registration_service_client_config.json
  ServiceDirectory/src/V1/resources/registration_service_descriptor_config.php
  ServiceDirectory/src/V1/resources/registration_service_rest_client_config.php
  ServiceDirectory/src/V1beta1/Gapic/LookupServiceGapicClient.php
  ServiceDirectory/src/V1beta1/Gapic/RegistrationServiceGapicClient.php
  ServiceDirectory/src/V1beta1/LookupServiceClient.php
  ServiceDirectory/src/V1beta1/RegistrationServiceClient.php
  ServiceDirectory/src/V1beta1/gapic_metadata.json
  ServiceDirectory/src/V1beta1/resources/lookup_service_client_config.json
  ServiceDirectory/src/V1beta1/resources/lookup_service_descriptor_config.php
  ServiceDirectory/src/V1beta1/resources/registration_service_client_config.json
  ServiceDirectory/src/V1beta1/resources/registration_service_descriptor_config.php
  ServiceDirectory/src/V1beta1/resources/registration_service_rest_client_config.php
  ServiceDirectory/synth.metadata
  ServiceDirectory/synth.py
  ServiceDirectory/tests/Unit/V1/LookupServiceClientTest.php
  ServiceDirectory/tests/Unit/V1/RegistrationServiceClientTest.php
  ServiceDirectory/tests/Unit/V1beta1/LookupServiceClientTest.php
  ServiceDirectory/tests/Unit/V1beta1/RegistrationServiceClientTest.php
Labels: cla: yes, context: full

#3969 chore: migrate retail/{v2,v2alpha,v2beta} to the PHP microgenerator
  Retail/src/V2/CatalogServiceClient.php
  Retail/src/V2/Gapic/CatalogServiceGapicClient.php
  Retail/src/V2/Gapic/PredictionServiceGapicClient.php
  Retail/src/V2/Gapic/ProductServiceGapicClient.php
  Retail/src/V2/Gapic/UserEventServiceGapicClient.php
  Retail/src/V2/PredictionServiceClient.php
  Retail/src/V2/ProductServiceClient.php
  Retail/src/V2/UserEventServiceClient.php
  Retail/src/V2/gapic_metadata.json
  Retail/src/V2/resources/catalog_service_client_config.json
  Retail/src/V2/resources/prediction_service_client_config.json
  Retail/src/V2/resources/prediction_service_descriptor_config.php
  Retail/src/V2/resources/product_service_client_config.json
  Retail/src/V2/resources/product_service_rest_client_config.php
  Retail/src/V2/resources/user_event_service_client_config.json
  Retail/src/V2/resources/user_event_service_descriptor_config.php
  Retail/src/V2/resources/user_event_service_rest_client_config.php
  Retail/synth.metadata
  Retail/synth.py
  Retail/tests/Unit/V2/CatalogServiceClientTest.php
  Retail/tests/Unit/V2/PredictionServiceClientTest.php
  Retail/tests/Unit/V2/ProductServiceClientTest.php
  Retail/tests/Unit/V2/UserEventServiceClientTest.php
Labels: cla: yes, context: full

#3967 chore: migrate recaptchaenterprise/{v1,v1beta} to the PHP microgenerator
  RecaptchaEnterprise/src/V1/Gapic/RecaptchaEnterpriseServiceGapicClient.php
  RecaptchaEnterprise/src/V1/RecaptchaEnterpriseServiceClient.php
  RecaptchaEnterprise/src/V1/gapic_metadata.json
  RecaptchaEnterprise/src/V1/resources/recaptcha_enterprise_service_client_config.json
  RecaptchaEnterprise/src/V1/resources/recaptcha_enterprise_service_rest_client_config.php
  RecaptchaEnterprise/synth.metadata
  RecaptchaEnterprise/synth.py
  RecaptchaEnterprise/tests/Unit/V1/RecaptchaEnterpriseServiceClientTest.php
Labels: cla: yes, context: full

#3976 feat: add support for tagging and update DDL progress (via synth)
  Spanner/metadata/Admin/Database/V1/Backup.php
  Spanner/metadata/Admin/Database/V1/Common.php
  Spanner/metadata/Admin/Database/V1/SpannerDatabaseAdmin.php
  Spanner/metadata/Admin/Instance/V1/SpannerInstanceAdmin.php
  Spanner/metadata/V1/CommitResponse.php
  Spanner/metadata/V1/Spanner.php
  Spanner/src/Admin/Database/V1/Backup.php
  Spanner/src/Admin/Database/V1/BackupInfo.php
  Spanner/src/Admin/Database/V1/CreateBackupEncryptionConfig.php
  Spanner/src/Admin/Database/V1/CreateBackupEncryptionConfig/EncryptionType.php
  Spanner/src/Admin/Database/V1/CreateBackupMetadata.php
  Spanner/src/Admin/Database/V1/CreateBackupRequest.php
  Spanner/src/Admin/Database/V1/CreateDatabaseRequest.php
  Spanner/src/Admin/Database/V1/Database.php
  Spanner/src/Admin/Database/V1/DatabaseAdminGrpcClient.php
  Spanner/src/Admin/Database/V1/DeleteBackupRequest.php
  Spanner/src/Admin/Database/V1/DropDatabaseRequest.php
  Spanner/src/Admin/Database/V1/EncryptionInfo.php
  Spanner/src/Admin/Database/V1/Gapic/DatabaseAdminGapicClient.php
  Spanner/src/Admin/Database/V1/GetBackupRequest.php
  Spanner/src/Admin/Database/V1/GetDatabaseDdlRequest.php
  Spanner/src/Admin/Database/V1/GetDatabaseDdlResponse.php
  Spanner/src/Admin/Database/V1/GetDatabaseRequest.php
  Spanner/src/Admin/Database/V1/ListBackupOperationsRequest.php
  Spanner/src/Admin/Database/V1/ListBackupOperationsResponse.php
  Spanner/src/Admin/Database/V1/ListBackupsRequest.php
  Spanner/src/Admin/Database/V1/ListBackupsResponse.php
  Spanner/src/Admin/Database/V1/ListDatabaseOperationsRequest.php
  Spanner/src/Admin/Database/V1/ListDatabasesRequest.php
  Spanner/src/Admin/Database/V1/ListDatabasesResponse.php
  Spanner/src/Admin/Database/V1/RestoreDatabaseEncryptionConfig.php
  Spanner/src/Admin/Database/V1/RestoreDatabaseEncryptionConfig/EncryptionType.php
  Spanner/src/Admin/Database/V1/RestoreDatabaseMetadata.php
  Spanner/src/Admin/Database/V1/RestoreDatabaseRequest.php
  Spanner/src/Admin/Database/V1/UpdateBackupRequest.php
  Spanner/src/Admin/Database/V1/UpdateDatabaseDdlMetadata.php
  Spanner/src/Admin/Database/V1/UpdateDatabaseDdlRequest.php
  Spanner/src/Admin/Database/V1/resources/database_admin_client_config.json
  Spanner/src/Admin/Database/V1/resources/database_admin_descriptor_config.php
  Spanner/src/Admin/Database/V1/resources/database_admin_rest_client_config.php
  Spanner/src/Admin/Instance/V1/Gapic/InstanceAdminGapicClient.php
  Spanner/src/Admin/Instance/V1/Instance.php
  Spanner/src/Admin/Instance/V1/InstanceAdminGrpcClient.php
  Spanner/src/Admin/Instance/V1/resources/instance_admin_client_config.json
  Spanner/src/Admin/Instance/V1/resources/instance_admin_rest_client_config.php
  Spanner/src/V1/CommitResponse.php
  Spanner/src/V1/CommitResponse/CommitStats.php
  Spanner/src/V1/CommitResponse_CommitStats.php
  Spanner/src/V1/ExecuteSqlRequest/QueryOptions.php
  Spanner/src/V1/Gapic/SpannerGapicClient.php
  Spanner/src/V1/RequestOptions.php
  Spanner/src/V1/resources/spanner_client_config.json
  Spanner/src/V1/resources/spanner_descriptor_config.php
  Spanner/src/V1/resources/spanner_rest_client_config.php
  Spanner/synth.metadata
  Spanner/synth.py
  Spanner/tests/Unit/Admin/Database/V1/DatabaseAdminClientTest.php
  Spanner/tests/Unit/Admin/Instance/V1/InstanceAdminClientTest.php
  Spanner/tests/Unit/V1/SpannerClientTest.php
Labels: cla: yes, context: full

#3943 chore: migrate bigquery-reservation/{v1,v1beta1} to the PHP microgenerator
  BigQueryReservation/src/V1/Gapic/ReservationServiceGapicClient.php
  BigQueryReservation/src/V1/ReservationServiceClient.php
  BigQueryReservation/src/V1/gapic_metadata.json
  BigQueryReservation/src/V1/resources/reservation_service_client_config.json
  BigQueryReservation/src/V1/resources/reservation_service_descriptor_config.php
  BigQueryReservation/src/V1/resources/reservation_service_rest_client_config.php
  BigQueryReservation/synth.metadata
  BigQueryReservation/synth.py
  BigQueryReservation/tests/Unit/V1/ReservationServiceClientTest.php
Labels: cla: yes, context: full

#3964 chore: migrate iot to the PHP microgenerator
  Iot/src/V1/DeviceManagerClient.php
  Iot/src/V1/Gapic/DeviceManagerGapicClient.php
  Iot/src/V1/gapic_metadata.json
  Iot/src/V1/resources/device_manager_client_config.json
  Iot/src/V1/resources/device_manager_rest_client_config.php
  Iot/synth.metadata
  Iot/synth.py
  Iot/tests/Unit/V1/DeviceManagerClientTest.php
Labels: cla: yes, context: full

#3966 chore: migrate oslogin/{v1,v1beta} to the PHP microgenerator
  OsLogin/src/V1/Gapic/OsLoginServiceGapicClient.php
  OsLogin/src/V1/OsLoginServiceClient.php
  OsLogin/src/V1/gapic_metadata.json
  OsLogin/src/V1/resources/os_login_service_client_config.json
  OsLogin/src/V1/resources/os_login_service_descriptor_config.php
  OsLogin/src/V1beta/Gapic/OsLoginServiceGapicClient.php
  OsLogin/src/V1beta/OsLoginServiceClient.php
  OsLogin/src/V1beta/gapic_metadata.json
  OsLogin/src/V1beta/resources/os_login_service_client_config.json
  OsLogin/src/V1beta/resources/os_login_service_descriptor_config.php
  OsLogin/synth.metadata
  OsLogin/synth.py
  OsLogin/tests/Unit/V1/OsLoginServiceClientTest.php
  OsLogin/tests/Unit/V1beta/OsLoginServiceClientTest.php
Labels: cla: yes, context: full

#3933 feat: add `kind` field which is used to distinguish between response types feat: add `potentially_thresholded_requests_per_hour` field to `PropertyQuota`
  AnalyticsData/metadata/V1Beta/AnalyticsDataApi.php
  AnalyticsData/metadata/V1Beta/Data.php
  AnalyticsData/src/V1alpha/AlphaAnalyticsDataClient.php
  AnalyticsData/src/V1alpha/Gapic/AlphaAnalyticsDataGapicClient.php
  AnalyticsData/src/V1alpha/gapic_metadata.json
  AnalyticsData/src/V1alpha/resources/alpha_analytics_data_client_config.json
  AnalyticsData/src/V1alpha/resources/alpha_analytics_data_descriptor_config.php
  AnalyticsData/src/V1alpha/resources/alpha_analytics_data_rest_client_config.php
  AnalyticsData/src/V1beta/BatchRunPivotReportsResponse.php
  AnalyticsData/src/V1beta/BatchRunReportsResponse.php
  AnalyticsData/src/V1beta/BetaAnalyticsDataClient.php
  AnalyticsData/src/V1beta/Gapic/BetaAnalyticsDataGapicClient.php
  AnalyticsData/src/V1beta/Pivot.php
  AnalyticsData/src/V1beta/PropertyQuota.php
  AnalyticsData/src/V1beta/RunPivotReportResponse.php
  AnalyticsData/src/V1beta/RunRealtimeReportResponse.php
  AnalyticsData/src/V1beta/RunReportResponse.php
  AnalyticsData/src/V1beta/gapic_metadata.json
  AnalyticsData/src/V1beta/resources/beta_analytics_data_client_config.json
  AnalyticsData/src/V1beta/resources/beta_analytics_data_descriptor_config.php
  AnalyticsData/src/V1beta/resources/beta_analytics_data_rest_client_config.php
  AnalyticsData/synth.metadata
  AnalyticsData/synth.py
  AnalyticsData/tests/Unit/V1alpha/AlphaAnalyticsDataClientTest.php
  AnalyticsData/tests/Unit/V1beta/BetaAnalyticsDataClientTest.php
Labels: cla: yes, context: full

#3958 chore: release gapic-generator-php v0.1.0
  TextToSpeech/src/V1/Gapic/TextToSpeechGapicClient.php
  TextToSpeech/src/V1/TextToSpeechClient.php
  TextToSpeech/synth.metadata
  TextToSpeech/synth.py
  TextToSpeech/tests/Unit/V1/TextToSpeechClientTest.php
Labels: cla: yes, context: full

#4005 chore: migrate videointelligence to the PHP microgenerator
  VideoIntelligence/src/V1/Gapic/VideoIntelligenceServiceGapicClient.php
  VideoIntelligence/src/V1/VideoIntelligenceServiceClient.php
  VideoIntelligence/src/V1/gapic_metadata.json
  VideoIntelligence/src/V1/resources/video_intelligence_service_client_config.json
  VideoIntelligence/src/V1beta2/AnnotateVideoRequest.php
  VideoIntelligence/src/V1beta2/Gapic/VideoIntelligenceServiceGapicClient.php
  VideoIntelligence/src/V1beta2/VideoIntelligenceServiceClient.php
  VideoIntelligence/src/V1beta2/gapic_metadata.json
  VideoIntelligence/src/V1beta2/resources/video_intelligence_service_client_config.json
  VideoIntelligence/synth.metadata
  VideoIntelligence/synth.py
  VideoIntelligence/tests/Unit/V1/VideoIntelligenceServiceClientTest.php
  VideoIntelligence/tests/Unit/V1beta2/VideoIntelligenceServiceClientTest.php
Labels: cla: yes, context: full

#3949 chore: migrate websecurityscanner/{v1,v1beta} to the PHP microgenerator
  WebSecurityScanner/src/V1beta/Gapic/WebSecurityScannerGapicClient.php
  WebSecurityScanner/src/V1beta/WebSecurityScannerClient.php
  WebSecurityScanner/src/V1beta/gapic_metadata.json
  WebSecurityScanner/src/V1beta/resources/web_security_scanner_client_config.json
  WebSecurityScanner/src/V1beta/resources/web_security_scanner_descriptor_config.php
  WebSecurityScanner/src/V1beta/resources/web_security_scanner_rest_client_config.php
  WebSecurityScanner/synth.metadata
  WebSecurityScanner/tests/Unit/V1beta/WebSecurityScannerClientTest.php
Labels: cla: yes, context: full

#3947 feat: add etag support
  SecretManager/metadata/V1/Resources.php
  SecretManager/metadata/V1/Service.php
  SecretManager/src/V1/AccessSecretVersionRequest.php
  SecretManager/src/V1/DeleteSecretRequest.php
  SecretManager/src/V1/DestroySecretVersionRequest.php
  SecretManager/src/V1/DisableSecretVersionRequest.php
  SecretManager/src/V1/EnableSecretVersionRequest.php
  SecretManager/src/V1/Gapic/SecretManagerServiceGapicClient.php
  SecretManager/src/V1/GetSecretVersionRequest.php
  SecretManager/src/V1/Rotation.php
  SecretManager/src/V1/Secret.php
  SecretManager/src/V1/SecretManagerServiceClient.php
  SecretManager/src/V1/SecretManagerServiceGrpcClient.php
  SecretManager/src/V1/SecretVersion.php
  SecretManager/src/V1/gapic_metadata.json
  SecretManager/src/V1/resources/secret_manager_service_client_config.json
  SecretManager/src/V1/resources/secret_manager_service_descriptor_config.php
  SecretManager/src/V1/resources/secret_manager_service_rest_client_config.php
  SecretManager/src/V1beta1/Gapic/SecretManagerServiceGapicClient.php
  SecretManager/src/V1beta1/SecretManagerServiceClient.php
  SecretManager/src/V1beta1/gapic_metadata.json
  SecretManager/src/V1beta1/resources/secret_manager_service_client_config.json
  SecretManager/src/V1beta1/resources/secret_manager_service_descriptor_config.php
  SecretManager/src/V1beta1/resources/secret_manager_service_rest_client_config.php
  SecretManager/synth.metadata
  SecretManager/tests/Unit/V1/SecretManagerServiceClientTest.php
  SecretManager/tests/Unit/V1beta1/SecretManagerServiceClientTest.php
Labels: cla: yes, context: full

#3965 chore: migrate memcache/{v1,v1beta2} to the PHP microgenerator
  Memcache/src/V1/CloudMemcacheClient.php
  Memcache/src/V1/Gapic/CloudMemcacheGapicClient.php
  Memcache/src/V1/gapic_metadata.json
  Memcache/src/V1/resources/cloud_memcache_client_config.json
  Memcache/src/V1/resources/cloud_memcache_descriptor_config.php
  Memcache/src/V1/resources/cloud_memcache_rest_client_config.php
  Memcache/src/V1beta2/CloudMemcacheClient.php
  Memcache/src/V1beta2/Gapic/CloudMemcacheGapicClient.php
  Memcache/src/V1beta2/gapic_metadata.json
  Memcache/src/V1beta2/resources/cloud_memcache_client_config.json
  Memcache/src/V1beta2/resources/cloud_memcache_descriptor_config.php
  Memcache/src/V1beta2/resources/cloud_memcache_rest_client_config.php
  Memcache/synth.metadata
  Memcache/tests/Unit/V1/CloudMemcacheClientTest.php
  Memcache/tests/Unit/V1beta2/CloudMemcacheClientTest.php
Labels: cla: yes, context: full

#3944 feat: add image type support
  Container/metadata/V1/ClusterService.php
  Container/src/V1/AutoprovisioningNodePoolDefaults.php
  Container/src/V1/ClusterManagerClient.php
  Container/src/V1/ClusterManagerGrpcClient.php
  Container/src/V1/Gapic/ClusterManagerGapicClient.php
  Container/src/V1/gapic_metadata.json
  Container/src/V1/resources/cluster_manager_client_config.json
  Container/src/V1/resources/cluster_manager_rest_client_config.php
  Container/synth.metadata
  Container/tests/Unit/V1/ClusterManagerClientTest.php
Labels: cla: yes, context: full

#3945 chore: migrate language/{v1,v1beta2} to the PHP microgenerator
  Language/src/V1/Gapic/LanguageServiceGapicClient.php
  Language/src/V1/LanguageServiceClient.php
  Language/src/V1/gapic_metadata.json
  Language/src/V1/resources/language_service_client_config.json
  Language/src/V1/resources/language_service_descriptor_config.php
  Language/src/V1/resources/language_service_rest_client_config.php
  Language/src/V1beta2/Gapic/LanguageServiceGapicClient.php
  Language/src/V1beta2/LanguageServiceClient.php
  Language/src/V1beta2/gapic_metadata.json
  Language/src/V1beta2/resources/language_service_client_config.json
  Language/src/V1beta2/resources/language_service_descriptor_config.php
  Language/src/V1beta2/resources/language_service_rest_client_config.php
  Language/synth.metadata
  Language/tests/Unit/V1/LanguageServiceClientTest.php
  Language/tests/Unit/V1beta2/LanguageServiceClientTest.php
Labels: cla: yes, context: full

#3999 chore: migrate automl/{v1,v1beta1} to the PHP microgenerator
  AutoMl/src/V1/AutoMlClient.php
  AutoMl/src/V1/Gapic/AutoMlGapicClient.php
  AutoMl/src/V1/Gapic/PredictionServiceGapicClient.php
  AutoMl/src/V1/PredictionServiceClient.php
  AutoMl/src/V1/gapic_metadata.json
  AutoMl/src/V1/resources/auto_ml_client_config.json
  AutoMl/src/V1/resources/auto_ml_descriptor_config.php
  AutoMl/src/V1/resources/auto_ml_rest_client_config.php
  AutoMl/src/V1/resources/prediction_service_client_config.json
  AutoMl/src/V1/resources/prediction_service_rest_client_config.php
  AutoMl/src/V1beta1/AutoMlClient.php
  AutoMl/src/V1beta1/Gapic/AutoMlGapicClient.php
  AutoMl/src/V1beta1/Gapic/PredictionServiceGapicClient.php
  AutoMl/src/V1beta1/PredictionServiceClient.php
  AutoMl/src/V1beta1/gapic_metadata.json
  AutoMl/src/V1beta1/resources/auto_ml_client_config.json
  AutoMl/src/V1beta1/resources/auto_ml_descriptor_config.php
  AutoMl/src/V1beta1/resources/auto_ml_rest_client_config.php
  AutoMl/src/V1beta1/resources/prediction_service_client_config.json
  AutoMl/src/V1beta1/resources/prediction_service_rest_client_config.php
  AutoMl/synth.metadata
  AutoMl/synth.py
  AutoMl/tests/Unit/V1/AutoMlClientTest.php
  AutoMl/tests/Unit/V1/PredictionServiceClientTest.php
  AutoMl/tests/Unit/V1beta1/AutoMlClientTest.php
  AutoMl/tests/Unit/V1beta1/PredictionServiceClientTest.php
Labels: cla: yes, context: full

#3968 chore: migrate recommender/{v1,v1beta} to the PHP microgenerator
  Recommender/src/V1/Gapic/RecommenderGapicClient.php
  Recommender/src/V1/RecommenderClient.php
  Recommender/src/V1/gapic_metadata.json
  Recommender/src/V1/resources/recommender_client_config.json
  Recommender/src/V1/resources/recommender_rest_client_config.php
  Recommender/synth.metadata
  Recommender/tests/Unit/V1/RecommenderClientTest.php
Labels: cla: yes, context: full

#4057 feat: migrate pubsub to the PHP microgenerator
  PubSub/src/V1/Gapic/PublisherGapicClient.php
  PubSub/src/V1/Gapic/SchemaServiceGapicClient.php
  PubSub/src/V1/Gapic/SubscriberGapicClient.php
  PubSub/src/V1/PublisherClient.php
  PubSub/src/V1/SchemaServiceClient.php
  PubSub/src/V1/SubscriberClient.php
  PubSub/src/V1/gapic_metadata.json
  PubSub/src/V1/resources/publisher_client_config.json
  PubSub/src/V1/resources/publisher_descriptor_config.php
  PubSub/src/V1/resources/publisher_rest_client_config.php
  PubSub/src/V1/resources/schema_service_client_config.json
  PubSub/src/V1/resources/schema_service_rest_client_config.php
  PubSub/src/V1/resources/subscriber_client_config.json
  PubSub/src/V1/resources/subscriber_descriptor_config.php
  PubSub/src/V1/resources/subscriber_rest_client_config.php
  PubSub/synth.metadata
  PubSub/tests/Unit/V1/PublisherClientTest.php
  PubSub/tests/Unit/V1/SchemaServiceClientTest.php
  PubSub/tests/Unit/V1/SubscriberClientTest.php
Labels: cla: yes, context: full

#4073 chore: migrate recommendationengine to the PHP microgenerator
  RecommendationEngine/src/V1beta1/CatalogServiceClient.php
  RecommendationEngine/src/V1beta1/Gapic/CatalogServiceGapicClient.php
  RecommendationEngine/src/V1beta1/Gapic/PredictionApiKeyRegistryGapicClient.php
  RecommendationEngine/src/V1beta1/Gapic/PredictionServiceGapicClient.php
  RecommendationEngine/src/V1beta1/Gapic/UserEventServiceGapicClient.php
  RecommendationEngine/src/V1beta1/PredictionApiKeyRegistryClient.php
  RecommendationEngine/src/V1beta1/PredictionServiceClient.php
  RecommendationEngine/src/V1beta1/UserEventServiceClient.php
  RecommendationEngine/src/V1beta1/gapic_metadata.json
  RecommendationEngine/src/V1beta1/resources/catalog_service_client_config.json
  RecommendationEngine/src/V1beta1/resources/catalog_service_rest_client_config.php
  RecommendationEngine/src/V1beta1/resources/prediction_api_key_registry_client_config.json
  RecommendationEngine/src/V1beta1/resources/prediction_api_key_registry_rest_client_config.php
  RecommendationEngine/src/V1beta1/resources/prediction_service_client_config.json
  RecommendationEngine/src/V1beta1/resources/user_event_service_client_config.json
  RecommendationEngine/src/V1beta1/resources/user_event_service_descriptor_config.php
  RecommendationEngine/src/V1beta1/resources/user_event_service_rest_client_config.php
  RecommendationEngine/synth.metadata
  RecommendationEngine/tests/Unit/V1beta1/CatalogServiceClientTest.php
  RecommendationEngine/tests/Unit/V1beta1/PredictionApiKeyRegistryClientTest.php
  RecommendationEngine/tests/Unit/V1beta1/PredictionServiceClientTest.php
  RecommendationEngine/tests/Unit/V1beta1/UserEventServiceClientTest.php
Labels: cla: yes, context: full

#3946 chore: migrate osconfig/{v1, v1beta} to the PHP microgenerator
  OsConfig/src/V1/Gapic/OsConfigServiceGapicClient.php
  OsConfig/src/V1/OsConfigServiceClient.php
  OsConfig/src/V1/gapic_metadata.json
  OsConfig/src/V1/resources/os_config_service_client_config.json
  OsConfig/src/V1/resources/os_config_service_descriptor_config.php
  OsConfig/src/V1/resources/os_config_service_rest_client_config.php
  OsConfig/synth.metadata
  OsConfig/tests/Unit/V1/OsConfigServiceClientTest.php
Labels: cla: yes, context: full

#4085 docs: update format method docblock
  SecurityCenter/src/V1/Gapic/SecurityCenterGapicClient.php
  SecurityCenter/src/V1p1beta1/Gapic/SecurityCenterGapicClient.php
  SecurityCenter/synth.metadata
Labels: cla: yes, context: none

#4079 docs: update format method docblock
  AnalyticsAdmin/src/V1alpha/Gapic/AnalyticsAdminServiceGapicClient.php
  AnalyticsAdmin/synth.metadata
Labels: cla: yes, context: full

#4082 docs: update format method docblock
  Memcache/src/V1/Gapic/CloudMemcacheGapicClient.php
  Memcache/src/V1beta2/Gapic/CloudMemcacheGapicClient.php
  Memcache/synth.metadata
Labels: cla: yes, context: none

#4083 docs: update format method docblock
  OsConfig/src/V1/Gapic/OsConfigServiceGapicClient.php
  OsConfig/synth.metadata
Labels: cla: yes, context: partial

#3998 chore: migrate assuredworkloads to the PHP microgenerator
  AssuredWorkloads/src/V1beta1/AssuredWorkloadsServiceClient.php
  AssuredWorkloads/src/V1beta1/Gapic/AssuredWorkloadsServiceGapicClient.php
  AssuredWorkloads/src/V1beta1/gapic_metadata.json
  AssuredWorkloads/src/V1beta1/resources/assured_workloads_service_client_config.json
  AssuredWorkloads/src/V1beta1/resources/assured_workloads_service_rest_client_config.php
  AssuredWorkloads/synth.metadata
  AssuredWorkloads/tests/Unit/V1beta1/AssuredWorkloadsServiceClientTest.php
Labels: cla: yes, context: full

#4002 chore: migrate redis to the PHP microgenerator
  Redis/src/V1/Gapic/CloudRedisGapicClient.php
  Redis/src/V1/resources/cloud_redis_client_config.json
  Redis/src/V1/resources/cloud_redis_descriptor_config.php
  Redis/src/V1/resources/cloud_redis_rest_client_config.php
  Redis/src/V1beta1/Gapic/CloudRedisGapicClient.php
  Redis/src/V1beta1/resources/cloud_redis_client_config.json
  Redis/src/V1beta1/resources/cloud_redis_descriptor_config.php
  Redis/src/V1beta1/resources/cloud_redis_rest_client_config.php
  Redis/synth.metadata
  Redis/tests/Unit/V1/CloudRedisClientTest.php
  Redis/tests/Unit/V1beta1/CloudRedisClientTest.php
Labels: cla: yes, context: full

#3819 chore: migrate to microgenerator
  Gaming/src/V1/CreateGameServerClusterRequest.php
  Gaming/src/V1/CreateGameServerConfigRequest.php
  Gaming/src/V1/CreateGameServerDeploymentRequest.php
  Gaming/src/V1/CreateRealmRequest.php
  Gaming/src/V1/DeployedFleetDetails.php
  Gaming/src/V1/DeployedFleetDetails/DeployedFleet.php
  Gaming/src/V1/DeployedFleetDetails/DeployedFleetAutoscaler.php
  Gaming/src/V1/GameServerCluster.php
  Gaming/src/V1/GameServerClusterConnectionInfo.php
  Gaming/src/V1/GameServerClustersServiceClient.php
  Gaming/src/V1/GameServerConfig.php
  Gaming/src/V1/GameServerConfigOverride.php
  Gaming/src/V1/GameServerConfigsServiceClient.php
  Gaming/src/V1/GameServerDeployment.php
  Gaming/src/V1/GameServerDeploymentRollout.php
  Gaming/src/V1/GameServerDeploymentsServiceClient.php
  Gaming/src/V1/Gapic/GameServerClustersServiceGapicClient.php
  Gaming/src/V1/Gapic/GameServerConfigsServiceGapicClient.php
  Gaming/src/V1/Gapic/GameServerDeploymentsServiceGapicClient.php
  Gaming/src/V1/Gapic/RealmsServiceGapicClient.php
  Gaming/src/V1/OperationMetadata.php
  Gaming/src/V1/PreviewCreateGameServerClusterRequest.php
  Gaming/src/V1/PreviewCreateGameServerClusterResponse.php
  Gaming/src/V1/PreviewDeleteGameServerClusterRequest.php
  Gaming/src/V1/PreviewDeleteGameServerClusterResponse.php
  Gaming/src/V1/PreviewGameServerDeploymentRolloutRequest.php
  Gaming/src/V1/PreviewGameServerDeploymentRolloutResponse.php
  Gaming/src/V1/PreviewRealmUpdateRequest.php
  Gaming/src/V1/PreviewRealmUpdateResponse.php
  Gaming/src/V1/PreviewUpdateGameServerClusterRequest.php
  Gaming/src/V1/PreviewUpdateGameServerClusterResponse.php
  Gaming/src/V1/Realm.php
  Gaming/src/V1/RealmsServiceClient.php
  Gaming/src/V1/Schedule.php
  Gaming/src/V1/TargetDetails/TargetFleetDetails.php
  Gaming/src/V1/TargetDetails/TargetFleetDetails/TargetFleet.php
  Gaming/src/V1/TargetDetails/TargetFleetDetails/TargetFleetAutoscaler.php
  Gaming/src/V1/UpdateGameServerClusterRequest.php
  Gaming/src/V1/UpdateGameServerDeploymentRequest.php
  Gaming/src/V1/UpdateGameServerDeploymentRolloutRequest.php
  Gaming/src/V1/UpdateRealmRequest.php
  Gaming/src/V1/gapic_metadata.json
  Gaming/src/V1/resources/game_server_clusters_service_client_config.json
  Gaming/src/V1/resources/game_server_clusters_service_rest_client_config.php
  Gaming/src/V1/resources/game_server_configs_service_client_config.json
  Gaming/src/V1/resources/game_server_configs_service_rest_client_config.php
  Gaming/src/V1/resources/game_server_deployments_service_client_config.json
  Gaming/src/V1/resources/game_server_deployments_service_rest_client_config.php
  Gaming/src/V1/resources/realms_service_client_config.json
  Gaming/src/V1/resources/realms_service_rest_client_config.php
  Gaming/synth.metadata
  Gaming/tests/Unit/V1/GameServerClustersServiceClientTest.php
  Gaming/tests/Unit/V1/GameServerConfigsServiceClientTest.php
  Gaming/tests/Unit/V1/GameServerDeploymentsServiceClientTest.php
  Gaming/tests/Unit/V1/RealmsServiceClientTest.php
Labels: cla: yes, context: full, context: none

#3820 chore: migrate to microgenerator
  SecurityPrivateCa/src/V1beta1/ActivateCertificateAuthorityRequest.php
  SecurityPrivateCa/src/V1beta1/Certificate.php
  SecurityPrivateCa/src/V1beta1/Certificate/RevocationDetails.php
  SecurityPrivateCa/src/V1beta1/CertificateAuthority.php
  SecurityPrivateCa/src/V1beta1/CertificateAuthority/CertificateAuthorityPolicy.php
  SecurityPrivateCa/src/V1beta1/CertificateAuthorityServiceClient.php
  SecurityPrivateCa/src/V1beta1/CertificateConfig.php
  SecurityPrivateCa/src/V1beta1/CertificateConfig/SubjectConfig.php
  SecurityPrivateCa/src/V1beta1/CertificateDescription.php
  SecurityPrivateCa/src/V1beta1/CertificateDescription/SubjectDescription.php
  SecurityPrivateCa/src/V1beta1/CertificateRevocationList.php
  SecurityPrivateCa/src/V1beta1/CreateCertificateAuthorityRequest.php
  SecurityPrivateCa/src/V1beta1/CreateCertificateRequest.php
  SecurityPrivateCa/src/V1beta1/Gapic/CertificateAuthorityServiceGapicClient.php
  SecurityPrivateCa/src/V1beta1/KeyUsage.php
  SecurityPrivateCa/src/V1beta1/OperationMetadata.php
  SecurityPrivateCa/src/V1beta1/ReusableConfig.php
  SecurityPrivateCa/src/V1beta1/ReusableConfigValues.php
  SecurityPrivateCa/src/V1beta1/ReusableConfigValues/CaOptions.php
  SecurityPrivateCa/src/V1beta1/ReusableConfigWrapper.php
  SecurityPrivateCa/src/V1beta1/SubordinateConfig.php
  SecurityPrivateCa/src/V1beta1/UpdateCertificateAuthorityRequest.php
  SecurityPrivateCa/src/V1beta1/UpdateCertificateRequest.php
  SecurityPrivateCa/src/V1beta1/UpdateCertificateRevocationListRequest.php
  SecurityPrivateCa/src/V1beta1/X509Extension.php
  SecurityPrivateCa/src/V1beta1/gapic_metadata.json
  SecurityPrivateCa/src/V1beta1/resources/certificate_authority_service_client_config.json
  SecurityPrivateCa/src/V1beta1/resources/certificate_authority_service_descriptor_config.php
  SecurityPrivateCa/src/V1beta1/resources/certificate_authority_service_rest_client_config.php
  SecurityPrivateCa/synth.metadata
  SecurityPrivateCa/tests/Unit/V1beta1/CertificateAuthorityServiceClientTest.php
Labels: cla: yes, context: full, context: none

#3822 chore: migrate to microgenerator
  Workflows/src/Executions/V1beta/CreateExecutionRequest.php
  Workflows/src/Executions/V1beta/Execution.php
  Workflows/src/Executions/V1beta/ExecutionsClient.php
  Workflows/src/Executions/V1beta/Gapic/ExecutionsGapicClient.php
  Workflows/src/Executions/V1beta/gapic_metadata.json
  Workflows/src/Executions/V1beta/resources/executions_client_config.json
  Workflows/src/Executions/V1beta/resources/executions_rest_client_config.php
  Workflows/src/V1beta/CreateWorkflowRequest.php
  Workflows/src/V1beta/Gapic/WorkflowsGapicClient.php
  Workflows/src/V1beta/OperationMetadata.php
  Workflows/src/V1beta/UpdateWorkflowRequest.php
  Workflows/src/V1beta/Workflow.php
  Workflows/src/V1beta/WorkflowsClient.php
  Workflows/src/V1beta/gapic_metadata.json
  Workflows/src/V1beta/resources/workflows_client_config.json
  Workflows/src/V1beta/resources/workflows_rest_client_config.php
  Workflows/synth.metadata
  Workflows/tests/Unit/Executions/V1beta/ExecutionsClientTest.php
  Workflows/tests/Unit/V1beta/WorkflowsClientTest.php
Labels: cla: yes, context: full, context: none

#3827 chore: migrate to microgenerator
  Translate/src/V3/BatchTranslateMetadata.php
  Translate/src/V3/BatchTranslateResponse.php
  Translate/src/V3/BatchTranslateTextRequest.php
  Translate/src/V3/CreateGlossaryMetadata.php
  Translate/src/V3/CreateGlossaryRequest.php
  Translate/src/V3/DeleteGlossaryMetadata.php
  Translate/src/V3/DeleteGlossaryResponse.php
  Translate/src/V3/Gapic/TranslationServiceGapicClient.php
  Translate/src/V3/Glossary.php
  Translate/src/V3/GlossaryInputConfig.php
  Translate/src/V3/InputConfig.php
  Translate/src/V3/OutputConfig.php
  Translate/src/V3/TranslateTextRequest.php
  Translate/src/V3/Translation.php
  Translate/src/V3/TranslationServiceClient.php
  Translate/src/V3/gapic_metadata.json
  Translate/src/V3/resources/translation_service_client_config.json
  Translate/src/V3/resources/translation_service_rest_client_config.php
  Translate/synth.metadata
  Translate/tests/Unit/V3/TranslationServiceClientTest.php
Labels: cla: yes, context: full, context: none

#4093 docs: update format method description
  PubSub/src/V1/Gapic/PublisherGapicClient.php
  PubSub/src/V1/Gapic/SchemaServiceGapicClient.php
  PubSub/src/V1/Gapic/SubscriberGapicClient.php
  PubSub/synth.metadata
Labels: cla: yes, context: none

#4089 docs: update format method description
  Channel/src/V1/Gapic/CloudChannelServiceGapicClient.php
  Channel/synth.metadata
Labels: cla: yes, context: none

#4092 docs: update format method description
  Memcache/src/V1/Gapic/CloudMemcacheGapicClient.php
  Memcache/src/V1beta2/Gapic/CloudMemcacheGapicClient.php
  Memcache/synth.metadata
Labels: cla: yes, context: none

#4090 docs: update format method description
  Dialogflow/src/V2/Gapic/AgentsGapicClient.php
  Dialogflow/src/V2/Gapic/AnswerRecordsGapicClient.php
  Dialogflow/src/V2/Gapic/ContextsGapicClient.php
  Dialogflow/src/V2/Gapic/ConversationProfilesGapicClient.php
  Dialogflow/src/V2/Gapic/ConversationsGapicClient.php
  Dialogflow/src/V2/Gapic/DocumentsGapicClient.php
  Dialogflow/src/V2/Gapic/EntityTypesGapicClient.php
  Dialogflow/src/V2/Gapic/EnvironmentsGapicClient.php
  Dialogflow/src/V2/Gapic/FulfillmentsGapicClient.php
  Dialogflow/src/V2/Gapic/IntentsGapicClient.php
  Dialogflow/src/V2/Gapic/KnowledgeBasesGapicClient.php
  Dialogflow/src/V2/Gapic/ParticipantsGapicClient.php
  Dialogflow/src/V2/Gapic/SessionEntityTypesGapicClient.php
  Dialogflow/src/V2/Gapic/SessionsGapicClient.php
  Dialogflow/src/V2/Gapic/VersionsGapicClient.php
  Dialogflow/synth.metadata
Labels: cla: yes, context: full

#4094 docs: update format method description
  Recommender/src/V1/Gapic/RecommenderGapicClient.php
  Recommender/synth.metadata
Labels: cla: yes, context: partial

#3816 feat: add schema support
  .github/emulator/start-emulator.sh
  .github/workflows/pubsub-emulator-system-tests.yaml
  PubSub/composer.json
  PubSub/src/Connection/ConnectionInterface.php
  PubSub/src/Connection/Grpc.php
  PubSub/src/Connection/Rest.php
  PubSub/src/Connection/ServiceDefinition/pubsub-v1.json
  PubSub/src/Message.php
  PubSub/src/PubSubClient.php
  PubSub/src/Schema.php
  PubSub/src/Snapshot.php
  PubSub/src/Topic.php
  PubSub/tests/Snippet/MessageBuilderTest.php
  PubSub/tests/Snippet/MessageTest.php
  PubSub/tests/Snippet/PubSubClientTest.php
  PubSub/tests/Snippet/SchemaTest.php
  PubSub/tests/Snippet/TopicTest.php
  PubSub/tests/System/SchemaTest.php
  PubSub/tests/System/testdata/generated/Metadata.php
  PubSub/tests/System/testdata/generated/StateProto.php
  PubSub/tests/System/testdata/schema.avsc
  PubSub/tests/System/testdata/schema.proto
  PubSub/tests/Unit/BatchPublisherTest.php
  PubSub/tests/Unit/Connection/GrpcTest.php
  PubSub/tests/Unit/Connection/RestTest.php
  PubSub/tests/Unit/PubSubClientTest.php
  PubSub/tests/Unit/SchemaTest.php
  PubSub/tests/Unit/TopicTest.php
  composer.json
Labels: api: pubsub, cla: yes

#4113 docs(Readme): Fixes "Authentication Guide" link
  README.md
Labels: cla: yes

#4112 ci(spanner): fix UNAUTHENTICATED emulator errors
  .github/workflows/spanner-emulator-system-tests.yaml
Labels: api: spanner, cla: yes

#4104 docs: update format method description
  Redis/src/V1/Gapic/CloudRedisGapicClient.php
  Redis/src/V1beta1/Gapic/CloudRedisGapicClient.php
  Redis/synth.metadata
Labels: cla: yes, context: partial

#4116 feat: introduce access approval
  AccessApproval/.gitattributes
  AccessApproval/.github/pull_request_template.md
  AccessApproval/.repo-metadata.json
  AccessApproval/CODE_OF_CONDUCT.md
  AccessApproval/CONTRIBUTING.md
  AccessApproval/LICENSE
  AccessApproval/README.md
  AccessApproval/SECURITY.md
  AccessApproval/VERSION
  AccessApproval/composer.json
  AccessApproval/metadata/V1/Accessapproval.php
  AccessApproval/phpunit-snippets.xml.dist
  AccessApproval/phpunit-system.xml.dist
  AccessApproval/phpunit.xml.dist
  AccessApproval/src/V1/AccessApprovalClient.php
  AccessApproval/src/V1/AccessApprovalGrpcClient.php
  AccessApproval/src/V1/AccessApprovalSettings.php
  AccessApproval/src/V1/AccessLocations.php
  AccessApproval/src/V1/AccessReason.php
  AccessApproval/src/V1/AccessReason/Type.php
  AccessApproval/src/V1/AccessReason_Type.php
  AccessApproval/src/V1/ApprovalRequest.php
  AccessApproval/src/V1/ApproveApprovalRequestMessage.php
  AccessApproval/src/V1/ApproveDecision.php
  AccessApproval/src/V1/DeleteAccessApprovalSettingsMessage.php
  AccessApproval/src/V1/DismissApprovalRequestMessage.php
  AccessApproval/src/V1/DismissDecision.php
  AccessApproval/src/V1/EnrolledService.php
  AccessApproval/src/V1/EnrollmentLevel.php
  AccessApproval/src/V1/Gapic/AccessApprovalGapicClient.php
  AccessApproval/src/V1/GetAccessApprovalSettingsMessage.php
  AccessApproval/src/V1/GetApprovalRequestMessage.php
  AccessApproval/src/V1/ListApprovalRequestsMessage.php
  AccessApproval/src/V1/ListApprovalRequestsResponse.php
  AccessApproval/src/V1/ResourceProperties.php
  AccessApproval/src/V1/UpdateAccessApprovalSettingsMessage.php
  AccessApproval/src/V1/gapic_metadata.json
  AccessApproval/src/V1/resources/access_approval_client_config.json
  AccessApproval/src/V1/resources/access_approval_descriptor_config.php
  AccessApproval/src/V1/resources/access_approval_rest_client_config.php
  AccessApproval/synth.metadata
  AccessApproval/synth.py
  AccessApproval/tests/Unit/V1/AccessApprovalClientTest.php
  docs/contents/cloud-access-approval.json
Labels: cla: yes

#4118 feat: introduce apigee connect
  ApigeeConnect/.gitattributes
  ApigeeConnect/.github/pull_request_template.md
  ApigeeConnect/.repo-metadata.json
  ApigeeConnect/CODE_OF_CONDUCT.md
  ApigeeConnect/CONTRIBUTING.md
  ApigeeConnect/LICENSE
  ApigeeConnect/README.md
  ApigeeConnect/SECURITY.md
  ApigeeConnect/VERSION
  ApigeeConnect/composer.json
  ApigeeConnect/metadata/V1/Connection.php
  ApigeeConnect/metadata/V1/Tether.php
  ApigeeConnect/phpunit-snippets.xml.dist
  ApigeeConnect/phpunit-system.xml.dist
  ApigeeConnect/phpunit.xml.dist
  ApigeeConnect/src/V1/Action.php
  ApigeeConnect/src/V1/Cluster.php
  ApigeeConnect/src/V1/Connection.php
  ApigeeConnect/src/V1/ConnectionServiceClient.php
  ApigeeConnect/src/V1/ConnectionServiceGrpcClient.php
  ApigeeConnect/src/V1/EgressRequest.php
  ApigeeConnect/src/V1/EgressResponse.php
  ApigeeConnect/src/V1/Gapic/ConnectionServiceGapicClient.php
  ApigeeConnect/src/V1/Gapic/TetherGapicClient.php
  ApigeeConnect/src/V1/Header.php
  ApigeeConnect/src/V1/HttpRequest.php
  ApigeeConnect/src/V1/HttpResponse.php
  ApigeeConnect/src/V1/ListConnectionsRequest.php
  ApigeeConnect/src/V1/ListConnectionsResponse.php
  ApigeeConnect/src/V1/Payload.php
  ApigeeConnect/src/V1/Scheme.php
  ApigeeConnect/src/V1/StreamInfo.php
  ApigeeConnect/src/V1/TetherClient.php
  ApigeeConnect/src/V1/TetherEndpoint.php
  ApigeeConnect/src/V1/TetherGrpcClient.php
  ApigeeConnect/src/V1/Url.php
  ApigeeConnect/src/V1/gapic_metadata.json
  ApigeeConnect/src/V1/resources/connection_service_client_config.json
  ApigeeConnect/src/V1/resources/connection_service_descriptor_config.php
  ApigeeConnect/src/V1/resources/connection_service_rest_client_config.php
  ApigeeConnect/src/V1/resources/tether_client_config.json
  ApigeeConnect/src/V1/resources/tether_descriptor_config.php
  ApigeeConnect/src/V1/resources/tether_rest_client_config.php
  ApigeeConnect/synth.metadata
  ApigeeConnect/synth.py
  ApigeeConnect/tests/Unit/V1/ConnectionServiceClientTest.php
  ApigeeConnect/tests/Unit/V1/TetherClientTest.php
  docs/contents/cloud-apigee-connect.json
Labels: cla: yes

#4126 fix: depend on osconfig for external metadata dependencies
  Asset/composer.json
Labels: cla: yes

#4109 feat: added Automated agent reply type and allow cancellation flag for partial response feature.
  Dialogflow/metadata/V2/Participant.php
  Dialogflow/src/V2/AutomatedAgentReply.php
  Dialogflow/src/V2/AutomatedAgentReply/AutomatedAgentReplyType.php
  Dialogflow/src/V2/AutomatedAgentReply_AutomatedAgentReplyType.php
  Dialogflow/synth.metadata
Labels: cla: yes, context: full

#4127 chore: prepare new libraries for release
  AppEngineAdmin/composer.json
  composer.json
  docs/contents/cloud-appengine-admin.json
  docs/contents/google-cloud.json
  docs/manifest.json
Labels: cla: yes

#4133 fix: add additional uri template binding for operations
  Asset/src/V1/resources/asset_service_rest_client_config.php
Labels: cla: yes

#4132 docs: update format method description
  BinaryAuthorization/src/V1beta1/Gapic/BinauthzManagementServiceV1Beta1GapicClient.php
  BinaryAuthorization/synth.metadata
Labels: cla: yes, context: none

#4129 docs: update format method description
  ApigeeConnect/src/V1/Gapic/ConnectionServiceGapicClient.php
  ApigeeConnect/synth.metadata
Labels: cla: yes, context: none

#4131 docs: update format method description
  BillingBudgets/src/V1/Gapic/BudgetServiceGapicClient.php
  BillingBudgets/src/V1beta1/Gapic/BudgetServiceGapicClient.php
  BillingBudgets/synth.metadata
Labels: cla: yes, context: none

#3299 feat(spanner): add query optimizer statistics package support
  Spanner/src/Connection/Grpc.php
  Spanner/tests/Unit/Connection/GrpcTest.php
Labels: api: spanner, cla: yes

#4018 feat(spanner): add support for RPC Priority
  Spanner/src/Connection/Grpc.php
  Spanner/src/Database.php
  Spanner/src/Operation.php
  Spanner/src/Transaction.php
  Spanner/src/TransactionalReadTrait.php
  Spanner/tests/System/QueryTest.php
  Spanner/tests/Unit/Connection/GrpcTest.php
Labels: api: spanner, automerge, cla: yes

#4154 feat: add additional path templates to environments client
  Dialogflow/metadata/V2/Environment.php
  Dialogflow/src/V2/AgentsGrpcClient.php
  Dialogflow/src/V2/EntityTypesGrpcClient.php
  Dialogflow/src/V2/Environment.php
  Dialogflow/src/V2/Gapic/AgentsGapicClient.php
  Dialogflow/src/V2/Gapic/EntityTypesGapicClient.php
  Dialogflow/src/V2/Gapic/EnvironmentsGapicClient.php
  Dialogflow/src/V2/Gapic/IntentsGapicClient.php
  Dialogflow/src/V2/IntentsGrpcClient.php
  Dialogflow/synth.metadata
Labels: cla: yes, context: full

#4152 feat: introduce vpc access
  VpcAccess/.gitattributes
  VpcAccess/.github/pull_request_template.md
  VpcAccess/.repo-metadata.json
  VpcAccess/CODE_OF_CONDUCT.md
  VpcAccess/CONTRIBUTING.md
  VpcAccess/LICENSE
  VpcAccess/README.md
  VpcAccess/SECURITY.md
  VpcAccess/VERSION
  VpcAccess/composer.json
  VpcAccess/metadata/V1/VpcAccess.php
  VpcAccess/phpunit-snippets.xml.dist
  VpcAccess/phpunit-system.xml.dist
  VpcAccess/phpunit.xml.dist
  VpcAccess/src/V1/Connector.php
  VpcAccess/src/V1/Connector/State.php
  VpcAccess/src/V1/Connector/Subnet.php
  VpcAccess/src/V1/Connector_State.php
  VpcAccess/src/V1/Connector_Subnet.php
  VpcAccess/src/V1/CreateConnectorRequest.php
  VpcAccess/src/V1/DeleteConnectorRequest.php
  VpcAccess/src/V1/Gapic/VpcAccessServiceGapicClient.php
  VpcAccess/src/V1/GetConnectorRequest.php
  VpcAccess/src/V1/ListConnectorsRequest.php
  VpcAccess/src/V1/ListConnectorsResponse.php
  VpcAccess/src/V1/OperationMetadata.php
  VpcAccess/src/V1/VpcAccessServiceClient.php
  VpcAccess/src/V1/VpcAccessServiceGrpcClient.php
  VpcAccess/src/V1/gapic_metadata.json
  VpcAccess/src/V1/resources/vpc_access_service_client_config.json
  VpcAccess/src/V1/resources/vpc_access_service_descriptor_config.php
  VpcAccess/src/V1/resources/vpc_access_service_rest_client_config.php
  VpcAccess/synth.metadata
  VpcAccess/synth.py
  VpcAccess/tests/Unit/V1/VpcAccessServiceClientTest.php
  docs/contents/cloud-vpc-access.json
Labels: cla: yes

#4150 feat: introduce tpu
  Tpu/.gitattributes
  Tpu/.github/pull_request_template.md
  Tpu/.repo-metadata.json
  Tpu/CODE_OF_CONDUCT.md
  Tpu/CONTRIBUTING.md
  Tpu/LICENSE
  Tpu/README.md
  Tpu/SECURITY.md
  Tpu/VERSION
  Tpu/composer.json
  Tpu/metadata/V1/CloudTpu.php
  Tpu/phpunit-snippets.xml.dist
  Tpu/phpunit-system.xml.dist
  Tpu/phpunit.xml.dist
  Tpu/src/V1/AcceleratorType.php
  Tpu/src/V1/CreateNodeRequest.php
  Tpu/src/V1/DeleteNodeRequest.php
  Tpu/src/V1/Gapic/TpuGapicClient.php
  Tpu/src/V1/GetAcceleratorTypeRequest.php
  Tpu/src/V1/GetNodeRequest.php
  Tpu/src/V1/GetTensorFlowVersionRequest.php
  Tpu/src/V1/ListAcceleratorTypesRequest.php
  Tpu/src/V1/ListAcceleratorTypesResponse.php
  Tpu/src/V1/ListNodesRequest.php
  Tpu/src/V1/ListNodesResponse.php
  Tpu/src/V1/ListTensorFlowVersionsRequest.php
  Tpu/src/V1/ListTensorFlowVersionsResponse.php
  Tpu/src/V1/NetworkEndpoint.php
  Tpu/src/V1/Node.php
  Tpu/src/V1/Node/ApiVersion.php
  Tpu/src/V1/Node/Health.php
  Tpu/src/V1/Node/State.php
  Tpu/src/V1/Node_ApiVersion.php
  Tpu/src/V1/Node_Health.php
  Tpu/src/V1/Node_State.php
  Tpu/src/V1/OperationMetadata.php
  Tpu/src/V1/ReimageNodeRequest.php
  Tpu/src/V1/SchedulingConfig.php
  Tpu/src/V1/StartNodeRequest.php
  Tpu/src/V1/StopNodeRequest.php
  Tpu/src/V1/Symptom.php
  Tpu/src/V1/Symptom/SymptomType.php
  Tpu/src/V1/Symptom_SymptomType.php
  Tpu/src/V1/TensorFlowVersion.php
  Tpu/src/V1/TpuClient.php
  Tpu/src/V1/TpuGrpcClient.php
  Tpu/src/V1/gapic_metadata.json
  Tpu/src/V1/resources/tpu_client_config.json
  Tpu/src/V1/resources/tpu_descriptor_config.php
  Tpu/src/V1/resources/tpu_rest_client_config.php
  Tpu/synth.metadata
  Tpu/synth.py
  Tpu/tests/Unit/V1/TpuClientTest.php
  docs/contents/cloud-tpu.json
Labels: cla: yes

#4149 feat: introduce profiler
  Profiler/.gitattributes
  Profiler/.github/pull_request_template.md
  Profiler/.repo-metadata.json
  Profiler/CODE_OF_CONDUCT.md
  Profiler/CONTRIBUTING.md
  Profiler/LICENSE
  Profiler/README.md
  Profiler/SECURITY.md
  Profiler/VERSION
  Profiler/composer.json
  Profiler/metadata/V2/Profiler.php
  Profiler/phpunit-snippets.xml.dist
  Profiler/phpunit-system.xml.dist
  Profiler/phpunit.xml.dist
  Profiler/src/V2/CreateOfflineProfileRequest.php
  Profiler/src/V2/CreateProfileRequest.php
  Profiler/src/V2/Deployment.php
  Profiler/src/V2/Gapic/ProfilerServiceGapicClient.php
  Profiler/src/V2/Profile.php
  Profiler/src/V2/ProfileType.php
  Profiler/src/V2/ProfilerServiceClient.php
  Profiler/src/V2/ProfilerServiceGrpcClient.php
  Profiler/src/V2/UpdateProfileRequest.php
  Profiler/src/V2/gapic_metadata.json
  Profiler/src/V2/resources/profiler_service_client_config.json
  Profiler/src/V2/resources/profiler_service_descriptor_config.php
  Profiler/src/V2/resources/profiler_service_rest_client_config.php
  Profiler/synth.metadata
  Profiler/synth.py
  Profiler/tests/Unit/V2/ProfilerServiceClientTest.php
  docs/contents/cloud-profiler.json
Labels: cla: yes

#4148 feat: introduce private catalog
  PrivateCatalog/.gitattributes
  PrivateCatalog/.github/pull_request_template.md
  PrivateCatalog/.repo-metadata.json
  PrivateCatalog/CODE_OF_CONDUCT.md
  PrivateCatalog/CONTRIBUTING.md
  PrivateCatalog/LICENSE
  PrivateCatalog/README.md
  PrivateCatalog/SECURITY.md
  PrivateCatalog/VERSION
  PrivateCatalog/composer.json
  PrivateCatalog/metadata/V1Beta1/PrivateCatalog.php
  PrivateCatalog/phpunit-snippets.xml.dist
  PrivateCatalog/phpunit-system.xml.dist
  PrivateCatalog/phpunit.xml.dist
  PrivateCatalog/src/V1beta1/AssetReference.php
  PrivateCatalog/src/V1beta1/AssetReference/AssetValidationState.php
  PrivateCatalog/src/V1beta1/AssetReference_AssetValidationState.php
  PrivateCatalog/src/V1beta1/Catalog.php
  PrivateCatalog/src/V1beta1/Gapic/PrivateCatalogGapicClient.php
  PrivateCatalog/src/V1beta1/GcsSource.php
  PrivateCatalog/src/V1beta1/GitSource.php
  PrivateCatalog/src/V1beta1/Inputs.php
  PrivateCatalog/src/V1beta1/PrivateCatalogClient.php
  PrivateCatalog/src/V1beta1/PrivateCatalogGrpcClient.php
  PrivateCatalog/src/V1beta1/Product.php
  PrivateCatalog/src/V1beta1/SearchCatalogsRequest.php
  PrivateCatalog/src/V1beta1/SearchCatalogsResponse.php
  PrivateCatalog/src/V1beta1/SearchProductsRequest.php
  PrivateCatalog/src/V1beta1/SearchProductsResponse.php
  PrivateCatalog/src/V1beta1/SearchVersionsRequest.php
  PrivateCatalog/src/V1beta1/SearchVersionsResponse.php
  PrivateCatalog/src/V1beta1/Version.php
  PrivateCatalog/src/V1beta1/gapic_metadata.json
  PrivateCatalog/src/V1beta1/resources/private_catalog_client_config.json
  PrivateCatalog/src/V1beta1/resources/private_catalog_descriptor_config.php
  PrivateCatalog/src/V1beta1/resources/private_catalog_rest_client_config.php
  PrivateCatalog/synth.metadata
  PrivateCatalog/synth.py
  PrivateCatalog/tests/Unit/V1beta1/PrivateCatalogClientTest.php
  docs/contents/cloud-private-catalog.json
Labels: cla: yes

#4146 feat: introduce media translation
  MediaTranslation/.gitattributes
  MediaTranslation/.github/pull_request_template.md
  MediaTranslation/.repo-metadata.json
  MediaTranslation/CODE_OF_CONDUCT.md
  MediaTranslation/CONTRIBUTING.md
  MediaTranslation/LICENSE
  MediaTranslation/README.md
  MediaTranslation/SECURITY.md
  MediaTranslation/VERSION
  MediaTranslation/composer.json
  MediaTranslation/metadata/V1Beta1/MediaTranslation.php
  MediaTranslation/phpunit-snippets.xml.dist
  MediaTranslation/phpunit-system.xml.dist
  MediaTranslation/phpunit.xml.dist
  MediaTranslation/src/V1beta1/Gapic/SpeechTranslationServiceGapicClient.php
  MediaTranslation/src/V1beta1/SpeechTranslationServiceClient.php
  MediaTranslation/src/V1beta1/SpeechTranslationServiceGrpcClient.php
  MediaTranslation/src/V1beta1/StreamingTranslateSpeechConfig.php
  MediaTranslation/src/V1beta1/StreamingTranslateSpeechRequest.php
  MediaTranslation/src/V1beta1/StreamingTranslateSpeechResponse.php
  MediaTranslation/src/V1beta1/StreamingTranslateSpeechResponse/SpeechEventType.php
  MediaTranslation/src/V1beta1/StreamingTranslateSpeechResponse_SpeechEventType.php
  MediaTranslation/src/V1beta1/StreamingTranslateSpeechResult.php
  MediaTranslation/src/V1beta1/StreamingTranslateSpeechResult/TextTranslationResult.php
  MediaTranslation/src/V1beta1/StreamingTranslateSpeechResult_TextTranslationResult.php
  MediaTranslation/src/V1beta1/TranslateSpeechConfig.php
  MediaTranslation/src/V1beta1/gapic_metadata.json
  MediaTranslation/src/V1beta1/resources/speech_translation_service_client_config.json
  MediaTranslation/src/V1beta1/resources/speech_translation_service_descriptor_config.php
  MediaTranslation/src/V1beta1/resources/speech_translation_service_rest_client_config.php
  MediaTranslation/synth.metadata
  MediaTranslation/synth.py
  MediaTranslation/tests/Unit/V1beta1/SpeechTranslationServiceClientTest.php
  docs/contents/cloud-media-translation.json
Labels: cla: yes

#4144 feat: introduce life sciences
  LifeSciences/.gitattributes
  LifeSciences/.github/pull_request_template.md
  LifeSciences/.repo-metadata.json
  LifeSciences/CODE_OF_CONDUCT.md
  LifeSciences/CONTRIBUTING.md
  LifeSciences/LICENSE
  LifeSciences/README.md
  LifeSciences/SECURITY.md
  LifeSciences/VERSION
  LifeSciences/composer.json
  LifeSciences/metadata/V2Beta/Workflows.php
  LifeSciences/phpunit-snippets.xml.dist
  LifeSciences/phpunit-system.xml.dist
  LifeSciences/phpunit.xml.dist
  LifeSciences/src/V2beta/Accelerator.php
  LifeSciences/src/V2beta/Action.php
  LifeSciences/src/V2beta/ContainerKilledEvent.php
  LifeSciences/src/V2beta/ContainerStartedEvent.php
  LifeSciences/src/V2beta/ContainerStoppedEvent.php
  LifeSciences/src/V2beta/DelayedEvent.php
  LifeSciences/src/V2beta/Disk.php
  LifeSciences/src/V2beta/Event.php
  LifeSciences/src/V2beta/ExistingDisk.php
  LifeSciences/src/V2beta/FailedEvent.php
  LifeSciences/src/V2beta/Gapic/WorkflowsServiceV2BetaGapicClient.php
  LifeSciences/src/V2beta/Metadata.php
  LifeSciences/src/V2beta/Mount.php
  LifeSciences/src/V2beta/NFSMount.php
  LifeSciences/src/V2beta/Network.php
  LifeSciences/src/V2beta/PersistentDisk.php
  LifeSciences/src/V2beta/Pipeline.php
  LifeSciences/src/V2beta/PullStartedEvent.php
  LifeSciences/src/V2beta/PullStoppedEvent.php
  LifeSciences/src/V2beta/Resources.php
  LifeSciences/src/V2beta/RunPipelineRequest.php
  LifeSciences/src/V2beta/RunPipelineResponse.php
  LifeSciences/src/V2beta/Secret.php
  LifeSciences/src/V2beta/ServiceAccount.php
  LifeSciences/src/V2beta/UnexpectedExitStatusEvent.php
  LifeSciences/src/V2beta/VirtualMachine.php
  LifeSciences/src/V2beta/Volume.php
  LifeSciences/src/V2beta/WorkerAssignedEvent.php
  LifeSciences/src/V2beta/WorkerReleasedEvent.php
  LifeSciences/src/V2beta/WorkflowsServiceV2BetaClient.php
  LifeSciences/src/V2beta/WorkflowsServiceV2BetaGrpcClient.php
  LifeSciences/src/V2beta/gapic_metadata.json
  LifeSciences/src/V2beta/resources/workflows_service_v2_beta_client_config.json
  LifeSciences/src/V2beta/resources/workflows_service_v2_beta_descriptor_config.php
  LifeSciences/src/V2beta/resources/workflows_service_v2_beta_rest_client_config.php
  LifeSciences/synth.metadata
  LifeSciences/synth.py
  LifeSciences/tests/Unit/V2beta/WorkflowsServiceV2BetaClientTest.php
  docs/contents/cloud-life-sciences.json
Labels: cla: yes

#4143 feat: introduce gkehub
  GkeHub/.gitattributes
  GkeHub/.github/pull_request_template.md
  GkeHub/.repo-metadata.json
  GkeHub/CODE_OF_CONDUCT.md
  GkeHub/CONTRIBUTING.md
  GkeHub/LICENSE
  GkeHub/README.md
  GkeHub/SECURITY.md
  GkeHub/VERSION
  GkeHub/composer.json
  GkeHub/metadata/V1Beta1/Membership.php
  GkeHub/phpunit-snippets.xml.dist
  GkeHub/phpunit-system.xml.dist
  GkeHub/phpunit.xml.dist
  GkeHub/src/V1beta1/Authority.php
  GkeHub/src/V1beta1/ConnectAgent.php
  GkeHub/src/V1beta1/ConnectAgentResource.php
  GkeHub/src/V1beta1/CreateMembershipRequest.php
  GkeHub/src/V1beta1/DeleteMembershipRequest.php
  GkeHub/src/V1beta1/Gapic/GkeHubMembershipServiceGapicClient.php
  GkeHub/src/V1beta1/GenerateConnectManifestRequest.php
  GkeHub/src/V1beta1/GenerateConnectManifestResponse.php
  GkeHub/src/V1beta1/GenerateExclusivityManifestRequest.php
  GkeHub/src/V1beta1/GenerateExclusivityManifestResponse.php
  GkeHub/src/V1beta1/GetMembershipRequest.php
  GkeHub/src/V1beta1/GkeCluster.php
  GkeHub/src/V1beta1/GkeHubMembershipServiceClient.php
  GkeHub/src/V1beta1/GkeHubMembershipServiceGrpcClient.php
  GkeHub/src/V1beta1/KubernetesMetadata.php
  GkeHub/src/V1beta1/KubernetesResource.php
  GkeHub/src/V1beta1/ListMembershipsRequest.php
  GkeHub/src/V1beta1/ListMembershipsResponse.php
  GkeHub/src/V1beta1/Membership.php
  GkeHub/src/V1beta1/Membership/InfrastructureType.php
  GkeHub/src/V1beta1/MembershipEndpoint.php
  GkeHub/src/V1beta1/MembershipState.php
  GkeHub/src/V1beta1/MembershipState/Code.php
  GkeHub/src/V1beta1/MembershipState_Code.php
  GkeHub/src/V1beta1/Membership_InfrastructureType.php
  GkeHub/src/V1beta1/OperationMetadata.php
  GkeHub/src/V1beta1/ResourceManifest.php
  GkeHub/src/V1beta1/ResourceOptions.php
  GkeHub/src/V1beta1/TypeMeta.php
  GkeHub/src/V1beta1/UpdateMembershipRequest.php
  GkeHub/src/V1beta1/ValidateExclusivityRequest.php
  GkeHub/src/V1beta1/ValidateExclusivityResponse.php
  GkeHub/src/V1beta1/gapic_metadata.json
  GkeHub/src/V1beta1/resources/gke_hub_membership_service_client_config.json
  GkeHub/src/V1beta1/resources/gke_hub_membership_service_descriptor_config.php
  GkeHub/src/V1beta1/resources/gke_hub_membership_service_rest_client_config.php
  GkeHub/synth.metadata
  GkeHub/synth.py
  GkeHub/tests/Unit/V1beta1/GkeHubMembershipServiceClientTest.php
  docs/contents/cloud-gke-hub.json
Labels: cla: yes

#4142 feat: introduce essential contacts
  EssentialContacts/.gitattributes
  EssentialContacts/.github/pull_request_template.md
  EssentialContacts/.repo-metadata.json
  EssentialContacts/CODE_OF_CONDUCT.md
  EssentialContacts/CONTRIBUTING.md
  EssentialContacts/LICENSE
  EssentialContacts/README.md
  EssentialContacts/SECURITY.md
  EssentialContacts/VERSION
  EssentialContacts/composer.json
  EssentialContacts/metadata/V1/Enums.php
  EssentialContacts/metadata/V1/Service.php
  EssentialContacts/phpunit-snippets.xml.dist
  EssentialContacts/phpunit-system.xml.dist
  EssentialContacts/phpunit.xml.dist
  EssentialContacts/src/V1/ComputeContactsRequest.php
  EssentialContacts/src/V1/ComputeContactsResponse.php
  EssentialContacts/src/V1/Contact.php
  EssentialContacts/src/V1/CreateContactRequest.php
  EssentialContacts/src/V1/DeleteContactRequest.php
  EssentialContacts/src/V1/EssentialContactsServiceClient.php
  EssentialContacts/src/V1/EssentialContactsServiceGrpcClient.php
  EssentialContacts/src/V1/Gapic/EssentialContactsServiceGapicClient.php
  EssentialContacts/src/V1/GetContactRequest.php
  EssentialContacts/src/V1/ListContactsRequest.php
  EssentialContacts/src/V1/ListContactsResponse.php
  EssentialContacts/src/V1/NotificationCategory.php
  EssentialContacts/src/V1/SendTestMessageRequest.php
  EssentialContacts/src/V1/UpdateContactRequest.php
  EssentialContacts/src/V1/ValidationState.php
  EssentialContacts/src/V1/gapic_metadata.json
  EssentialContacts/src/V1/resources/essential_contacts_service_client_config.json
  EssentialContacts/src/V1/resources/essential_contacts_service_descriptor_config.php
  EssentialContacts/src/V1/resources/essential_contacts_service_rest_client_config.php
  EssentialContacts/synth.metadata
  EssentialContacts/synth.py
  EssentialContacts/tests/Unit/V1/EssentialContactsServiceClientTest.php
  docs/contents/cloud-essential-contacts.json
Labels: cla: yes

#4136 fix: correct endpoint for operations bindings
  ArtifactRegistry/src/V1beta2/resources/artifact_registry_rest_client_config.php
Labels: cla: yes

#4157 chore: fix secretmanager sample in README
  SecretManager/README.md
Labels: cla: yes, samples

#4156 chore: prepare new libraries for release
  composer.json
  docs/contents/google-cloud.json
  docs/manifest.json
Labels: cla: yes

#4191 docs: update format method description
  WebRisk/src/V1/Gapic/WebRiskServiceGapicClient.php
  WebRisk/synth.metadata
  WebRisk/synth.py
Labels: cla: yes, context: none

#4040 feat: update phpdocumentor to 4.0
  .kokoro/presubmit/run-tests.sh
  Core/src/LongRunning/LROTrait.php
  Core/src/ServiceBuilder.php
  PubSub/src/Topic.php
  dev/src/DocGenerator/DocBlock/DescriptionFactory.php
  dev/src/DocGenerator/DocGenerator.php
  dev/src/DocGenerator/Parser/CodeParser.php
  dev/src/DocGenerator/ReflectorRegister.php
Labels: cla: yes

#4197 chore: correct casing for namespace
  PubSub/src/Schema.php
Labels: cla: yes

#4196 chore: require phpdocumentor/reflection v4 for doc generation
  .github/workflows/docs.yml
Labels: cla: yes

#4195 chore: clean up composer
  .github/workflows/docs.yml
  composer.json
Labels: cla: yes

#4198 chore: move setup PHP step prior to composer install
  .github/workflows/docs.yml
Labels: automerge, cla: yes

#4159 fix: correct data labeling
  docs/contents/google-cloud.json
  docs/manifest.json
Labels: cla: yes

#4168 docs: update format method description
  DataprocMetastore/src/V1/Gapic/DataprocMetastoreGapicClient.php
  DataprocMetastore/src/V1alpha/Gapic/DataprocMetastoreGapicClient.php
  DataprocMetastore/src/V1beta/Gapic/DataprocMetastoreGapicClient.php
  DataprocMetastore/synth.metadata
Labels: cla: yes, context: none

#4172 docs: update format method description
  Dms/src/V1/Gapic/DataMigrationServiceGapicClient.php
  Dms/synth.metadata
Labels: cla: yes, context: none

#3621 feat: add support for public access prevention
  Storage/src/Bucket.php
  Storage/src/Connection/ServiceDefinition/storage-v1.json
  Storage/tests/System/IamConfigurationTest.php
Labels: api: storage, cla: yes

#4183 feat(spanner): add processing_units to Instance resource
  Spanner/metadata/Admin/Instance/V1/SpannerInstanceAdmin.php
  Spanner/src/Admin/Database/V1/Gapic/DatabaseAdminGapicClient.php
  Spanner/src/Admin/Instance/V1/Gapic/InstanceAdminGapicClient.php
  Spanner/src/Admin/Instance/V1/Instance.php
  Spanner/src/V1/Gapic/SpannerGapicClient.php
  Spanner/synth.metadata
  Spanner/tests/Unit/Admin/Instance/V1/InstanceAdminClientTest.php
Labels: cla: yes, context: partial

#4162 docs: update format method description
  AutoMl/src/V1/Gapic/AutoMlGapicClient.php
  AutoMl/src/V1/Gapic/PredictionServiceGapicClient.php
  AutoMl/src/V1beta1/Gapic/AutoMlGapicClient.php
  AutoMl/src/V1beta1/Gapic/PredictionServiceGapicClient.php
  AutoMl/synth.metadata
Labels: cla: yes, context: none

#4163 docs: update format method description
  BigQueryConnection/src/V1/Gapic/ConnectionServiceGapicClient.php
  BigQueryConnection/synth.metadata
Labels: cla: yes, context: none

#4165 docs: update format method description
  BigQueryStorage/src/V1/Gapic/BigQueryReadGapicClient.php
  BigQueryStorage/synth.metadata
Labels: cla: yes, context: none

#4166 docs: update format method description
  Billing/src/V1/Gapic/CloudBillingGapicClient.php
  Billing/src/V1/Gapic/CloudCatalogGapicClient.php
  Billing/synth.metadata
Labels: cla: yes, context: none

#4171 docs: update format method description
  Dlp/src/V2/Gapic/DlpServiceGapicClient.php
  Dlp/synth.metadata
Labels: cla: yes, context: none

#4174 docs: update format method description
  EssentialContacts/src/V1/Gapic/EssentialContactsServiceGapicClient.php
  EssentialContacts/synth.metadata
Labels: cla: yes, context: none

#4176 docs: update format method description
  Iot/src/V1/Gapic/DeviceManagerGapicClient.php
  Iot/synth.metadata
Labels: cla: yes, context: none

#4211 feat: add JSON type
  Spanner/metadata/V1/Type.php
  Spanner/src/Admin/Database/V1/Gapic/DatabaseAdminGapicClient.php
  Spanner/src/Admin/Instance/V1/Gapic/InstanceAdminGapicClient.php
  Spanner/src/V1/Gapic/SpannerGapicClient.php
  Spanner/src/V1/TypeCode.php
  Spanner/synth.metadata
Labels: cla: yes, context: partial

#4185 docs: update format method description
  Tpu/src/V1/Gapic/TpuGapicClient.php
  Tpu/synth.metadata
Labels: cla: yes, context: none

#4180 docs: update format method description
  RecaptchaEnterprise/src/V1/Gapic/RecaptchaEnterpriseServiceGapicClient.php
  RecaptchaEnterprise/synth.metadata
Labels: cla: yes, context: none

#4182 feat: add vpc network/create/update time
  ServiceDirectory/metadata/V1Beta1/Endpoint.php
  ServiceDirectory/metadata/V1Beta1/PBNamespace.php
  ServiceDirectory/metadata/V1Beta1/Service.php
  ServiceDirectory/src/V1/Gapic/LookupServiceGapicClient.php
  ServiceDirectory/src/V1/Gapic/RegistrationServiceGapicClient.php
  ServiceDirectory/src/V1beta1/Endpoint.php
  ServiceDirectory/src/V1beta1/Gapic/LookupServiceGapicClient.php
  ServiceDirectory/src/V1beta1/Gapic/RegistrationServiceGapicClient.php
  ServiceDirectory/src/V1beta1/GetServiceRequest.php
  ServiceDirectory/src/V1beta1/ListEndpointsRequest.php
  ServiceDirectory/src/V1beta1/ListNamespacesRequest.php
  ServiceDirectory/src/V1beta1/ListServicesRequest.php
  ServiceDirectory/src/V1beta1/PBNamespace.php
  ServiceDirectory/src/V1beta1/RegistrationServiceGrpcClient.php
  ServiceDirectory/src/V1beta1/ResolveServiceRequest.php
  ServiceDirectory/src/V1beta1/Service.php
  ServiceDirectory/src/V1beta1/resources/lookup_service_rest_client_config.php
  ServiceDirectory/src/V1beta1/resources/registration_service_rest_client_config.php
  ServiceDirectory/synth.metadata
  ServiceDirectory/tests/Unit/V1beta1/RegistrationServiceClientTest.php
Labels: cla: yes, context: none, context: partial

#4181 docs: update format method description
  Retail/src/V2/Gapic/CatalogServiceGapicClient.php
  Retail/src/V2/Gapic/ProductServiceGapicClient.php
  Retail/synth.metadata
Labels: cla: yes, context: none

#4179 docs: update format method description
  OsLogin/src/V1/Gapic/OsLoginServiceGapicClient.php
  OsLogin/src/V1beta/Gapic/OsLoginServiceGapicClient.php
  OsLogin/synth.metadata
Labels: cla: yes, context: none

#4178 docs: update format method description
  Notebooks/src/V1beta1/Gapic/NotebookServiceGapicClient.php
  Notebooks/synth.metadata
Labels: cla: yes, context: none

#4175 docs: update format method description
  GkeHub/src/V1beta1/Gapic/GkeHubMembershipServiceGapicClient.php
  GkeHub/synth.metadata
Labels: cla: yes, context: none

#4161 docs: update format method description
  AnalyticsData/src/V1alpha/Gapic/AlphaAnalyticsDataGapicClient.php
  AnalyticsData/src/V1beta/Gapic/BetaAnalyticsDataGapicClient.php
  AnalyticsData/synth.metadata
Labels: cla: yes, context: none

#4190 docs: update format method description
  VpcAccess/src/V1/Gapic/VpcAccessServiceGapicClient.php
  VpcAccess/synth.metadata
Labels: cla: yes, context: none

#4189 docs: update format method description
  Vision/src/V1/Gapic/ProductSearchGapicClient.php
  Vision/synth.metadata
Labels: cla: yes, context: none

#4186 docs: update format method description
  Trace/src/V2/Gapic/TraceServiceGapicClient.php
  Trace/synth.metadata
Labels: cla: yes, context: none

#4164 docs: update format method description
  BigQueryReservation/src/V1/Gapic/ReservationServiceGapicClient.php
  BigQueryReservation/synth.metadata
Labels: cla: yes, context: none

#4188 docs: update format method description
  VideoTranscoder/src/V1beta1/Gapic/TranscoderServiceGapicClient.php
  VideoTranscoder/synth.metadata
Labels: cla: yes, context: none

#4207 feat: introduce org policy
  OrgPolicy/.gitattributes
  OrgPolicy/.github/pull_request_template.md
  OrgPolicy/.repo-metadata.json
  OrgPolicy/CODE_OF_CONDUCT.md
  OrgPolicy/CONTRIBUTING.md
  OrgPolicy/LICENSE
  OrgPolicy/README.md
  OrgPolicy/SECURITY.md
  OrgPolicy/VERSION
  OrgPolicy/composer.json
  OrgPolicy/metadata/V2/Constraint.php
  OrgPolicy/metadata/V2/Orgpolicy.php
  OrgPolicy/phpunit-snippets.xml.dist
  OrgPolicy/phpunit-system.xml.dist
  OrgPolicy/phpunit.xml.dist
  OrgPolicy/src/V2/AlternatePolicySpec.php
  OrgPolicy/src/V2/Constraint.php
  OrgPolicy/src/V2/Constraint/BooleanConstraint.php
  OrgPolicy/src/V2/Constraint/ConstraintDefault.php
  OrgPolicy/src/V2/Constraint/ListConstraint.php
  OrgPolicy/src/V2/Constraint_BooleanConstraint.php
  OrgPolicy/src/V2/Constraint_ConstraintDefault.php
  OrgPolicy/src/V2/Constraint_ListConstraint.php
  OrgPolicy/src/V2/CreatePolicyRequest.php
  OrgPolicy/src/V2/DeletePolicyRequest.php
  OrgPolicy/src/V2/Gapic/OrgPolicyGapicClient.php
  OrgPolicy/src/V2/GetEffectivePolicyRequest.php
  OrgPolicy/src/V2/GetPolicyRequest.php
  OrgPolicy/src/V2/ListConstraintsRequest.php
  OrgPolicy/src/V2/ListConstraintsResponse.php
  OrgPolicy/src/V2/ListPoliciesRequest.php
  OrgPolicy/src/V2/ListPoliciesResponse.php
  OrgPolicy/src/V2/OrgPolicyClient.php
  OrgPolicy/src/V2/OrgPolicyGrpcClient.php
  OrgPolicy/src/V2/Policy.php
  OrgPolicy/src/V2/PolicySpec.php
  OrgPolicy/src/V2/PolicySpec/PolicyRule.php
  OrgPolicy/src/V2/PolicySpec/PolicyRule/StringValues.php
  OrgPolicy/src/V2/PolicySpec_PolicyRule.php
  OrgPolicy/src/V2/PolicySpec_PolicyRule_StringValues.php
  OrgPolicy/src/V2/UpdatePolicyRequest.php
  OrgPolicy/src/V2/gapic_metadata.json
  OrgPolicy/src/V2/resources/org_policy_client_config.json
  OrgPolicy/src/V2/resources/org_policy_descriptor_config.php
  OrgPolicy/src/V2/resources/org_policy_rest_client_config.php
  OrgPolicy/synth.metadata
  OrgPolicy/synth.py
  OrgPolicy/tests/Unit/V2/OrgPolicyClientTest.php
  docs/contents/cloud-org-policy.json
Labels: cla: yes

#4210 feat: introduce iam credentials
  IamCredentials/.gitattributes
  IamCredentials/.github/pull_request_template.md
  IamCredentials/.repo-metadata.json
  IamCredentials/CODE_OF_CONDUCT.md
  IamCredentials/CONTRIBUTING.md
  IamCredentials/LICENSE
  IamCredentials/README.md
  IamCredentials/SECURITY.md
  IamCredentials/VERSION
  IamCredentials/composer.json
  IamCredentials/metadata/V1/Common.php
  IamCredentials/metadata/V1/Iamcredentials.php
  IamCredentials/phpunit-snippets.xml.dist
  IamCredentials/phpunit-system.xml.dist
  IamCredentials/phpunit.xml.dist
  IamCredentials/src/V1/Gapic/IAMCredentialsGapicClient.php
  IamCredentials/src/V1/GenerateAccessTokenRequest.php
  IamCredentials/src/V1/GenerateAccessTokenResponse.php
  IamCredentials/src/V1/GenerateIdTokenRequest.php
  IamCredentials/src/V1/GenerateIdTokenResponse.php
  IamCredentials/src/V1/IAMCredentialsClient.php
  IamCredentials/src/V1/IAMCredentialsGrpcClient.php
  IamCredentials/src/V1/SignBlobRequest.php
  IamCredentials/src/V1/SignBlobResponse.php
  IamCredentials/src/V1/SignJwtRequest.php
  IamCredentials/src/V1/SignJwtResponse.php
  IamCredentials/src/V1/gapic_metadata.json
  IamCredentials/src/V1/resources/iam_credentials_client_config.json
  IamCredentials/src/V1/resources/iam_credentials_descriptor_config.php
  IamCredentials/src/V1/resources/iam_credentials_rest_client_config.php
  IamCredentials/synth.metadata
  IamCredentials/synth.py
  IamCredentials/tests/Unit/V1/IAMCredentialsClientTest.php
  docs/contents/cloud-iam-credentials.json
Labels: cla: yes

#4206 feat: introduce service usage
  ServiceUsage/.gitattributes
  ServiceUsage/.github/pull_request_template.md
  ServiceUsage/.repo-metadata.json
  ServiceUsage/CODE_OF_CONDUCT.md
  ServiceUsage/CONTRIBUTING.md
  ServiceUsage/LICENSE
  ServiceUsage/README.md
  ServiceUsage/SECURITY.md
  ServiceUsage/VERSION
  ServiceUsage/composer.json
  ServiceUsage/metadata/V1/Resources.php
  ServiceUsage/metadata/V1/Serviceusage.php
  ServiceUsage/phpunit-snippets.xml.dist
  ServiceUsage/phpunit-system.xml.dist
  ServiceUsage/phpunit.xml.dist
  ServiceUsage/src/V1/BatchEnableServicesRequest.php
  ServiceUsage/src/V1/BatchEnableServicesResponse.php
  ServiceUsage/src/V1/BatchEnableServicesResponse/EnableFailure.php
  ServiceUsage/src/V1/BatchEnableServicesResponse_EnableFailure.php
  ServiceUsage/src/V1/BatchGetServicesRequest.php
  ServiceUsage/src/V1/BatchGetServicesResponse.php
  ServiceUsage/src/V1/DisableServiceRequest.php
  ServiceUsage/src/V1/DisableServiceRequest/CheckIfServiceHasUsage.php
  ServiceUsage/src/V1/DisableServiceRequest_CheckIfServiceHasUsage.php
  ServiceUsage/src/V1/DisableServiceResponse.php
  ServiceUsage/src/V1/EnableServiceRequest.php
  ServiceUsage/src/V1/EnableServiceResponse.php
  ServiceUsage/src/V1/Gapic/ServiceUsageGapicClient.php
  ServiceUsage/src/V1/GetServiceRequest.php
  ServiceUsage/src/V1/ListServicesRequest.php
  ServiceUsage/src/V1/ListServicesResponse.php
  ServiceUsage/src/V1/OperationMetadata.php
  ServiceUsage/src/V1/Service.php
  ServiceUsage/src/V1/ServiceConfig.php
  ServiceUsage/src/V1/ServiceUsageClient.php
  ServiceUsage/src/V1/ServiceUsageGrpcClient.php
  ServiceUsage/src/V1/State.php
  ServiceUsage/src/V1/gapic_metadata.json
  ServiceUsage/src/V1/resources/service_usage_client_config.json
  ServiceUsage/src/V1/resources/service_usage_descriptor_config.php
  ServiceUsage/src/V1/resources/service_usage_rest_client_config.php
  ServiceUsage/synth.metadata
  ServiceUsage/synth.py
  ServiceUsage/tests/Unit/V1/ServiceUsageClientTest.php
  docs/contents/cloud-service-usage.json
Labels: cla: yes

#4209 feat: introduce policy troubleshooter
  PolicyTroubleshooter/.gitattributes
  PolicyTroubleshooter/.github/pull_request_template.md
  PolicyTroubleshooter/.repo-metadata.json
  PolicyTroubleshooter/CODE_OF_CONDUCT.md
  PolicyTroubleshooter/CONTRIBUTING.md
  PolicyTroubleshooter/LICENSE
  PolicyTroubleshooter/README.md
  PolicyTroubleshooter/SECURITY.md
  PolicyTroubleshooter/VERSION
  PolicyTroubleshooter/composer.json
  PolicyTroubleshooter/metadata/V1/Checker.php
  PolicyTroubleshooter/metadata/V1/Explanations.php
  PolicyTroubleshooter/phpunit-snippets.xml.dist
  PolicyTroubleshooter/phpunit-system.xml.dist
  PolicyTroubleshooter/phpunit.xml.dist
  PolicyTroubleshooter/src/V1/AccessState.php
  PolicyTroubleshooter/src/V1/AccessTuple.php
  PolicyTroubleshooter/src/V1/BindingExplanation.php
  PolicyTroubleshooter/src/V1/BindingExplanation/AnnotatedMembership.php
  PolicyTroubleshooter/src/V1/BindingExplanation/Membership.php
  PolicyTroubleshooter/src/V1/BindingExplanation/RolePermission.php
  PolicyTroubleshooter/src/V1/BindingExplanation_AnnotatedMembership.php
  PolicyTroubleshooter/src/V1/BindingExplanation_Membership.php
  PolicyTroubleshooter/src/V1/BindingExplanation_RolePermission.php
  PolicyTroubleshooter/src/V1/ExplainedPolicy.php
  PolicyTroubleshooter/src/V1/Gapic/IamCheckerGapicClient.php
  PolicyTroubleshooter/src/V1/HeuristicRelevance.php
  PolicyTroubleshooter/src/V1/IamCheckerClient.php
  PolicyTroubleshooter/src/V1/IamCheckerGrpcClient.php
  PolicyTroubleshooter/src/V1/TroubleshootIamPolicyRequest.php
  PolicyTroubleshooter/src/V1/TroubleshootIamPolicyResponse.php
  PolicyTroubleshooter/src/V1/gapic_metadata.json
  PolicyTroubleshooter/src/V1/resources/iam_checker_client_config.json
  PolicyTroubleshooter/src/V1/resources/iam_checker_descriptor_config.php
  PolicyTroubleshooter/src/V1/resources/iam_checker_rest_client_config.php
  PolicyTroubleshooter/synth.metadata
  PolicyTroubleshooter/synth.py
  PolicyTroubleshooter/tests/Unit/V1/IamCheckerClientTest.php
  docs/contents/cloud-policy-troubleshooter.json
Labels: cla: yes

#4214 docs: update format method description
  OrgPolicy/src/V2/Gapic/OrgPolicyGapicClient.php
  OrgPolicy/synth.metadata
Labels: cla: yes, context: none

#4203 feat: introduce cloud shell
  Shell/.gitattributes
  Shell/.github/pull_request_template.md
  Shell/.repo-metadata.json
  Shell/CODE_OF_CONDUCT.md
  Shell/CONTRIBUTING.md
  Shell/LICENSE
  Shell/README.md
  Shell/SECURITY.md
  Shell/VERSION
  Shell/composer.json
  Shell/metadata/V1/Cloudshell.php
  Shell/phpunit-snippets.xml.dist
  Shell/phpunit-system.xml.dist
  Shell/phpunit.xml.dist
  Shell/src/V1/AddPublicKeyMetadata.php
  Shell/src/V1/AddPublicKeyRequest.php
  Shell/src/V1/AddPublicKeyResponse.php
  Shell/src/V1/AuthorizeEnvironmentMetadata.php
  Shell/src/V1/AuthorizeEnvironmentRequest.php
  Shell/src/V1/AuthorizeEnvironmentResponse.php
  Shell/src/V1/CloudShellErrorDetails.php
  Shell/src/V1/CloudShellErrorDetails/CloudShellErrorCode.php
  Shell/src/V1/CloudShellErrorDetails_CloudShellErrorCode.php
  Shell/src/V1/CloudShellServiceClient.php
  Shell/src/V1/CloudShellServiceGrpcClient.php
  Shell/src/V1/CreateEnvironmentMetadata.php
  Shell/src/V1/DeleteEnvironmentMetadata.php
  Shell/src/V1/Environment.php
  Shell/src/V1/Environment/State.php
  Shell/src/V1/Environment_State.php
  Shell/src/V1/Gapic/CloudShellServiceGapicClient.php
  Shell/src/V1/GetEnvironmentRequest.php
  Shell/src/V1/RemovePublicKeyMetadata.php
  Shell/src/V1/RemovePublicKeyRequest.php
  Shell/src/V1/RemovePublicKeyResponse.php
  Shell/src/V1/StartEnvironmentMetadata.php
  Shell/src/V1/StartEnvironmentMetadata/State.php
  Shell/src/V1/StartEnvironmentMetadata_State.php
  Shell/src/V1/StartEnvironmentRequest.php
  Shell/src/V1/StartEnvironmentResponse.php
  Shell/src/V1/gapic_metadata.json
  Shell/src/V1/resources/cloud_shell_service_client_config.json
  Shell/src/V1/resources/cloud_shell_service_descriptor_config.php
  Shell/src/V1/resources/cloud_shell_service_rest_client_config.php
  Shell/synth.metadata
  Shell/synth.py
  Shell/tests/Unit/V1/CloudShellServiceClientTest.php
  docs/contents/cloud-shell.json
Labels: cla: yes

#4215 feat: add status to quota error
  ServiceControl/metadata/V1/Distribution.php
  ServiceControl/metadata/V1/QuotaController.php
  ServiceControl/metadata/V1/ServiceController.php
  ServiceControl/src/V1/CheckResponse.php
  ServiceControl/src/V1/Distribution.php
  ServiceControl/src/V1/Gapic/ServiceControllerGapicClient.php
  ServiceControl/src/V1/MetricValue.php
  ServiceControl/src/V1/Operation.php
  ServiceControl/src/V1/Operation/Importance.php
  ServiceControl/src/V1/QuotaError.php
  ServiceControl/src/V1/QuotaOperation/QuotaMode.php
  ServiceControl/src/V1/ReportRequest.php
  ServiceControl/src/V1/ReportResponse/ReportError.php
  ServiceControl/src/V1/ServiceControllerGrpcClient.php
  ServiceControl/src/V1/resources/quota_controller_client_config.json
  ServiceControl/src/V1/resources/service_controller_client_config.json
  ServiceControl/synth.metadata
Labels: cla: yes, context: full

#4216 chore: update manifest default services
  docs/manifest.json
Labels: cla: yes
