Repository googleapis/google-cloud-php, pull requests merged in 2021-08, with the labels that each got.

#4314 fix: phpparser syntax error for 8.1 and OOM errors in AppEngineFlexHandlerTest
  composer.json
  dev/src/DocGenerator/DocGenerator.php
Labels: cla: yes

#4114 feat: add support for JSON type
  Spanner/src/Database.php
  Spanner/src/ValueMapper.php
  Spanner/tests/System/QueryTest.php
  Spanner/tests/Unit/ValueMapperTest.php
Labels: cla: yes, api: spanner

#4318 chore: strike allowlist verbiage from documentation
  WebRisk/README.md
Labels: cla: yes

#4316 chore: use ubuntu-latest for docs job run
  .github/workflows/docs.yml
Labels: cla: yes

#4312 feat: introduce clientCertSource configuration option
  .github/workflows/release.yml
  WebSecurityScanner/src/V1beta/Gapic/WebSecurityScannerGapicClient.php
  WebSecurityScanner/synth.metadata
Labels: cla: yes, automerge, context: full

#4322 [WebSecurityScanner] chore: release gapic-generator-php v1.0.5
  WebSecurityScanner/src/V1beta/resources/web_security_scanner_rest_client_config.php
  WebSecurityScanner/synth.metadata
Labels: cla: yes, context: full

#4310 feat: introduce clientCertSource option
  VpcAccess/src/V1/Gapic/VpcAccessServiceGapicClient.php
  VpcAccess/src/V1/resources/vpc_access_service_rest_client_config.php
  VpcAccess/synth.metadata
Labels: cla: yes, context: full

#4309 feat: introduce clientCertSource option
  Vision/src/V1/Gapic/ImageAnnotatorGapicClient.php
  Vision/src/V1/Gapic/ProductSearchGapicClient.php
  Vision/synth.metadata
Labels: cla: yes, context: partial

#4308 feat: introduce clientCertSource option / add TTL
  VideoTranscoder/metadata/V1Beta1/Resources.php
  VideoTranscoder/metadata/V1Beta1/Services.php
  VideoTranscoder/src/V1beta1/Gapic/TranscoderServiceGapicClient.php
  VideoTranscoder/src/V1beta1/Input.php
  VideoTranscoder/src/V1beta1/Job.php
  VideoTranscoder/src/V1beta1/Job/OriginUri.php
  VideoTranscoder/src/V1beta1/Overlay/AnimationFade.php
  VideoTranscoder/src/V1beta1/Overlay/AnimationStatic.php
  VideoTranscoder/src/V1beta1/Overlay/Image.php
  VideoTranscoder/src/V1beta1/PreprocessingConfig.php
  VideoTranscoder/src/V1beta1/PreprocessingConfig/Audio.php
  VideoTranscoder/src/V1beta1/PreprocessingConfig/Crop.php
  VideoTranscoder/src/V1beta1/PreprocessingConfig/Pad.php
  VideoTranscoder/src/V1beta1/PreprocessingConfig_Crop.php
  VideoTranscoder/src/V1beta1/PreprocessingConfig_Pad.php
  VideoTranscoder/src/V1beta1/SegmentSettings.php
  VideoTranscoder/src/V1beta1/SpriteSheet.php
  VideoTranscoder/src/V1beta1/VideoStream.php
  VideoTranscoder/src/V1beta1/resources/transcoder_service_rest_client_config.php
  VideoTranscoder/synth.metadata
  VideoTranscoder/tests/Unit/V1beta1/TranscoderServiceClientTest.php
Labels: cla: yes, context: full

#4307 feat: introduce clientCertSource option
  Trace/src/V2/Gapic/TraceServiceGapicClient.php
  Trace/synth.metadata
Labels: cla: yes, context: partial

#4306 feat: introduce clientCertSource option
  Tpu/src/V1/Gapic/TpuGapicClient.php
  Tpu/synth.metadata
Labels: cla: yes, context: full

#4311 feat: introduce clientCertSource option
  WebRisk/src/V1/Gapic/WebRiskServiceGapicClient.php
  WebRisk/src/V1beta1/Gapic/WebRiskServiceV1Beta1GapicClient.php
  WebRisk/synth.metadata
Labels: cla: yes, context: partial

#4305 feat: introduce clientCertSource option
  TextToSpeech/src/V1/Gapic/TextToSpeechGapicClient.php
  TextToSpeech/synth.metadata
Labels: cla: yes, context: full

#4304 feat: introduce clientCertSource option
  Spanner/src/Admin/Database/V1/Gapic/DatabaseAdminGapicClient.php
  Spanner/src/Admin/Instance/V1/Gapic/InstanceAdminGapicClient.php
  Spanner/src/V1/Gapic/SpannerGapicClient.php
  Spanner/synth.metadata
Labels: cla: yes, context: full

#4303 feat: introduce clientCertSource option
  ServiceUsage/src/V1/Gapic/ServiceUsageGapicClient.php
  ServiceUsage/synth.metadata
Labels: cla: yes, context: full

#4302 feat: introduce clientCertSource option
  ServiceManagement/src/V1/Gapic/ServiceManagerGapicClient.php
  ServiceManagement/synth.metadata
Labels: cla: yes, context: full

#4301 feat: introduce clientCertSource option
  ServiceDirectory/src/V1/Gapic/LookupServiceGapicClient.php
  ServiceDirectory/src/V1/Gapic/RegistrationServiceGapicClient.php
  ServiceDirectory/src/V1beta1/Gapic/LookupServiceGapicClient.php
  ServiceDirectory/src/V1beta1/Gapic/RegistrationServiceGapicClient.php
  ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#4300 feat: introduce clientCertSource option
  ServiceControl/src/V1/Gapic/QuotaControllerGapicClient.php
  ServiceControl/src/V1/Gapic/ServiceControllerGapicClient.php
  ServiceControl/synth.metadata
Labels: cla: yes, context: full

#4299 [ResourceManager] chore: release gapic-generator-php v1.0.3
  ResourceManager/src/V3/Gapic/FoldersGapicClient.php
  ResourceManager/src/V3/Gapic/OrganizationsGapicClient.php
  ResourceManager/src/V3/Gapic/ProjectsGapicClient.php
  ResourceManager/src/V3/Gapic/TagBindingsGapicClient.php
  ResourceManager/src/V3/Gapic/TagKeysGapicClient.php
  ResourceManager/src/V3/Gapic/TagValuesGapicClient.php
  ResourceManager/synth.metadata
Labels: cla: yes, context: full

#4298 feat: introduce clientCertSource option
  Redis/src/V1/Gapic/CloudRedisGapicClient.php
  Redis/src/V1beta1/Gapic/CloudRedisGapicClient.php
  Redis/synth.metadata
Labels: cla: yes, context: full

#4296 feat: introduce clientCertSource option
  Recommender/src/V1/Gapic/RecommenderGapicClient.php
  Recommender/synth.metadata
Labels: cla: yes, context: full

#4295 feat: introduce clientCertSource option
  RecommendationEngine/src/V1beta1/Gapic/CatalogServiceGapicClient.php
  RecommendationEngine/src/V1beta1/Gapic/PredictionApiKeyRegistryGapicClient.php
  RecommendationEngine/src/V1beta1/Gapic/PredictionServiceGapicClient.php
  RecommendationEngine/src/V1beta1/Gapic/UserEventServiceGapicClient.php
  RecommendationEngine/synth.metadata
Labels: cla: yes, context: full

#4293 feat: introduce clientCertSource option
  Profiler/src/V2/Gapic/ProfilerServiceGapicClient.php
  Profiler/synth.metadata
Labels: cla: yes, context: full

#4290 feat: introduce clientCertSource option
  OsLogin/src/V1/Gapic/OsLoginServiceGapicClient.php
  OsLogin/src/V1beta/Gapic/OsLoginServiceGapicClient.php
  OsLogin/synth.metadata
Labels: cla: yes, context: full

#4289 [OsConfig] chore: release gapic-generator-php v1.0.3
  OsConfig/src/V1/Gapic/OsConfigServiceGapicClient.php
  OsConfig/synth.metadata
Labels: cla: yes, context: full

#4288 feat: introduce clientCertSource option
  OrgPolicy/src/V2/Gapic/OrgPolicyGapicClient.php
  OrgPolicy/synth.metadata
Labels: cla: yes, context: full

#4287 feat: introduce clientCertSource option
  Notebooks/src/V1beta1/Gapic/NotebookServiceGapicClient.php
  Notebooks/synth.metadata
Labels: cla: yes, context: full

#4286 feat: introduce clientCertSource option
  Memcache/src/V1/Gapic/CloudMemcacheGapicClient.php
  Memcache/src/V1beta2/Gapic/CloudMemcacheGapicClient.php
  Memcache/synth.metadata
Labels: cla: yes, context: full

#4284 feat: introduce clientCertSource option
  LifeSciences/src/V2beta/Gapic/WorkflowsServiceV2BetaGapicClient.php
  LifeSciences/synth.metadata
Labels: cla: yes, context: full

#4294 feat: introduce clientCertSource option
  RecaptchaEnterprise/src/V1/Gapic/RecaptchaEnterpriseServiceGapicClient.php
  RecaptchaEnterprise/synth.metadata
Labels: cla: yes, context: full

#4292 feat: introduce clientCertSource option
  PrivateCatalog/src/V1beta1/Gapic/PrivateCatalogGapicClient.php
  PrivateCatalog/synth.metadata
Labels: cla: yes, context: full

#4291 feat: introduce clientCertSource option
  PolicyTroubleshooter/src/V1/Gapic/IamCheckerGapicClient.php
  PolicyTroubleshooter/synth.metadata
Labels: cla: yes, context: full

#4285 feat: introduce clientCertSource option
  MediaTranslation/src/V1beta1/Gapic/SpeechTranslationServiceGapicClient.php
  MediaTranslation/synth.metadata
Labels: cla: yes, context: full

#4279 feat: introduce clientCertSource option
  Dms/src/V1/Gapic/DataMigrationServiceGapicClient.php
  Dms/synth.metadata
Labels: cla: yes, context: full

#4278 feat: introduce clientCertSource option
  Dlp/src/V2/Gapic/DlpServiceGapicClient.php
  Dlp/synth.metadata
Labels: cla: yes, context: partial

#4277 feat: introduce clientCertSource option
  Dialogflow/src/V2/Gapic/AgentsGapicClient.php
  Dialogflow/src/V2/Gapic/AnswerRecordsGapicClient.php
  Dialogflow/src/V2/Gapic/ContextsGapicClient.php
  Dialogflow/src/V2/Gapic/ConversationProfilesGapicClient.php
  Dialogflow/src/V2/Gapic/ConversationsGapicClient.php
  Dialogflow/src/V2/Gapic/DocumentsGapicClient.php
  Dialogflow/src/V2/Gapic/EntityTypesGapicClient.php
  Dialogflow/src/V2/Gapic/EnvironmentsGapicClient.php
  Dialogflow/src/V2/Gapic/FulfillmentsGapicClient.php
  Dialogflow/src/V2/Gapic/IntentsGapicClient.php
  Dialogflow/src/V2/Gapic/KnowledgeBasesGapicClient.php
  Dialogflow/src/V2/Gapic/ParticipantsGapicClient.php
  Dialogflow/src/V2/Gapic/SessionEntityTypesGapicClient.php
  Dialogflow/src/V2/Gapic/SessionsGapicClient.php
  Dialogflow/src/V2/Gapic/VersionsGapicClient.php
  Dialogflow/synth.metadata
Labels: cla: yes, context: full

#4275 feat: introduce clientCertSource option
  DatastoreAdmin/src/V1/Gapic/DatastoreAdminGapicClient.php
  DatastoreAdmin/synth.metadata
Labels: cla: yes, context: full

#4274 [DataprocMetastore] chore: release gapic-generator-php v1.0.3
  DataprocMetastore/src/V1/Gapic/DataprocMetastoreGapicClient.php
  DataprocMetastore/src/V1alpha/Gapic/DataprocMetastoreGapicClient.php
  DataprocMetastore/src/V1beta/Gapic/DataprocMetastoreGapicClient.php
  DataprocMetastore/synth.metadata
Labels: cla: yes, context: full

#4268 feat: introduce clientCertSource option
  BigQueryReservation/src/V1/Gapic/ReservationServiceGapicClient.php
  BigQueryReservation/synth.metadata
Labels: cla: yes, context: full

#4265 feat: introduce clientCertSource option
  AppEngineAdmin/src/V1/Gapic/ApplicationsGapicClient.php
  AppEngineAdmin/src/V1/Gapic/AuthorizedCertificatesGapicClient.php
  AppEngineAdmin/src/V1/Gapic/AuthorizedDomainsGapicClient.php
  AppEngineAdmin/src/V1/Gapic/DomainMappingsGapicClient.php
  AppEngineAdmin/src/V1/Gapic/FirewallGapicClient.php
  AppEngineAdmin/src/V1/Gapic/InstancesGapicClient.php
  AppEngineAdmin/src/V1/Gapic/ServicesGapicClient.php
  AppEngineAdmin/src/V1/Gapic/VersionsGapicClient.php
  AppEngineAdmin/synth.metadata
Labels: cla: yes, context: full

#4264 feat: introduce clientCertSource option
  ApigeeConnect/src/V1/Gapic/ConnectionServiceGapicClient.php
  ApigeeConnect/src/V1/Gapic/TetherGapicClient.php
  ApigeeConnect/synth.metadata
Labels: cla: yes, context: full

#4263 feat: introduce clientCertSource option
  AnalyticsAdmin/src/V1alpha/Gapic/AnalyticsAdminServiceGapicClient.php
  AnalyticsAdmin/synth.metadata
Labels: cla: yes, context: full

#4283 feat: introduce clientCertSource option
  Language/src/V1/Gapic/LanguageServiceGapicClient.php
  Language/src/V1beta2/Gapic/LanguageServiceGapicClient.php
  Language/synth.metadata
Labels: cla: yes, context: partial

#4282 feat: introduce clientCertSource option
  Iot/src/V1/Gapic/DeviceManagerGapicClient.php
  Iot/synth.metadata
Labels: cla: yes, context: full

#4281 feat: introduce clientCertSource option
  GkeHub/src/V1beta1/Gapic/GkeHubMembershipServiceGapicClient.php
  GkeHub/synth.metadata
Labels: cla: yes, context: full

#4280 feat: introduce clientCertSource option
  EssentialContacts/src/V1/Gapic/EssentialContactsServiceGapicClient.php
  EssentialContacts/synth.metadata
Labels: cla: yes, context: full

#4276 feat: introduce clientCertSource option
  Debugger/src/V2/Gapic/Controller2GapicClient.php
  Debugger/src/V2/Gapic/Debugger2GapicClient.php
  Debugger/synth.metadata
Labels: cla: yes, context: full

#4273 feat: introduce clientCertSource option
  Channel/src/V1/Gapic/CloudChannelServiceGapicClient.php
  Channel/synth.metadata
Labels: cla: yes, context: partial

#4272 feat: introduce clientCertSource option
  BinaryAuthorization/src/V1beta1/Gapic/BinauthzManagementServiceV1Beta1GapicClient.php
  BinaryAuthorization/synth.metadata
Labels: cla: yes, context: full

#4271 feat: introduce clientCertSource option
  BillingBudgets/src/V1/Gapic/BudgetServiceGapicClient.php
  BillingBudgets/src/V1beta1/Gapic/BudgetServiceGapicClient.php
  BillingBudgets/synth.metadata
Labels: cla: yes, context: full

#4270 feat: introduce clientCertSource option
  Billing/src/V1/Gapic/CloudBillingGapicClient.php
  Billing/src/V1/Gapic/CloudCatalogGapicClient.php
  Billing/synth.metadata
Labels: cla: yes, context: partial

#4269 feat: introduce clientCertSource option
  BigQueryStorage/src/V1/Gapic/BigQueryReadGapicClient.php
  BigQueryStorage/synth.metadata
Labels: cla: yes, context: partial

#4241 feat: allow updating security group on existing clusters
  Container/metadata/V1/ClusterService.php
  Container/src/V1/ClusterUpdate.php
  Container/synth.metadata
Labels: cla: yes, context: full

#4255 feat: add finding_class and indicator fields in Finding
  SecurityCenter/metadata/V1/Finding.php
  SecurityCenter/metadata/V1/Indicator.php
  SecurityCenter/src/V1/CreateFindingRequest.php
  SecurityCenter/src/V1/CreateNotificationConfigRequest.php
  SecurityCenter/src/V1/CreateSourceRequest.php
  SecurityCenter/src/V1/Finding.php
  SecurityCenter/src/V1/Finding/FindingClass.php
  SecurityCenter/src/V1/Finding_FindingClass.php
  SecurityCenter/src/V1/Gapic/SecurityCenterGapicClient.php
  SecurityCenter/src/V1/GetOrganizationSettingsRequest.php
  SecurityCenter/src/V1/GroupAssetsRequest.php
  SecurityCenter/src/V1/GroupFindingsRequest.php
  SecurityCenter/src/V1/Indicator.php
  SecurityCenter/src/V1/ListSourcesRequest.php
  SecurityCenter/src/V1/RunAssetDiscoveryRequest.php
  SecurityCenter/src/V1/UpdateFindingRequest.php
  SecurityCenter/synth.metadata
Labels: cla: yes, context: full

#4266 feat: introduce clientCertSource option
  AutoMl/src/V1/Gapic/AutoMlGapicClient.php
  AutoMl/src/V1/Gapic/PredictionServiceGapicClient.php
  AutoMl/src/V1beta1/Gapic/AutoMlGapicClient.php
  AutoMl/src/V1beta1/Gapic/PredictionServiceGapicClient.php
  AutoMl/synth.metadata
Labels: cla: yes, context: full

#4262 feat: introduce clientCertSource option
  AccessApproval/src/V1/Gapic/AccessApprovalGapicClient.php
  AccessApproval/synth.metadata
Labels: cla: yes, kokoro:force-run, context: full

#4259 feat: introduce filter to customize the output of ListSecrets/ListSecretVersions calls
  SecretManager/metadata/V1/Service.php
  SecretManager/src/V1/Gapic/SecretManagerServiceGapicClient.php
  SecretManager/src/V1/ListSecretVersionsRequest.php
  SecretManager/src/V1/ListSecretsRequest.php
  SecretManager/synth.metadata
Labels: cla: yes, context: full

#4260 feat: Add EU Regions And Support compliance regime
  AssuredWorkloads/metadata/V1Beta1/AssuredworkloadsV1Beta1.php
  AssuredWorkloads/src/V1beta1/Workload/ComplianceRegime.php
  AssuredWorkloads/synth.metadata
Labels: cla: yes, context: full

#4240 feat: add `minute_ranges` field to `RunRealtimeReportRequest` object
  AnalyticsData/metadata/V1Beta/AnalyticsDataApi.php
  AnalyticsData/metadata/V1Beta/Data.php
  AnalyticsData/src/V1beta/Dimension.php
  AnalyticsData/src/V1beta/Gapic/BetaAnalyticsDataGapicClient.php
  AnalyticsData/src/V1beta/MinuteRange.php
  AnalyticsData/src/V1beta/RunRealtimeReportRequest.php
  AnalyticsData/synth.metadata
Labels: cla: yes, context: full

#4397 chore: release gapic-generator-php v1.0.5
  Channel/src/V1/resources/cloud_channel_service_rest_client_config.php
  Channel/synth.metadata
Labels: cla: yes, context: full

#4396 chore: generate with gapic-generator-php v1.0.5
  BinaryAuthorization/src/V1beta1/Policy/GlobalPolicyEvaluationMode.php
  BinaryAuthorization/src/V1beta1/resources/binauthz_management_service_v1_beta1_rest_client_config.php
  BinaryAuthorization/synth.metadata
Labels: cla: yes, context: full

#4398 feat: introduce clientCertSource option
  Container/src/V1/Gapic/ClusterManagerGapicClient.php
  Container/synth.metadata
Labels: cla: yes, context: full

#4332 feat: introduce clientCertSource option
  AnalyticsData/src/V1alpha/Gapic/AlphaAnalyticsDataGapicClient.php
  AnalyticsData/src/V1beta/Gapic/BetaAnalyticsDataGapicClient.php
  AnalyticsData/synth.metadata
Labels: cla: yes, context: full

#4422 feat: introduce clientCertSource option
  SecretManager/src/V1/Gapic/SecretManagerServiceGapicClient.php
  SecretManager/src/V1/resources/secret_manager_service_rest_client_config.php
  SecretManager/src/V1beta1/Gapic/SecretManagerServiceGapicClient.php
  SecretManager/src/V1beta1/resources/secret_manager_service_rest_client_config.php
  SecretManager/synth.metadata
Labels: cla: yes, context: full

#4419 chore: generate with gapic-generator-php v1.0.5
  ResourceManager/src/V3/resources/folders_rest_client_config.php
  ResourceManager/src/V3/resources/projects_rest_client_config.php
  ResourceManager/src/V3/resources/tag_bindings_rest_client_config.php
  ResourceManager/src/V3/resources/tag_keys_rest_client_config.php
  ResourceManager/src/V3/resources/tag_values_rest_client_config.php
  ResourceManager/synth.metadata
Labels: cla: yes, context: full

#4418 chore: generate with gapic-generator-php v1.0.5
  Redis/src/V1/resources/cloud_redis_rest_client_config.php
  Redis/src/V1beta1/resources/cloud_redis_rest_client_config.php
  Redis/synth.metadata
Labels: cla: yes, context: full

#4417 feat: introduce message retention duration
  PubSub/metadata/V1/Pubsub.php
  PubSub/src/V1/Gapic/PublisherGapicClient.php
  PubSub/src/V1/Gapic/SchemaServiceGapicClient.php
  PubSub/src/V1/Gapic/SubscriberGapicClient.php
  PubSub/src/V1/Subscription.php
  PubSub/src/V1/Topic.php
  PubSub/src/V1/ValidateMessageResponse.php
  PubSub/src/V1/ValidateSchemaResponse.php
  PubSub/src/V1/resources/publisher_rest_client_config.php
  PubSub/src/V1/resources/schema_service_rest_client_config.php
  PubSub/src/V1/resources/subscriber_rest_client_config.php
  PubSub/synth.metadata
Labels: cla: yes, context: full

#4414 chore: generate with gapic-generator-php v1.0.5
  Notebooks/src/V1beta1/resources/notebook_service_rest_client_config.php
  Notebooks/synth.metadata
Labels: cla: yes, context: full

#4411 chore: generate with gapic-generator-php v1.0.5
  Memcache/src/V1/resources/cloud_memcache_rest_client_config.php
  Memcache/src/V1beta2/resources/cloud_memcache_rest_client_config.php
  Memcache/synth.metadata
Labels: cla: yes, context: full

#4410 chore: generate with gapic-generator-php v1.0.5
  Iot/src/V1/resources/device_manager_rest_client_config.php
  Iot/synth.metadata
Labels: cla: yes, context: full

#4404 chore: generate with gapic-generator-php v1.0.5
  Dms/src/V1/resources/data_migration_service_rest_client_config.php
  Dms/synth.metadata
Labels: cla: yes, context: full

#4402 chore: generate with gapic-generator-php v1.0.5
  Debugger/src/V2/resources/debugger2_rest_client_config.php
  Debugger/synth.metadata
Labels: cla: yes, context: full

#4408 feat: Add request_id under `DeleteMembershipRequest` and `UpdateMembembershipRequest`
  GkeHub/metadata/V1Beta1/Membership.php
  GkeHub/src/V1beta1/CreateMembershipRequest.php
  GkeHub/src/V1beta1/DeleteMembershipRequest.php
  GkeHub/src/V1beta1/Gapic/GkeHubMembershipServiceGapicClient.php
  GkeHub/src/V1beta1/GkeCluster.php
  GkeHub/src/V1beta1/GkeHubMembershipServiceGrpcClient.php
  GkeHub/src/V1beta1/Membership.php
  GkeHub/src/V1beta1/MembershipEndpoint.php
  GkeHub/src/V1beta1/MultiCloudCluster.php
  GkeHub/src/V1beta1/OnPremCluster.php
  GkeHub/src/V1beta1/UpdateMembershipRequest.php
  GkeHub/src/V1beta1/resources/gke_hub_membership_service_rest_client_config.php
  GkeHub/synth.metadata
  GkeHub/tests/Unit/V1beta1/GkeHubMembershipServiceClientTest.php
Labels: cla: yes, context: full

#4423 feat: introduce clientCertSource option
  SecurityCenter/src/V1/Gapic/SecurityCenterGapicClient.php
  SecurityCenter/src/V1/resources/security_center_rest_client_config.php
  SecurityCenter/src/V1p1beta1/Gapic/SecurityCenterGapicClient.php
  SecurityCenter/src/V1p1beta1/resources/security_center_rest_client_config.php
  SecurityCenter/synth.metadata
Labels: cla: yes, context: full

#4426 chore: generate with gapic-generator-php v1.0.5
  Spanner/src/Admin/Database/V1/resources/database_admin_rest_client_config.php
  Spanner/synth.metadata
Labels: cla: yes, context: full

#4425 chore: generate with gapic-generator-php v1.0.5
  ServiceManagement/src/V1/resources/service_manager_rest_client_config.php
  ServiceManagement/synth.metadata
Labels: cla: yes, context: full

#4424 chore: generate with gapic-generator-php v1.0.5
  ServiceDirectory/src/V1/resources/registration_service_rest_client_config.php
  ServiceDirectory/src/V1beta1/resources/registration_service_rest_client_config.php
  ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#4267 feat: introduce clientCertSource option
  BigQueryConnection/src/V1/Gapic/ConnectionServiceGapicClient.php
  BigQueryConnection/synth.metadata
Labels: cla: yes, context: full

#4399 feat: introduce datafusion client
  DataFusion/metadata/V1/Datafusion.php
  DataFusion/src/V1/Accelerator.php
  DataFusion/src/V1/Accelerator/AcceleratorType.php
  DataFusion/src/V1/Accelerator/State.php
  DataFusion/src/V1/Accelerator_AcceleratorType.php
  DataFusion/src/V1/Accelerator_State.php
  DataFusion/src/V1/CreateInstanceRequest.php
  DataFusion/src/V1/CryptoKeyConfig.php
  DataFusion/src/V1/DataFusionClient.php
  DataFusion/src/V1/DataFusionGrpcClient.php
  DataFusion/src/V1/DeleteInstanceRequest.php
  DataFusion/src/V1/Gapic/DataFusionGapicClient.php
  DataFusion/src/V1/GetInstanceRequest.php
  DataFusion/src/V1/Instance.php
  DataFusion/src/V1/Instance/State.php
  DataFusion/src/V1/Instance/Type.php
  DataFusion/src/V1/Instance_State.php
  DataFusion/src/V1/Instance_Type.php
  DataFusion/src/V1/ListAvailableVersionsRequest.php
  DataFusion/src/V1/ListAvailableVersionsResponse.php
  DataFusion/src/V1/ListInstancesRequest.php
  DataFusion/src/V1/ListInstancesResponse.php
  DataFusion/src/V1/NetworkConfig.php
  DataFusion/src/V1/OperationMetadata.php
  DataFusion/src/V1/RestartInstanceRequest.php
  DataFusion/src/V1/UpdateInstanceRequest.php
  DataFusion/src/V1/Version.php
  DataFusion/src/V1/gapic_metadata.json
  DataFusion/src/V1/resources/data_fusion_client_config.json
  DataFusion/src/V1/resources/data_fusion_descriptor_config.php
  DataFusion/src/V1/resources/data_fusion_rest_client_config.php
  DataFusion/synth.metadata
  DataFusion/tests/Unit/V1/DataFusionClientTest.php
Labels: cla: yes, context: none

#4430 chore: generate with gapic-generator-php v1.0.5
  BigQueryConnection/src/V1/resources/connection_service_rest_client_config.php
  BigQueryConnection/synth.metadata
Labels: cla: yes, context: full

#4428 feat: introduce storage transfer client
  StorageTransfer/metadata/V1/Transfer.php
  StorageTransfer/metadata/V1/TransferTypes.php
  StorageTransfer/src/V1/AwsAccessKey.php
  StorageTransfer/src/V1/AwsS3Data.php
  StorageTransfer/src/V1/AzureBlobStorageData.php
  StorageTransfer/src/V1/AzureCredentials.php
  StorageTransfer/src/V1/CreateTransferJobRequest.php
  StorageTransfer/src/V1/ErrorLogEntry.php
  StorageTransfer/src/V1/ErrorSummary.php
  StorageTransfer/src/V1/Gapic/StorageTransferServiceGapicClient.php
  StorageTransfer/src/V1/GcsData.php
  StorageTransfer/src/V1/GetGoogleServiceAccountRequest.php
  StorageTransfer/src/V1/GetTransferJobRequest.php
  StorageTransfer/src/V1/GoogleServiceAccount.php
  StorageTransfer/src/V1/HttpData.php
  StorageTransfer/src/V1/ListTransferJobsRequest.php
  StorageTransfer/src/V1/ListTransferJobsResponse.php
  StorageTransfer/src/V1/NotificationConfig.php
  StorageTransfer/src/V1/NotificationConfig/EventType.php
  StorageTransfer/src/V1/NotificationConfig/PayloadFormat.php
  StorageTransfer/src/V1/NotificationConfig_EventType.php
  StorageTransfer/src/V1/NotificationConfig_PayloadFormat.php
  StorageTransfer/src/V1/ObjectConditions.php
  StorageTransfer/src/V1/PauseTransferOperationRequest.php
  StorageTransfer/src/V1/ResumeTransferOperationRequest.php
  StorageTransfer/src/V1/RunTransferJobRequest.php
  StorageTransfer/src/V1/Schedule.php
  StorageTransfer/src/V1/StorageTransferServiceClient.php
  StorageTransfer/src/V1/StorageTransferServiceGrpcClient.php
  StorageTransfer/src/V1/TransferCounters.php
  StorageTransfer/src/V1/TransferJob.php
  StorageTransfer/src/V1/TransferJob/Status.php
  StorageTransfer/src/V1/TransferJob_Status.php
  StorageTransfer/src/V1/TransferOperation.php
  StorageTransfer/src/V1/TransferOperation/Status.php
  StorageTransfer/src/V1/TransferOperation_Status.php
  StorageTransfer/src/V1/TransferOptions.php
  StorageTransfer/src/V1/TransferSpec.php
  StorageTransfer/src/V1/UpdateTransferJobRequest.php
  StorageTransfer/src/V1/gapic_metadata.json
  StorageTransfer/src/V1/resources/storage_transfer_service_client_config.json
  StorageTransfer/src/V1/resources/storage_transfer_service_descriptor_config.php
  StorageTransfer/src/V1/resources/storage_transfer_service_rest_client_config.php
  StorageTransfer/synth.metadata
  StorageTransfer/tests/Unit/V1/StorageTransferServiceClientTest.php
Labels: cla: yes, context: none

#4415 feat: introduce orchestration airflow client
  OrchestrationAirflow/metadata/V1/Environments.php
  OrchestrationAirflow/metadata/V1/ImageVersions.php
  OrchestrationAirflow/metadata/V1/Operations.php
  OrchestrationAirflow/src/V1/CheckUpgradeResponse.php
  OrchestrationAirflow/src/V1/CheckUpgradeResponse/ConflictResult.php
  OrchestrationAirflow/src/V1/CheckUpgradeResponse_ConflictResult.php
  OrchestrationAirflow/src/V1/CreateEnvironmentRequest.php
  OrchestrationAirflow/src/V1/DatabaseConfig.php
  OrchestrationAirflow/src/V1/DeleteEnvironmentRequest.php
  OrchestrationAirflow/src/V1/EncryptionConfig.php
  OrchestrationAirflow/src/V1/Environment.php
  OrchestrationAirflow/src/V1/Environment/State.php
  OrchestrationAirflow/src/V1/EnvironmentConfig.php
  OrchestrationAirflow/src/V1/Environment_State.php
  OrchestrationAirflow/src/V1/EnvironmentsClient.php
  OrchestrationAirflow/src/V1/EnvironmentsGrpcClient.php
  OrchestrationAirflow/src/V1/Gapic/EnvironmentsGapicClient.php
  OrchestrationAirflow/src/V1/Gapic/ImageVersionsGapicClient.php
  OrchestrationAirflow/src/V1/GetEnvironmentRequest.php
  OrchestrationAirflow/src/V1/IPAllocationPolicy.php
  OrchestrationAirflow/src/V1/ImageVersion.php
  OrchestrationAirflow/src/V1/ImageVersionsClient.php
  OrchestrationAirflow/src/V1/ImageVersionsGrpcClient.php
  OrchestrationAirflow/src/V1/ListEnvironmentsRequest.php
  OrchestrationAirflow/src/V1/ListEnvironmentsResponse.php
  OrchestrationAirflow/src/V1/ListImageVersionsRequest.php
  OrchestrationAirflow/src/V1/ListImageVersionsResponse.php
  OrchestrationAirflow/src/V1/NodeConfig.php
  OrchestrationAirflow/src/V1/OperationMetadata.php
  OrchestrationAirflow/src/V1/OperationMetadata/State.php
  OrchestrationAirflow/src/V1/OperationMetadata/Type.php
  OrchestrationAirflow/src/V1/OperationMetadata_State.php
  OrchestrationAirflow/src/V1/OperationMetadata_Type.php
  OrchestrationAirflow/src/V1/PrivateClusterConfig.php
  OrchestrationAirflow/src/V1/PrivateEnvironmentConfig.php
  OrchestrationAirflow/src/V1/SoftwareConfig.php
  OrchestrationAirflow/src/V1/UpdateEnvironmentRequest.php
  OrchestrationAirflow/src/V1/WebServerConfig.php
  OrchestrationAirflow/src/V1/WebServerNetworkAccessControl.php
  OrchestrationAirflow/src/V1/WebServerNetworkAccessControl/AllowedIpRange.php
  OrchestrationAirflow/src/V1/WebServerNetworkAccessControl_AllowedIpRange.php
  OrchestrationAirflow/src/V1/gapic_metadata.json
  OrchestrationAirflow/src/V1/resources/environments_client_config.json
  OrchestrationAirflow/src/V1/resources/environments_descriptor_config.php
  OrchestrationAirflow/src/V1/resources/environments_rest_client_config.php
  OrchestrationAirflow/src/V1/resources/image_versions_client_config.json
  OrchestrationAirflow/src/V1/resources/image_versions_descriptor_config.php
  OrchestrationAirflow/src/V1/resources/image_versions_rest_client_config.php
  OrchestrationAirflow/synth.metadata
  OrchestrationAirflow/tests/Unit/V1/EnvironmentsClientTest.php
  OrchestrationAirflow/tests/Unit/V1/ImageVersionsClientTest.php
Labels: cla: yes, context: none

#4412 feat: introduce network connectivity client
  NetworkConnectivity/metadata/V1/Common.php
  NetworkConnectivity/metadata/V1/Hub.php
  NetworkConnectivity/src/V1/CreateHubRequest.php
  NetworkConnectivity/src/V1/CreateSpokeRequest.php
  NetworkConnectivity/src/V1/DeleteHubRequest.php
  NetworkConnectivity/src/V1/DeleteSpokeRequest.php
  NetworkConnectivity/src/V1/Gapic/HubServiceGapicClient.php
  NetworkConnectivity/src/V1/GetHubRequest.php
  NetworkConnectivity/src/V1/GetSpokeRequest.php
  NetworkConnectivity/src/V1/Hub.php
  NetworkConnectivity/src/V1/HubServiceClient.php
  NetworkConnectivity/src/V1/HubServiceGrpcClient.php
  NetworkConnectivity/src/V1/LinkedInterconnectAttachments.php
  NetworkConnectivity/src/V1/LinkedRouterApplianceInstances.php
  NetworkConnectivity/src/V1/LinkedVpnTunnels.php
  NetworkConnectivity/src/V1/ListHubsRequest.php
  NetworkConnectivity/src/V1/ListHubsResponse.php
  NetworkConnectivity/src/V1/ListSpokesRequest.php
  NetworkConnectivity/src/V1/ListSpokesResponse.php
  NetworkConnectivity/src/V1/OperationMetadata.php
  NetworkConnectivity/src/V1/RouterApplianceInstance.php
  NetworkConnectivity/src/V1/RoutingVPC.php
  NetworkConnectivity/src/V1/Spoke.php
  NetworkConnectivity/src/V1/State.php
  NetworkConnectivity/src/V1/UpdateHubRequest.php
  NetworkConnectivity/src/V1/UpdateSpokeRequest.php
  NetworkConnectivity/src/V1/gapic_metadata.json
  NetworkConnectivity/src/V1/resources/hub_service_client_config.json
  NetworkConnectivity/src/V1/resources/hub_service_descriptor_config.php
  NetworkConnectivity/src/V1/resources/hub_service_rest_client_config.php
  NetworkConnectivity/synth.metadata
  NetworkConnectivity/tests/Unit/V1/HubServiceClientTest.php
Labels: cla: yes, context: none

#4409 feat: introduce iap client
  Iap/metadata/V1/Service.php
  Iap/src/V1/AccessDeniedPageSettings.php
  Iap/src/V1/AccessSettings.php
  Iap/src/V1/ApplicationSettings.php
  Iap/src/V1/Brand.php
  Iap/src/V1/CorsSettings.php
  Iap/src/V1/CreateBrandRequest.php
  Iap/src/V1/CreateIdentityAwareProxyClientRequest.php
  Iap/src/V1/CsmSettings.php
  Iap/src/V1/DeleteIdentityAwareProxyClientRequest.php
  Iap/src/V1/Gapic/IdentityAwareProxyAdminServiceGapicClient.php
  Iap/src/V1/Gapic/IdentityAwareProxyOAuthServiceGapicClient.php
  Iap/src/V1/GcipSettings.php
  Iap/src/V1/GetBrandRequest.php
  Iap/src/V1/GetIapSettingsRequest.php
  Iap/src/V1/GetIdentityAwareProxyClientRequest.php
  Iap/src/V1/IapSettings.php
  Iap/src/V1/IdentityAwareProxyAdminServiceClient.php
  Iap/src/V1/IdentityAwareProxyAdminServiceGrpcClient.php
  Iap/src/V1/IdentityAwareProxyClient.php
  Iap/src/V1/IdentityAwareProxyOAuthServiceClient.php
  Iap/src/V1/IdentityAwareProxyOAuthServiceGrpcClient.php
  Iap/src/V1/ListBrandsRequest.php
  Iap/src/V1/ListBrandsResponse.php
  Iap/src/V1/ListIdentityAwareProxyClientsRequest.php
  Iap/src/V1/ListIdentityAwareProxyClientsResponse.php
  Iap/src/V1/OAuthSettings.php
  Iap/src/V1/ResetIdentityAwareProxyClientSecretRequest.php
  Iap/src/V1/UpdateIapSettingsRequest.php
  Iap/src/V1/gapic_metadata.json
  Iap/src/V1/resources/identity_aware_proxy_admin_service_client_config.json
  Iap/src/V1/resources/identity_aware_proxy_admin_service_descriptor_config.php
  Iap/src/V1/resources/identity_aware_proxy_admin_service_rest_client_config.php
  Iap/src/V1/resources/identity_aware_proxy_o_auth_service_client_config.json
  Iap/src/V1/resources/identity_aware_proxy_o_auth_service_descriptor_config.php
  Iap/src/V1/resources/identity_aware_proxy_o_auth_service_rest_client_config.php
  Iap/synth.metadata
  Iap/tests/Unit/V1/IdentityAwareProxyAdminServiceClientTest.php
  Iap/tests/Unit/V1/IdentityAwareProxyOAuthServiceClientTest.php
Labels: cla: yes, context: none
