Repository googleapis/google-cloud-php, pull requests merged in 2021-11, with the labels that each got.

#4694 chore: update owlbot lock
  .github/.OwlBot.lock.yaml
Labels: cla: yes

#4677 chore: update protobuf from 3.15.3 to 3.18.1
  Vision/src/V1/AnnotateFileRequest.php
  Vision/src/V1/AnnotateFileResponse.php
  Vision/src/V1/AnnotateImageRequest.php
  Vision/src/V1/AnnotateImageResponse.php
  Vision/src/V1/AsyncAnnotateFileRequest.php
  Vision/src/V1/AsyncAnnotateFileResponse.php
  Vision/src/V1/AsyncBatchAnnotateImagesRequest.php
  Vision/src/V1/AsyncBatchAnnotateImagesResponse.php
  Vision/src/V1/BatchOperationMetadata.php
  Vision/src/V1/Block.php
  Vision/src/V1/ColorInfo.php
  Vision/src/V1/CreateProductRequest.php
  Vision/src/V1/CreateProductSetRequest.php
  Vision/src/V1/CreateReferenceImageRequest.php
  Vision/src/V1/CropHint.php
  Vision/src/V1/EntityAnnotation.php
  Vision/src/V1/FaceAnnotation.php
  Vision/src/V1/FaceAnnotation/Landmark.php
  Vision/src/V1/Image.php
  Vision/src/V1/ImageContext.php
  Vision/src/V1/ImageProperties.php
  Vision/src/V1/ImportProductSetsRequest.php
  Vision/src/V1/InputConfig.php
  Vision/src/V1/LatLongRect.php
  Vision/src/V1/LocalizedObjectAnnotation.php
  Vision/src/V1/LocationInfo.php
  Vision/src/V1/OperationMetadata.php
  Vision/src/V1/OutputConfig.php
  Vision/src/V1/Page.php
  Vision/src/V1/Paragraph.php
  Vision/src/V1/ProductSearchParams.php
  Vision/src/V1/ProductSearchResults.php
  Vision/src/V1/ProductSearchResults/GroupedResult.php
  Vision/src/V1/ProductSearchResults/Result.php
  Vision/src/V1/ProductSet.php
  Vision/src/V1/Symbol.php
  Vision/src/V1/TextAnnotation/TextProperty.php
  Vision/src/V1/UpdateProductRequest.php
  Vision/src/V1/UpdateProductSetRequest.php
  Vision/src/V1/Word.php
  Vision/synth.metadata
Labels: cla: yes, context: full

#4675 [Trace] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  Trace/src/V2/Module.php
  Trace/src/V2/Span.php
  Trace/src/V2/Span/Link.php
  Trace/src/V2/Span/TimeEvent.php
  Trace/src/V2/Span/TimeEvent/Annotation.php
  Trace/src/V2/StackTrace.php
  Trace/src/V2/StackTrace/StackFrame.php
  Trace/synth.metadata
Labels: cla: yes, context: full

#4644 [Iot] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  Iot/src/V1/CreateDeviceRegistryRequest.php
  Iot/src/V1/CreateDeviceRequest.php
  Iot/src/V1/Device.php
  Iot/src/V1/DeviceConfig.php
  Iot/src/V1/DeviceCredential.php
  Iot/src/V1/DeviceRegistry.php
  Iot/src/V1/DeviceState.php
  Iot/src/V1/GatewayConfig.php
  Iot/src/V1/GetDeviceRequest.php
  Iot/src/V1/ListDevicesRequest.php
  Iot/src/V1/PublicKeyCertificate.php
  Iot/src/V1/UpdateDeviceRegistryRequest.php
  Iot/src/V1/UpdateDeviceRequest.php
  Iot/src/V1/X509CertificateDetails.php
  Iot/synth.metadata
Labels: cla: yes, context: full

#4643 [Iap] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  Iap/src/V1/AccessDeniedPageSettings.php
  Iap/src/V1/AccessSettings.php
  Iap/src/V1/ApplicationSettings.php
  Iap/src/V1/CorsSettings.php
  Iap/src/V1/CreateBrandRequest.php
  Iap/src/V1/CreateIdentityAwareProxyClientRequest.php
  Iap/src/V1/CsmSettings.php
  Iap/src/V1/GcipSettings.php
  Iap/src/V1/IapSettings.php
  Iap/src/V1/OAuthSettings.php
  Iap/src/V1/UpdateIapSettingsRequest.php
  Iap/synth.metadata
Labels: cla: yes, context: full

#4642 [Grafeas] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  Grafeas/src/V1/AttestationNote.php
  Grafeas/src/V1/BuildOccurrence.php
  Grafeas/src/V1/BuildProvenance.php
  Grafeas/src/V1/CloudRepoSourceContext.php
  Grafeas/src/V1/CreateNoteRequest.php
  Grafeas/src/V1/CreateOccurrenceRequest.php
  Grafeas/src/V1/DeploymentOccurrence.php
  Grafeas/src/V1/DiscoveryOccurrence.php
  Grafeas/src/V1/Distribution.php
  Grafeas/src/V1/ImageNote.php
  Grafeas/src/V1/ImageOccurrence.php
  Grafeas/src/V1/Location.php
  Grafeas/src/V1/Note.php
  Grafeas/src/V1/Occurrence.php
  Grafeas/src/V1/Source.php
  Grafeas/src/V1/UpdateNoteRequest.php
  Grafeas/src/V1/UpdateOccurrenceRequest.php
  Grafeas/src/V1/UpgradeNote.php
  Grafeas/src/V1/UpgradeOccurrence.php
  Grafeas/src/V1/VulnerabilityNote.php
  Grafeas/src/V1/VulnerabilityNote/Detail.php
  Grafeas/src/V1/VulnerabilityOccurrence/PackageIssue.php
  Grafeas/src/V1/WindowsUpdate.php
  Grafeas/synth.metadata
Labels: cla: yes, context: full

#4641 [GkeHub] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  GkeHub/src/V1beta1/ConnectAgentResource.php
  GkeHub/src/V1beta1/CreateMembershipRequest.php
  GkeHub/src/V1beta1/GenerateConnectManifestRequest.php
  GkeHub/src/V1beta1/KubernetesMetadata.php
  GkeHub/src/V1beta1/KubernetesResource.php
  GkeHub/src/V1beta1/Membership.php
  GkeHub/src/V1beta1/MembershipEndpoint.php
  GkeHub/src/V1beta1/MembershipState.php
  GkeHub/src/V1beta1/OperationMetadata.php
  GkeHub/src/V1beta1/UpdateMembershipRequest.php
  GkeHub/src/V1beta1/ValidateExclusivityResponse.php
  GkeHub/synth.metadata
Labels: cla: yes, context: full

#4640 [Firestore] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  Firestore/src/Admin/V1/CreateIndexRequest.php
  Firestore/src/Admin/V1/ExportDocumentsMetadata.php
  Firestore/src/Admin/V1/Field.php
  Firestore/src/Admin/V1/FieldOperationMetadata.php
  Firestore/src/Admin/V1/FieldOperationMetadata/IndexConfigDelta.php
  Firestore/src/Admin/V1/ImportDocumentsMetadata.php
  Firestore/src/Admin/V1/IndexOperationMetadata.php
  Firestore/src/Admin/V1/UpdateFieldRequest.php
  Firestore/src/V1/BatchGetDocumentsRequest.php
  Firestore/src/V1/BatchGetDocumentsResponse.php
  Firestore/src/V1/BeginTransactionRequest.php
  Firestore/src/V1/CommitResponse.php
  Firestore/src/V1/CreateDocumentRequest.php
  Firestore/src/V1/DeleteDocumentRequest.php
  Firestore/src/V1/Document.php
  Firestore/src/V1/DocumentChange.php
  Firestore/src/V1/DocumentDelete.php
  Firestore/src/V1/DocumentRemove.php
  Firestore/src/V1/GetDocumentRequest.php
  Firestore/src/V1/ListDocumentsRequest.php
  Firestore/src/V1/RunQueryResponse.php
  Firestore/src/V1/StructuredQuery.php
  Firestore/src/V1/StructuredQuery/FieldFilter.php
  Firestore/src/V1/StructuredQuery/Order.php
  Firestore/src/V1/TargetChange.php
  Firestore/src/V1/UpdateDocumentRequest.php
  Firestore/src/V1/Write.php
  Firestore/src/V1/WriteResponse.php
  Firestore/src/V1/WriteResult.php
  Firestore/synth.metadata
Labels: cla: yes, context: full

#4639 [Eventarc] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  Eventarc/src/V1/CreateTriggerRequest.php
  Eventarc/src/V1/OperationMetadata.php
  Eventarc/src/V1/Trigger.php
  Eventarc/src/V1/UpdateTriggerRequest.php
  Eventarc/synth.metadata
Labels: cla: yes, context: full

#4637 [Dms] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  Dms/src/V1/CloudSqlConnectionProfile.php
  Dms/src/V1/CloudSqlSettings.php
  Dms/src/V1/ConnectionProfile.php
  Dms/src/V1/CreateConnectionProfileRequest.php
  Dms/src/V1/CreateMigrationJobRequest.php
  Dms/src/V1/MigrationJob.php
  Dms/src/V1/MySqlConnectionProfile.php
  Dms/src/V1/OperationMetadata.php
  Dms/src/V1/PostgreSqlConnectionProfile.php
  Dms/src/V1/SqlIpConfig.php
  Dms/src/V1/UpdateConnectionProfileRequest.php
  Dms/src/V1/UpdateMigrationJobRequest.php
  Dms/synth.metadata
Labels: cla: yes, context: full

#4634 [Debugger] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  Debugger/src/V2/Breakpoint.php
  Debugger/src/V2/Debuggee.php
  Debugger/src/V2/GetBreakpointResponse.php
  Debugger/src/V2/ListBreakpointsRequest.php
  Debugger/src/V2/RegisterDebuggeeRequest.php
  Debugger/src/V2/RegisterDebuggeeResponse.php
  Debugger/src/V2/SetBreakpointRequest.php
  Debugger/src/V2/SetBreakpointResponse.php
  Debugger/src/V2/StackFrame.php
  Debugger/src/V2/StatusMessage.php
  Debugger/src/V2/UpdateActiveBreakpointRequest.php
  Debugger/src/V2/Variable.php
  Debugger/synth.metadata
Labels: cla: yes, context: full

#4674 [Tpu] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  Tpu/src/V1/CreateNodeRequest.php
  Tpu/src/V1/Node.php
  Tpu/src/V1/OperationMetadata.php
  Tpu/src/V1/Symptom.php
  Tpu/synth.metadata
Labels: cla: yes, context: full

#4580 [DataprocMetastore] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  DataprocMetastore/src/V1/Backup.php
  DataprocMetastore/src/V1/CreateBackupRequest.php
  DataprocMetastore/src/V1/CreateMetadataImportRequest.php
  DataprocMetastore/src/V1/CreateServiceRequest.php
  DataprocMetastore/src/V1/HiveMetastoreConfig.php
  DataprocMetastore/src/V1/KerberosConfig.php
  DataprocMetastore/src/V1/MaintenanceWindow.php
  DataprocMetastore/src/V1/MetadataExport.php
  DataprocMetastore/src/V1/MetadataImport.php
  DataprocMetastore/src/V1/OperationMetadata.php
  DataprocMetastore/src/V1/Restore.php
  DataprocMetastore/src/V1/Service.php
  DataprocMetastore/src/V1/UpdateMetadataImportRequest.php
  DataprocMetastore/src/V1/UpdateServiceRequest.php
  DataprocMetastore/src/V1alpha/Backup.php
  DataprocMetastore/src/V1alpha/CreateBackupRequest.php
  DataprocMetastore/src/V1alpha/CreateMetadataImportRequest.php
  DataprocMetastore/src/V1alpha/CreateServiceRequest.php
  DataprocMetastore/src/V1alpha/HiveMetastoreConfig.php
  DataprocMetastore/src/V1alpha/KerberosConfig.php
  DataprocMetastore/src/V1alpha/MaintenanceWindow.php
  DataprocMetastore/src/V1alpha/MetadataExport.php
  DataprocMetastore/src/V1alpha/MetadataImport.php
  DataprocMetastore/src/V1alpha/MetadataIntegration.php
  DataprocMetastore/src/V1alpha/OperationMetadata.php
  DataprocMetastore/src/V1alpha/Restore.php
  DataprocMetastore/src/V1alpha/Service.php
  DataprocMetastore/src/V1alpha/UpdateMetadataImportRequest.php
  DataprocMetastore/src/V1alpha/UpdateServiceRequest.php
  DataprocMetastore/src/V1beta/Backup.php
  DataprocMetastore/src/V1beta/CreateBackupRequest.php
  DataprocMetastore/src/V1beta/CreateMetadataImportRequest.php
  DataprocMetastore/src/V1beta/CreateServiceRequest.php
  DataprocMetastore/src/V1beta/HiveMetastoreConfig.php
  DataprocMetastore/src/V1beta/KerberosConfig.php
  DataprocMetastore/src/V1beta/MaintenanceWindow.php
  DataprocMetastore/src/V1beta/MetadataExport.php
  DataprocMetastore/src/V1beta/MetadataImport.php
  DataprocMetastore/src/V1beta/MetadataIntegration.php
  DataprocMetastore/src/V1beta/OperationMetadata.php
  DataprocMetastore/src/V1beta/Restore.php
  DataprocMetastore/src/V1beta/Service.php
  DataprocMetastore/src/V1beta/UpdateMetadataImportRequest.php
  DataprocMetastore/src/V1beta/UpdateServiceRequest.php
  DataprocMetastore/synth.metadata
Labels: cla: yes, context: full

#4575 [ContactCenterInsights] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  ContactCenterInsights/src/V1/Analysis.php
  ContactCenterInsights/src/V1/AnalysisResult.php
  ContactCenterInsights/src/V1/AnalysisResult/CallAnalysisMetadata.php
  ContactCenterInsights/src/V1/CalculateIssueModelStatsResponse.php
  ContactCenterInsights/src/V1/CalculateStatsResponse.php
  ContactCenterInsights/src/V1/CalculateStatsResponse/TimeSeries.php
  ContactCenterInsights/src/V1/CalculateStatsResponse/TimeSeries/Interval.php
  ContactCenterInsights/src/V1/CallAnnotation.php
  ContactCenterInsights/src/V1/Conversation.php
  ContactCenterInsights/src/V1/Conversation/Transcript/TranscriptSegment.php
  ContactCenterInsights/src/V1/Conversation/Transcript/TranscriptSegment/WordInfo.php
  ContactCenterInsights/src/V1/ConversationLevelSentiment.php
  ContactCenterInsights/src/V1/CreateAnalysisOperationMetadata.php
  ContactCenterInsights/src/V1/CreateAnalysisRequest.php
  ContactCenterInsights/src/V1/CreateConversationRequest.php
  ContactCenterInsights/src/V1/CreateIssueModelMetadata.php
  ContactCenterInsights/src/V1/CreateIssueModelRequest.php
  ContactCenterInsights/src/V1/CreatePhraseMatcherRequest.php
  ContactCenterInsights/src/V1/DeleteIssueModelMetadata.php
  ContactCenterInsights/src/V1/DeployIssueModelMetadata.php
  ContactCenterInsights/src/V1/Entity.php
  ContactCenterInsights/src/V1/EntityMentionData.php
  ContactCenterInsights/src/V1/ExportInsightsDataMetadata.php
  ContactCenterInsights/src/V1/Issue.php
  ContactCenterInsights/src/V1/IssueModel.php
  ContactCenterInsights/src/V1/PhraseMatchRule.php
  ContactCenterInsights/src/V1/PhraseMatcher.php
  ContactCenterInsights/src/V1/RuntimeAnnotation.php
  ContactCenterInsights/src/V1/Settings.php
  ContactCenterInsights/src/V1/UndeployIssueModelMetadata.php
  ContactCenterInsights/src/V1/UpdateConversationRequest.php
  ContactCenterInsights/src/V1/UpdateIssueModelRequest.php
  ContactCenterInsights/src/V1/UpdateIssueRequest.php
  ContactCenterInsights/src/V1/UpdateSettingsRequest.php
  ContactCenterInsights/synth.metadata
Labels: cla: yes, context: full

#4573 [BinaryAuthorization] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  BinaryAuthorization/src/V1beta1/Attestor.php
  BinaryAuthorization/src/V1beta1/ContinuousValidationEvent/ContinuousValidationPodEvent.php
  BinaryAuthorization/src/V1beta1/CreateAttestorRequest.php
  BinaryAuthorization/src/V1beta1/Policy.php
  BinaryAuthorization/src/V1beta1/UpdateAttestorRequest.php
  BinaryAuthorization/src/V1beta1/UpdatePolicyRequest.php
  BinaryAuthorization/synth.metadata
Labels: cla: yes, context: full

#4672 [StorageTransfer] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  StorageTransfer/src/V1/AwsS3Data.php
  StorageTransfer/src/V1/AzureBlobStorageData.php
  StorageTransfer/src/V1/CreateTransferJobRequest.php
  StorageTransfer/src/V1/ObjectConditions.php
  StorageTransfer/src/V1/Schedule.php
  StorageTransfer/src/V1/TransferJob.php
  StorageTransfer/src/V1/TransferOperation.php
  StorageTransfer/src/V1/TransferSpec.php
  StorageTransfer/src/V1/UpdateTransferJobRequest.php
  StorageTransfer/synth.metadata
Labels: cla: yes, context: full

#4572 [BillingBudgets] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  BillingBudgets/src/V1/Budget.php
  BillingBudgets/src/V1/CreateBudgetRequest.php
  BillingBudgets/src/V1/CustomPeriod.php
  BillingBudgets/src/V1/UpdateBudgetRequest.php
  BillingBudgets/src/V1beta1/Budget.php
  BillingBudgets/src/V1beta1/CreateBudgetRequest.php
  BillingBudgets/src/V1beta1/CustomPeriod.php
  BillingBudgets/src/V1beta1/UpdateBudgetRequest.php
  BillingBudgets/synth.metadata
Labels: cla: yes, context: full

#4571 [Billing] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  Billing/src/V1/CreateBillingAccountRequest.php
  Billing/src/V1/ListSkusRequest.php
  Billing/src/V1/PricingExpression/TierRate.php
  Billing/src/V1/PricingInfo.php
  Billing/src/V1/Sku.php
  Billing/src/V1/UpdateBillingAccountRequest.php
  Billing/src/V1/UpdateProjectBillingInfoRequest.php
  Billing/synth.metadata
Labels: cla: yes, context: full

#4569 [BigQueryReservation] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  BigQueryReservation/src/V1/BiReservation.php
  BigQueryReservation/src/V1/CapacityCommitment.php
  BigQueryReservation/src/V1/CreateAssignmentRequest.php
  BigQueryReservation/src/V1/CreateCapacityCommitmentRequest.php
  BigQueryReservation/src/V1/CreateReservationRequest.php
  BigQueryReservation/src/V1/Reservation.php
  BigQueryReservation/src/V1/SplitCapacityCommitmentResponse.php
  BigQueryReservation/src/V1/UpdateBiReservationRequest.php
  BigQueryReservation/src/V1/UpdateCapacityCommitmentRequest.php
  BigQueryReservation/src/V1/UpdateReservationRequest.php
  BigQueryReservation/synth.metadata
Labels: cla: yes, context: full

#4568 [BigQueryConnection] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  BigQueryConnection/src/V1/CloudSqlProperties.php
  BigQueryConnection/src/V1/CreateConnectionRequest.php
  BigQueryConnection/src/V1/UpdateConnectionRequest.php
  BigQueryConnection/synth.metadata
Labels: cla: yes, context: full

#4566 [AppEngineAdmin] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  AppEngineAdmin/src/V1/Application.php
  AppEngineAdmin/src/V1/AuthorizedCertificate.php
  AppEngineAdmin/src/V1/AutomaticScaling.php
  AppEngineAdmin/src/V1/BasicScaling.php
  AppEngineAdmin/src/V1/CloudBuildOptions.php
  AppEngineAdmin/src/V1/CpuUtilization.php
  AppEngineAdmin/src/V1/CreateApplicationRequest.php
  AppEngineAdmin/src/V1/CreateAuthorizedCertificateRequest.php
  AppEngineAdmin/src/V1/CreateDomainMappingRequest.php
  AppEngineAdmin/src/V1/CreateIngressRuleRequest.php
  AppEngineAdmin/src/V1/CreateVersionMethod.php
  AppEngineAdmin/src/V1/CreateVersionRequest.php
  AppEngineAdmin/src/V1/Deployment.php
  AppEngineAdmin/src/V1/DomainMapping.php
  AppEngineAdmin/src/V1/HealthCheck.php
  AppEngineAdmin/src/V1/Instance.php
  AppEngineAdmin/src/V1/LivenessCheck.php
  AppEngineAdmin/src/V1/ManagedCertificate.php
  AppEngineAdmin/src/V1/OperationMetadataV1.php
  AppEngineAdmin/src/V1/ReadinessCheck.php
  AppEngineAdmin/src/V1/Service.php
  AppEngineAdmin/src/V1/StaticFilesHandler.php
  AppEngineAdmin/src/V1/UpdateApplicationRequest.php
  AppEngineAdmin/src/V1/UpdateAuthorizedCertificateRequest.php
  AppEngineAdmin/src/V1/UpdateDomainMappingRequest.php
  AppEngineAdmin/src/V1/UpdateIngressRuleRequest.php
  AppEngineAdmin/src/V1/UpdateServiceMethod.php
  AppEngineAdmin/src/V1/UpdateServiceRequest.php
  AppEngineAdmin/src/V1/UpdateVersionRequest.php
  AppEngineAdmin/src/V1/Version.php
  AppEngineAdmin/synth.metadata
Labels: cla: yes, context: full

#4563 [AccessApproval] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  AccessApproval/src/V1/ApprovalRequest.php
  AccessApproval/src/V1/ApproveApprovalRequestMessage.php
  AccessApproval/src/V1/ApproveDecision.php
  AccessApproval/src/V1/DismissDecision.php
  AccessApproval/src/V1/UpdateAccessApprovalSettingsMessage.php
  AccessApproval/synth.metadata
Labels: cla: yes, context: full

#4564 [AccessContextManager] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  AccessContextManager/src/V1/AccessLevel.php
  AccessContextManager/src/V1/AccessPolicy.php
  AccessContextManager/src/V1/Condition.php
  AccessContextManager/src/V1/CreateAccessLevelRequest.php
  AccessContextManager/src/V1/CreateGcpUserAccessBindingRequest.php
  AccessContextManager/src/V1/CreateServicePerimeterRequest.php
  AccessContextManager/src/V1/CustomLevel.php
  AccessContextManager/src/V1/ServicePerimeter.php
  AccessContextManager/src/V1/ServicePerimeterConfig.php
  AccessContextManager/src/V1/ServicePerimeterConfig/EgressPolicy.php
  AccessContextManager/src/V1/ServicePerimeterConfig/IngressPolicy.php
  AccessContextManager/src/V1/UpdateAccessLevelRequest.php
  AccessContextManager/src/V1/UpdateAccessPolicyRequest.php
  AccessContextManager/src/V1/UpdateGcpUserAccessBindingRequest.php
  AccessContextManager/src/V1/UpdateServicePerimeterRequest.php
  AccessContextManager/synth.metadata
Labels: cla: yes, context: full

#4565 [ApigeeConnect] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  ApigeeConnect/src/V1/Connection.php
  ApigeeConnect/src/V1/EgressRequest.php
  ApigeeConnect/src/V1/EgressResponse.php
  ApigeeConnect/src/V1/HttpRequest.php
  ApigeeConnect/synth.metadata
Labels: cla: yes, context: full

#4691 chore: migrate AccessApproval to owlbot
  AccessApproval/.OwlBot.yaml
  AccessApproval/owlbot.py
  CONTRIBUTING.md
Labels: cla: yes

#4673 [TextToSpeech] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  TextToSpeech/src/V1/SynthesizeSpeechRequest.php
  TextToSpeech/synth.metadata
Labels: cla: yes, context: full

#4668 [ServiceManagement] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  ServiceManagement/src/V1/CreateServiceConfigRequest.php
  ServiceManagement/src/V1/CreateServiceRequest.php
  ServiceManagement/src/V1/CreateServiceRolloutRequest.php
  ServiceManagement/src/V1/GenerateConfigReportRequest.php
  ServiceManagement/src/V1/OperationMetadata.php
  ServiceManagement/src/V1/Rollout.php
  ServiceManagement/src/V1/SubmitConfigSourceRequest.php
  ServiceManagement/src/V1/SubmitConfigSourceResponse.php
  ServiceManagement/src/V1/UndeleteServiceResponse.php
  ServiceManagement/synth.metadata
Labels: cla: yes, context: full

#4670 [Spanner] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  Spanner/src/Admin/Database/V1/Backup.php
  Spanner/src/Admin/Database/V1/BackupInfo.php
  Spanner/src/Admin/Database/V1/CreateBackupMetadata.php
  Spanner/src/Admin/Database/V1/CreateBackupRequest.php
  Spanner/src/Admin/Database/V1/CreateDatabaseRequest.php
  Spanner/src/Admin/Database/V1/Database.php
  Spanner/src/Admin/Database/V1/EncryptionInfo.php
  Spanner/src/Admin/Database/V1/OperationProgress.php
  Spanner/src/Admin/Database/V1/OptimizeRestoredDatabaseMetadata.php
  Spanner/src/Admin/Database/V1/RestoreDatabaseMetadata.php
  Spanner/src/Admin/Database/V1/RestoreDatabaseRequest.php
  Spanner/src/Admin/Database/V1/UpdateBackupRequest.php
  Spanner/src/Admin/Instance/V1/CreateInstanceMetadata.php
  Spanner/src/Admin/Instance/V1/CreateInstanceRequest.php
  Spanner/src/Admin/Instance/V1/GetInstanceRequest.php
  Spanner/src/Admin/Instance/V1/UpdateInstanceMetadata.php
  Spanner/src/Admin/Instance/V1/UpdateInstanceRequest.php
  Spanner/src/V1/BatchCreateSessionsRequest.php
  Spanner/src/V1/BeginTransactionRequest.php
  Spanner/src/V1/CommitRequest.php
  Spanner/src/V1/CommitResponse.php
  Spanner/src/V1/CreateSessionRequest.php
  Spanner/src/V1/ExecuteBatchDmlRequest.php
  Spanner/src/V1/ExecuteBatchDmlRequest/Statement.php
  Spanner/src/V1/ExecuteBatchDmlResponse.php
  Spanner/src/V1/ExecuteSqlRequest.php
  Spanner/src/V1/Mutation/Delete.php
  Spanner/src/V1/PartialResultSet.php
  Spanner/src/V1/PartitionQueryRequest.php
  Spanner/src/V1/PartitionReadRequest.php
  Spanner/src/V1/PartitionResponse.php
  Spanner/src/V1/PlanNode.php
  Spanner/src/V1/ReadRequest.php
  Spanner/src/V1/ResultSet.php
  Spanner/src/V1/ResultSetMetadata.php
  Spanner/src/V1/ResultSetStats.php
  Spanner/src/V1/Session.php
  Spanner/src/V1/StructType/Field.php
  Spanner/src/V1/Transaction.php
  Spanner/src/V1/Type.php
  Spanner/synth.metadata
Labels: cla: yes, context: full

#4671 [SqlAdmin] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  SqlAdmin/src/V1beta4/AclEntry.php
  SqlAdmin/src/V1beta4/BackupConfiguration.php
  SqlAdmin/src/V1beta4/BackupRetentionSettings.php
  SqlAdmin/src/V1beta4/BackupRun.php
  SqlAdmin/src/V1beta4/CloneContext.php
  SqlAdmin/src/V1beta4/DatabaseInstance.php
  SqlAdmin/src/V1beta4/DatabaseInstance/SqlFailoverReplica.php
  SqlAdmin/src/V1beta4/DatabaseInstance/SqlOutOfDiskReport.php
  SqlAdmin/src/V1beta4/DatabaseInstance/SqlScheduledMaintenance.php
  SqlAdmin/src/V1beta4/DemoteMasterConfiguration.php
  SqlAdmin/src/V1beta4/DemoteMasterContext.php
  SqlAdmin/src/V1beta4/ExportContext.php
  SqlAdmin/src/V1beta4/ExportContext/SqlExportOptions.php
  SqlAdmin/src/V1beta4/ExportContext/SqlExportOptions/MysqlExportOptions.php
  SqlAdmin/src/V1beta4/Flag.php
  SqlAdmin/src/V1beta4/ImportContext.php
  SqlAdmin/src/V1beta4/ImportContext/SqlBakImportOptions.php
  SqlAdmin/src/V1beta4/InsightsConfig.php
  SqlAdmin/src/V1beta4/InstancesCloneRequest.php
  SqlAdmin/src/V1beta4/InstancesDemoteMasterRequest.php
  SqlAdmin/src/V1beta4/InstancesExportRequest.php
  SqlAdmin/src/V1beta4/InstancesFailoverRequest.php
  SqlAdmin/src/V1beta4/InstancesImportRequest.php
  SqlAdmin/src/V1beta4/InstancesRestoreBackupRequest.php
  SqlAdmin/src/V1beta4/InstancesRotateServerCaRequest.php
  SqlAdmin/src/V1beta4/InstancesTruncateLogRequest.php
  SqlAdmin/src/V1beta4/IpConfiguration.php
  SqlAdmin/src/V1beta4/IpMapping.php
  SqlAdmin/src/V1beta4/MaintenanceWindow.php
  SqlAdmin/src/V1beta4/MySqlReplicaConfiguration.php
  SqlAdmin/src/V1beta4/Operation.php
  SqlAdmin/src/V1beta4/ReplicaConfiguration.php
  SqlAdmin/src/V1beta4/Settings.php
  SqlAdmin/src/V1beta4/SqlBackupRunsInsertRequest.php
  SqlAdmin/src/V1beta4/SqlDatabasesInsertRequest.php
  SqlAdmin/src/V1beta4/SqlDatabasesUpdateRequest.php
  SqlAdmin/src/V1beta4/SqlInstancesCloneRequest.php
  SqlAdmin/src/V1beta4/SqlInstancesCreateEphemeralCertRequest.php
  SqlAdmin/src/V1beta4/SqlInstancesDemoteMasterRequest.php
  SqlAdmin/src/V1beta4/SqlInstancesExportRequest.php
  SqlAdmin/src/V1beta4/SqlInstancesFailoverRequest.php
  SqlAdmin/src/V1beta4/SqlInstancesImportRequest.php
  SqlAdmin/src/V1beta4/SqlInstancesInsertRequest.php
  SqlAdmin/src/V1beta4/SqlInstancesPatchRequest.php
  SqlAdmin/src/V1beta4/SqlInstancesRescheduleMaintenanceRequest.php
  SqlAdmin/src/V1beta4/SqlInstancesRescheduleMaintenanceRequestBody.php
  SqlAdmin/src/V1beta4/SqlInstancesRescheduleMaintenanceRequestBody/Reschedule.php
  SqlAdmin/src/V1beta4/SqlInstancesRestoreBackupRequest.php
  SqlAdmin/src/V1beta4/SqlInstancesRotateServerCaRequest.php
  SqlAdmin/src/V1beta4/SqlInstancesTruncateLogRequest.php
  SqlAdmin/src/V1beta4/SqlInstancesUpdateRequest.php
  SqlAdmin/src/V1beta4/SqlSslCertsInsertRequest.php
  SqlAdmin/src/V1beta4/SqlUsersInsertRequest.php
  SqlAdmin/src/V1beta4/SqlUsersUpdateRequest.php
  SqlAdmin/src/V1beta4/SslCert.php
  SqlAdmin/src/V1beta4/SslCertDetail.php
  SqlAdmin/src/V1beta4/SslCertsInsertResponse.php
  SqlAdmin/synth.metadata
Labels: cla: yes, context: full

#4667 [ServiceDirectory] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  ServiceDirectory/src/V1/CreateEndpointRequest.php
  ServiceDirectory/src/V1/CreateNamespaceRequest.php
  ServiceDirectory/src/V1/CreateServiceRequest.php
  ServiceDirectory/src/V1/ResolveServiceResponse.php
  ServiceDirectory/src/V1/UpdateEndpointRequest.php
  ServiceDirectory/src/V1/UpdateNamespaceRequest.php
  ServiceDirectory/src/V1/UpdateServiceRequest.php
  ServiceDirectory/src/V1beta1/CreateEndpointRequest.php
  ServiceDirectory/src/V1beta1/CreateNamespaceRequest.php
  ServiceDirectory/src/V1beta1/CreateServiceRequest.php
  ServiceDirectory/src/V1beta1/Endpoint.php
  ServiceDirectory/src/V1beta1/PBNamespace.php
  ServiceDirectory/src/V1beta1/ResolveServiceResponse.php
  ServiceDirectory/src/V1beta1/Service.php
  ServiceDirectory/src/V1beta1/UpdateEndpointRequest.php
  ServiceDirectory/src/V1beta1/UpdateNamespaceRequest.php
  ServiceDirectory/src/V1beta1/UpdateServiceRequest.php
  ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#4666 [ServiceControl] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  ServiceControl/src/V1/AllocateQuotaRequest.php
  ServiceControl/src/V1/CheckError.php
  ServiceControl/src/V1/CheckRequest.php
  ServiceControl/src/V1/CheckResponse.php
  ServiceControl/src/V1/CheckResponse/CheckInfo.php
  ServiceControl/src/V1/HttpRequest.php
  ServiceControl/src/V1/LogEntry.php
  ServiceControl/src/V1/MetricValue.php
  ServiceControl/src/V1/Operation.php
  ServiceControl/src/V1/QuotaError.php
  ServiceControl/src/V1/ReportResponse/ReportError.php
  ServiceControl/synth.metadata
Labels: cla: yes, context: full

#4665 [SecurityCenter] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  SecurityCenter/src/V1/Asset.php
  SecurityCenter/src/V1/CreateFindingRequest.php
  SecurityCenter/src/V1/CreateNotificationConfigRequest.php
  SecurityCenter/src/V1/CreateSourceRequest.php
  SecurityCenter/src/V1/Cve.php
  SecurityCenter/src/V1/Finding.php
  SecurityCenter/src/V1/GroupAssetsRequest.php
  SecurityCenter/src/V1/GroupAssetsResponse.php
  SecurityCenter/src/V1/GroupFindingsRequest.php
  SecurityCenter/src/V1/GroupFindingsResponse.php
  SecurityCenter/src/V1/ListAssetsRequest.php
  SecurityCenter/src/V1/ListAssetsResponse.php
  SecurityCenter/src/V1/ListAssetsResponse/ListAssetsResult.php
  SecurityCenter/src/V1/ListFindingsRequest.php
  SecurityCenter/src/V1/ListFindingsResponse.php
  SecurityCenter/src/V1/ListFindingsResponse/ListFindingsResult.php
  SecurityCenter/src/V1/NotificationMessage.php
  SecurityCenter/src/V1/OrganizationSettings.php
  SecurityCenter/src/V1/RunAssetDiscoveryResponse.php
  SecurityCenter/src/V1/SetFindingStateRequest.php
  SecurityCenter/src/V1/UpdateFindingRequest.php
  SecurityCenter/src/V1/UpdateNotificationConfigRequest.php
  SecurityCenter/src/V1/UpdateOrganizationSettingsRequest.php
  SecurityCenter/src/V1/UpdateSecurityMarksRequest.php
  SecurityCenter/src/V1/UpdateSourceRequest.php
  SecurityCenter/src/V1/Vulnerability.php
  SecurityCenter/src/V1p1beta1/Asset.php
  SecurityCenter/src/V1p1beta1/CreateFindingRequest.php
  SecurityCenter/src/V1p1beta1/CreateNotificationConfigRequest.php
  SecurityCenter/src/V1p1beta1/CreateSourceRequest.php
  SecurityCenter/src/V1p1beta1/Finding.php
  SecurityCenter/src/V1p1beta1/GroupAssetsRequest.php
  SecurityCenter/src/V1p1beta1/GroupAssetsResponse.php
  SecurityCenter/src/V1p1beta1/GroupFindingsRequest.php
  SecurityCenter/src/V1p1beta1/GroupFindingsResponse.php
  SecurityCenter/src/V1p1beta1/ListAssetsRequest.php
  SecurityCenter/src/V1p1beta1/ListAssetsResponse.php
  SecurityCenter/src/V1p1beta1/ListAssetsResponse/ListAssetsResult.php
  SecurityCenter/src/V1p1beta1/ListFindingsRequest.php
  SecurityCenter/src/V1p1beta1/ListFindingsResponse.php
  SecurityCenter/src/V1p1beta1/ListFindingsResponse/ListFindingsResult.php
  SecurityCenter/src/V1p1beta1/NotificationMessage.php
  SecurityCenter/src/V1p1beta1/OrganizationSettings.php
  SecurityCenter/src/V1p1beta1/RunAssetDiscoveryResponse.php
  SecurityCenter/src/V1p1beta1/SetFindingStateRequest.php
  SecurityCenter/src/V1p1beta1/UpdateFindingRequest.php
  SecurityCenter/src/V1p1beta1/UpdateNotificationConfigRequest.php
  SecurityCenter/src/V1p1beta1/UpdateOrganizationSettingsRequest.php
  SecurityCenter/src/V1p1beta1/UpdateSecurityMarksRequest.php
  SecurityCenter/src/V1p1beta1/UpdateSourceRequest.php
  SecurityCenter/synth.metadata
Labels: cla: yes, context: full

#4664 [SecretManager] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  SecretManager/src/V1/AccessSecretVersionResponse.php
  SecretManager/src/V1/AddSecretVersionRequest.php
  SecretManager/src/V1/CreateSecretRequest.php
  SecretManager/src/V1/Replication/Automatic.php
  SecretManager/src/V1/Replication/UserManaged/Replica.php
  SecretManager/src/V1/ReplicationStatus/AutomaticStatus.php
  SecretManager/src/V1/ReplicationStatus/UserManagedStatus/ReplicaStatus.php
  SecretManager/src/V1/Rotation.php
  SecretManager/src/V1/Secret.php
  SecretManager/src/V1/SecretVersion.php
  SecretManager/src/V1/UpdateSecretRequest.php
  SecretManager/src/V1beta1/AccessSecretVersionResponse.php
  SecretManager/src/V1beta1/AddSecretVersionRequest.php
  SecretManager/src/V1beta1/CreateSecretRequest.php
  SecretManager/src/V1beta1/Secret.php
  SecretManager/src/V1beta1/SecretVersion.php
  SecretManager/src/V1beta1/UpdateSecretRequest.php
  SecretManager/synth.metadata
Labels: cla: yes, context: full

#4663 [ResourceSettings] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  ResourceSettings/src/V1/Setting.php
  ResourceSettings/src/V1/SettingMetadata.php
  ResourceSettings/src/V1/UpdateSettingRequest.php
  ResourceSettings/synth.metadata
Labels: cla: yes, context: full

#4638 [EssentialContacts] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  EssentialContacts/src/V1/Contact.php
  EssentialContacts/src/V1/CreateContactRequest.php
  EssentialContacts/src/V1/UpdateContactRequest.php
  EssentialContacts/synth.metadata
Labels: cla: yes, context: full

#4662 [ResourceManager] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  ResourceManager/src/V3/CreateFolderRequest.php
  ResourceManager/src/V3/CreateProjectMetadata.php
  ResourceManager/src/V3/CreateProjectRequest.php
  ResourceManager/src/V3/CreateTagBindingRequest.php
  ResourceManager/src/V3/CreateTagKeyRequest.php
  ResourceManager/src/V3/CreateTagValueRequest.php
  ResourceManager/src/V3/Folder.php
  ResourceManager/src/V3/Organization.php
  ResourceManager/src/V3/Project.php
  ResourceManager/src/V3/TagKey.php
  ResourceManager/src/V3/TagValue.php
  ResourceManager/src/V3/UpdateFolderRequest.php
  ResourceManager/src/V3/UpdateProjectRequest.php
  ResourceManager/src/V3/UpdateTagKeyRequest.php
  ResourceManager/src/V3/UpdateTagValueRequest.php
  ResourceManager/synth.metadata
Labels: cla: yes, context: full

#4661 [Redis] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  Redis/src/V1/CreateInstanceRequest.php
  Redis/src/V1/ExportInstanceRequest.php
  Redis/src/V1/ImportInstanceRequest.php
  Redis/src/V1/Instance.php
  Redis/src/V1/OperationMetadata.php
  Redis/src/V1/UpdateInstanceRequest.php
  Redis/src/V1beta1/CreateInstanceRequest.php
  Redis/src/V1beta1/ExportInstanceRequest.php
  Redis/src/V1beta1/ImportInstanceRequest.php
  Redis/src/V1beta1/Instance.php
  Redis/src/V1beta1/UpdateInstanceRequest.php
  Redis/synth.metadata
Labels: cla: yes, context: full

#4660 [Recommender] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  Recommender/src/V1/CostProjection.php
  Recommender/src/V1/Insight.php
  Recommender/src/V1/Recommendation.php
  Recommender/synth.metadata
Labels: cla: yes, context: full

#4658 [Profiler] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  Profiler/src/V2/CreateOfflineProfileRequest.php
  Profiler/src/V2/CreateProfileRequest.php
  Profiler/src/V2/Profile.php
  Profiler/src/V2/UpdateProfileRequest.php
  Profiler/synth.metadata
Labels: cla: yes, context: full

#4657 [PrivateCatalog] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  PrivateCatalog/src/V1beta1/AssetReference.php
  PrivateCatalog/src/V1beta1/Catalog.php
  PrivateCatalog/src/V1beta1/GcsSource.php
  PrivateCatalog/src/V1beta1/Inputs.php
  PrivateCatalog/src/V1beta1/Product.php
  PrivateCatalog/src/V1beta1/Version.php
  PrivateCatalog/synth.metadata
Labels: cla: yes, context: full

#4655 [OsLogin] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  OsLogin/src/V1/ImportSshPublicKeyRequest.php
  OsLogin/src/V1/ImportSshPublicKeyResponse.php
  OsLogin/src/V1/UpdateSshPublicKeyRequest.php
  OsLogin/src/V1beta/ImportSshPublicKeyRequest.php
  OsLogin/src/V1beta/ImportSshPublicKeyResponse.php
  OsLogin/src/V1beta/UpdateSshPublicKeyRequest.php
  OsLogin/synth.metadata
Labels: cla: yes, context: full

#4654 [OrgPolicy] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  OrgPolicy/src/V2/AlternatePolicySpec.php
  OrgPolicy/src/V2/CreatePolicyRequest.php
  OrgPolicy/src/V2/Policy.php
  OrgPolicy/src/V2/PolicySpec.php
  OrgPolicy/src/V2/PolicySpec/PolicyRule.php
  OrgPolicy/src/V2/UpdatePolicyRequest.php
  OrgPolicy/synth.metadata
Labels: cla: yes, context: full

#4656 [PolicyTroubleshooter] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  PolicyTroubleshooter/src/V1/BindingExplanation.php
  PolicyTroubleshooter/src/V1/ExplainedPolicy.php
  PolicyTroubleshooter/src/V1/TroubleshootIamPolicyRequest.php
  PolicyTroubleshooter/synth.metadata
Labels: cla: yes, context: full

#4651 [NetworkSecurity] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  NetworkSecurity/src/V1beta1/AuthorizationPolicy.php
  NetworkSecurity/src/V1beta1/AuthorizationPolicy/Rule/Destination.php
  NetworkSecurity/src/V1beta1/ClientTlsPolicy.php
  NetworkSecurity/src/V1beta1/CreateAuthorizationPolicyRequest.php
  NetworkSecurity/src/V1beta1/CreateClientTlsPolicyRequest.php
  NetworkSecurity/src/V1beta1/CreateServerTlsPolicyRequest.php
  NetworkSecurity/src/V1beta1/OperationMetadata.php
  NetworkSecurity/src/V1beta1/ServerTlsPolicy.php
  NetworkSecurity/src/V1beta1/UpdateAuthorizationPolicyRequest.php
  NetworkSecurity/src/V1beta1/UpdateClientTlsPolicyRequest.php
  NetworkSecurity/src/V1beta1/UpdateServerTlsPolicyRequest.php
  NetworkSecurity/synth.metadata
Labels: cla: yes, context: full

#4650 [NetworkManagement] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  NetworkManagement/src/V1/ConnectivityTest.php
  NetworkManagement/src/V1/CreateConnectivityTestRequest.php
  NetworkManagement/src/V1/OperationMetadata.php
  NetworkManagement/src/V1/ReachabilityDetails.php
  NetworkManagement/src/V1/Trace.php
  NetworkManagement/src/V1/UpdateConnectivityTestRequest.php
  NetworkManagement/synth.metadata
Labels: cla: yes, context: full

#4653 [OrchestrationAirflow] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  OrchestrationAirflow/src/V1/CreateEnvironmentRequest.php
  OrchestrationAirflow/src/V1/Environment.php
  OrchestrationAirflow/src/V1/EnvironmentConfig.php
  OrchestrationAirflow/src/V1/ImageVersion.php
  OrchestrationAirflow/src/V1/NodeConfig.php
  OrchestrationAirflow/src/V1/OperationMetadata.php
  OrchestrationAirflow/src/V1/PrivateEnvironmentConfig.php
  OrchestrationAirflow/src/V1/UpdateEnvironmentRequest.php
  OrchestrationAirflow/synth.metadata
Labels: cla: yes, context: full

#4649 [NetworkConnectivity] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  NetworkConnectivity/src/V1/CreateHubRequest.php
  NetworkConnectivity/src/V1/CreateSpokeRequest.php
  NetworkConnectivity/src/V1/Hub.php
  NetworkConnectivity/src/V1/OperationMetadata.php
  NetworkConnectivity/src/V1/Spoke.php
  NetworkConnectivity/src/V1/UpdateHubRequest.php
  NetworkConnectivity/src/V1/UpdateSpokeRequest.php
  NetworkConnectivity/synth.metadata
Labels: cla: yes, context: full

#4648 [Memcache] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  Memcache/src/V1/CreateInstanceRequest.php
  Memcache/src/V1/Instance.php
  Memcache/src/V1/Instance/Node.php
  Memcache/src/V1/OperationMetadata.php
  Memcache/src/V1/UpdateInstanceRequest.php
  Memcache/src/V1/UpdateParametersRequest.php
  Memcache/src/V1beta2/CreateInstanceRequest.php
  Memcache/src/V1beta2/Instance.php
  Memcache/src/V1beta2/Instance/Node.php
  Memcache/src/V1beta2/OperationMetadata.php
  Memcache/src/V1beta2/UpdateInstanceRequest.php
  Memcache/src/V1beta2/UpdateParametersRequest.php
  Memcache/synth.metadata
Labels: cla: yes, context: full

#4570 [Bigtable] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  Bigtable/src/Admin/V2/Backup.php
  Bigtable/src/Admin/V2/BackupInfo.php
  Bigtable/src/Admin/V2/Cluster.php
  Bigtable/src/Admin/V2/ColumnFamily.php
  Bigtable/src/Admin/V2/CreateAppProfileRequest.php
  Bigtable/src/Admin/V2/CreateBackupMetadata.php
  Bigtable/src/Admin/V2/CreateBackupRequest.php
  Bigtable/src/Admin/V2/CreateClusterMetadata.php
  Bigtable/src/Admin/V2/CreateClusterRequest.php
  Bigtable/src/Admin/V2/CreateInstanceMetadata.php
  Bigtable/src/Admin/V2/CreateInstanceRequest.php
  Bigtable/src/Admin/V2/CreateTableFromSnapshotMetadata.php
  Bigtable/src/Admin/V2/CreateTableRequest.php
  Bigtable/src/Admin/V2/EncryptionInfo.php
  Bigtable/src/Admin/V2/OperationProgress.php
  Bigtable/src/Admin/V2/OptimizeRestoredTableMetadata.php
  Bigtable/src/Admin/V2/PartialUpdateInstanceRequest.php
  Bigtable/src/Admin/V2/RestoreTableMetadata.php
  Bigtable/src/Admin/V2/Snapshot.php
  Bigtable/src/Admin/V2/SnapshotTableMetadata.php
  Bigtable/src/Admin/V2/SnapshotTableRequest.php
  Bigtable/src/Admin/V2/Table.php
  Bigtable/src/Admin/V2/UpdateAppProfileRequest.php
  Bigtable/src/Admin/V2/UpdateBackupRequest.php
  Bigtable/src/Admin/V2/UpdateClusterMetadata.php
  Bigtable/src/Admin/V2/UpdateInstanceMetadata.php
  Bigtable/src/V2/CheckAndMutateRowRequest.php
  Bigtable/src/V2/MutateRowsResponse/Entry.php
  Bigtable/src/V2/Mutation/DeleteFromColumn.php
  Bigtable/src/V2/ReadModifyWriteRowResponse.php
  Bigtable/src/V2/ReadRowsRequest.php
  Bigtable/src/V2/ReadRowsResponse/CellChunk.php
  Bigtable/src/V2/RowFilter/Condition.php
  Bigtable/synth.metadata
Labels: cla: yes, context: full

#4647 [MediaTranslation] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  MediaTranslation/src/V1beta1/StreamingTranslateSpeechConfig.php
  MediaTranslation/src/V1beta1/StreamingTranslateSpeechResponse.php
  MediaTranslation/synth.metadata
Labels: cla: yes, context: full

#4646 [LifeSciences] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  LifeSciences/src/V2beta/Action.php
  LifeSciences/src/V2beta/Event.php
  LifeSciences/src/V2beta/Metadata.php
  LifeSciences/src/V2beta/Pipeline.php
  LifeSciences/src/V2beta/Resources.php
  LifeSciences/src/V2beta/RunPipelineRequest.php
  LifeSciences/src/V2beta/VirtualMachine.php
  LifeSciences/synth.metadata
Labels: cla: yes, context: full

#4645 [Language] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  Language/src/V1/AnalyzeEntitiesRequest.php
  Language/src/V1/AnalyzeEntitySentimentRequest.php
  Language/src/V1/AnalyzeSentimentRequest.php
  Language/src/V1/AnalyzeSentimentResponse.php
  Language/src/V1/AnalyzeSyntaxRequest.php
  Language/src/V1/AnnotateTextRequest.php
  Language/src/V1/AnnotateTextResponse.php
  Language/src/V1/ClassifyTextRequest.php
  Language/src/V1/Entity.php
  Language/src/V1/EntityMention.php
  Language/src/V1/Sentence.php
  Language/src/V1/Token.php
  Language/src/V1beta2/AnalyzeEntitiesRequest.php
  Language/src/V1beta2/AnalyzeEntitySentimentRequest.php
  Language/src/V1beta2/AnalyzeSentimentRequest.php
  Language/src/V1beta2/AnalyzeSentimentResponse.php
  Language/src/V1beta2/AnalyzeSyntaxRequest.php
  Language/src/V1beta2/AnnotateTextRequest.php
  Language/src/V1beta2/AnnotateTextResponse.php
  Language/src/V1beta2/ClassifyTextRequest.php
  Language/src/V1beta2/Entity.php
  Language/src/V1beta2/EntityMention.php
  Language/src/V1beta2/Sentence.php
  Language/src/V1beta2/Token.php
  Language/synth.metadata
Labels: cla: yes, context: full

#4579 [Dataproc] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  Dataproc/src/V1/AutoscalingPolicy.php
  Dataproc/src/V1/BasicAutoscalingAlgorithm.php
  Dataproc/src/V1/BasicYarnAutoscalingConfig.php
  Dataproc/src/V1/BatchOperationMetadata.php
  Dataproc/src/V1/Cluster.php
  Dataproc/src/V1/ClusterConfig.php
  Dataproc/src/V1/ClusterOperationMetadata.php
  Dataproc/src/V1/ClusterOperationStatus.php
  Dataproc/src/V1/ClusterStatus.php
  Dataproc/src/V1/CreateAutoscalingPolicyRequest.php
  Dataproc/src/V1/CreateClusterRequest.php
  Dataproc/src/V1/CreateWorkflowTemplateRequest.php
  Dataproc/src/V1/EnvironmentConfig.php
  Dataproc/src/V1/GceClusterConfig.php
  Dataproc/src/V1/GkeClusterConfig.php
  Dataproc/src/V1/HadoopJob.php
  Dataproc/src/V1/InstanceGroupConfig.php
  Dataproc/src/V1/InstantiateInlineWorkflowTemplateRequest.php
  Dataproc/src/V1/Job.php
  Dataproc/src/V1/JobMetadata.php
  Dataproc/src/V1/JobStatus.php
  Dataproc/src/V1/LifecycleConfig.php
  Dataproc/src/V1/ManagedCluster.php
  Dataproc/src/V1/NodeInitializationAction.php
  Dataproc/src/V1/OrderedJob.php
  Dataproc/src/V1/PeripheralsConfig.php
  Dataproc/src/V1/PigJob.php
  Dataproc/src/V1/PrestoJob.php
  Dataproc/src/V1/PySparkJob.php
  Dataproc/src/V1/SecurityConfig.php
  Dataproc/src/V1/SparkJob.php
  Dataproc/src/V1/SparkRJob.php
  Dataproc/src/V1/SparkSqlJob.php
  Dataproc/src/V1/SubmitJobRequest.php
  Dataproc/src/V1/TemplateParameter.php
  Dataproc/src/V1/UpdateAutoscalingPolicyRequest.php
  Dataproc/src/V1/UpdateClusterRequest.php
  Dataproc/src/V1/UpdateJobRequest.php
  Dataproc/src/V1/UpdateWorkflowTemplateRequest.php
  Dataproc/src/V1/WorkflowMetadata.php
  Dataproc/src/V1/WorkflowTemplate.php
  Dataproc/synth.metadata
Labels: cla: yes, context: full

#4577 [DataFusion] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  DataFusion/src/V1/CreateInstanceRequest.php
  DataFusion/src/V1/Instance.php
  DataFusion/src/V1/OperationMetadata.php
  DataFusion/src/V1/UpdateInstanceRequest.php
  DataFusion/synth.metadata
Labels: cla: yes, context: full

#4576 [Container] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  Container/src/V1/AddonsConfig.php
  Container/src/V1/AutoprovisioningNodePoolDefaults.php
  Container/src/V1/Cluster.php
  Container/src/V1/ClusterAutoscaling.php
  Container/src/V1/ClusterUpdate.php
  Container/src/V1/CreateClusterRequest.php
  Container/src/V1/CreateNodePoolRequest.php
  Container/src/V1/MaintenancePolicy.php
  Container/src/V1/MasterAuth.php
  Container/src/V1/NetworkConfig.php
  Container/src/V1/NodeConfig.php
  Container/src/V1/NodeManagement.php
  Container/src/V1/NodePool.php
  Container/src/V1/Operation.php
  Container/src/V1/PrivateClusterConfig.php
  Container/src/V1/RecurringTimeWindow.php
  Container/src/V1/ResourceUsageExportConfig.php
  Container/src/V1/SetAddonsConfigRequest.php
  Container/src/V1/SetMaintenancePolicyRequest.php
  Container/src/V1/SetMasterAuthRequest.php
  Container/src/V1/SetNetworkPolicyRequest.php
  Container/src/V1/SetNodePoolAutoscalingRequest.php
  Container/src/V1/SetNodePoolManagementRequest.php
  Container/src/V1/TimeWindow.php
  Container/src/V1/UpdateClusterRequest.php
  Container/src/V1/UpdateNodePoolRequest.php
  Container/synth.metadata
Labels: cla: yes, context: full

#4578 [Dataflow] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  Dataflow/src/V1beta3/AutoscalingEvent.php
  Dataflow/src/V1beta3/ContainerSpec.php
  Dataflow/src/V1beta3/CreateJobFromTemplateRequest.php
  Dataflow/src/V1beta3/CreateJobRequest.php
  Dataflow/src/V1beta3/Environment.php
  Dataflow/src/V1beta3/ExecutionStageState.php
  Dataflow/src/V1beta3/GetJobMetricsRequest.php
  Dataflow/src/V1beta3/GetStageExecutionDetailsRequest.php
  Dataflow/src/V1beta3/GetTemplateResponse.php
  Dataflow/src/V1beta3/Job.php
  Dataflow/src/V1beta3/JobMessage.php
  Dataflow/src/V1beta3/JobMetadata.php
  Dataflow/src/V1beta3/JobMetrics.php
  Dataflow/src/V1beta3/LaunchFlexTemplateParameter.php
  Dataflow/src/V1beta3/LaunchFlexTemplateRequest.php
  Dataflow/src/V1beta3/LaunchFlexTemplateResponse.php
  Dataflow/src/V1beta3/LaunchTemplateParameters.php
  Dataflow/src/V1beta3/LaunchTemplateRequest.php
  Dataflow/src/V1beta3/LaunchTemplateResponse.php
  Dataflow/src/V1beta3/ListJobMessagesRequest.php
  Dataflow/src/V1beta3/MetricUpdate.php
  Dataflow/src/V1beta3/ProgressTimeseries/Point.php
  Dataflow/src/V1beta3/PubsubSnapshotMetadata.php
  Dataflow/src/V1beta3/RuntimeMetadata.php
  Dataflow/src/V1beta3/Snapshot.php
  Dataflow/src/V1beta3/SnapshotJobRequest.php
  Dataflow/src/V1beta3/StageSummary.php
  Dataflow/src/V1beta3/Step.php
  Dataflow/src/V1beta3/StructuredMessage/Parameter.php
  Dataflow/src/V1beta3/TaskRunnerSettings.php
  Dataflow/src/V1beta3/UpdateJobRequest.php
  Dataflow/src/V1beta3/WorkItemDetails.php
  Dataflow/src/V1beta3/WorkerPool.php
  Dataflow/synth.metadata
Labels: cla: yes, context: full

#4659 [PubSub] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  PubSub/src/V1/CreateSchemaRequest.php
  PubSub/src/V1/ExpirationPolicy.php
  PubSub/src/V1/ModifyPushConfigRequest.php
  PubSub/src/V1/PubsubMessage.php
  PubSub/src/V1/ReceivedMessage.php
  PubSub/src/V1/RetryPolicy.php
  PubSub/src/V1/Snapshot.php
  PubSub/src/V1/StreamingPullResponse.php
  PubSub/src/V1/Subscription.php
  PubSub/src/V1/Topic.php
  PubSub/src/V1/UpdateSnapshotRequest.php
  PubSub/src/V1/UpdateSubscriptionRequest.php
  PubSub/src/V1/UpdateTopicRequest.php
  PubSub/src/V1/ValidateSchemaRequest.php
  PubSub/synth.metadata
Labels: cla: yes, context: full

#4652 [Notebooks] chore(ruby): Re-enable bigquery-storage-v1 generation, which also required updating protobuf from 3.15.3 to 3.18.1 for codegen
  Notebooks/src/V1beta1/CreateEnvironmentRequest.php
  Notebooks/src/V1beta1/CreateInstanceRequest.php
  Notebooks/src/V1beta1/Environment.php
  Notebooks/src/V1beta1/Instance.php
  Notebooks/src/V1beta1/OperationMetadata.php
  Notebooks/synth.metadata
Labels: cla: yes, context: full

#4697 [ServiceControl] docs: fix docstring formatting
  ServiceControl/src/V1/Distribution.php
  ServiceControl/synth.metadata
Labels: cla: yes, context: full

#4698 [ServiceDirectory] docs: fix docstring formatting
  ServiceDirectory/src/V1/Endpoint.php
  ServiceDirectory/src/V1/PBNamespace.php
  ServiceDirectory/src/V1/Service.php
  ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#4700 [Recommender] docs: fix docstring formatting
  Recommender/src/V1/Gapic/RecommenderGapicClient.php
  Recommender/src/V1/MarkRecommendationClaimedRequest.php
  Recommender/src/V1/MarkRecommendationFailedRequest.php
  Recommender/src/V1/MarkRecommendationSucceededRequest.php
  Recommender/src/V1/Operation.php
  Recommender/synth.metadata
Labels: cla: yes, context: full

#4574 chore: updating protobuf from 3.15.3 to 3.18.1
  Channel/metadata/V1/Service.php
  Channel/src/V1/ChangeRenewalSettingsRequest.php
  Channel/src/V1/ChannelPartnerLink.php
  Channel/src/V1/CloudIdentityInfo.php
  Channel/src/V1/CommitmentSettings.php
  Channel/src/V1/Constraints.php
  Channel/src/V1/CreateChannelPartnerLinkRequest.php
  Channel/src/V1/CreateCustomerRequest.php
  Channel/src/V1/CreateEntitlementRequest.php
  Channel/src/V1/Customer.php
  Channel/src/V1/Entitlement.php
  Channel/src/V1/MarketingInfo.php
  Channel/src/V1/Offer.php
  Channel/src/V1/Parameter.php
  Channel/src/V1/ParameterDefinition.php
  Channel/src/V1/Plan.php
  Channel/src/V1/Price.php
  Channel/src/V1/PriceByResource.php
  Channel/src/V1/PricePhase.php
  Channel/src/V1/PriceTier.php
  Channel/src/V1/Product.php
  Channel/src/V1/ProvisionCloudIdentityRequest.php
  Channel/src/V1/PurchasableOffer.php
  Channel/src/V1/PurchasableSku.php
  Channel/src/V1/RenewalSettings.php
  Channel/src/V1/Sku.php
  Channel/src/V1/TransferableOffer.php
  Channel/src/V1/TransferableSku.php
  Channel/src/V1/TrialSettings.php
  Channel/src/V1/UpdateChannelPartnerLinkRequest.php
  Channel/src/V1/UpdateCustomerRequest.php
  Channel/synth.metadata
Labels: cla: yes, context: partial

#4706 feat: added resource type and display_name field to the FindingResult
  SecurityCenter/metadata/V1/Resource.php
  SecurityCenter/metadata/V1/SecuritycenterService.php
  SecurityCenter/src/V1/Gapic/SecurityCenterGapicClient.php
  SecurityCenter/src/V1/ListFindingsRequest.php
  SecurityCenter/src/V1/ListFindingsResponse/ListFindingsResult/Resource.php
  SecurityCenter/src/V1/Resource.php
  SecurityCenter/src/V1p1beta1/UpdateOrganizationSettingsRequest.php
  SecurityCenter/synth.metadata
Labels: cla: yes, context: full

#4703 [ResourceManager] docs: fix docstring formatting
  ResourceManager/src/V3/Gapic/FoldersGapicClient.php
  ResourceManager/src/V3/Gapic/OrganizationsGapicClient.php
  ResourceManager/src/V3/Gapic/ProjectsGapicClient.php
  ResourceManager/src/V3/SearchFoldersRequest.php
  ResourceManager/src/V3/SearchOrganizationsRequest.php
  ResourceManager/src/V3/SearchProjectsRequest.php
  ResourceManager/synth.metadata
Labels: cla: yes, context: full
