Repository googleapis/google-cloud-php, pull requests merged in 2021-07, with the labels that each got.

#4221 docs: update format method description
  ResourceManager/metadata/V3/Folders.php
  ResourceManager/metadata/V3/Organizations.php
  ResourceManager/metadata/V3/Projects.php
  ResourceManager/metadata/V3/TagBindings.php
  ResourceManager/metadata/V3/TagKeys.php
  ResourceManager/metadata/V3/TagValues.php
  ResourceManager/src/V3/Gapic/FoldersGapicClient.php
  ResourceManager/src/V3/Gapic/OrganizationsGapicClient.php
  ResourceManager/src/V3/Gapic/ProjectsGapicClient.php
  ResourceManager/src/V3/Gapic/TagBindingsGapicClient.php
  ResourceManager/src/V3/Gapic/TagKeysGapicClient.php
  ResourceManager/src/V3/Gapic/TagValuesGapicClient.php
  ResourceManager/synth.metadata
Labels: cla: yes, context: partial

#4220 [PubSub] feat: Adding subscription properties to streaming pull response in third party pubsub.proto.
  PubSub/metadata/V1/Pubsub.php
  PubSub/src/V1/StreamingPullResponse.php
  PubSub/src/V1/StreamingPullResponse/SubscriptionProperties.php
  PubSub/src/V1/StreamingPullResponse_SubscriptionProperties.php
  PubSub/synth.metadata
Labels: cla: yes, context: full

#4223 feat: add leader_options to InstanceConfig and default_leader to Database
  Spanner/metadata/Admin/Database/V1/SpannerDatabaseAdmin.php
  Spanner/metadata/Admin/Instance/V1/SpannerInstanceAdmin.php
  Spanner/src/Admin/Database/V1/Database.php
  Spanner/src/Admin/Instance/V1/InstanceConfig.php
  Spanner/synth.metadata
  Spanner/tests/Unit/Admin/Database/V1/DatabaseAdminClientTest.php
Labels: api: spanner, cla: yes, context: full

#4111 feat(spanner): add support for LCI
  .github/workflows/spanner-emulator-system-tests.yaml
  Spanner/src/Connection/Grpc.php
  Spanner/src/Instance.php
  Spanner/tests/System/AdminTest.php
  Spanner/tests/Unit/Connection/GrpcTest.php
  Spanner/tests/Unit/InstanceTest.php
  Spanner/tests/Unit/SpannerClientTest.php
Labels: api: spanner, cla: yes

#4229 docs: add more detail on notification class usage
  Storage/src/Notification.php
Labels: cla: yes

#4243 fix: return method signature to non breaking state
  VideoIntelligence/src/V1/Gapic/VideoIntelligenceServiceGapicClient.php
  VideoIntelligence/tests/Unit/V1/VideoIntelligenceServiceClientTest.php
Labels: cla: yes

#4256 chore: update bigquery discovery document
  BigQuery/src/Connection/ServiceDefinition/bigquery-v2.json
Labels: api: bigquery, cla: yes

#4252 fix: correctly decode empty map values
  Firestore/src/ValueMapper.php
  Firestore/tests/System/ValueMapperTest.php
  Firestore/tests/Unit/ValueMapperTest.php
Labels: cla: yes

#4246 [BigQueryConnection] feat: add cloud spanner connection support
  BigQueryConnection/metadata/V1/Connection.php
  BigQueryConnection/src/V1/AwsAccessRole.php
  BigQueryConnection/src/V1/AwsProperties.php
  BigQueryConnection/src/V1/CloudSpannerProperties.php
  BigQueryConnection/src/V1/Connection.php
  BigQueryConnection/synth.metadata
Labels: cla: yes, context: full

#4242 [SecretManager] feat: Tune Secret Manager auto retry parameters
  SecretManager/src/V1/resources/secret_manager_service_client_config.json
  SecretManager/synth.metadata
Labels: cla: yes, context: full
