Repository googleapis/google-cloud-php, pull requests merged in 2021-03, with the labels that each got.

#3889 [WebSecurityScanner] chore: update protobuf v3.15.3
  WebSecurityScanner/src/V1beta/CreateScanConfigRequest.php
  WebSecurityScanner/src/V1beta/Finding.php
  WebSecurityScanner/src/V1beta/ScanConfig.php
  WebSecurityScanner/src/V1beta/ScanConfig/Authentication.php
  WebSecurityScanner/src/V1beta/ScanConfig/Schedule.php
  WebSecurityScanner/src/V1beta/ScanRun.php
  WebSecurityScanner/src/V1beta/ScanRunErrorTrace.php
  WebSecurityScanner/src/V1beta/UpdateScanConfigRequest.php
  WebSecurityScanner/synth.metadata
Labels: cla: yes, context: full

#3888 [WebRisk] chore: update protobuf v3.15.3
  WebRisk/src/V1/ComputeThreatListDiffRequest.php
  WebRisk/src/V1/ComputeThreatListDiffResponse.php
  WebRisk/src/V1/CreateSubmissionRequest.php
  WebRisk/src/V1/SearchHashesResponse.php
  WebRisk/src/V1/SearchHashesResponse/ThreatHash.php
  WebRisk/src/V1/SearchUrisResponse.php
  WebRisk/src/V1/SearchUrisResponse/ThreatUri.php
  WebRisk/src/V1/ThreatEntryAdditions.php
  WebRisk/src/V1/ThreatEntryRemovals.php
  WebRisk/src/V1beta1/ComputeThreatListDiffRequest.php
  WebRisk/src/V1beta1/ComputeThreatListDiffResponse.php
  WebRisk/src/V1beta1/SearchHashesResponse.php
  WebRisk/src/V1beta1/SearchHashesResponse/ThreatHash.php
  WebRisk/src/V1beta1/SearchUrisResponse.php
  WebRisk/src/V1beta1/SearchUrisResponse/ThreatUri.php
  WebRisk/src/V1beta1/ThreatEntryAdditions.php
  WebRisk/src/V1beta1/ThreatEntryRemovals.php
  WebRisk/synth.metadata
Labels: cla: yes, context: full

#3887 [Vision] chore: update protobuf v3.15.3
  Vision/src/V1/AnnotateFileRequest.php
  Vision/src/V1/AnnotateFileResponse.php
  Vision/src/V1/AnnotateImageRequest.php
  Vision/src/V1/AnnotateImageResponse.php
  Vision/src/V1/AsyncAnnotateFileRequest.php
  Vision/src/V1/AsyncAnnotateFileResponse.php
  Vision/src/V1/AsyncBatchAnnotateImagesRequest.php
  Vision/src/V1/AsyncBatchAnnotateImagesResponse.php
  Vision/src/V1/BatchOperationMetadata.php
  Vision/src/V1/Block.php
  Vision/src/V1/ColorInfo.php
  Vision/src/V1/CreateProductRequest.php
  Vision/src/V1/CreateProductSetRequest.php
  Vision/src/V1/CreateReferenceImageRequest.php
  Vision/src/V1/CropHint.php
  Vision/src/V1/EntityAnnotation.php
  Vision/src/V1/FaceAnnotation.php
  Vision/src/V1/FaceAnnotation/Landmark.php
  Vision/src/V1/Image.php
  Vision/src/V1/ImageContext.php
  Vision/src/V1/ImageProperties.php
  Vision/src/V1/ImportProductSetsInputConfig.php
  Vision/src/V1/ImportProductSetsRequest.php
  Vision/src/V1/InputConfig.php
  Vision/src/V1/LatLongRect.php
  Vision/src/V1/LocalizedObjectAnnotation.php
  Vision/src/V1/LocationInfo.php
  Vision/src/V1/OperationMetadata.php
  Vision/src/V1/OutputConfig.php
  Vision/src/V1/Page.php
  Vision/src/V1/Paragraph.php
  Vision/src/V1/ProductSearchParams.php
  Vision/src/V1/ProductSearchResults.php
  Vision/src/V1/ProductSearchResults/GroupedResult.php
  Vision/src/V1/ProductSearchResults/Result.php
  Vision/src/V1/ProductSet.php
  Vision/src/V1/PurgeProductsRequest.php
  Vision/src/V1/SafeSearchAnnotation.php
  Vision/src/V1/Symbol.php
  Vision/src/V1/TextAnnotation/TextProperty.php
  Vision/src/V1/UpdateProductRequest.php
  Vision/src/V1/UpdateProductSetRequest.php
  Vision/src/V1/Word.php
  Vision/synth.metadata
Labels: cla: yes, context: full

#3886 [VideoIntelligence] chore: update protobuf v3.15.3
  VideoIntelligence/src/V1/AnnotateVideoRequest.php
  VideoIntelligence/src/V1/DetectedLandmark.php
  VideoIntelligence/src/V1/ExplicitContentFrame.php
  VideoIntelligence/src/V1/FaceFrame.php
  VideoIntelligence/src/V1/FaceSegment.php
  VideoIntelligence/src/V1/LabelAnnotation.php
  VideoIntelligence/src/V1/LabelFrame.php
  VideoIntelligence/src/V1/LabelSegment.php
  VideoIntelligence/src/V1/LogoRecognitionAnnotation.php
  VideoIntelligence/src/V1/ObjectTrackingAnnotation.php
  VideoIntelligence/src/V1/ObjectTrackingFrame.php
  VideoIntelligence/src/V1/TextFrame.php
  VideoIntelligence/src/V1/TextSegment.php
  VideoIntelligence/src/V1/TimestampedObject.php
  VideoIntelligence/src/V1/Track.php
  VideoIntelligence/src/V1/VideoAnnotationProgress.php
  VideoIntelligence/src/V1/VideoAnnotationResults.php
  VideoIntelligence/src/V1/VideoContext.php
  VideoIntelligence/src/V1/VideoSegment.php
  VideoIntelligence/src/V1/WordInfo.php
  VideoIntelligence/src/V1beta2/AnnotateVideoRequest.php
  VideoIntelligence/src/V1beta2/ExplicitContentFrame.php
  VideoIntelligence/src/V1beta2/FaceFrame.php
  VideoIntelligence/src/V1beta2/FaceSegment.php
  VideoIntelligence/src/V1beta2/LabelAnnotation.php
  VideoIntelligence/src/V1beta2/LabelFrame.php
  VideoIntelligence/src/V1beta2/LabelSegment.php
  VideoIntelligence/src/V1beta2/VideoAnnotationProgress.php
  VideoIntelligence/src/V1beta2/VideoAnnotationResults.php
  VideoIntelligence/src/V1beta2/VideoContext.php
  VideoIntelligence/src/V1beta2/VideoSegment.php
  VideoIntelligence/synth.metadata
Labels: cla: yes, context: full

#3884 [TextToSpeech] chore: update protobuf v3.15.3
  TextToSpeech/src/V1/SynthesizeSpeechRequest.php
  TextToSpeech/synth.metadata
Labels: cla: yes, context: full

#3885 [Trace] chore: update protobuf v3.15.3
  Trace/src/V2/AttributeValue.php
  Trace/src/V2/Module.php
  Trace/src/V2/Span.php
  Trace/src/V2/Span/Link.php
  Trace/src/V2/Span/TimeEvent.php
  Trace/src/V2/Span/TimeEvent/Annotation.php
  Trace/src/V2/StackTrace.php
  Trace/src/V2/StackTrace/StackFrame.php
  Trace/synth.metadata
Labels: cla: yes, context: full

#3881 [ServiceDirectory] chore: update protobuf v3.15.3
  ServiceDirectory/src/V1/CreateEndpointRequest.php
  ServiceDirectory/src/V1/CreateNamespaceRequest.php
  ServiceDirectory/src/V1/CreateServiceRequest.php
  ServiceDirectory/src/V1/ResolveServiceResponse.php
  ServiceDirectory/src/V1/UpdateEndpointRequest.php
  ServiceDirectory/src/V1/UpdateNamespaceRequest.php
  ServiceDirectory/src/V1/UpdateServiceRequest.php
  ServiceDirectory/src/V1beta1/CreateEndpointRequest.php
  ServiceDirectory/src/V1beta1/CreateNamespaceRequest.php
  ServiceDirectory/src/V1beta1/CreateServiceRequest.php
  ServiceDirectory/src/V1beta1/ResolveServiceResponse.php
  ServiceDirectory/src/V1beta1/UpdateEndpointRequest.php
  ServiceDirectory/src/V1beta1/UpdateNamespaceRequest.php
  ServiceDirectory/src/V1beta1/UpdateServiceRequest.php
  ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#3879 [Scheduler] chore: update protobuf v3.15.3
  Scheduler/src/V1/AppEngineHttpTarget.php
  Scheduler/src/V1/CreateJobRequest.php
  Scheduler/src/V1/HttpTarget.php
  Scheduler/src/V1/Job.php
  Scheduler/src/V1/RetryConfig.php
  Scheduler/src/V1/UpdateJobRequest.php
  Scheduler/src/V1beta1/AppEngineHttpTarget.php
  Scheduler/src/V1beta1/CreateJobRequest.php
  Scheduler/src/V1beta1/HttpTarget.php
  Scheduler/src/V1beta1/Job.php
  Scheduler/src/V1beta1/RetryConfig.php
  Scheduler/src/V1beta1/UpdateJobRequest.php
  Scheduler/synth.metadata
Labels: cla: yes, context: full

#3874 [PubSub] chore: update protobuf v3.15.3
  PubSub/src/V1/CreateSchemaRequest.php
  PubSub/src/V1/ExpirationPolicy.php
  PubSub/src/V1/ModifyPushConfigRequest.php
  PubSub/src/V1/PubsubMessage.php
  PubSub/src/V1/PullRequest.php
  PubSub/src/V1/PushConfig.php
  PubSub/src/V1/ReceivedMessage.php
  PubSub/src/V1/RetryPolicy.php
  PubSub/src/V1/SeekRequest.php
  PubSub/src/V1/Snapshot.php
  PubSub/src/V1/Subscription.php
  PubSub/src/V1/Topic.php
  PubSub/src/V1/UpdateSnapshotRequest.php
  PubSub/src/V1/UpdateSubscriptionRequest.php
  PubSub/src/V1/UpdateTopicRequest.php
  PubSub/src/V1/ValidateMessageRequest.php
  PubSub/src/V1/ValidateSchemaRequest.php
  PubSub/synth.metadata
Labels: cla: yes, context: full

#3877 [Redis] chore: update protobuf v3.15.3
  Redis/src/V1/CreateInstanceRequest.php
  Redis/src/V1/ExportInstanceRequest.php
  Redis/src/V1/ImportInstanceRequest.php
  Redis/src/V1/InputConfig.php
  Redis/src/V1/Instance.php
  Redis/src/V1/OperationMetadata.php
  Redis/src/V1/OutputConfig.php
  Redis/src/V1/UpdateInstanceRequest.php
  Redis/src/V1beta1/CreateInstanceRequest.php
  Redis/src/V1beta1/ExportInstanceRequest.php
  Redis/src/V1beta1/ImportInstanceRequest.php
  Redis/src/V1beta1/InputConfig.php
  Redis/src/V1beta1/Instance.php
  Redis/src/V1beta1/OutputConfig.php
  Redis/src/V1beta1/UpdateInstanceRequest.php
  Redis/synth.metadata
Labels: cla: yes, context: full

#3875 [RecaptchaEnterprise] chore: update protobuf v3.15.3
  RecaptchaEnterprise/src/V1/Assessment.php
  RecaptchaEnterprise/src/V1/CreateAssessmentRequest.php
  RecaptchaEnterprise/src/V1/CreateKeyRequest.php
  RecaptchaEnterprise/src/V1/Key.php
  RecaptchaEnterprise/src/V1/TokenProperties.php
  RecaptchaEnterprise/src/V1/UpdateKeyRequest.php
  RecaptchaEnterprise/synth.metadata
Labels: cla: yes, context: full

#3873 [OsLogin] chore: update protobuf v3.15.3
  OsLogin/src/V1/ImportSshPublicKeyRequest.php
  OsLogin/src/V1/ImportSshPublicKeyResponse.php
  OsLogin/src/V1/UpdateSshPublicKeyRequest.php
  OsLogin/src/V1beta/ImportSshPublicKeyRequest.php
  OsLogin/src/V1beta/ImportSshPublicKeyResponse.php
  OsLogin/src/V1beta/UpdateSshPublicKeyRequest.php
  OsLogin/synth.metadata
Labels: cla: yes, context: full

#3872 [OsConfig] chore: update protobuf v3.15.3
  OsConfig/src/V1/CreatePatchDeploymentRequest.php
  OsConfig/src/V1/ExecStep.php
  OsConfig/src/V1/ExecStepConfig.php
  OsConfig/src/V1/ExecutePatchJobRequest.php
  OsConfig/src/V1/Inventory.php
  OsConfig/src/V1/Inventory/Item.php
  OsConfig/src/V1/Inventory/SoftwarePackage.php
  OsConfig/src/V1/Inventory/WindowsQuickFixEngineeringPackage.php
  OsConfig/src/V1/Inventory/WindowsUpdatePackage.php
  OsConfig/src/V1/MonthlySchedule.php
  OsConfig/src/V1/OneTimeSchedule.php
  OsConfig/src/V1/PatchConfig.php
  OsConfig/src/V1/PatchDeployment.php
  OsConfig/src/V1/PatchJob.php
  OsConfig/src/V1/PatchRollout.php
  OsConfig/src/V1/RecurringSchedule.php
  OsConfig/synth.metadata
Labels: cla: yes, context: full

#3865 [Debugger] chore: update protobuf v3.15.3
  Debugger/src/V2/Breakpoint.php
  Debugger/src/V2/Debuggee.php
  Debugger/src/V2/GetBreakpointResponse.php
  Debugger/src/V2/ListBreakpointsRequest.php
  Debugger/src/V2/RegisterDebuggeeRequest.php
  Debugger/src/V2/RegisterDebuggeeResponse.php
  Debugger/src/V2/SetBreakpointRequest.php
  Debugger/src/V2/SetBreakpointResponse.php
  Debugger/src/V2/StackFrame.php
  Debugger/src/V2/StatusMessage.php
  Debugger/src/V2/UpdateActiveBreakpointRequest.php
  Debugger/src/V2/Variable.php
  Debugger/synth.metadata
Labels: cla: yes, context: full

#3868 [Iot] chore: update protobuf v3.15.3
  Iot/src/V1/CreateDeviceRegistryRequest.php
  Iot/src/V1/CreateDeviceRequest.php
  Iot/src/V1/Device.php
  Iot/src/V1/DeviceConfig.php
  Iot/src/V1/DeviceCredential.php
  Iot/src/V1/DeviceRegistry.php
  Iot/src/V1/DeviceState.php
  Iot/src/V1/GatewayConfig.php
  Iot/src/V1/GetDeviceRequest.php
  Iot/src/V1/ListDevicesRequest.php
  Iot/src/V1/PublicKeyCertificate.php
  Iot/src/V1/RegistryCredential.php
  Iot/src/V1/UpdateDeviceRegistryRequest.php
  Iot/src/V1/UpdateDeviceRequest.php
  Iot/src/V1/X509CertificateDetails.php
  Iot/synth.metadata
Labels: cla: yes, context: full

#3871 [Memcache] chore: update protobuf v3.15.3
  Memcache/src/V1/CreateInstanceRequest.php
  Memcache/src/V1/Instance.php
  Memcache/src/V1/Instance/Node.php
  Memcache/src/V1/OperationMetadata.php
  Memcache/src/V1/UpdateInstanceRequest.php
  Memcache/src/V1/UpdateParametersRequest.php
  Memcache/src/V1beta2/CreateInstanceRequest.php
  Memcache/src/V1beta2/Instance.php
  Memcache/src/V1beta2/Instance/Node.php
  Memcache/src/V1beta2/OperationMetadata.php
  Memcache/src/V1beta2/UpdateInstanceRequest.php
  Memcache/src/V1beta2/UpdateParametersRequest.php
  Memcache/synth.metadata
Labels: cla: yes, context: full

#3870 [Language] chore: update protobuf v3.15.3
  Language/src/V1/AnalyzeEntitiesRequest.php
  Language/src/V1/AnalyzeEntitySentimentRequest.php
  Language/src/V1/AnalyzeSentimentRequest.php
  Language/src/V1/AnalyzeSentimentResponse.php
  Language/src/V1/AnalyzeSyntaxRequest.php
  Language/src/V1/AnnotateTextRequest.php
  Language/src/V1/AnnotateTextResponse.php
  Language/src/V1/ClassifyTextRequest.php
  Language/src/V1/Entity.php
  Language/src/V1/EntityMention.php
  Language/src/V1/Sentence.php
  Language/src/V1/Token.php
  Language/src/V1beta2/AnalyzeEntitiesRequest.php
  Language/src/V1beta2/AnalyzeEntitySentimentRequest.php
  Language/src/V1beta2/AnalyzeSentimentRequest.php
  Language/src/V1beta2/AnalyzeSentimentResponse.php
  Language/src/V1beta2/AnalyzeSyntaxRequest.php
  Language/src/V1beta2/AnnotateTextRequest.php
  Language/src/V1beta2/AnnotateTextResponse.php
  Language/src/V1beta2/ClassifyTextRequest.php
  Language/src/V1beta2/Entity.php
  Language/src/V1beta2/EntityMention.php
  Language/src/V1beta2/Sentence.php
  Language/src/V1beta2/Token.php
  Language/synth.metadata
Labels: cla: yes, context: full

#3869 [Kms] chore: update protobuf v3.15.3
  Kms/src/V1/AsymmetricDecryptRequest.php
  Kms/src/V1/AsymmetricDecryptResponse.php
  Kms/src/V1/AsymmetricSignRequest.php
  Kms/src/V1/AsymmetricSignResponse.php
  Kms/src/V1/CreateCryptoKeyRequest.php
  Kms/src/V1/CreateCryptoKeyVersionRequest.php
  Kms/src/V1/CreateImportJobRequest.php
  Kms/src/V1/CreateKeyRingRequest.php
  Kms/src/V1/CryptoKey.php
  Kms/src/V1/CryptoKeyVersion.php
  Kms/src/V1/DecryptRequest.php
  Kms/src/V1/DecryptResponse.php
  Kms/src/V1/EncryptRequest.php
  Kms/src/V1/EncryptResponse.php
  Kms/src/V1/ImportJob.php
  Kms/src/V1/KeyRing.php
  Kms/src/V1/PublicKey.php
  Kms/src/V1/UpdateCryptoKeyRequest.php
  Kms/src/V1/UpdateCryptoKeyVersionRequest.php
  Kms/synth.metadata
Labels: cla: yes, context: full

#3867 [Firestore] chore: update protobuf v3.15.3
  Firestore/src/Admin/V1/CreateIndexRequest.php
  Firestore/src/Admin/V1/ExportDocumentsMetadata.php
  Firestore/src/Admin/V1/Field.php
  Firestore/src/Admin/V1/FieldOperationMetadata.php
  Firestore/src/Admin/V1/FieldOperationMetadata/IndexConfigDelta.php
  Firestore/src/Admin/V1/ImportDocumentsMetadata.php
  Firestore/src/Admin/V1/IndexOperationMetadata.php
  Firestore/src/Admin/V1/UpdateFieldRequest.php
  Firestore/src/V1/BatchGetDocumentsRequest.php
  Firestore/src/V1/BatchGetDocumentsResponse.php
  Firestore/src/V1/BeginTransactionRequest.php
  Firestore/src/V1/CommitResponse.php
  Firestore/src/V1/CreateDocumentRequest.php
  Firestore/src/V1/DeleteDocumentRequest.php
  Firestore/src/V1/Document.php
  Firestore/src/V1/DocumentChange.php
  Firestore/src/V1/DocumentDelete.php
  Firestore/src/V1/DocumentRemove.php
  Firestore/src/V1/DocumentTransform/FieldTransform.php
  Firestore/src/V1/GetDocumentRequest.php
  Firestore/src/V1/ListDocumentsRequest.php
  Firestore/src/V1/ListenRequest.php
  Firestore/src/V1/ListenResponse.php
  Firestore/src/V1/PartitionQueryRequest.php
  Firestore/src/V1/Precondition.php
  Firestore/src/V1/RunQueryRequest.php
  Firestore/src/V1/RunQueryResponse.php
  Firestore/src/V1/StructuredQuery.php
  Firestore/src/V1/StructuredQuery/FieldFilter.php
  Firestore/src/V1/StructuredQuery/Filter.php
  Firestore/src/V1/StructuredQuery/Order.php
  Firestore/src/V1/StructuredQuery/UnaryFilter.php
  Firestore/src/V1/Target.php
  Firestore/src/V1/Target/QueryTarget.php
  Firestore/src/V1/TargetChange.php
  Firestore/src/V1/TransactionOptions.php
  Firestore/src/V1/TransactionOptions/ReadOnly.php
  Firestore/src/V1/UpdateDocumentRequest.php
  Firestore/src/V1/Value.php
  Firestore/src/V1/Write.php
  Firestore/src/V1/WriteResponse.php
  Firestore/src/V1/WriteResult.php
  Firestore/synth.metadata
Labels: cla: yes, context: full

#3854 [AssuredWorkloads] chore: update protobuf v3.15.3
  AssuredWorkloads/src/V1beta1/CreateWorkloadOperationMetadata.php
  AssuredWorkloads/src/V1beta1/CreateWorkloadRequest.php
  AssuredWorkloads/src/V1beta1/UpdateWorkloadRequest.php
  AssuredWorkloads/src/V1beta1/Workload.php
  AssuredWorkloads/src/V1beta1/Workload/CJISSettings.php
  AssuredWorkloads/src/V1beta1/Workload/FedrampHighSettings.php
  AssuredWorkloads/src/V1beta1/Workload/FedrampModerateSettings.php
  AssuredWorkloads/src/V1beta1/Workload/IL4Settings.php
  AssuredWorkloads/src/V1beta1/Workload/KMSSettings.php
  AssuredWorkloads/synth.metadata
Labels: cla: yes, context: full

#3856 [BigQueryConnection] chore: update protobuf v3.15.3
  BigQueryConnection/src/V1/AwsProperties.php
  BigQueryConnection/src/V1/CloudSqlProperties.php
  BigQueryConnection/src/V1/Connection.php
  BigQueryConnection/src/V1/CreateConnectionRequest.php
  BigQueryConnection/src/V1/UpdateConnectionRequest.php
  BigQueryConnection/synth.metadata
Labels: cla: yes, context: full

#3862 [DataCatalog] chore: update protobuf v3.15.3
  DataCatalog/src/V1/BigQueryTableSpec.php
  DataCatalog/src/V1/CreateEntryGroupRequest.php
  DataCatalog/src/V1/CreateEntryRequest.php
  DataCatalog/src/V1/CreateTagRequest.php
  DataCatalog/src/V1/CreateTagTemplateFieldRequest.php
  DataCatalog/src/V1/CreateTagTemplateRequest.php
  DataCatalog/src/V1/Entry.php
  DataCatalog/src/V1/EntryGroup.php
  DataCatalog/src/V1/FieldType.php
  DataCatalog/src/V1/GcsFileSpec.php
  DataCatalog/src/V1/GetEntryGroupRequest.php
  DataCatalog/src/V1/ListEntriesRequest.php
  DataCatalog/src/V1/SearchCatalogRequest.php
  DataCatalog/src/V1/SystemTimestamps.php
  DataCatalog/src/V1/TagField.php
  DataCatalog/src/V1/TagTemplateField.php
  DataCatalog/src/V1/UpdateEntryGroupRequest.php
  DataCatalog/src/V1/UpdateEntryRequest.php
  DataCatalog/src/V1/UpdateTagRequest.php
  DataCatalog/src/V1/UpdateTagTemplateFieldRequest.php
  DataCatalog/src/V1/UpdateTagTemplateRequest.php
  DataCatalog/synth.metadata
Labels: cla: yes, context: full

#3861 [Container] chore: update protobuf v3.15.3
  Container/src/V1/AddonsConfig.php
  Container/src/V1/AutoprovisioningNodePoolDefaults.php
  Container/src/V1/CancelOperationRequest.php
  Container/src/V1/Cluster.php
  Container/src/V1/ClusterAutoscaling.php
  Container/src/V1/ClusterUpdate.php
  Container/src/V1/CompleteIPRotationRequest.php
  Container/src/V1/CreateClusterRequest.php
  Container/src/V1/CreateNodePoolRequest.php
  Container/src/V1/DeleteClusterRequest.php
  Container/src/V1/DeleteNodePoolRequest.php
  Container/src/V1/GetClusterRequest.php
  Container/src/V1/GetNodePoolRequest.php
  Container/src/V1/GetOperationRequest.php
  Container/src/V1/GetServerConfigRequest.php
  Container/src/V1/IPAllocationPolicy.php
  Container/src/V1/ListClustersRequest.php
  Container/src/V1/ListNodePoolsRequest.php
  Container/src/V1/ListOperationsRequest.php
  Container/src/V1/MaintenancePolicy.php
  Container/src/V1/MaintenanceWindow.php
  Container/src/V1/MasterAuth.php
  Container/src/V1/NetworkConfig.php
  Container/src/V1/NodeConfig.php
  Container/src/V1/NodeManagement.php
  Container/src/V1/NodePool.php
  Container/src/V1/Operation.php
  Container/src/V1/PrivateClusterConfig.php
  Container/src/V1/RecurringTimeWindow.php
  Container/src/V1/ResourceUsageExportConfig.php
  Container/src/V1/RollbackNodePoolUpgradeRequest.php
  Container/src/V1/SetAddonsConfigRequest.php
  Container/src/V1/SetLabelsRequest.php
  Container/src/V1/SetLegacyAbacRequest.php
  Container/src/V1/SetLocationsRequest.php
  Container/src/V1/SetLoggingServiceRequest.php
  Container/src/V1/SetMaintenancePolicyRequest.php
  Container/src/V1/SetMasterAuthRequest.php
  Container/src/V1/SetMonitoringServiceRequest.php
  Container/src/V1/SetNetworkPolicyRequest.php
  Container/src/V1/SetNodePoolAutoscalingRequest.php
  Container/src/V1/SetNodePoolManagementRequest.php
  Container/src/V1/SetNodePoolSizeRequest.php
  Container/src/V1/StartIPRotationRequest.php
  Container/src/V1/TimeWindow.php
  Container/src/V1/UpdateClusterRequest.php
  Container/src/V1/UpdateMasterRequest.php
  Container/src/V1/UpdateNodePoolRequest.php
  Container/synth.metadata
Labels: cla: yes, context: full

#3860 [Billing] chore: update protobuf v3.15.3
  Billing/src/V1/CreateBillingAccountRequest.php
  Billing/src/V1/ListSkusRequest.php
  Billing/src/V1/PricingExpression/TierRate.php
  Billing/src/V1/PricingInfo.php
  Billing/src/V1/Sku.php
  Billing/src/V1/UpdateBillingAccountRequest.php
  Billing/src/V1/UpdateProjectBillingInfoRequest.php
  Billing/synth.metadata
Labels: cla: yes, context: full

#3864 [Datastore] chore: update protobuf v3.15.3
  Datastore/src/V1/BeginTransactionRequest.php
  Datastore/src/V1/Entity.php
  Datastore/src/V1/EntityResult.php
  Datastore/src/V1/Filter.php
  Datastore/src/V1/GqlQueryParameter.php
  Datastore/src/V1/Key.php
  Datastore/src/V1/LookupRequest.php
  Datastore/src/V1/Mutation.php
  Datastore/src/V1/MutationResult.php
  Datastore/src/V1/Projection.php
  Datastore/src/V1/PropertyFilter.php
  Datastore/src/V1/PropertyOrder.php
  Datastore/src/V1/Query.php
  Datastore/src/V1/RunQueryRequest.php
  Datastore/src/V1/RunQueryResponse.php
  Datastore/src/V1/TransactionOptions.php
  Datastore/src/V1/Value.php
  Datastore/synth.metadata
Labels: cla: yes, context: full

#3857 [BigQueryDataTransfer] chore: update protobuf v3.15.3
  BigQueryDataTransfer/src/V1/CreateTransferConfigRequest.php
  BigQueryDataTransfer/src/V1/DataSource.php
  BigQueryDataTransfer/src/V1/DataSourceParameter.php
  BigQueryDataTransfer/src/V1/ScheduleOptions.php
  BigQueryDataTransfer/src/V1/ScheduleTransferRunsRequest.php
  BigQueryDataTransfer/src/V1/StartManualTransferRunsRequest.php
  BigQueryDataTransfer/src/V1/StartManualTransferRunsRequest/TimeRange.php
  BigQueryDataTransfer/src/V1/TransferConfig.php
  BigQueryDataTransfer/src/V1/TransferMessage.php
  BigQueryDataTransfer/src/V1/TransferRun.php
  BigQueryDataTransfer/src/V1/UpdateTransferConfigRequest.php
  BigQueryDataTransfer/synth.metadata
Labels: cla: yes, context: full

#3859 [BigQueryStorage] chore: update protobuf v3.15.3
  BigQueryStorage/src/V1/CreateReadSessionRequest.php
  BigQueryStorage/src/V1/ReadRowsResponse.php
  BigQueryStorage/src/V1/ReadSession.php
  BigQueryStorage/src/V1/ReadSession/TableModifiers.php
  BigQueryStorage/src/V1/SplitReadStreamResponse.php
  BigQueryStorage/src/V1/StreamStats.php
  BigQueryStorage/synth.metadata
Labels: cla: yes, context: full

#3858 [BigQueryReservation] chore: update protobuf v3.15.3
  BigQueryReservation/src/V1/BiReservation.php
  BigQueryReservation/src/V1/CapacityCommitment.php
  BigQueryReservation/src/V1/CreateAssignmentRequest.php
  BigQueryReservation/src/V1/CreateCapacityCommitmentRequest.php
  BigQueryReservation/src/V1/CreateReservationRequest.php
  BigQueryReservation/src/V1/SplitCapacityCommitmentResponse.php
  BigQueryReservation/src/V1/UpdateBiReservationRequest.php
  BigQueryReservation/src/V1/UpdateCapacityCommitmentRequest.php
  BigQueryReservation/src/V1/UpdateReservationRequest.php
  BigQueryReservation/synth.metadata
Labels: cla: yes, context: full

#3845 [Bigtable] feat: Publish new fields to support Customer Managed Encryption Keys (CMEK) on the existing Cloud Bigtable service methods.
  Bigtable/metadata/Admin/V2/Instance.php
  Bigtable/metadata/Admin/V2/Table.php
  Bigtable/src/Admin/V2/AppProfile.php
  Bigtable/src/Admin/V2/Backup.php
  Bigtable/src/Admin/V2/Cluster.php
  Bigtable/src/Admin/V2/Cluster/EncryptionConfig.php
  Bigtable/src/Admin/V2/Cluster_EncryptionConfig.php
  Bigtable/src/Admin/V2/EncryptionInfo.php
  Bigtable/src/Admin/V2/EncryptionInfo/EncryptionType.php
  Bigtable/src/Admin/V2/EncryptionInfo_EncryptionType.php
  Bigtable/src/Admin/V2/Gapic/BigtableInstanceAdminGapicClient.php
  Bigtable/src/Admin/V2/Snapshot.php
  Bigtable/src/Admin/V2/Table.php
  Bigtable/src/Admin/V2/Table/ClusterState.php
  Bigtable/src/Admin/V2/Table/View.php
  Bigtable/synth.metadata
Labels: cla: yes, context: full

#3840 [Dialogflow] feat: add additional_bindings to Dialogflow v2 ListIntents API docs: update copyrights and session docs
  Dialogflow/metadata/V2/Intent.php
  Dialogflow/src/V2/AgentsGrpcClient.php
  Dialogflow/src/V2/ContextsGrpcClient.php
  Dialogflow/src/V2/DetectIntentRequest.php
  Dialogflow/src/V2/EntityTypesGrpcClient.php
  Dialogflow/src/V2/EnvironmentsGrpcClient.php
  Dialogflow/src/V2/Gapic/SessionsGapicClient.php
  Dialogflow/src/V2/IntentsGrpcClient.php
  Dialogflow/src/V2/SessionEntityTypesGrpcClient.php
  Dialogflow/src/V2/SessionsGrpcClient.php
  Dialogflow/src/V2/resources/agents_rest_client_config.php
  Dialogflow/src/V2/resources/contexts_rest_client_config.php
  Dialogflow/src/V2/resources/entity_types_rest_client_config.php
  Dialogflow/src/V2/resources/environments_rest_client_config.php
  Dialogflow/src/V2/resources/intents_rest_client_config.php
  Dialogflow/src/V2/resources/session_entity_types_rest_client_config.php
  Dialogflow/src/V2/resources/sessions_rest_client_config.php
  Dialogflow/synth.metadata
Labels: cla: yes, context: full

#3883 [Tasks] chore: update protobuf v3.15.3
  Tasks/src/V2/AppEngineHttpRequest.php
  Tasks/src/V2/Attempt.php
  Tasks/src/V2/CreateQueueRequest.php
  Tasks/src/V2/CreateTaskRequest.php
  Tasks/src/V2/HttpRequest.php
  Tasks/src/V2/Queue.php
  Tasks/src/V2/RetryConfig.php
  Tasks/src/V2/Task.php
  Tasks/src/V2/UpdateQueueRequest.php
  Tasks/src/V2beta2/AcknowledgeTaskRequest.php
  Tasks/src/V2beta2/AppEngineHttpRequest.php
  Tasks/src/V2beta2/AppEngineHttpTarget.php
  Tasks/src/V2beta2/AttemptStatus.php
  Tasks/src/V2beta2/CancelLeaseRequest.php
  Tasks/src/V2beta2/CreateQueueRequest.php
  Tasks/src/V2beta2/CreateTaskRequest.php
  Tasks/src/V2beta2/GetQueueRequest.php
  Tasks/src/V2beta2/LeaseTasksRequest.php
  Tasks/src/V2beta2/ListQueuesRequest.php
  Tasks/src/V2beta2/Queue.php
  Tasks/src/V2beta2/QueueStats.php
  Tasks/src/V2beta2/RenewLeaseRequest.php
  Tasks/src/V2beta2/RetryConfig.php
  Tasks/src/V2beta2/Task.php
  Tasks/src/V2beta2/TaskStatus.php
  Tasks/src/V2beta2/UpdateQueueRequest.php
  Tasks/src/V2beta3/AppEngineHttpQueue.php
  Tasks/src/V2beta3/AppEngineHttpRequest.php
  Tasks/src/V2beta3/Attempt.php
  Tasks/src/V2beta3/CreateQueueRequest.php
  Tasks/src/V2beta3/CreateTaskRequest.php
  Tasks/src/V2beta3/GetQueueRequest.php
  Tasks/src/V2beta3/HttpRequest.php
  Tasks/src/V2beta3/ListQueuesRequest.php
  Tasks/src/V2beta3/Queue.php
  Tasks/src/V2beta3/QueueStats.php
  Tasks/src/V2beta3/RetryConfig.php
  Tasks/src/V2beta3/Task.php
  Tasks/src/V2beta3/UpdateQueueRequest.php
  Tasks/synth.metadata
Labels: cla: yes, context: full

#3853 [AnalyticsData] chore: update protobuf v3.15.3
  AnalyticsData/src/V1alpha/BatchRunPivotReportsRequest.php
  AnalyticsData/src/V1alpha/BatchRunReportsRequest.php
  AnalyticsData/src/V1alpha/Cohort.php
  AnalyticsData/src/V1alpha/CohortSpec.php
  AnalyticsData/src/V1alpha/Dimension.php
  AnalyticsData/src/V1alpha/DimensionExpression.php
  AnalyticsData/src/V1alpha/Filter.php
  AnalyticsData/src/V1alpha/Filter/BetweenFilter.php
  AnalyticsData/src/V1alpha/Filter/NumericFilter.php
  AnalyticsData/src/V1alpha/FilterExpression.php
  AnalyticsData/src/V1alpha/OrderBy.php
  AnalyticsData/src/V1alpha/PropertyQuota.php
  AnalyticsData/src/V1alpha/RunPivotReportRequest.php
  AnalyticsData/src/V1alpha/RunPivotReportResponse.php
  AnalyticsData/src/V1alpha/RunRealtimeReportRequest.php
  AnalyticsData/src/V1alpha/RunRealtimeReportResponse.php
  AnalyticsData/src/V1alpha/RunReportRequest.php
  AnalyticsData/src/V1alpha/RunReportResponse.php
  AnalyticsData/synth.metadata
Labels: cla: yes, context: full

#3878 [Retail] chore: update protobuf v3.15.3
  Retail/src/V2/Catalog.php
  Retail/src/V2/CreateProductRequest.php
  Retail/src/V2/ImportMetadata.php
  Retail/src/V2/ImportProductsRequest.php
  Retail/src/V2/ImportProductsResponse.php
  Retail/src/V2/ImportUserEventsRequest.php
  Retail/src/V2/ImportUserEventsResponse.php
  Retail/src/V2/PredictRequest.php
  Retail/src/V2/Product.php
  Retail/src/V2/ProductDetail.php
  Retail/src/V2/ProductInputConfig.php
  Retail/src/V2/UpdateCatalogRequest.php
  Retail/src/V2/UpdateProductRequest.php
  Retail/src/V2/UserEvent.php
  Retail/src/V2/UserEventInputConfig.php
  Retail/src/V2/WriteUserEventRequest.php
  Retail/synth.metadata
Labels: cla: yes, context: full

#3876 [Recommender] chore: update protobuf v3.15.3
  Recommender/src/V1/CostProjection.php
  Recommender/src/V1/Impact.php
  Recommender/src/V1/Insight.php
  Recommender/src/V1/Operation.php
  Recommender/src/V1/Recommendation.php
  Recommender/synth.metadata
Labels: cla: yes, context: full

#3843 [Spanner] feat(spanner): add CMEK fields to backup and database
  Spanner/metadata/Admin/Database/V1/Backup.php
  Spanner/metadata/Admin/Database/V1/Common.php
  Spanner/metadata/Admin/Database/V1/SpannerDatabaseAdmin.php
  Spanner/src/Admin/Database/V1/Backup.php
  Spanner/src/Admin/Database/V1/BackupInfo.php
  Spanner/src/Admin/Database/V1/CreateBackupEncryptionConfig.php
  Spanner/src/Admin/Database/V1/CreateBackupEncryptionConfig/EncryptionType.php
  Spanner/src/Admin/Database/V1/CreateBackupEncryptionConfig_EncryptionType.php
  Spanner/src/Admin/Database/V1/CreateBackupMetadata.php
  Spanner/src/Admin/Database/V1/CreateBackupRequest.php
  Spanner/src/Admin/Database/V1/CreateDatabaseRequest.php
  Spanner/src/Admin/Database/V1/Database.php
  Spanner/src/Admin/Database/V1/DatabaseAdminGrpcClient.php
  Spanner/src/Admin/Database/V1/DeleteBackupRequest.php
  Spanner/src/Admin/Database/V1/DropDatabaseRequest.php
  Spanner/src/Admin/Database/V1/EncryptionConfig.php
  Spanner/src/Admin/Database/V1/EncryptionInfo.php
  Spanner/src/Admin/Database/V1/EncryptionInfo/Type.php
  Spanner/src/Admin/Database/V1/EncryptionInfo_Type.php
  Spanner/src/Admin/Database/V1/Gapic/DatabaseAdminGapicClient.php
  Spanner/src/Admin/Database/V1/GetBackupRequest.php
  Spanner/src/Admin/Database/V1/GetDatabaseDdlRequest.php
  Spanner/src/Admin/Database/V1/GetDatabaseDdlResponse.php
  Spanner/src/Admin/Database/V1/GetDatabaseRequest.php
  Spanner/src/Admin/Database/V1/ListBackupOperationsRequest.php
  Spanner/src/Admin/Database/V1/ListBackupOperationsResponse.php
  Spanner/src/Admin/Database/V1/ListBackupsRequest.php
  Spanner/src/Admin/Database/V1/ListBackupsResponse.php
  Spanner/src/Admin/Database/V1/ListDatabaseOperationsRequest.php
  Spanner/src/Admin/Database/V1/ListDatabasesRequest.php
  Spanner/src/Admin/Database/V1/ListDatabasesResponse.php
  Spanner/src/Admin/Database/V1/RestoreDatabaseEncryptionConfig.php
  Spanner/src/Admin/Database/V1/RestoreDatabaseEncryptionConfig/EncryptionType.php
  Spanner/src/Admin/Database/V1/RestoreDatabaseEncryptionConfig_EncryptionType.php
  Spanner/src/Admin/Database/V1/RestoreDatabaseMetadata.php
  Spanner/src/Admin/Database/V1/RestoreDatabaseRequest.php
  Spanner/src/Admin/Database/V1/UpdateBackupRequest.php
  Spanner/src/Admin/Database/V1/UpdateDatabaseDdlRequest.php
  Spanner/synth.metadata
Labels: api: spanner, cla: yes, context: full

#3900 [AnalyticsData] fix!: rename the 'page_size', 'page_token', 'total_size' fields to 'limit', 'offset' and 'row_count' respectively
  AnalyticsData/metadata/V1Beta/AnalyticsDataApi.php
  AnalyticsData/src/V1beta/Gapic/BetaAnalyticsDataGapicClient.php
  AnalyticsData/src/V1beta/RunRealtimeReportRequest.php
  AnalyticsData/src/V1beta/RunRealtimeReportResponse.php
  AnalyticsData/src/V1beta/RunReportRequest.php
  AnalyticsData/src/V1beta/RunReportResponse.php
  AnalyticsData/src/V1beta/resources/beta_analytics_data_descriptor_config.php
  AnalyticsData/synth.metadata
  AnalyticsData/tests/Unit/V1beta/BetaAnalyticsDataClientTest.php
Labels: cla: yes, context: full

#3905 feat: introduce optimizer statistics
  Spanner/metadata/V1/Spanner.php
  Spanner/src/Admin/Database/V1/Backup.php
  Spanner/src/Admin/Database/V1/BackupInfo.php
  Spanner/src/Admin/Database/V1/CreateBackupMetadata.php
  Spanner/src/Admin/Database/V1/CreateBackupRequest.php
  Spanner/src/Admin/Database/V1/CreateDatabaseRequest.php
  Spanner/src/Admin/Database/V1/Database.php
  Spanner/src/Admin/Database/V1/EncryptionInfo.php
  Spanner/src/Admin/Database/V1/OperationProgress.php
  Spanner/src/Admin/Database/V1/OptimizeRestoredDatabaseMetadata.php
  Spanner/src/Admin/Database/V1/RestoreDatabaseMetadata.php
  Spanner/src/Admin/Database/V1/RestoreDatabaseRequest.php
  Spanner/src/Admin/Database/V1/RestoreInfo.php
  Spanner/src/Admin/Database/V1/UpdateBackupRequest.php
  Spanner/src/Admin/Instance/V1/CreateInstanceMetadata.php
  Spanner/src/Admin/Instance/V1/CreateInstanceRequest.php
  Spanner/src/Admin/Instance/V1/GetInstanceRequest.php
  Spanner/src/Admin/Instance/V1/UpdateInstanceMetadata.php
  Spanner/src/Admin/Instance/V1/UpdateInstanceRequest.php
  Spanner/src/V1/BatchCreateSessionsRequest.php
  Spanner/src/V1/BeginTransactionRequest.php
  Spanner/src/V1/CommitRequest.php
  Spanner/src/V1/CommitResponse.php
  Spanner/src/V1/CreateSessionRequest.php
  Spanner/src/V1/ExecuteBatchDmlRequest.php
  Spanner/src/V1/ExecuteBatchDmlRequest/Statement.php
  Spanner/src/V1/ExecuteBatchDmlResponse.php
  Spanner/src/V1/ExecuteSqlRequest.php
  Spanner/src/V1/ExecuteSqlRequest/QueryOptions.php
  Spanner/src/V1/KeyRange.php
  Spanner/src/V1/Mutation.php
  Spanner/src/V1/Mutation/Delete.php
  Spanner/src/V1/PartialResultSet.php
  Spanner/src/V1/PartitionQueryRequest.php
  Spanner/src/V1/PartitionReadRequest.php
  Spanner/src/V1/PartitionResponse.php
  Spanner/src/V1/PlanNode.php
  Spanner/src/V1/ReadRequest.php
  Spanner/src/V1/ResultSet.php
  Spanner/src/V1/ResultSetMetadata.php
  Spanner/src/V1/ResultSetStats.php
  Spanner/src/V1/Session.php
  Spanner/src/V1/SpannerGrpcClient.php
  Spanner/src/V1/StructType/Field.php
  Spanner/src/V1/Transaction.php
  Spanner/src/V1/TransactionOptions.php
  Spanner/src/V1/TransactionOptions/ReadOnly.php
  Spanner/src/V1/TransactionSelector.php
  Spanner/src/V1/Type.php
  Spanner/synth.metadata
Labels: cla: yes, context: full

#3892 [Dialogflow] chore: update protobuf v3.15.3
  Dialogflow/src/V2/Agent.php
  Dialogflow/src/V2/BatchUpdateEntitiesRequest.php
  Dialogflow/src/V2/BatchUpdateEntityTypesRequest.php
  Dialogflow/src/V2/BatchUpdateIntentsRequest.php
  Dialogflow/src/V2/Context.php
  Dialogflow/src/V2/CreateContextRequest.php
  Dialogflow/src/V2/CreateEntityTypeRequest.php
  Dialogflow/src/V2/CreateIntentRequest.php
  Dialogflow/src/V2/CreateSessionEntityTypeRequest.php
  Dialogflow/src/V2/DetectIntentRequest.php
  Dialogflow/src/V2/DetectIntentResponse.php
  Dialogflow/src/V2/Environment.php
  Dialogflow/src/V2/EventInput.php
  Dialogflow/src/V2/InputAudioConfig.php
  Dialogflow/src/V2/Intent/Message.php
  Dialogflow/src/V2/Intent/Message/BasicCard.php
  Dialogflow/src/V2/Intent/Message/BasicCard/Button.php
  Dialogflow/src/V2/Intent/Message/BrowseCarouselCard/BrowseCarouselCardItem.php
  Dialogflow/src/V2/Intent/Message/CarouselSelect/Item.php
  Dialogflow/src/V2/Intent/Message/ListSelect/Item.php
  Dialogflow/src/V2/Intent/Message/MediaContent/ResponseMediaObject.php
  Dialogflow/src/V2/Intent/Message/TableCard.php
  Dialogflow/src/V2/OriginalDetectIntentRequest.php
  Dialogflow/src/V2/OutputAudioConfig.php
  Dialogflow/src/V2/QueryInput.php
  Dialogflow/src/V2/QueryParameters.php
  Dialogflow/src/V2/QueryResult.php
  Dialogflow/src/V2/SentimentAnalysisResult.php
  Dialogflow/src/V2/SetAgentRequest.php
  Dialogflow/src/V2/SpeechWordInfo.php
  Dialogflow/src/V2/StreamingDetectIntentRequest.php
  Dialogflow/src/V2/StreamingDetectIntentResponse.php
  Dialogflow/src/V2/StreamingRecognitionResult.php
  Dialogflow/src/V2/SynthesizeSpeechConfig.php
  Dialogflow/src/V2/UpdateContextRequest.php
  Dialogflow/src/V2/UpdateEntityTypeRequest.php
  Dialogflow/src/V2/UpdateIntentRequest.php
  Dialogflow/src/V2/UpdateSessionEntityTypeRequest.php
  Dialogflow/src/V2/WebhookRequest.php
  Dialogflow/src/V2/WebhookResponse.php
  Dialogflow/synth.metadata
Labels: cla: yes, context: full

#3895 [PubSub] docs: Remove experimental note for schema APIs
  PubSub/src/V1/Gapic/PublisherGapicClient.php
  PubSub/src/V1/Gapic/SchemaServiceGapicClient.php
  PubSub/src/V1/SchemaServiceGrpcClient.php
  PubSub/src/V1/Topic.php
  PubSub/synth.metadata
Labels: cla: yes, context: full

#3891 [Bigtable] chore: update protobuf v3.15.3
  Bigtable/src/Admin/V2/AppProfile.php
  Bigtable/src/Admin/V2/Backup.php
  Bigtable/src/Admin/V2/BackupInfo.php
  Bigtable/src/Admin/V2/Cluster.php
  Bigtable/src/Admin/V2/ColumnFamily.php
  Bigtable/src/Admin/V2/CreateAppProfileRequest.php
  Bigtable/src/Admin/V2/CreateBackupMetadata.php
  Bigtable/src/Admin/V2/CreateBackupRequest.php
  Bigtable/src/Admin/V2/CreateClusterMetadata.php
  Bigtable/src/Admin/V2/CreateClusterRequest.php
  Bigtable/src/Admin/V2/CreateInstanceMetadata.php
  Bigtable/src/Admin/V2/CreateInstanceRequest.php
  Bigtable/src/Admin/V2/CreateTableFromSnapshotMetadata.php
  Bigtable/src/Admin/V2/CreateTableRequest.php
  Bigtable/src/Admin/V2/EncryptionInfo.php
  Bigtable/src/Admin/V2/GcRule.php
  Bigtable/src/Admin/V2/ModifyColumnFamiliesRequest/Modification.php
  Bigtable/src/Admin/V2/OperationProgress.php
  Bigtable/src/Admin/V2/OptimizeRestoredTableMetadata.php
  Bigtable/src/Admin/V2/PartialUpdateInstanceRequest.php
  Bigtable/src/Admin/V2/RestoreInfo.php
  Bigtable/src/Admin/V2/RestoreTableMetadata.php
  Bigtable/src/Admin/V2/Snapshot.php
  Bigtable/src/Admin/V2/SnapshotTableMetadata.php
  Bigtable/src/Admin/V2/SnapshotTableRequest.php
  Bigtable/src/Admin/V2/Table.php
  Bigtable/src/Admin/V2/UpdateAppProfileRequest.php
  Bigtable/src/Admin/V2/UpdateBackupRequest.php
  Bigtable/src/Admin/V2/UpdateClusterMetadata.php
  Bigtable/src/Admin/V2/UpdateInstanceMetadata.php
  Bigtable/src/V2/CheckAndMutateRowRequest.php
  Bigtable/src/V2/MutateRowsResponse/Entry.php
  Bigtable/src/V2/Mutation.php
  Bigtable/src/V2/Mutation/DeleteFromColumn.php
  Bigtable/src/V2/ReadModifyWriteRowResponse.php
  Bigtable/src/V2/ReadRowsRequest.php
  Bigtable/src/V2/ReadRowsResponse/CellChunk.php
  Bigtable/src/V2/RowFilter.php
  Bigtable/src/V2/RowFilter/Condition.php
  Bigtable/synth.metadata
Labels: cla: yes, context: full

#3902 Fix Authentication guide link
  AUTHENTICATION.md
Labels: cla: yes

#3913 [AssuredWorkloads] feat: Add 'resource_settings' field to provide custom properties (ids) for the provisioned projects.
  AssuredWorkloads/metadata/V1Beta1/AssuredworkloadsV1Beta1.php
  AssuredWorkloads/src/V1beta1/AssuredWorkloadsServiceGrpcClient.php
  AssuredWorkloads/src/V1beta1/Workload.php
  AssuredWorkloads/src/V1beta1/Workload/ResourceSettings.php
  AssuredWorkloads/src/V1beta1/Workload_ResourceSettings.php
  AssuredWorkloads/synth.metadata
Labels: cla: yes, context: full

#3565 feat: add keepalive setting in data client
  Bigtable/src/BigtableClient.php
Labels: cla: yes

#3850 [SecretManager] feat: added topic field to Secret
  SecretManager/metadata/V1/Resources.php
  SecretManager/src/V1/Secret.php
  SecretManager/src/V1/Topic.php
  SecretManager/synth.metadata
Labels: cla: yes, context: full

#3844 fix!: transferableSkus field deprecation
  Channel/metadata/V1/Entitlements.php
  Channel/metadata/V1/Service.php
  Channel/src/V1/CloudChannelServiceGrpcClient.php
  Channel/src/V1/CreateChannelPartnerLinkRequest.php
  Channel/src/V1/Gapic/CloudChannelServiceGapicClient.php
  Channel/src/V1/TransferableSku.php
  Channel/synth.metadata
Labels: cla: yes, context: full

#3924 docs: fix logging README link to API docs
  Logging/README.md
Labels: cla: yes

#3922 [SecretManager] chore: update protobuf v3.15.3
  SecretManager/src/V1/AccessSecretVersionResponse.php
  SecretManager/src/V1/AddSecretVersionRequest.php
  SecretManager/src/V1/CreateSecretRequest.php
  SecretManager/src/V1/Replication.php
  SecretManager/src/V1/Replication/Automatic.php
  SecretManager/src/V1/Replication/UserManaged/Replica.php
  SecretManager/src/V1/ReplicationStatus.php
  SecretManager/src/V1/ReplicationStatus/AutomaticStatus.php
  SecretManager/src/V1/ReplicationStatus/UserManagedStatus/ReplicaStatus.php
  SecretManager/src/V1/Secret.php
  SecretManager/src/V1/SecretVersion.php
  SecretManager/src/V1/UpdateSecretRequest.php
  SecretManager/src/V1beta1/AccessSecretVersionResponse.php
  SecretManager/src/V1beta1/AddSecretVersionRequest.php
  SecretManager/src/V1beta1/CreateSecretRequest.php
  SecretManager/src/V1beta1/Replication.php
  SecretManager/src/V1beta1/Secret.php
  SecretManager/src/V1beta1/SecretVersion.php
  SecretManager/src/V1beta1/UpdateSecretRequest.php
  SecretManager/synth.metadata
Labels: cla: yes, context: full

#3921 chore: update protobuf v3.15.3
  Channel/metadata/V1/Offers.php
  Channel/src/V1/ChangeRenewalSettingsRequest.php
  Channel/src/V1/ChannelPartnerLink.php
  Channel/src/V1/CloudChannelServiceGrpcClient.php
  Channel/src/V1/CloudIdentityInfo.php
  Channel/src/V1/CommitmentSettings.php
  Channel/src/V1/Constraints.php
  Channel/src/V1/CreateChannelPartnerLinkRequest.php
  Channel/src/V1/CreateCustomerRequest.php
  Channel/src/V1/CreateEntitlementRequest.php
  Channel/src/V1/Customer.php
  Channel/src/V1/Entitlement.php
  Channel/src/V1/Gapic/CloudChannelServiceGapicClient.php
  Channel/src/V1/ListPurchasableOffersRequest.php
  Channel/src/V1/ListPurchasableSkusRequest.php
  Channel/src/V1/MarketingInfo.php
  Channel/src/V1/Offer.php
  Channel/src/V1/Parameter.php
  Channel/src/V1/ParameterDefinition.php
  Channel/src/V1/Plan.php
  Channel/src/V1/Price.php
  Channel/src/V1/PriceByResource.php
  Channel/src/V1/PricePhase.php
  Channel/src/V1/PriceTier.php
  Channel/src/V1/Product.php
  Channel/src/V1/ProvisionCloudIdentityRequest.php
  Channel/src/V1/PurchasableOffer.php
  Channel/src/V1/PurchasableSku.php
  Channel/src/V1/RenewalSettings.php
  Channel/src/V1/Sku.php
  Channel/src/V1/SubscriberEvent.php
  Channel/src/V1/TransferableOffer.php
  Channel/src/V1/TransferableSku.php
  Channel/src/V1/TrialSettings.php
  Channel/src/V1/UpdateChannelPartnerLinkRequest.php
  Channel/src/V1/UpdateCustomerRequest.php
  Channel/src/V1/Value.php
  Channel/synth.metadata
Labels: cla: yes, context: full

#3463 feat: introduce create/delete index RPCs
  DatastoreAdmin/metadata/V1/DatastoreAdmin.php
  DatastoreAdmin/metadata/V1/Index.php
  DatastoreAdmin/src/V1/CommonMetadata.php
  DatastoreAdmin/src/V1/CreateIndexRequest.php
  DatastoreAdmin/src/V1/DatastoreAdminGrpcClient.php
  DatastoreAdmin/src/V1/DeleteIndexRequest.php
  DatastoreAdmin/src/V1/ExportEntitiesMetadata.php
  DatastoreAdmin/src/V1/ExportEntitiesRequest.php
  DatastoreAdmin/src/V1/Gapic/DatastoreAdminGapicClient.php
  DatastoreAdmin/src/V1/ImportEntitiesMetadata.php
  DatastoreAdmin/src/V1/ImportEntitiesRequest.php
  DatastoreAdmin/src/V1/Index.php
  DatastoreAdmin/src/V1/IndexOperationMetadata.php
  DatastoreAdmin/src/V1/resources/datastore_admin_client_config.json
  DatastoreAdmin/src/V1/resources/datastore_admin_descriptor_config.php
  DatastoreAdmin/src/V1/resources/datastore_admin_rest_client_config.php
  DatastoreAdmin/synth.metadata
  DatastoreAdmin/tests/Unit/V1/DatastoreAdminClientTest.php
Labels: cla: yes, context: none

#3912 feat(spanner): add support for Customer Managed Encryption Key (CMEK)
  Spanner/src/Connection/Grpc.php
  Spanner/src/Database.php
  Spanner/tests/System/BackupTest.php
  Spanner/tests/Unit/Connection/GrpcTest.php
Labels: api: spanner, cla: yes

#3932 [SecretManager] feat: Rotation for Secrets
  SecretManager/metadata/V1/Resources.php
  SecretManager/src/V1/Rotation.php
  SecretManager/src/V1/Secret.php
  SecretManager/synth.metadata
Labels: cla: yes, context: full

#3930 [BigQueryStorage] feat: add a Arrow compression options (Only LZ4 for now) & Return schema on first ReadRowsResponse
  BigQueryStorage/metadata/V1/Arrow.php
  BigQueryStorage/metadata/V1/Storage.php
  BigQueryStorage/metadata/V1/Stream.php
  BigQueryStorage/src/V1/ArrowSerializationOptions.php
  BigQueryStorage/src/V1/ArrowSerializationOptions/CompressionCodec.php
  BigQueryStorage/src/V1/ArrowSerializationOptions_CompressionCodec.php
  BigQueryStorage/src/V1/BigQueryReadGrpcClient.php
  BigQueryStorage/src/V1/ReadRowsResponse.php
  BigQueryStorage/src/V1/ReadSession.php
  BigQueryStorage/src/V1/ReadSession/TableReadOptions.php
  BigQueryStorage/synth.metadata
Labels: cla: yes, context: full
