Repository googleapis/google-cloud-php, pull requests merged in 2021-02, with the labels that each got.

#3745 [WebSecurityScanner] chore: update with latest version of protobuf
  WebSecurityScanner/metadata/V1Beta/CrawledUrl.php
  WebSecurityScanner/metadata/V1Beta/Finding.php
  WebSecurityScanner/metadata/V1Beta/FindingAddon.php
  WebSecurityScanner/metadata/V1Beta/FindingTypeStats.php
  WebSecurityScanner/metadata/V1Beta/ScanConfig.php
  WebSecurityScanner/metadata/V1Beta/ScanConfigError.php
  WebSecurityScanner/metadata/V1Beta/ScanRun.php
  WebSecurityScanner/metadata/V1Beta/ScanRunErrorTrace.php
  WebSecurityScanner/metadata/V1Beta/ScanRunWarningTrace.php
  WebSecurityScanner/metadata/V1Beta/WebSecurityScanner.php
  WebSecurityScanner/synth.metadata
Labels: cla: yes, context: full

#3744 [Trace] chore: update with latest version of protobuf
  Trace/metadata/V2/Trace.php
  Trace/metadata/V2/Tracing.php
  Trace/synth.metadata
Labels: cla: yes, context: full

#3743 feat: add read mask / ttl / queue stats / refresh with latest protobuf
  Tasks/metadata/V2/Cloudtasks.php
  Tasks/metadata/V2/Queue.php
  Tasks/metadata/V2/Target.php
  Tasks/metadata/V2/Task.php
  Tasks/metadata/V2Beta2/Cloudtasks.php
  Tasks/metadata/V2Beta2/Queue.php
  Tasks/metadata/V2Beta2/Target.php
  Tasks/metadata/V2Beta2/Task.php
  Tasks/metadata/V2Beta3/Cloudtasks.php
  Tasks/metadata/V2Beta3/Queue.php
  Tasks/metadata/V2Beta3/Target.php
  Tasks/metadata/V2Beta3/Task.php
  Tasks/src/V2beta2/AppEngineHttpRequest.php
  Tasks/src/V2beta2/CloudTasksGrpcClient.php
  Tasks/src/V2beta2/Gapic/CloudTasksGapicClient.php
  Tasks/src/V2beta2/GetQueueRequest.php
  Tasks/src/V2beta2/ListQueuesRequest.php
  Tasks/src/V2beta2/Queue.php
  Tasks/src/V2beta2/QueueStats.php
  Tasks/src/V2beta2/RateLimits.php
  Tasks/src/V2beta2/RetryConfig.php
  Tasks/src/V2beta2/resources/cloud_tasks_client_config.json
  Tasks/src/V2beta3/Gapic/CloudTasksGapicClient.php
  Tasks/src/V2beta3/GetQueueRequest.php
  Tasks/src/V2beta3/ListQueuesRequest.php
  Tasks/src/V2beta3/PullMessage.php
  Tasks/src/V2beta3/Queue.php
  Tasks/src/V2beta3/QueueStats.php
  Tasks/src/V2beta3/RateLimits.php
  Tasks/src/V2beta3/Task.php
  Tasks/src/V2beta3/resources/cloud_tasks_client_config.json
  Tasks/synth.metadata
Labels: cla: yes, context: full

#3741 [Speech] chore: update with latest version of protobuf
  Speech/metadata/V1/CloudSpeech.php
  Speech/metadata/V1P1Beta1/CloudSpeech.php
  Speech/metadata/V1P1Beta1/Resource.php
  Speech/synth.metadata
Labels: cla: yes, context: full

#3740 feat: add option for returning Spanner commit stats / update with latest version of protobuf
  Spanner/metadata/Admin/Database/V1/Backup.php
  Spanner/metadata/Admin/Database/V1/Common.php
  Spanner/metadata/Admin/Database/V1/SpannerDatabaseAdmin.php
  Spanner/metadata/Admin/Instance/V1/SpannerInstanceAdmin.php
  Spanner/metadata/V1/Keys.php
  Spanner/metadata/V1/Mutation.php
  Spanner/metadata/V1/QueryPlan.php
  Spanner/metadata/V1/ResultSet.php
  Spanner/metadata/V1/Spanner.php
  Spanner/metadata/V1/Transaction.php
  Spanner/metadata/V1/Type.php
  Spanner/src/V1/CommitRequest.php
  Spanner/src/V1/CommitResponse.php
  Spanner/src/V1/CommitResponse/CommitStats.php
  Spanner/src/V1/CommitResponse_CommitStats.php
  Spanner/src/V1/ExecuteSqlRequest.php
  Spanner/src/V1/ExecuteSqlRequest/QueryOptions.php
  Spanner/src/V1/Gapic/SpannerGapicClient.php
  Spanner/src/V1/Session.php
  Spanner/src/V1/SpannerGrpcClient.php
  Spanner/src/V1/StructType/Field.php
  Spanner/src/V1/TransactionOptions.php
  Spanner/synth.metadata
Labels: cla: yes, context: full

#3772 [WebRisk] chore: update with latest version of protobuf
  WebRisk/metadata/V1/Webrisk.php
  WebRisk/metadata/V1Beta1/Webrisk.php
  WebRisk/synth.metadata
Labels: cla: yes, context: full

#3758 [AutoMl] chore: update with latest version of protobuf
  AutoMl/metadata/V1/AnnotationPayload.php
  AutoMl/metadata/V1/AnnotationSpec.php
  AutoMl/metadata/V1/Classification.php
  AutoMl/metadata/V1/DataItems.php
  AutoMl/metadata/V1/Dataset.php
  AutoMl/metadata/V1/Detection.php
  AutoMl/metadata/V1/Geometry.php
  AutoMl/metadata/V1/Image.php
  AutoMl/metadata/V1/Io.php
  AutoMl/metadata/V1/Model.php
  AutoMl/metadata/V1/ModelEvaluation.php
  AutoMl/metadata/V1/Operations.php
  AutoMl/metadata/V1/PredictionService.php
  AutoMl/metadata/V1/Service.php
  AutoMl/metadata/V1/Text.php
  AutoMl/metadata/V1/TextExtraction.php
  AutoMl/metadata/V1/TextSegment.php
  AutoMl/metadata/V1/TextSentiment.php
  AutoMl/metadata/V1/Translation.php
  AutoMl/metadata/V1Beta1/AnnotationPayload.php
  AutoMl/metadata/V1Beta1/AnnotationSpec.php
  AutoMl/metadata/V1Beta1/Classification.php
  AutoMl/metadata/V1Beta1/ColumnSpec.php
  AutoMl/metadata/V1Beta1/DataItems.php
  AutoMl/metadata/V1Beta1/DataStats.php
  AutoMl/metadata/V1Beta1/DataTypes.php
  AutoMl/metadata/V1Beta1/Dataset.php
  AutoMl/metadata/V1Beta1/Detection.php
  AutoMl/metadata/V1Beta1/Geometry.php
  AutoMl/metadata/V1Beta1/Image.php
  AutoMl/metadata/V1Beta1/Io.php
  AutoMl/metadata/V1Beta1/Model.php
  AutoMl/metadata/V1Beta1/ModelEvaluation.php
  AutoMl/metadata/V1Beta1/Operations.php
  AutoMl/metadata/V1Beta1/PredictionService.php
  AutoMl/metadata/V1Beta1/Ranges.php
  AutoMl/metadata/V1Beta1/Regression.php
  AutoMl/metadata/V1Beta1/Service.php
  AutoMl/metadata/V1Beta1/TableSpec.php
  AutoMl/metadata/V1Beta1/Tables.php
  AutoMl/metadata/V1Beta1/Temporal.php
  AutoMl/metadata/V1Beta1/Text.php
  AutoMl/metadata/V1Beta1/TextExtraction.php
  AutoMl/metadata/V1Beta1/TextSegment.php
  AutoMl/metadata/V1Beta1/TextSentiment.php
  AutoMl/metadata/V1Beta1/Translation.php
  AutoMl/metadata/V1Beta1/Video.php
  AutoMl/synth.metadata
Labels: cla: yes, context: full

#3771 [TextToSpeech] chore: update with latest version of protobuf
  TextToSpeech/metadata/V1/CloudTts.php
  TextToSpeech/synth.metadata
Labels: cla: yes, context: full

#3770 [Spanner] feat: adds PITR fields to backup and database
  Spanner/metadata/Admin/Database/V1/Backup.php
  Spanner/metadata/Admin/Database/V1/SpannerDatabaseAdmin.php
  Spanner/src/Admin/Database/V1/Backup.php
  Spanner/src/Admin/Database/V1/BackupInfo.php
  Spanner/src/Admin/Database/V1/CreateBackupMetadata.php
  Spanner/src/Admin/Database/V1/Database.php
  Spanner/src/Admin/Database/V1/Gapic/DatabaseAdminGapicClient.php
  Spanner/src/Admin/Database/V1/GetDatabaseDdlRequest.php
  Spanner/src/Admin/Database/V1/ListBackupOperationsRequest.php
  Spanner/src/Admin/Database/V1/ListDatabaseOperationsRequest.php
  Spanner/src/Admin/Database/V1/OptimizeRestoredDatabaseMetadata.php
  Spanner/src/Admin/Database/V1/RestoreDatabaseMetadata.php
  Spanner/synth.metadata
  Spanner/tests/Unit/Admin/Database/V1/DatabaseAdminClientTest.php
Labels: cla: yes, context: full

#3769 [ServiceDirectory] chore: update with latest version of protobuf
  ServiceDirectory/metadata/V1Beta1/Endpoint.php
  ServiceDirectory/metadata/V1Beta1/LookupService.php
  ServiceDirectory/metadata/V1Beta1/PBNamespace.php
  ServiceDirectory/metadata/V1Beta1/RegistrationService.php
  ServiceDirectory/metadata/V1Beta1/Service.php
  ServiceDirectory/synth.metadata
Labels: cla: yes, context: full

#3768 [SecurityCenter] chore: update with latest version of protobuf
  SecurityCenter/metadata/V1/Asset.php
  SecurityCenter/metadata/V1/Finding.php
  SecurityCenter/metadata/V1/NotificationConfig.php
  SecurityCenter/metadata/V1/NotificationMessage.php
  SecurityCenter/metadata/V1/OrganizationSettings.php
  SecurityCenter/metadata/V1/Resource.php
  SecurityCenter/metadata/V1/RunAssetDiscoveryResponse.php
  SecurityCenter/metadata/V1/SecurityMarks.php
  SecurityCenter/metadata/V1/SecuritycenterService.php
  SecurityCenter/metadata/V1/Source.php
  SecurityCenter/metadata/V1P1Beta1/Asset.php
  SecurityCenter/metadata/V1P1Beta1/Finding.php
  SecurityCenter/metadata/V1P1Beta1/NotificationConfig.php
  SecurityCenter/metadata/V1P1Beta1/NotificationMessage.php
  SecurityCenter/metadata/V1P1Beta1/OrganizationSettings.php
  SecurityCenter/metadata/V1P1Beta1/Resource.php
  SecurityCenter/metadata/V1P1Beta1/RunAssetDiscoveryResponse.php
  SecurityCenter/metadata/V1P1Beta1/SecurityMarks.php
  SecurityCenter/metadata/V1P1Beta1/SecuritycenterService.php
  SecurityCenter/metadata/V1P1Beta1/Source.php
  SecurityCenter/synth.metadata
Labels: cla: yes, context: full

#3767 [Scheduler] chore: update with latest version of protobuf
  Scheduler/metadata/V1/Cloudscheduler.php
  Scheduler/metadata/V1/Job.php
  Scheduler/metadata/V1/Target.php
  Scheduler/metadata/V1Beta1/Cloudscheduler.php
  Scheduler/metadata/V1Beta1/Job.php
  Scheduler/metadata/V1Beta1/Target.php
  Scheduler/synth.metadata
Labels: cla: yes, context: full

#3766 [Redis] chore: update with latest version of protobuf
  Redis/metadata/V1/CloudRedis.php
  Redis/metadata/V1Beta1/CloudRedis.php
  Redis/synth.metadata
Labels: cla: yes, context: full

#3765 [RecommendationEngine] chore: update with latest version of protobuf
  RecommendationEngine/metadata/V1Beta1/Catalog.php
  RecommendationEngine/metadata/V1Beta1/CatalogService.php
  RecommendationEngine/metadata/V1Beta1/Common.php
  RecommendationEngine/metadata/V1Beta1/Import.php
  RecommendationEngine/metadata/V1Beta1/PredictionApikeyRegistryService.php
  RecommendationEngine/metadata/V1Beta1/PredictionService.php
  RecommendationEngine/metadata/V1Beta1/RecommendationengineResources.php
  RecommendationEngine/metadata/V1Beta1/UserEvent.php
  RecommendationEngine/metadata/V1Beta1/UserEventService.php
  RecommendationEngine/synth.metadata
Labels: cla: yes, context: full

#3764 [OsLogin] chore: update with latest version of protobuf
  OsLogin/metadata/Common/Common.php
  OsLogin/metadata/V1/Oslogin.php
  OsLogin/metadata/V1Beta/Oslogin.php
  OsLogin/synth.metadata
Labels: cla: yes, context: full

#3763 [Firestore] chore: update with latest version of protobuf
  Firestore/metadata/Admin/V1/Field.php
  Firestore/metadata/Admin/V1/FirestoreAdmin.php
  Firestore/metadata/Admin/V1/Index.php
  Firestore/metadata/Admin/V1/Location.php
  Firestore/metadata/Admin/V1/Operation.php
  Firestore/metadata/V1/Common.php
  Firestore/metadata/V1/Document.php
  Firestore/metadata/V1/Firestore.php
  Firestore/metadata/V1/Query.php
  Firestore/metadata/V1/Write.php
  Firestore/synth.metadata
Labels: cla: yes, context: full

#3762 [ErrorReporting] chore: update with latest version of protobuf
  ErrorReporting/metadata/V1Beta1/Common.php
  ErrorReporting/metadata/V1Beta1/ErrorGroupService.php
  ErrorReporting/metadata/V1Beta1/ErrorStatsService.php
  ErrorReporting/metadata/V1Beta1/ReportErrorsService.php
  ErrorReporting/synth.metadata
Labels: cla: yes, context: full

#3761 [Debugger] chore: update with latest version of protobuf
  Debugger/metadata/V2/Controller.php
  Debugger/metadata/V2/Data.php
  Debugger/metadata/V2/Debugger.php
  Debugger/synth.metadata
Labels: cla: yes, context: full

#3760 [DataCatalog] chore: update with latest version of protobuf
  DataCatalog/metadata/V1/Common.php
  DataCatalog/metadata/V1/Datacatalog.php
  DataCatalog/metadata/V1/GcsFilesetSpec.php
  DataCatalog/metadata/V1/Schema.php
  DataCatalog/metadata/V1/Search.php
  DataCatalog/metadata/V1/TableSpec.php
  DataCatalog/metadata/V1/Tags.php
  DataCatalog/metadata/V1/Timestamps.php
  DataCatalog/synth.metadata
Labels: cla: yes, context: full

#3742 [Talent] chore: update with latest version of protobuf
  Talent/metadata/V4/Common.php
  Talent/metadata/V4/Company.php
  Talent/metadata/V4/CompanyService.php
  Talent/metadata/V4/CompletionService.php
  Talent/metadata/V4/Event.php
  Talent/metadata/V4/EventService.php
  Talent/metadata/V4/Filters.php
  Talent/metadata/V4/Histogram.php
  Talent/metadata/V4/Job.php
  Talent/metadata/V4/JobService.php
  Talent/metadata/V4/Tenant.php
  Talent/metadata/V4/TenantService.php
  Talent/metadata/V4Beta1/Application.php
  Talent/metadata/V4Beta1/ApplicationService.php
  Talent/metadata/V4Beta1/Batch.php
  Talent/metadata/V4Beta1/Common.php
  Talent/metadata/V4Beta1/Company.php
  Talent/metadata/V4Beta1/CompanyService.php
  Talent/metadata/V4Beta1/CompletionService.php
  Talent/metadata/V4Beta1/Event.php
  Talent/metadata/V4Beta1/EventService.php
  Talent/metadata/V4Beta1/Filters.php
  Talent/metadata/V4Beta1/Histogram.php
  Talent/metadata/V4Beta1/Job.php
  Talent/metadata/V4Beta1/JobService.php
  Talent/metadata/V4Beta1/Profile.php
  Talent/metadata/V4Beta1/ProfileService.php
  Talent/metadata/V4Beta1/Tenant.php
  Talent/metadata/V4Beta1/TenantService.php
  Talent/synth.metadata
Labels: cla: yes, context: full, kokoro:force-run

#3715 [RecaptchaEnterprise] chore: update with latest version of protobuf
  RecaptchaEnterprise/metadata/V1/Recaptchaenterprise.php
  RecaptchaEnterprise/synth.metadata
Labels: cla: yes, context: full

#3713 [Memcache] chore: update with latest version of protobuf
  Memcache/metadata/V1Beta2/CloudMemcache.php
  Memcache/synth.metadata
Labels: cla: yes, context: full

#3712 [Language] chore: update with latest version of protobuf
  Language/metadata/V1/LanguageService.php
  Language/metadata/V1Beta2/LanguageService.php
  Language/synth.metadata
Labels: cla: yes, context: full

#3711 [Kms] chore: update with latest version of protobuf
  Kms/metadata/V1/Resources.php
  Kms/metadata/V1/Service.php
  Kms/synth.metadata
Labels: cla: yes, context: full

#3710 [Iot] chore: update with latest version of protobuf
  Iot/metadata/V1/DeviceManager.php
  Iot/metadata/V1/Resources.php
  Iot/synth.metadata
Labels: cla: yes, context: full

#3719 feat: allow user-specified gapic clients
  PubSub/src/Connection/Grpc.php
  PubSub/tests/Unit/PubSubClientTest.php
Labels: cla: yes

#3759 [BigQueryStorage] chore: update with latest version of protobuf
  BigQueryStorage/metadata/V1/Arrow.php
  BigQueryStorage/metadata/V1/Avro.php
  BigQueryStorage/metadata/V1/Storage.php
  BigQueryStorage/metadata/V1/Stream.php
  BigQueryStorage/synth.metadata
Labels: cla: yes, context: full

#3748 feat: run the Garbage Collector after each BatchDaemon iteration
  Core/src/Batch/BatchDaemon.php
Labels: cla: yes

#3709 [Dlp] chore: update with latest version of protobuf
  Dlp/metadata/V2/Dlp.php
  Dlp/metadata/V2/Storage.php
  Dlp/synth.metadata
Labels: cla: yes, context: full

#3708 [Datastore] chore: update with latest version of protobuf
  Datastore/metadata/V1/Datastore.php
  Datastore/metadata/V1/Entity.php
  Datastore/metadata/V1/Query.php
  Datastore/synth.metadata
Labels: cla: yes, context: full

#3707 [Billing] chore: update with latest version of protobuf
  Billing/metadata/V1/CloudBilling.php
  Billing/metadata/V1/CloudCatalog.php
  Billing/synth.metadata
Labels: cla: yes, context: full

#3706 [BigQueryReservation] chore: update with latest version of protobuf
  BigQueryReservation/metadata/V1/Reservation.php
  BigQueryReservation/synth.metadata
Labels: cla: yes, context: full

#3705 [BigQueryDataTransfer] chore: update with latest version of protobuf
  BigQueryDataTransfer/metadata/V1/Datatransfer.php
  BigQueryDataTransfer/metadata/V1/Transfer.php
  BigQueryDataTransfer/synth.metadata
Labels: cla: yes, context: full

#3663 [SecretManager] feat: added expire_time and ttl fields to Secret
  SecretManager/metadata/V1/Resources.php
  SecretManager/metadata/V1/Service.php
  SecretManager/metadata/V1Beta1/Resources.php
  SecretManager/metadata/V1Beta1/Service.php
  SecretManager/src/V1/Secret.php
  SecretManager/synth.metadata
Labels: cla: yes, context: full

#3704 [BigQueryConnection] chore: update with latest version of protobuf
  BigQueryConnection/metadata/V1/Connection.php
  BigQueryConnection/synth.metadata
Labels: cla: yes, context: full

#3812 feat: added PatchRollout feature to PatchDeployments
  OsConfig/metadata/V1/Inventory.php
  OsConfig/metadata/V1/OsconfigCommon.php
  OsConfig/metadata/V1/OsconfigService.php
  OsConfig/metadata/V1/PatchDeployments.php
  OsConfig/metadata/V1/PatchJobs.php
  OsConfig/src/V1/CreatePatchDeploymentRequest.php
  OsConfig/src/V1/ExecutePatchJobRequest.php
  OsConfig/src/V1/FixedOrPercent.php
  OsConfig/src/V1/Gapic/OsConfigServiceGapicClient.php
  OsConfig/src/V1/Inventory.php
  OsConfig/src/V1/Inventory/Item.php
  OsConfig/src/V1/Inventory/Item/OriginType.php
  OsConfig/src/V1/Inventory/Item/Type.php
  OsConfig/src/V1/Inventory/OsInfo.php
  OsConfig/src/V1/Inventory/SoftwarePackage.php
  OsConfig/src/V1/Inventory/VersionedPackage.php
  OsConfig/src/V1/Inventory/WindowsQuickFixEngineeringPackage.php
  OsConfig/src/V1/Inventory/WindowsUpdatePackage.php
  OsConfig/src/V1/Inventory/WindowsUpdatePackage/WindowsUpdateCategory.php
  OsConfig/src/V1/Inventory/ZypperPatch.php
  OsConfig/src/V1/Inventory_Item.php
  OsConfig/src/V1/Inventory_Item_OriginType.php
  OsConfig/src/V1/Inventory_Item_Type.php
  OsConfig/src/V1/Inventory_OsInfo.php
  OsConfig/src/V1/Inventory_SoftwarePackage.php
  OsConfig/src/V1/Inventory_VersionedPackage.php
  OsConfig/src/V1/Inventory_WindowsQuickFixEngineeringPackage.php
  OsConfig/src/V1/Inventory_WindowsUpdatePackage.php
  OsConfig/src/V1/Inventory_WindowsUpdatePackage_WindowsUpdateCategory.php
  OsConfig/src/V1/Inventory_ZypperPatch.php
  OsConfig/src/V1/ListPatchDeploymentsRequest.php
  OsConfig/src/V1/ListPatchJobInstanceDetailsRequest.php
  OsConfig/src/V1/MonthlySchedule.php
  OsConfig/src/V1/PatchDeployment.php
  OsConfig/src/V1/PatchJob.php
  OsConfig/src/V1/PatchRollout.php
  OsConfig/src/V1/PatchRollout/Mode.php
  OsConfig/src/V1/PatchRollout_Mode.php
  OsConfig/src/V1/RecurringSchedule.php
  OsConfig/src/V1/WeekDayOfMonth.php
  OsConfig/synth.metadata
Labels: cla: yes, context: full

#3776 feat: add support for custom definitions
  AnalyticsData/metadata/V1Alpha/AnalyticsDataApi.php
  AnalyticsData/metadata/V1Alpha/Data.php
  AnalyticsData/src/V1alpha/Cohort.php
  AnalyticsData/src/V1alpha/CohortReportSettings.php
  AnalyticsData/src/V1alpha/CohortSpec.php
  AnalyticsData/src/V1alpha/CohortsRange.php
  AnalyticsData/src/V1alpha/CohortsRange/Granularity.php
  AnalyticsData/src/V1alpha/Dimension.php
  AnalyticsData/src/V1alpha/DimensionMetadata.php
  AnalyticsData/src/V1alpha/Entity.php
  AnalyticsData/src/V1alpha/Gapic/AlphaAnalyticsDataGapicClient.php
  AnalyticsData/src/V1alpha/GetMetadataRequest.php
  AnalyticsData/src/V1alpha/Metric.php
  AnalyticsData/src/V1alpha/MetricMetadata.php
  AnalyticsData/src/V1alpha/RunRealtimeReportRequest.php
  AnalyticsData/src/V1alpha/RunReportRequest.php
  AnalyticsData/src/V1alpha/RunReportResponse.php
  AnalyticsData/synth.metadata
Labels: cla: yes, context: full

#3810 [Iot] docs: add fieldMask format clarification to avoid misunderstandings.
  Iot/src/V1/DeviceManagerGrpcClient.php
  Iot/src/V1/Gapic/DeviceManagerGapicClient.php
  Iot/src/V1/GetDeviceRequest.php
  Iot/src/V1/ListDevicesRequest.php
  Iot/synth.metadata
Labels: cla: yes, context: full

#3803 feat: add tracks/thumbnails support to face detection
  VideoIntelligence/metadata/V1/VideoIntelligence.php
  VideoIntelligence/metadata/V1Beta2/VideoIntelligence.php
  VideoIntelligence/src/V1/FaceDetectionAnnotation.php
  VideoIntelligence/synth.metadata
Labels: cla: yes, context: full

#3703 feat: adds support for workloads with US_REGIONAL_ACCESS compliance regime
  AssuredWorkloads/metadata/V1Beta1/AssuredworkloadsV1Beta1.php
  AssuredWorkloads/src/V1beta1/Workload/ComplianceRegime.php
  AssuredWorkloads/synth.metadata
Labels: cla: yes, context: full

#3714 feat: add schema service
  PubSub/metadata/V1/Pubsub.php
  PubSub/metadata/V1/Schema.php
  PubSub/src/V1/CreateSchemaRequest.php
  PubSub/src/V1/DeleteSchemaRequest.php
  PubSub/src/V1/Encoding.php
  PubSub/src/V1/Gapic/PublisherGapicClient.php
  PubSub/src/V1/Gapic/SchemaServiceGapicClient.php
  PubSub/src/V1/Gapic/SubscriberGapicClient.php
  PubSub/src/V1/GetSchemaRequest.php
  PubSub/src/V1/ListSchemasRequest.php
  PubSub/src/V1/ListSchemasResponse.php
  PubSub/src/V1/PublisherGrpcClient.php
  PubSub/src/V1/Schema.php
  PubSub/src/V1/Schema/Type.php
  PubSub/src/V1/SchemaServiceClient.php
  PubSub/src/V1/SchemaServiceGrpcClient.php
  PubSub/src/V1/SchemaSettings.php
  PubSub/src/V1/SchemaView.php
  PubSub/src/V1/Schema_Type.php
  PubSub/src/V1/SubscriberGrpcClient.php
  PubSub/src/V1/Topic.php
  PubSub/src/V1/ValidateMessageRequest.php
  PubSub/src/V1/ValidateMessageResponse.php
  PubSub/src/V1/ValidateSchemaRequest.php
  PubSub/src/V1/ValidateSchemaResponse.php
  PubSub/src/V1/resources/schema_service_client_config.json
  PubSub/src/V1/resources/schema_service_descriptor_config.php
  PubSub/src/V1/resources/schema_service_rest_client_config.php
  PubSub/synth.metadata
  PubSub/synth.py
  PubSub/tests/Unit/V1/PublisherClientTest.php
  PubSub/tests/Unit/V1/SchemaServiceClientTest.php
Labels: cla: yes, context: full

#3756 fix: do not attempt to serialize SysvSemaphore in PHP8
  Core/src/Batch/SysvConfigStorage.php
Labels: cla: yes

#3808 feat: allow webhook headers through query parameters
  Dialogflow/metadata/V2/Agent.php
  Dialogflow/metadata/V2/AudioConfig.php
  Dialogflow/metadata/V2/Context.php
  Dialogflow/metadata/V2/EntityType.php
  Dialogflow/metadata/V2/Environment.php
  Dialogflow/metadata/V2/Intent.php
  Dialogflow/metadata/V2/Session.php
  Dialogflow/metadata/V2/SessionEntityType.php
  Dialogflow/metadata/V2/ValidationResult.php
  Dialogflow/metadata/V2/Webhook.php
  Dialogflow/src/V2/Agent.php
  Dialogflow/src/V2/Context.php
  Dialogflow/src/V2/DetectIntentRequest.php
  Dialogflow/src/V2/EventInput.php
  Dialogflow/src/V2/Gapic/SessionsGapicClient.php
  Dialogflow/src/V2/QueryParameters.php
  Dialogflow/src/V2/QueryResult.php
  Dialogflow/src/V2/SessionsGrpcClient.php
  Dialogflow/src/V2/StreamingDetectIntentRequest.php
  Dialogflow/src/V2/ValidationError/Severity.php
  Dialogflow/synth.metadata
Labels: cla: yes, context: full

#3640 feat: migrate retry/timeout settings to gRPC service configs
  Bigtable/metadata/Admin/V2/BigtableInstanceAdmin.php
  Bigtable/metadata/Admin/V2/BigtableTableAdmin.php
  Bigtable/metadata/Admin/V2/Common.php
  Bigtable/metadata/Admin/V2/Instance.php
  Bigtable/metadata/Admin/V2/Table.php
  Bigtable/metadata/V2/Bigtable.php
  Bigtable/metadata/V2/Data.php
  Bigtable/src/V2/resources/bigtable_client_config.json
  Bigtable/synth.metadata
Labels: cla: yes, context: full

#3558 feat(spanner): add commit stats support
  Spanner/src/Operation.php
  Spanner/src/Transaction.php
  Spanner/tests/Snippet/TransactionTest.php
  Spanner/tests/Unit/OperationTest.php
  Spanner/tests/Unit/TransactionTest.php
Labels: api: spanner, cla: yes

#3773 feat: add support for hive partitioning
  BigQuery/src/Connection/ServiceDefinition/bigquery-v2.json
  BigQuery/src/LoadJobConfiguration.php
  BigQuery/tests/Snippet/LoadJobConfigurationTest.php
  BigQuery/tests/System/LoadDataAndQueryTest.php
Labels: api: bigquery, cla: yes

#3818 feat!: add applySoftwareUpdate, change deleteInstance signature
  Memcache/metadata/V1Beta2/CloudMemcache.php
  Memcache/src/V1beta2/ApplyParametersRequest.php
  Memcache/src/V1beta2/ApplySoftwareUpdateRequest.php
  Memcache/src/V1beta2/CloudMemcacheGrpcClient.php
  Memcache/src/V1beta2/CreateInstanceRequest.php
  Memcache/src/V1beta2/DeleteInstanceRequest.php
  Memcache/src/V1beta2/Gapic/CloudMemcacheGapicClient.php
  Memcache/src/V1beta2/Instance.php
  Memcache/src/V1beta2/Instance/Node.php
  Memcache/src/V1beta2/Instance/Node/State.php
  Memcache/src/V1beta2/Instance/State.php
  Memcache/src/V1beta2/ListInstancesRequest.php
  Memcache/src/V1beta2/MemcacheParameters.php
  Memcache/src/V1beta2/OperationMetadata.php
  Memcache/src/V1beta2/UpdateInstanceRequest.php
  Memcache/src/V1beta2/resources/cloud_memcache_client_config.json
  Memcache/src/V1beta2/resources/cloud_memcache_descriptor_config.php
  Memcache/src/V1beta2/resources/cloud_memcache_rest_client_config.php
  Memcache/synth.metadata
  Memcache/tests/Unit/V1beta2/CloudMemcacheClientTest.php
Labels: cla: yes, context: full

#3813 feat: add resource formatting methods
  Recommender/metadata/V1/Insight.php
  Recommender/metadata/V1/Recommendation.php
  Recommender/metadata/V1/RecommenderService.php
  Recommender/src/V1/Gapic/RecommenderGapicClient.php
  Recommender/src/V1/resources/recommender_rest_client_config.php
  Recommender/synth.metadata
Labels: cla: yes, context: full

#3804 feat: add text decoration params suppport
  Vision/metadata/V1/Geometry.php
  Vision/metadata/V1/ImageAnnotator.php
  Vision/metadata/V1/ProductSearch.php
  Vision/metadata/V1/ProductSearchService.php
  Vision/metadata/V1/TextAnnotation.php
  Vision/metadata/V1/WebDetection.php
  Vision/src/V1/ImageContext.php
  Vision/src/V1/TextDetectionParams.php
  Vision/synth.metadata
Labels: cla: yes, context: full

#3805 feat: update to latest version of gapic generator
  Workflows/metadata/Executions/V1Beta/Executions.php
  Workflows/metadata/V1Beta/Workflows.php
  Workflows/src/Executions/V1beta/Gapic/ExecutionsGapicClient.php
  Workflows/src/V1beta/Gapic/WorkflowsGapicClient.php
  Workflows/synth.metadata
Labels: cla: yes, context: partial

#3809 feat: update to latest version of gapic generator
  Gaming/metadata/V1/Common.php
  Gaming/metadata/V1/GameServerClusters.php
  Gaming/metadata/V1/GameServerClustersService.php
  Gaming/metadata/V1/GameServerConfigs.php
  Gaming/metadata/V1/GameServerConfigsService.php
  Gaming/metadata/V1/GameServerDeployments.php
  Gaming/metadata/V1/GameServerDeploymentsService.php
  Gaming/metadata/V1/Realms.php
  Gaming/metadata/V1/RealmsService.php
  Gaming/src/V1/Gapic/GameServerClustersServiceGapicClient.php
  Gaming/src/V1/Gapic/GameServerConfigsServiceGapicClient.php
  Gaming/src/V1/Gapic/GameServerDeploymentsServiceGapicClient.php
  Gaming/src/V1/Gapic/RealmsServiceGapicClient.php
  Gaming/synth.metadata
Labels: cla: yes, context: partial

#3807 feat: sync changes in v1beta2 client. note: minor breaking changes in pre-GA API
  Dataproc/metadata/V1/AutoscalingPolicies.php
  Dataproc/metadata/V1/Clusters.php
  Dataproc/metadata/V1/Jobs.php
  Dataproc/metadata/V1/Operations.php
  Dataproc/metadata/V1/Shared.php
  Dataproc/metadata/V1/WorkflowTemplates.php
  Dataproc/metadata/V1Beta2/AutoscalingPolicies.php
  Dataproc/metadata/V1Beta2/Clusters.php
  Dataproc/metadata/V1Beta2/Jobs.php
  Dataproc/metadata/V1Beta2/Operations.php
  Dataproc/metadata/V1Beta2/Shared.php
  Dataproc/metadata/V1Beta2/WorkflowTemplates.php
  Dataproc/src/V1beta2/BasicYarnAutoscalingConfig.php
  Dataproc/src/V1beta2/ClusterConfig.php
  Dataproc/src/V1beta2/Component.php
  Dataproc/src/V1beta2/CreateClusterRequest.php
  Dataproc/src/V1beta2/DeleteClusterRequest.php
  Dataproc/src/V1beta2/Gapic/ClusterControllerGapicClient.php
  Dataproc/src/V1beta2/Gapic/WorkflowTemplateServiceGapicClient.php
  Dataproc/src/V1beta2/GceClusterConfig.php
  Dataproc/src/V1beta2/InstanceGroupConfig.php
  Dataproc/src/V1beta2/InstanceGroupConfig/Preemptibility.php
  Dataproc/src/V1beta2/InstanceGroupConfig_Preemptibility.php
  Dataproc/src/V1beta2/JobReference.php
  Dataproc/src/V1beta2/KerberosConfig.php
  Dataproc/src/V1beta2/LifecycleConfig.php
  Dataproc/src/V1beta2/OrderedJob.php
  Dataproc/src/V1beta2/PySparkJob.php
  Dataproc/src/V1beta2/SoftwareConfig.php
  Dataproc/src/V1beta2/SparkJob.php
  Dataproc/src/V1beta2/SparkRJob.php
  Dataproc/src/V1beta2/TemplateParameter.php
  Dataproc/src/V1beta2/UpdateClusterRequest.php
  Dataproc/src/V1beta2/WorkflowMetadata.php
  Dataproc/src/V1beta2/WorkflowTemplate.php
  Dataproc/src/V1beta2/WorkflowTemplateServiceGrpcClient.php
  Dataproc/synth.metadata
Labels: cla: yes, context: full

#3814 feat: update to latest version of gapic generator
  SecurityPrivateCa/metadata/V1Beta1/Resources.php
  SecurityPrivateCa/metadata/V1Beta1/Service.php
  SecurityPrivateCa/src/V1beta1/Gapic/CertificateAuthorityServiceGapicClient.php
  SecurityPrivateCa/synth.metadata
Labels: cla: yes, context: partial

#3802 feat: update to latest version of gapic generator
  Translate/metadata/V3/TranslationService.php
  Translate/src/V3/Gapic/TranslationServiceGapicClient.php
  Translate/synth.metadata
Labels: cla: yes, context: partial

#3823 feat: introduce memcache v1 client
  Memcache/README.md
  Memcache/metadata/V1/CloudMemcache.php
  Memcache/src/V1/ApplyParametersRequest.php
  Memcache/src/V1/CloudMemcacheClient.php
  Memcache/src/V1/CloudMemcacheGrpcClient.php
  Memcache/src/V1/CreateInstanceRequest.php
  Memcache/src/V1/DeleteInstanceRequest.php
  Memcache/src/V1/Gapic/CloudMemcacheGapicClient.php
  Memcache/src/V1/GetInstanceRequest.php
  Memcache/src/V1/Instance.php
  Memcache/src/V1/Instance/InstanceMessage.php
  Memcache/src/V1/Instance/InstanceMessage/Code.php
  Memcache/src/V1/Instance/Node.php
  Memcache/src/V1/Instance/Node/State.php
  Memcache/src/V1/Instance/NodeConfig.php
  Memcache/src/V1/Instance/State.php
  Memcache/src/V1/Instance_InstanceMessage.php
  Memcache/src/V1/Instance_InstanceMessage_Code.php
  Memcache/src/V1/Instance_Node.php
  Memcache/src/V1/Instance_NodeConfig.php
  Memcache/src/V1/Instance_Node_State.php
  Memcache/src/V1/Instance_State.php
  Memcache/src/V1/ListInstancesRequest.php
  Memcache/src/V1/ListInstancesResponse.php
  Memcache/src/V1/MemcacheParameters.php
  Memcache/src/V1/MemcacheVersion.php
  Memcache/src/V1/OperationMetadata.php
  Memcache/src/V1/README.md
  Memcache/src/V1/UpdateInstanceRequest.php
  Memcache/src/V1/UpdateParametersRequest.php
  Memcache/src/V1/resources/cloud_memcache_client_config.json
  Memcache/src/V1/resources/cloud_memcache_descriptor_config.php
  Memcache/src/V1/resources/cloud_memcache_rest_client_config.php
  Memcache/synth.metadata
  Memcache/synth.py
  Memcache/tests/Unit/V1/CloudMemcacheClientTest.php
  docs/contents/cloud-memcache.json
Labels: cla: yes

#3821 feat: add new face annotation landmark types
  Vision/metadata/V1/ImageAnnotator.php
  Vision/metadata/V1/ProductSearch.php
  Vision/src/V1/BatchAnnotateFilesRequest.php
  Vision/src/V1/FaceAnnotation/Landmark/Type.php
  Vision/src/V1/Gapic/ImageAnnotatorGapicClient.php
  Vision/src/V1/Gapic/ProductSearchGapicClient.php
  Vision/src/V1/GetProductSetRequest.php
  Vision/src/V1/Image.php
  Vision/src/V1/ImageAnnotatorGrpcClient.php
  Vision/src/V1/Product.php
  Vision/src/V1/ProductSearchGrpcClient.php
  Vision/src/V1/ProductSearchParams.php
  Vision/src/V1/SafeSearchAnnotation.php
  Vision/synth.metadata
Labels: cla: yes, context: full

#3662 feat!: update v1alpha client to latest
  AnalyticsAdmin/metadata/V1Alpha/AnalyticsAdmin.php
  AnalyticsAdmin/metadata/V1Alpha/Resources.php
  AnalyticsAdmin/src/V1alpha/Account.php
  AnalyticsAdmin/src/V1alpha/AnalyticsAdminServiceGrpcClient.php
  AnalyticsAdmin/src/V1alpha/EnhancedMeasurementSettings.php
  AnalyticsAdmin/src/V1alpha/Gapic/AnalyticsAdminServiceGapicClient.php
  AnalyticsAdmin/src/V1alpha/GlobalSiteTag.php
  AnalyticsAdmin/src/V1alpha/GoogleAdsLink.php
  AnalyticsAdmin/src/V1alpha/ListFirebaseLinksRequest.php
  AnalyticsAdmin/src/V1alpha/ListFirebaseLinksResponse.php
  AnalyticsAdmin/src/V1alpha/ListPropertiesRequest.php
  AnalyticsAdmin/src/V1alpha/UpdateAccountRequest.php
  AnalyticsAdmin/src/V1alpha/UpdateAndroidAppDataStreamRequest.php
  AnalyticsAdmin/src/V1alpha/UpdateEnhancedMeasurementSettingsRequest.php
  AnalyticsAdmin/src/V1alpha/UpdateFirebaseLinkRequest.php
  AnalyticsAdmin/src/V1alpha/UpdateGoogleAdsLinkRequest.php
  AnalyticsAdmin/src/V1alpha/UpdateIosAppDataStreamRequest.php
  AnalyticsAdmin/src/V1alpha/UpdatePropertyRequest.php
  AnalyticsAdmin/src/V1alpha/UpdateWebDataStreamRequest.php
  AnalyticsAdmin/src/V1alpha/resources/analytics_admin_service_descriptor_config.php
  AnalyticsAdmin/synth.metadata
  AnalyticsAdmin/tests/Unit/V1alpha/AnalyticsAdminServiceClientTest.php
Labels: cla: yes, context: partial

#3824 feat: introduce service directory v1 client
  ServiceDirectory/README.md
  ServiceDirectory/metadata/V1/Endpoint.php
  ServiceDirectory/metadata/V1/LookupService.php
  ServiceDirectory/metadata/V1/PBNamespace.php
  ServiceDirectory/metadata/V1/RegistrationService.php
  ServiceDirectory/metadata/V1/Service.php
  ServiceDirectory/src/V1/CreateEndpointRequest.php
  ServiceDirectory/src/V1/CreateNamespaceRequest.php
  ServiceDirectory/src/V1/CreateServiceRequest.php
  ServiceDirectory/src/V1/DeleteEndpointRequest.php
  ServiceDirectory/src/V1/DeleteNamespaceRequest.php
  ServiceDirectory/src/V1/DeleteServiceRequest.php
  ServiceDirectory/src/V1/Endpoint.php
  ServiceDirectory/src/V1/Gapic/LookupServiceGapicClient.php
  ServiceDirectory/src/V1/Gapic/RegistrationServiceGapicClient.php
  ServiceDirectory/src/V1/GetEndpointRequest.php
  ServiceDirectory/src/V1/GetNamespaceRequest.php
  ServiceDirectory/src/V1/GetServiceRequest.php
  ServiceDirectory/src/V1/ListEndpointsRequest.php
  ServiceDirectory/src/V1/ListEndpointsResponse.php
  ServiceDirectory/src/V1/ListNamespacesRequest.php
  ServiceDirectory/src/V1/ListNamespacesResponse.php
  ServiceDirectory/src/V1/ListServicesRequest.php
  ServiceDirectory/src/V1/ListServicesResponse.php
  ServiceDirectory/src/V1/LookupServiceClient.php
  ServiceDirectory/src/V1/LookupServiceGrpcClient.php
  ServiceDirectory/src/V1/PBNamespace.php
  ServiceDirectory/src/V1/README.md
  ServiceDirectory/src/V1/RegistrationServiceClient.php
  ServiceDirectory/src/V1/RegistrationServiceGrpcClient.php
  ServiceDirectory/src/V1/ResolveServiceRequest.php
  ServiceDirectory/src/V1/ResolveServiceResponse.php
  ServiceDirectory/src/V1/Service.php
  ServiceDirectory/src/V1/UpdateEndpointRequest.php
  ServiceDirectory/src/V1/UpdateNamespaceRequest.php
  ServiceDirectory/src/V1/UpdateServiceRequest.php
  ServiceDirectory/src/V1/resources/lookup_service_client_config.json
  ServiceDirectory/src/V1/resources/lookup_service_descriptor_config.php
  ServiceDirectory/src/V1/resources/lookup_service_rest_client_config.php
  ServiceDirectory/src/V1/resources/registration_service_client_config.json
  ServiceDirectory/src/V1/resources/registration_service_descriptor_config.php
  ServiceDirectory/src/V1/resources/registration_service_rest_client_config.php
  ServiceDirectory/synth.metadata
  ServiceDirectory/synth.py
  ServiceDirectory/tests/Unit/V1/LookupServiceClientTest.php
  ServiceDirectory/tests/Unit/V1/RegistrationServiceClientTest.php
  docs/contents/cloud-service-directory.json
Labels: cla: yes

#3826 feat: add Pub/Sub endpoints for Cloud Channel API
  Channel/metadata/V1/Service.php
  Channel/metadata/V1/SubscriberEvent.php
  Channel/src/V1/CloudChannelServiceGrpcClient.php
  Channel/src/V1/CustomerEvent.php
  Channel/src/V1/CustomerEvent/Type.php
  Channel/src/V1/CustomerEvent_Type.php
  Channel/src/V1/EntitlementEvent.php
  Channel/src/V1/EntitlementEvent/Type.php
  Channel/src/V1/EntitlementEvent_Type.php
  Channel/src/V1/Gapic/CloudChannelServiceGapicClient.php
  Channel/src/V1/ListSubscribersRequest.php
  Channel/src/V1/ListSubscribersResponse.php
  Channel/src/V1/RegisterSubscriberRequest.php
  Channel/src/V1/RegisterSubscriberResponse.php
  Channel/src/V1/SubscriberEvent.php
  Channel/src/V1/UnregisterSubscriberRequest.php
  Channel/src/V1/UnregisterSubscriberResponse.php
  Channel/src/V1/resources/cloud_channel_service_client_config.json
  Channel/src/V1/resources/cloud_channel_service_descriptor_config.php
  Channel/src/V1/resources/cloud_channel_service_rest_client_config.php
  Channel/synth.metadata
  Channel/tests/Unit/V1/CloudChannelServiceClientTest.php
Labels: cla: yes, context: full

#3653 fix: add support for reading Bigtable key value of zero
  Bigtable/src/ChunkFormatter.php
  Bigtable/tests/Unit/ChunkFormatterTest.php
Labels: cla: yes

#3815 feat(spanner): add support for Point In Time Restore (PITR)
  Spanner/src/Backup.php
  Spanner/src/Connection/Grpc.php
  Spanner/tests/System/BackupTest.php
  Spanner/tests/Unit/BackupTest.php
Labels: api: spanner, cla: yes

#3835 chore: update auth link
  AUTHENTICATION.md
Labels: cla: yes
