Repository googleapis/google-cloud-php, pull requests merged in 2021-12, with the labels that each got.

#4736 tests: update compute tests to use LRO instead of custom polling
  Compute/tests/System/V1/AddressTest.php
  Compute/tests/System/V1/SmokeTest.php
Labels: cla: yes

#4748 chore(AccessContextManager): migrate to owlbot
  AccessContextManager/.OwlBot.yaml
  AccessContextManager/owlbot.py
Labels: api: accesscontextmanager

#4737 chore(vision): Added files to migrate to owlbot
  Vision/.OwlBot.yaml
  Vision/owlbot.py
Labels: cla: yes, api: vision

#4759 [ApigeeConnect] chore(bazel): Update gapic-generator-php to v1.2.1
  ApigeeConnect/src/V1/ConnectionServiceClient.php
  ApigeeConnect/src/V1/Gapic/ConnectionServiceGapicClient.php
  ApigeeConnect/src/V1/Gapic/TetherGapicClient.php
  ApigeeConnect/src/V1/TetherClient.php
  ApigeeConnect/synth.metadata
Labels: context: full

#4806 [WebSecurityScanner] chore(bazel): Update gapic-generator-php to v1.2.1
  WebSecurityScanner/src/V1beta/Gapic/WebSecurityScannerGapicClient.php
  WebSecurityScanner/src/V1beta/WebSecurityScannerClient.php
  WebSecurityScanner/synth.metadata
Labels: context: full

#4805 [WebRisk] chore(bazel): Update gapic-generator-php to v1.2.1
  WebRisk/src/V1/Gapic/WebRiskServiceGapicClient.php
  WebRisk/src/V1/WebRiskServiceClient.php
  WebRisk/src/V1beta1/Gapic/WebRiskServiceV1Beta1GapicClient.php
  WebRisk/src/V1beta1/WebRiskServiceV1Beta1Client.php
  WebRisk/synth.metadata
Labels: context: full

#4804 [VpcAccess] chore(bazel): Update gapic-generator-php to v1.2.1
  VpcAccess/src/V1/Gapic/VpcAccessServiceGapicClient.php
  VpcAccess/src/V1/VpcAccessServiceClient.php
  VpcAccess/synth.metadata
Labels: context: full

#4803 [Translate] chore(bazel): Update gapic-generator-php to v1.2.1
  Translate/src/V3/Gapic/TranslationServiceGapicClient.php
  Translate/src/V3/TranslationServiceClient.php
  Translate/synth.metadata
Labels: context: full

#4802 [Trace] chore(bazel): Update gapic-generator-php to v1.2.1
  Trace/src/V2/Gapic/TraceServiceGapicClient.php
  Trace/src/V2/TraceServiceClient.php
  Trace/synth.metadata
Labels: context: full

#4788 [OrgPolicy] chore(bazel): Update gapic-generator-php to v1.2.1
  OrgPolicy/src/V2/Gapic/OrgPolicyGapicClient.php
  OrgPolicy/src/V2/OrgPolicyClient.php
  OrgPolicy/synth.metadata
Labels: context: full

#4790 [PolicyTroubleshooter] chore(bazel): Update gapic-generator-php to v1.2.1
  PolicyTroubleshooter/src/V1/Gapic/IamCheckerGapicClient.php
  PolicyTroubleshooter/src/V1/IamCheckerClient.php
  PolicyTroubleshooter/synth.metadata
Labels: context: full

#4791 [RecommendationEngine] chore(bazel): Update gapic-generator-php to v1.2.1
  RecommendationEngine/src/V1beta1/CatalogServiceClient.php
  RecommendationEngine/src/V1beta1/Gapic/CatalogServiceGapicClient.php
  RecommendationEngine/src/V1beta1/Gapic/PredictionApiKeyRegistryGapicClient.php
  RecommendationEngine/src/V1beta1/Gapic/PredictionServiceGapicClient.php
  RecommendationEngine/src/V1beta1/Gapic/UserEventServiceGapicClient.php
  RecommendationEngine/src/V1beta1/PredictionApiKeyRegistryClient.php
  RecommendationEngine/src/V1beta1/PredictionServiceClient.php
  RecommendationEngine/src/V1beta1/UserEventServiceClient.php
  RecommendationEngine/synth.metadata
Labels: context: full

#4792 [Recommender] chore(bazel): Update gapic-generator-php to v1.2.1
  Recommender/src/V1/Gapic/RecommenderGapicClient.php
  Recommender/src/V1/RecommenderClient.php
  Recommender/synth.metadata
Labels: context: full

#4793 [Redis] chore(bazel): Update gapic-generator-php to v1.2.1
  Redis/src/V1/Gapic/CloudRedisGapicClient.php
  Redis/src/V1beta1/Gapic/CloudRedisGapicClient.php
  Redis/synth.metadata
Labels: context: full

#4794 [ResourceSettings] chore(bazel): Update gapic-generator-php to v1.2.1
  ResourceSettings/src/V1/Gapic/ResourceSettingsServiceGapicClient.php
  ResourceSettings/src/V1/ResourceSettingsServiceClient.php
  ResourceSettings/synth.metadata
Labels: context: full

#4795 [SecretManager] chore(bazel): Update gapic-generator-php to v1.2.1
  SecretManager/src/V1/Gapic/SecretManagerServiceGapicClient.php
  SecretManager/src/V1/SecretManagerServiceClient.php
  SecretManager/src/V1beta1/Gapic/SecretManagerServiceGapicClient.php
  SecretManager/src/V1beta1/SecretManagerServiceClient.php
  SecretManager/synth.metadata
Labels: context: full

#4796 [ServiceControl] chore(bazel): Update gapic-generator-php to v1.2.1
  ServiceControl/src/V1/Gapic/QuotaControllerGapicClient.php
  ServiceControl/src/V1/Gapic/ServiceControllerGapicClient.php
  ServiceControl/src/V1/QuotaControllerClient.php
  ServiceControl/src/V1/ServiceControllerClient.php
  ServiceControl/synth.metadata
Labels: context: full

#4798 [ServiceManagement] chore(bazel): Update gapic-generator-php to v1.2.1
  ServiceManagement/src/V1/Gapic/ServiceManagerGapicClient.php
  ServiceManagement/src/V1/ServiceManagerClient.php
  ServiceManagement/synth.metadata
Labels: context: full

#4789 [OsLogin] chore(bazel): Update gapic-generator-php to v1.2.1
  OsLogin/src/V1/Gapic/OsLoginServiceGapicClient.php
  OsLogin/src/V1/OsLoginServiceClient.php
  OsLogin/src/V1beta/Gapic/OsLoginServiceGapicClient.php
  OsLogin/src/V1beta/OsLoginServiceClient.php
  OsLogin/synth.metadata
Labels: context: full

#4786 [Notebooks] chore(bazel): Update gapic-generator-php to v1.2.1
  Notebooks/src/V1beta1/Gapic/NotebookServiceGapicClient.php
  Notebooks/src/V1beta1/NotebookServiceClient.php
  Notebooks/synth.metadata
Labels: context: full

#4767 [DataFusion] chore(bazel): Update gapic-generator-php to v1.2.1
  DataFusion/src/V1/DataFusionClient.php
  DataFusion/src/V1/Gapic/DataFusionGapicClient.php
  DataFusion/synth.metadata
Labels: context: full

#4763 [Billing] chore(bazel): Update gapic-generator-php to v1.2.1
  Billing/src/V1/CloudBillingClient.php
  Billing/src/V1/CloudCatalogClient.php
  Billing/src/V1/Gapic/CloudBillingGapicClient.php
  Billing/src/V1/Gapic/CloudCatalogGapicClient.php
  Billing/synth.metadata
Labels: context: full

#4762 [BigQueryReservation] chore(bazel): Update gapic-generator-php to v1.2.1
  BigQueryReservation/src/V1/Gapic/ReservationServiceGapicClient.php
  BigQueryReservation/src/V1/ReservationServiceClient.php
  BigQueryReservation/synth.metadata
Labels: context: full

#4761 [BigQueryConnection] chore(bazel): Update gapic-generator-php to v1.2.1
  BigQueryConnection/src/V1/ConnectionServiceClient.php
  BigQueryConnection/src/V1/Gapic/ConnectionServiceGapicClient.php
  BigQueryConnection/synth.metadata
Labels: context: full

#4760 [AppEngineAdmin] chore(bazel): Update gapic-generator-php to v1.2.1
  AppEngineAdmin/src/V1/ApplicationsClient.php
  AppEngineAdmin/src/V1/AuthorizedCertificatesClient.php
  AppEngineAdmin/src/V1/AuthorizedDomainsClient.php
  AppEngineAdmin/src/V1/DomainMappingsClient.php
  AppEngineAdmin/src/V1/FirewallClient.php
  AppEngineAdmin/src/V1/Gapic/ApplicationsGapicClient.php
  AppEngineAdmin/src/V1/Gapic/AuthorizedCertificatesGapicClient.php
  AppEngineAdmin/src/V1/Gapic/AuthorizedDomainsGapicClient.php
  AppEngineAdmin/src/V1/Gapic/DomainMappingsGapicClient.php
  AppEngineAdmin/src/V1/Gapic/FirewallGapicClient.php
  AppEngineAdmin/src/V1/Gapic/InstancesGapicClient.php
  AppEngineAdmin/src/V1/Gapic/ServicesGapicClient.php
  AppEngineAdmin/src/V1/Gapic/VersionsGapicClient.php
  AppEngineAdmin/src/V1/InstancesClient.php
  AppEngineAdmin/src/V1/ServicesClient.php
  AppEngineAdmin/src/V1/VersionsClient.php
  AppEngineAdmin/synth.metadata
Labels: context: full

#4765 [Container] chore(bazel): Update gapic-generator-php to v1.2.1
  Container/src/V1/ClusterManagerClient.php
  Container/src/V1/Gapic/ClusterManagerGapicClient.php
  Container/synth.metadata
Labels: context: full

#4764 [BillingBudgets] chore(bazel): Update gapic-generator-php to v1.2.1
  BillingBudgets/src/V1/BudgetServiceClient.php
  BillingBudgets/src/V1/Gapic/BudgetServiceGapicClient.php
  BillingBudgets/src/V1beta1/BudgetServiceClient.php
  BillingBudgets/src/V1beta1/Gapic/BudgetServiceGapicClient.php
  BillingBudgets/synth.metadata
Labels: context: full

#4782 [MediaTranslation] chore(bazel): Update gapic-generator-php to v1.2.1
  MediaTranslation/src/V1beta1/Gapic/SpeechTranslationServiceGapicClient.php
  MediaTranslation/src/V1beta1/SpeechTranslationServiceClient.php
  MediaTranslation/synth.metadata
Labels: context: full

#4780 [Language] chore(bazel): Update gapic-generator-php to v1.2.1
  Language/src/V1/Gapic/LanguageServiceGapicClient.php
  Language/src/V1/LanguageServiceClient.php
  Language/src/V1beta2/Gapic/LanguageServiceGapicClient.php
  Language/src/V1beta2/LanguageServiceClient.php
  Language/synth.metadata
Labels: context: full

#4778 [Iap] chore(bazel): Update gapic-generator-php to v1.2.1
  Iap/src/V1/Gapic/IdentityAwareProxyAdminServiceGapicClient.php
  Iap/src/V1/Gapic/IdentityAwareProxyOAuthServiceGapicClient.php
  Iap/src/V1/IdentityAwareProxyAdminServiceClient.php
  Iap/src/V1/IdentityAwareProxyOAuthServiceClient.php
  Iap/synth.metadata
Labels: context: full

#4777 [GkeHub] chore(bazel): Update gapic-generator-php to v1.2.1
  GkeHub/src/V1beta1/Gapic/GkeHubMembershipServiceGapicClient.php
  GkeHub/src/V1beta1/GkeHubMembershipServiceClient.php
  GkeHub/synth.metadata
Labels: context: full

#4781 [LifeSciences] chore(bazel): Update gapic-generator-php to v1.2.1
  LifeSciences/src/V2beta/Gapic/WorkflowsServiceV2BetaGapicClient.php
  LifeSciences/src/V2beta/WorkflowsServiceV2BetaClient.php
  LifeSciences/synth.metadata
Labels: context: full

#4775 [Eventarc] chore(bazel): Update gapic-generator-php to v1.2.1
  Eventarc/src/V1/EventarcClient.php
  Eventarc/src/V1/Gapic/EventarcGapicClient.php
  Eventarc/synth.metadata
Labels: context: full

#4774 [EssentialContacts] chore(bazel): Update gapic-generator-php to v1.2.1
  EssentialContacts/src/V1/EssentialContactsServiceClient.php
  EssentialContacts/src/V1/Gapic/EssentialContactsServiceGapicClient.php
  EssentialContacts/synth.metadata
Labels: context: full

#4785 [NetworkSecurity] chore(bazel): Update gapic-generator-php to v1.2.1
  NetworkSecurity/src/V1beta1/Gapic/NetworkSecurityGapicClient.php
  NetworkSecurity/src/V1beta1/NetworkSecurityClient.php
  NetworkSecurity/synth.metadata
Labels: context: full

#4784 [NetworkManagement] chore(bazel): Update gapic-generator-php to v1.2.1
  NetworkManagement/src/V1/Gapic/ReachabilityServiceGapicClient.php
  NetworkManagement/src/V1/ReachabilityServiceClient.php
  NetworkManagement/synth.metadata
Labels: context: full

#4783 [Memcache] chore(bazel): Update gapic-generator-php to v1.2.1
  Memcache/src/V1/CloudMemcacheClient.php
  Memcache/src/V1/Gapic/CloudMemcacheGapicClient.php
  Memcache/src/V1beta2/CloudMemcacheClient.php
  Memcache/src/V1beta2/Gapic/CloudMemcacheGapicClient.php
  Memcache/synth.metadata
Labels: kokoro:run, context: full

#4779 [Iot] chore(bazel): Update gapic-generator-php to v1.2.1
  Iot/src/V1/DeviceManagerClient.php
  Iot/src/V1/Gapic/DeviceManagerGapicClient.php
  Iot/synth.metadata
Labels: context: full

#4772 [Deploy] chore(bazel): Update gapic-generator-php to v1.2.1
  Deploy/src/V1/CloudDeployClient.php
  Deploy/src/V1/Gapic/CloudDeployGapicClient.php
  Deploy/synth.metadata
Labels: context: full

#4770 [DatastoreAdmin] chore(bazel): Update gapic-generator-php to v1.2.1
  DatastoreAdmin/src/V1/DatastoreAdminClient.php
  DatastoreAdmin/src/V1/Gapic/DatastoreAdminGapicClient.php
  DatastoreAdmin/synth.metadata
Labels: context: full

#4769 [DataprocMetastore] chore(bazel): Update gapic-generator-php to v1.2.1
  DataprocMetastore/src/V1/DataprocMetastoreClient.php
  DataprocMetastore/src/V1/Gapic/DataprocMetastoreGapicClient.php
  DataprocMetastore/src/V1alpha/DataprocMetastoreClient.php
  DataprocMetastore/src/V1alpha/Gapic/DataprocMetastoreGapicClient.php
  DataprocMetastore/src/V1beta/DataprocMetastoreClient.php
  DataprocMetastore/src/V1beta/Gapic/DataprocMetastoreGapicClient.php
  DataprocMetastore/synth.metadata
Labels: context: full

#4768 [Dataflow] chore(bazel): Update gapic-generator-php to v1.2.1
  Dataflow/src/V1beta3/FlexTemplatesServiceClient.php
  Dataflow/src/V1beta3/Gapic/FlexTemplatesServiceGapicClient.php
  Dataflow/src/V1beta3/Gapic/JobsV1Beta3GapicClient.php
  Dataflow/src/V1beta3/Gapic/MessagesV1Beta3GapicClient.php
  Dataflow/src/V1beta3/Gapic/MetricsV1Beta3GapicClient.php
  Dataflow/src/V1beta3/Gapic/SnapshotsV1Beta3GapicClient.php
  Dataflow/src/V1beta3/Gapic/TemplatesServiceGapicClient.php
  Dataflow/src/V1beta3/JobsV1Beta3Client.php
  Dataflow/src/V1beta3/MessagesV1Beta3Client.php
  Dataflow/src/V1beta3/MetricsV1Beta3Client.php
  Dataflow/src/V1beta3/SnapshotsV1Beta3Client.php
  Dataflow/src/V1beta3/TemplatesServiceClient.php
  Dataflow/synth.metadata
Labels: context: full

#4771 [Debugger] chore(bazel): Update gapic-generator-php to v1.2.1
  Debugger/src/V2/Controller2Client.php
  Debugger/src/V2/Debugger2Client.php
  Debugger/src/V2/Gapic/Controller2GapicClient.php
  Debugger/src/V2/Gapic/Debugger2GapicClient.php
  Debugger/synth.metadata
Labels: context: full

#4738 [Dlp] feat: added deidentify replacement dictionaries feat: added field for BigQuery inspect template inclusion lists feat: added field to support infotype versioning
  Dlp/metadata/V2/Dlp.php
  Dlp/metadata/V2/Storage.php
  Dlp/src/V2/Action/PublishFindingsToCloudDataCatalog.php
  Dlp/src/V2/BigQueryOptions.php
  Dlp/src/V2/ByteContentItem/BytesType.php
  Dlp/src/V2/CloudStorageOptions.php
  Dlp/src/V2/CloudStorageRegexFileSet.php
  Dlp/src/V2/CreateDlpJobRequest.php
  Dlp/src/V2/CryptoDeterministicConfig.php
  Dlp/src/V2/CryptoKey.php
  Dlp/src/V2/CustomInfoType/Dictionary.php
  Dlp/src/V2/CustomInfoType/Regex.php
  Dlp/src/V2/CustomInfoType/SurrogateType.php
  Dlp/src/V2/DeidentifyTemplate.php
  Dlp/src/V2/DlpJobType.php
  Dlp/src/V2/DlpServiceGrpcClient.php
  Dlp/src/V2/FieldTransformation.php
  Dlp/src/V2/FileType.php
  Dlp/src/V2/Finding.php
  Dlp/src/V2/FixedSizeBucketingConfig.php
  Dlp/src/V2/Gapic/DlpServiceGapicClient.php
  Dlp/src/V2/InfoType.php
  Dlp/src/V2/InspectConfig/FindingLimits.php
  Dlp/src/V2/InspectDataSourceDetails.php
  Dlp/src/V2/InspectDataSourceDetails/Result.php
  Dlp/src/V2/JobTrigger/Trigger.php
  Dlp/src/V2/KmsWrappedCryptoKey.php
  Dlp/src/V2/ListJobTriggersRequest.php
  Dlp/src/V2/PrimitiveTransformation.php
  Dlp/src/V2/ReplaceDictionaryConfig.php
  Dlp/src/V2/Schedule.php
  Dlp/src/V2/StorageConfig.php
  Dlp/src/V2/Table.php
  Dlp/src/V2/resources/dlp_service_rest_client_config.php
  Dlp/synth.metadata
Labels: cla: yes, context: full

#4735 [Spanner] chore(ruby): Set up Ruby build configs for vmmigration clients
  Spanner/src/V1/resources/spanner_rest_client_config.php
  Spanner/synth.metadata
Labels: cla: yes, context: full

#4720 [TextToSpeech] docs: fix docstring formatting
  TextToSpeech/metadata/V1/CloudTts.php
  TextToSpeech/src/V1/AudioEncoding.php
  TextToSpeech/src/V1/Gapic/TextToSpeechGapicClient.php
  TextToSpeech/src/V1/ListVoicesRequest.php
  TextToSpeech/src/V1/SsmlVoiceGender.php
  TextToSpeech/src/V1/TextToSpeechGrpcClient.php
  TextToSpeech/src/V1/resources/text_to_speech_client_config.json
  TextToSpeech/synth.metadata
Labels: cla: yes, context: full

#4719 [SecurityCenter] feat: Added mute related APIs, proto messages and fields
  SecurityCenter/metadata/V1/ExternalSystem.php
  SecurityCenter/metadata/V1/Finding.php
  SecurityCenter/metadata/V1/MuteConfig.php
  SecurityCenter/metadata/V1/SecuritycenterService.php
  SecurityCenter/src/V1/BulkMuteFindingsRequest.php
  SecurityCenter/src/V1/BulkMuteFindingsResponse.php
  SecurityCenter/src/V1/CreateMuteConfigRequest.php
  SecurityCenter/src/V1/DeleteMuteConfigRequest.php
  SecurityCenter/src/V1/ExternalSystem.php
  SecurityCenter/src/V1/Finding.php
  SecurityCenter/src/V1/Finding/Mute.php
  SecurityCenter/src/V1/Finding_Mute.php
  SecurityCenter/src/V1/Gapic/SecurityCenterGapicClient.php
  SecurityCenter/src/V1/GetMuteConfigRequest.php
  SecurityCenter/src/V1/ListMuteConfigsRequest.php
  SecurityCenter/src/V1/ListMuteConfigsResponse.php
  SecurityCenter/src/V1/MuteConfig.php
  SecurityCenter/src/V1/SecurityCenterGrpcClient.php
  SecurityCenter/src/V1/SetMuteRequest.php
  SecurityCenter/src/V1/UpdateExternalSystemRequest.php
  SecurityCenter/src/V1/UpdateMuteConfigRequest.php
  SecurityCenter/src/V1/gapic_metadata.json
  SecurityCenter/src/V1/resources/security_center_client_config.json
  SecurityCenter/src/V1/resources/security_center_descriptor_config.php
  SecurityCenter/src/V1/resources/security_center_rest_client_config.php
  SecurityCenter/synth.metadata
  SecurityCenter/tests/Unit/V1/SecurityCenterClientTest.php
Labels: cla: yes, context: full

#4718 [ResourceManager] docs: fix docstring formatting
  ResourceManager/src/V3/Gapic/ProjectsGapicClient.php
  ResourceManager/src/V3/SearchProjectsRequest.php
  ResourceManager/synth.metadata
Labels: cla: yes, context: full

#4712 [NetworkConnectivity] chore: Add C# generation for Compute v1
  NetworkConnectivity/metadata/V1/Hub.php
  NetworkConnectivity/src/V1/CreateHubRequest.php
  NetworkConnectivity/src/V1/CreateSpokeRequest.php
  NetworkConnectivity/src/V1/Gapic/HubServiceGapicClient.php
  NetworkConnectivity/src/V1/Hub.php
  NetworkConnectivity/src/V1/RoutingVPC.php
  NetworkConnectivity/src/V1/Spoke.php
  NetworkConnectivity/src/V1/resources/hub_service_rest_client_config.php
  NetworkConnectivity/synth.metadata
  NetworkConnectivity/tests/Unit/V1/HubServiceClientTest.php
Labels: cla: yes, context: full

#4702 [Dataproc] feat: Add support for dataproc BatchController service
  Dataproc/metadata/V1/Batches.php
  Dataproc/src/V1/Batch.php
  Dataproc/src/V1/Batch/State.php
  Dataproc/src/V1/Batch/StateHistory.php
  Dataproc/src/V1/BatchControllerClient.php
  Dataproc/src/V1/BatchControllerGrpcClient.php
  Dataproc/src/V1/Batch_State.php
  Dataproc/src/V1/Batch_StateHistory.php
  Dataproc/src/V1/CreateBatchRequest.php
  Dataproc/src/V1/DeleteBatchRequest.php
  Dataproc/src/V1/Gapic/BatchControllerGapicClient.php
  Dataproc/src/V1/GetBatchRequest.php
  Dataproc/src/V1/ListBatchesRequest.php
  Dataproc/src/V1/ListBatchesResponse.php
  Dataproc/src/V1/PySparkBatch.php
  Dataproc/src/V1/SparkBatch.php
  Dataproc/src/V1/SparkRBatch.php
  Dataproc/src/V1/SparkSqlBatch.php
  Dataproc/src/V1/gapic_metadata.json
  Dataproc/src/V1/resources/batch_controller_client_config.json
  Dataproc/src/V1/resources/batch_controller_descriptor_config.php
  Dataproc/src/V1/resources/batch_controller_rest_client_config.php
  Dataproc/synth.metadata
  Dataproc/tests/Unit/V1/BatchControllerClientTest.php
Labels: cla: yes, context: full

#4699 [ContactCenterInsights] feat: Add ability to update phrase matchers feat: Add issue model stats to time series feat: Add display name to issue model stats
  ContactCenterInsights/metadata/V1/ContactCenterInsights.php
  ContactCenterInsights/metadata/V1/Resources.php
  ContactCenterInsights/src/V1/CalculateStatsResponse.php
  ContactCenterInsights/src/V1/ContactCenterInsightsGrpcClient.php
  ContactCenterInsights/src/V1/CreateConversationRequest.php
  ContactCenterInsights/src/V1/ExportInsightsDataRequest.php
  ContactCenterInsights/src/V1/ExportInsightsDataRequest/WriteDisposition.php
  ContactCenterInsights/src/V1/Gapic/ContactCenterInsightsGapicClient.php
  ContactCenterInsights/src/V1/IssueModelLabelStats/IssueStats.php
  ContactCenterInsights/src/V1/UpdatePhraseMatcherRequest.php
  ContactCenterInsights/src/V1/gapic_metadata.json
  ContactCenterInsights/src/V1/resources/contact_center_insights_client_config.json
  ContactCenterInsights/src/V1/resources/contact_center_insights_rest_client_config.php
  ContactCenterInsights/synth.metadata
  ContactCenterInsights/tests/Unit/V1/ContactCenterInsightsClientTest.php
Labels: cla: yes, context: full

#4696 [Grafeas] feat: Updating the grafeas protos to include compliance and intoto attestation protos
  Grafeas/metadata/V1/Attestation.php
  Grafeas/metadata/V1/Build.php
  Grafeas/metadata/V1/Common.php
  Grafeas/metadata/V1/Compliance.php
  Grafeas/metadata/V1/DsseAttestation.php
  Grafeas/metadata/V1/Grafeas.php
  Grafeas/metadata/V1/IntotoProvenance.php
  Grafeas/metadata/V1/IntotoStatement.php
  Grafeas/metadata/V1/Package.php
  Grafeas/metadata/V1/SlsaProvenance.php
  Grafeas/metadata/V1/Vulnerability.php
  Grafeas/src/V1/AttestationOccurrence.php
  Grafeas/src/V1/BuildOccurrence.php
  Grafeas/src/V1/BuilderConfig.php
  Grafeas/src/V1/Completeness.php
  Grafeas/src/V1/ComplianceNote.php
  Grafeas/src/V1/ComplianceNote/CisBenchmark.php
  Grafeas/src/V1/ComplianceOccurrence.php
  Grafeas/src/V1/ComplianceVersion.php
  Grafeas/src/V1/DSSEAttestationNote.php
  Grafeas/src/V1/DSSEAttestationNote/DSSEHint.php
  Grafeas/src/V1/DSSEAttestationOccurrence.php
  Grafeas/src/V1/Envelope.php
  Grafeas/src/V1/EnvelopeSignature.php
  Grafeas/src/V1/InTotoProvenance.php
  Grafeas/src/V1/InTotoStatement.php
  Grafeas/src/V1/Jwt.php
  Grafeas/src/V1/Metadata.php
  Grafeas/src/V1/NonCompliantFile.php
  Grafeas/src/V1/Note.php
  Grafeas/src/V1/NoteKind.php
  Grafeas/src/V1/Occurrence.php
  Grafeas/src/V1/Recipe.php
  Grafeas/src/V1/Signature.php
  Grafeas/src/V1/SlsaProvenance.php
  Grafeas/src/V1/SlsaProvenance/Material.php
  Grafeas/src/V1/SlsaProvenance/SlsaBuilder.php
  Grafeas/src/V1/SlsaProvenance/SlsaCompleteness.php
  Grafeas/src/V1/SlsaProvenance/SlsaMetadata.php
  Grafeas/src/V1/SlsaProvenance/SlsaRecipe.php
  Grafeas/src/V1/Subject.php
  Grafeas/src/V1/Version.php
  Grafeas/src/V1/VulnerabilityNote/Detail.php
  Grafeas/src/V1/VulnerabilityOccurrence.php
  Grafeas/src/V1/VulnerabilityOccurrence/CVSSV3.php
  Grafeas/src/V1/VulnerabilityOccurrence/PackageIssue.php
  Grafeas/synth.metadata
Labels: cla: yes, context: full

#4540 [VideoTranscoder] docs: clarify that project number is used as the canonical project identifier for job and job template names docs: fix broken link and code formatting feat: add support for allow_missing param on DELETE request fix!: remove Encrypti
  VideoTranscoder/metadata/V1/Resources.php
  VideoTranscoder/metadata/V1/Services.php
  VideoTranscoder/src/V1/AdBreak.php
  VideoTranscoder/src/V1/AudioStream.php
  VideoTranscoder/src/V1/CreateJobRequest.php
  VideoTranscoder/src/V1/CreateJobTemplateRequest.php
  VideoTranscoder/src/V1/DeleteJobRequest.php
  VideoTranscoder/src/V1/DeleteJobTemplateRequest.php
  VideoTranscoder/src/V1/EditAtom.php
  VideoTranscoder/src/V1/Gapic/TranscoderServiceGapicClient.php
  VideoTranscoder/src/V1/Input.php
  VideoTranscoder/src/V1/Job.php
  VideoTranscoder/src/V1/JobConfig.php
  VideoTranscoder/src/V1/JobTemplate.php
  VideoTranscoder/src/V1/Manifest.php
  VideoTranscoder/src/V1/Manifest/ManifestType.php
  VideoTranscoder/src/V1/MuxStream.php
  VideoTranscoder/src/V1/Overlay.php
  VideoTranscoder/src/V1/Overlay/AnimationEnd.php
  VideoTranscoder/src/V1/Overlay/AnimationFade.php
  VideoTranscoder/src/V1/Overlay/AnimationStatic.php
  VideoTranscoder/src/V1/Overlay/Image.php
  VideoTranscoder/src/V1/PreprocessingConfig.php
  VideoTranscoder/src/V1/PreprocessingConfig/Denoise.php
  VideoTranscoder/src/V1/SegmentSettings.php
  VideoTranscoder/src/V1/SpriteSheet.php
  VideoTranscoder/src/V1/TextStream.php
  VideoTranscoder/src/V1/VideoStream/H264CodecSettings.php
  VideoTranscoder/src/V1/VideoStream/H265CodecSettings.php
  VideoTranscoder/src/V1/VideoStream/Vp9CodecSettings.php
  VideoTranscoder/src/V1beta1/AdBreak.php
  VideoTranscoder/src/V1beta1/CreateJobRequest.php
  VideoTranscoder/src/V1beta1/CreateJobTemplateRequest.php
  VideoTranscoder/src/V1beta1/EditAtom.php
  VideoTranscoder/src/V1beta1/Input.php
  VideoTranscoder/src/V1beta1/Job.php
  VideoTranscoder/src/V1beta1/JobConfig.php
  VideoTranscoder/src/V1beta1/JobTemplate.php
  VideoTranscoder/src/V1beta1/MuxStream.php
  VideoTranscoder/src/V1beta1/Overlay.php
  VideoTranscoder/src/V1beta1/Overlay/AnimationEnd.php
  VideoTranscoder/src/V1beta1/Overlay/AnimationFade.php
  VideoTranscoder/src/V1beta1/Overlay/AnimationStatic.php
  VideoTranscoder/src/V1beta1/Overlay/Image.php
  VideoTranscoder/src/V1beta1/PreprocessingConfig.php
  VideoTranscoder/src/V1beta1/SegmentSettings.php
  VideoTranscoder/src/V1beta1/SpriteSheet.php
  VideoTranscoder/synth.metadata
Labels: cla: yes, context: full

#4810 [Profiler] chore(bazel): Update gapic-generator-php to v1.2.1
  Profiler/src/V2/Gapic/ProfilerServiceGapicClient.php
  Profiler/src/V2/ProfilerServiceClient.php
  Profiler/synth.metadata
Labels: context: full

#4809 [PrivateCatalog] chore(bazel): Update gapic-generator-php to v1.2.1
  PrivateCatalog/src/V1beta1/Gapic/PrivateCatalogGapicClient.php
  PrivateCatalog/src/V1beta1/PrivateCatalogClient.php
  PrivateCatalog/synth.metadata
Labels: context: full

#4811 [PubSub] chore(bazel): Update gapic-generator-php to v1.2.1
  PubSub/src/V1/Gapic/PublisherGapicClient.php
  PubSub/src/V1/Gapic/SchemaServiceGapicClient.php
  PubSub/src/V1/Gapic/SubscriberGapicClient.php
  PubSub/src/V1/PublisherClient.php
  PubSub/src/V1/SchemaServiceClient.php
  PubSub/src/V1/SubscriberClient.php
  PubSub/synth.metadata
Labels: context: full

#4742 chore: auto-assign issues to new Spanner owner
  .github/blunderbuss.yml
Labels: api: spanner

#4826 [Spanner] chore(bazel): Update gapic-generator-php to v1.2.1
  Spanner/src/Admin/Database/V1/Gapic/DatabaseAdminGapicClient.php
  Spanner/src/Admin/Instance/V1/Gapic/InstanceAdminGapicClient.php
  Spanner/src/V1/Gapic/SpannerGapicClient.php
  Spanner/synth.metadata
Labels: context: full

#4827 [Talent] chore(bazel): Update gapic-generator-php to v1.2.1
  Talent/src/V4/CompanyServiceClient.php
  Talent/src/V4/CompletionClient.php
  Talent/src/V4/EventServiceClient.php
  Talent/src/V4/Gapic/CompanyServiceGapicClient.php
  Talent/src/V4/Gapic/CompletionGapicClient.php
  Talent/src/V4/Gapic/EventServiceGapicClient.php
  Talent/src/V4/Gapic/JobServiceGapicClient.php
  Talent/src/V4/Gapic/TenantServiceGapicClient.php
  Talent/src/V4/JobServiceClient.php
  Talent/src/V4/TenantServiceClient.php
  Talent/src/V4beta1/ApplicationServiceClient.php
  Talent/src/V4beta1/CompanyServiceClient.php
  Talent/src/V4beta1/CompletionClient.php
  Talent/src/V4beta1/EventServiceClient.php
  Talent/src/V4beta1/Gapic/ApplicationServiceGapicClient.php
  Talent/src/V4beta1/Gapic/CompanyServiceGapicClient.php
  Talent/src/V4beta1/Gapic/CompletionGapicClient.php
  Talent/src/V4beta1/Gapic/EventServiceGapicClient.php
  Talent/src/V4beta1/Gapic/JobServiceGapicClient.php
  Talent/src/V4beta1/Gapic/ProfileServiceGapicClient.php
  Talent/src/V4beta1/Gapic/TenantServiceGapicClient.php
  Talent/src/V4beta1/JobServiceClient.php
  Talent/src/V4beta1/ProfileServiceClient.php
  Talent/src/V4beta1/TenantServiceClient.php
  Talent/synth.metadata
Labels: context: full

#4828 [TextToSpeech] chore(bazel): Update gapic-generator-php to v1.2.1
  TextToSpeech/src/V1/Gapic/TextToSpeechGapicClient.php
  TextToSpeech/src/V1/TextToSpeechClient.php
  TextToSpeech/synth.metadata
Labels: context: full

#4824 [ResourceManager] chore(bazel): Update gapic-generator-php to v1.2.1
  ResourceManager/src/V3/FoldersClient.php
  ResourceManager/src/V3/Gapic/FoldersGapicClient.php
  ResourceManager/src/V3/Gapic/OrganizationsGapicClient.php
  ResourceManager/src/V3/Gapic/ProjectsGapicClient.php
  ResourceManager/src/V3/Gapic/TagBindingsGapicClient.php
  ResourceManager/src/V3/Gapic/TagKeysGapicClient.php
  ResourceManager/src/V3/Gapic/TagValuesGapicClient.php
  ResourceManager/src/V3/OrganizationsClient.php
  ResourceManager/src/V3/ProjectsClient.php
  ResourceManager/src/V3/TagBindingsClient.php
  ResourceManager/src/V3/TagKeysClient.php
  ResourceManager/src/V3/TagValuesClient.php
  ResourceManager/synth.metadata
Labels: context: full

#4823 [NetworkConnectivity] chore(bazel): Update gapic-generator-php to v1.2.1
  NetworkConnectivity/src/V1/Gapic/HubServiceGapicClient.php
  NetworkConnectivity/src/V1/HubServiceClient.php
  NetworkConnectivity/synth.metadata
Labels: context: full

#4861 chore(Firestore): migrate Firestore to owlbot
  Firestore/.OwlBot.yaml
  Firestore/owlbot.py
  Firestore/synth.metadata
Labels: api: firestore

#4860 chore(Bigtable): migrate Bigtable to owlbot
  Bigtable/.OwlBot.yaml
  Bigtable/owlbot.py
  Bigtable/synth.metadata
Labels: api: bigtable

#4862 chore(Domains): migrate Domains to owlbot
  Domains/.OwlBot.yaml
  Domains/owlbot.py
  Domains/synth.metadata
Labels: api: domains

#4867 chore: Migrate Gaming to OwlBot
  Gaming/.OwlBot.yaml
  Gaming/owlbot.py
  Gaming/synth.metadata
Labels: automerge
