Repository googleapis/google-cloud-php, pull requests merged in 2023-06, with the labels that each got.

#6246 feat(docs): upgrade phpdoc to latest version, add magic methods
  .github/workflows/docs.yaml
  .kokoro/docs/docker/Dockerfile
  dev/src/DocFx/Node/ClassNode.php
  dev/tests/Unit/Command/DocFxCommandTest.php
  dev/tests/fixtures/docfx/NewClient/V1.Client.SecretManagerServiceClient.yml
  dev/tests/fixtures/docfx/NewClient/toc.yml
  dev/tests/fixtures/phpdoc/newclient.xml
Labels: next release

#6281 feat: Add support for Firebase client
  Debugger/composer.json
  Debugger/src/Connection/Firebase.php
  Debugger/src/DebuggerClient.php
  composer.json
Labels: next release

#6324 fix(Pub/Sub): Ensure uniqueness of batch publishers under a topic
  PubSub/src/BatchPublisher.php
Labels: type: feature request, api: pubsub, priority: p1

#6322 fix: dupe magic methods for async methods
  dev/src/DocFx/Node/ClassNode.php
  dev/tests/Unit/Command/DocFxCommandTest.php
  dev/tests/fixtures/docfx/NewClient/V1.Client.SecretManagerServiceClient.yml
Labels: release blocking, priority: p1, next release

#6300 feat(Spanner): Federation M2
  Spanner/src/Batch/BatchSnapshot.php
  Spanner/tests/System/BatchTest.php
  Spanner/tests/Unit/Batch/BatchSnapshotTest.php
Labels: api: spanner

#6330 chore(dev): sort beta clients to bottom, remove new and previous labels
  dev/src/DocFx/Page/PageTree.php
  dev/src/DocFx/Toc/NamespaceToc.php
  dev/tests/fixtures/docfx/NewClient/toc.yml
Labels: next release

#6311 feat: introduce RapidMigrationAssessment
  RapidMigrationAssessment/.OwlBot.yaml
  RapidMigrationAssessment/.gitattributes
  RapidMigrationAssessment/.github/pull_request_template.md
  RapidMigrationAssessment/.repo-metadata.json
  RapidMigrationAssessment/CONTRIBUTING.md
  RapidMigrationAssessment/LICENSE
  RapidMigrationAssessment/README.md
  RapidMigrationAssessment/VERSION
  RapidMigrationAssessment/composer.json
  RapidMigrationAssessment/metadata/V1/ApiEntities.php
  RapidMigrationAssessment/metadata/V1/Rapidmigrationassessment.php
  RapidMigrationAssessment/owlbot.py
  RapidMigrationAssessment/phpunit.xml.dist
  RapidMigrationAssessment/samples/V1/RapidMigrationAssessmentClient/create_annotation.php
  RapidMigrationAssessment/samples/V1/RapidMigrationAssessmentClient/create_collector.php
  RapidMigrationAssessment/samples/V1/RapidMigrationAssessmentClient/delete_collector.php
  RapidMigrationAssessment/samples/V1/RapidMigrationAssessmentClient/get_annotation.php
  RapidMigrationAssessment/samples/V1/RapidMigrationAssessmentClient/get_collector.php
  RapidMigrationAssessment/samples/V1/RapidMigrationAssessmentClient/get_location.php
  RapidMigrationAssessment/samples/V1/RapidMigrationAssessmentClient/list_collectors.php
  RapidMigrationAssessment/samples/V1/RapidMigrationAssessmentClient/list_locations.php
  RapidMigrationAssessment/samples/V1/RapidMigrationAssessmentClient/pause_collector.php
  RapidMigrationAssessment/samples/V1/RapidMigrationAssessmentClient/register_collector.php
  RapidMigrationAssessment/samples/V1/RapidMigrationAssessmentClient/resume_collector.php
  RapidMigrationAssessment/samples/V1/RapidMigrationAssessmentClient/update_collector.php
  RapidMigrationAssessment/src/V1/Annotation.php
  RapidMigrationAssessment/src/V1/Annotation/Type.php
  RapidMigrationAssessment/src/V1/Client/BaseClient/RapidMigrationAssessmentBaseClient.php
  RapidMigrationAssessment/src/V1/Client/RapidMigrationAssessmentClient.php
  RapidMigrationAssessment/src/V1/Collector.php
  RapidMigrationAssessment/src/V1/Collector/State.php
  RapidMigrationAssessment/src/V1/CreateAnnotationRequest.php
  RapidMigrationAssessment/src/V1/CreateCollectorRequest.php
  RapidMigrationAssessment/src/V1/DeleteCollectorRequest.php
  RapidMigrationAssessment/src/V1/GetAnnotationRequest.php
  RapidMigrationAssessment/src/V1/GetCollectorRequest.php
  RapidMigrationAssessment/src/V1/GuestOsScan.php
  RapidMigrationAssessment/src/V1/ListCollectorsRequest.php
  RapidMigrationAssessment/src/V1/ListCollectorsResponse.php
  RapidMigrationAssessment/src/V1/OperationMetadata.php
  RapidMigrationAssessment/src/V1/PauseCollectorRequest.php
  RapidMigrationAssessment/src/V1/RegisterCollectorRequest.php
  RapidMigrationAssessment/src/V1/ResumeCollectorRequest.php
  RapidMigrationAssessment/src/V1/UpdateCollectorRequest.php
  RapidMigrationAssessment/src/V1/VSphereScan.php
  RapidMigrationAssessment/src/V1/gapic_metadata.json
  RapidMigrationAssessment/src/V1/resources/rapid_migration_assessment_client_config.json
  RapidMigrationAssessment/src/V1/resources/rapid_migration_assessment_descriptor_config.php
  RapidMigrationAssessment/src/V1/resources/rapid_migration_assessment_rest_client_config.php
  RapidMigrationAssessment/tests/Unit/V1/Client/RapidMigrationAssessmentClientTest.php
  composer.json
Labels: priority: p1, next release

#6328 feat(docs): support examples phpdoc tag for methods
  dev/src/DocFx/Node/MethodNode.php
  dev/src/DocFx/Page/Page.php
  dev/tests/Unit/DocFx/PageTest.php
  dev/tests/fixtures/component/ClientSnippets/samples/V1/ClientSnippetsClient/an_rpc_method.php
  dev/tests/fixtures/component/ClientSnippets/src/V1/Client/BaseClient/ClientSnippetsBaseClient.php
  dev/tests/fixtures/component/ClientSnippets/src/V1/Client/ClientSnippetsClient.php
  dev/tests/fixtures/docfx/Vision/V1.ProductSearchClient.yml
  dev/tests/fixtures/phpdoc/clientsnippets.xml
Labels: next release

#6329 fix(docs): mark classes with experimental tag as beta
  dev/src/DocFx/Node/ClassNode.php
  dev/tests/fixtures/docfx/NewClient/V1.Client.SecretManagerServiceClient.yml
  dev/tests/fixtures/docfx/NewClient/toc.yml
Labels: next release

#6333 fix(docs): newline between link markdown, see tags in parameter descriptions
  dev/src/DocFx/Node/MethodNode.php
  dev/src/DocFx/Node/XrefTrait.php
  dev/tests/Unit/DocFx/NodeTest.php
  dev/tests/fixtures/docfx/Vision/V1.ImageAnnotatorClient.yml
Labels: next release

#6249 chore: suppport guzzle/promises:v2
  Core/composer.json
  Core/tests/Unit/RequestWrapperTest.php
  Core/tests/Unit/Upload/MultipartUploaderTest.php
  Storage/composer.json
  Storage/src/StorageObject.php
  Storage/tests/Snippet/BucketTest.php
  Storage/tests/Snippet/StorageObjectTest.php
  Storage/tests/Unit/BucketTest.php
  Storage/tests/Unit/Connection/RestTest.php
  Storage/tests/Unit/StorageObjectTest.php
Labels: next release

#6341 chore(docs): use version number instead of namespace
  dev/src/DocFx/Toc/NamespaceToc.php
  dev/tests/fixtures/docfx/NewClient/toc.yml
  dev/tests/fixtures/docfx/Vision/toc.yml
Labels: next release

#6008 feat(Spanner): enable drop db protection
  Spanner/src/Connection/ConnectionInterface.php
  Spanner/src/Connection/Grpc.php
  Spanner/src/Database.php
  Spanner/tests/System/AdminTest.php
  Spanner/tests/Unit/DatabaseTest.php
Labels: release blocking, api: spanner, breaking change allowed

#6244 chore(Spanner): Add tests for FGAC Postgres dialect
  Spanner/tests/System/BatchTest.php
  Spanner/tests/System/DatabaseRoleTrait.php
  Spanner/tests/System/OperationsTest.php
  Spanner/tests/System/PgBatchTest.php
  Spanner/tests/System/PgOperationsTest.php
  Spanner/tests/System/PgTransactionTest.php
  Spanner/tests/System/SpannerPgTestCase.php
  Spanner/tests/System/SpannerTestCase.php
  Spanner/tests/System/TransactionTest.php
Labels: api: spanner

#6363 feat(dev): add release-info command
  Dlp/composer.json
  dev/README.md
  dev/google-cloud
  dev/src/Command/ReleaseInfoCommand.php
  dev/tests/Unit/Command/ComponentInfoCommandTest.php
  dev/tests/Unit/Command/DocFxCommandTest.php
  dev/tests/Unit/Command/ReleaseInfoCommandTest.php
Labels: release blocking, next release

#6388 feat(PubSub): Enable publisher compression
  PubSub/src/BatchPublisher.php
  PubSub/src/Connection/Grpc.php
  PubSub/src/PubSubClient.php
  PubSub/src/Topic.php
  PubSub/tests/Unit/BatchPublisherTest.php
  PubSub/tests/Unit/Connection/GrpcTest.php
  PubSub/tests/Unit/TopicTest.php
Labels: api: pubsub
