Repository googleapis/google-cloud-php, pull requests merged in 2023-10, with the labels that each got.

#6470 chore(dev): change expanded format
  dev/src/Command/ComponentInfoCommand.php
  dev/src/ComponentPackage.php
Labels: next release

#6696 chore: mark google/cloud-game-servers abandoned
  composer.json
Labels: next release

#6699 fix(dev): update dev tooling for changes in new surface
  dev/src/ComponentPackage.php
  dev/src/DocFx/Node/ClassNode.php
  dev/src/DocFx/Page/PageTree.php
  dev/tests/Unit/Command/DocFxCommandTest.php
  dev/tests/Unit/DocFx/PageTest.php
  dev/tests/fixtures/component/ClientSnippets/src/V1/Client/BaseClient/ClientSnippetsBaseClient.php
  dev/tests/fixtures/component/ClientSnippets/src/V1/Client/ClientSnippetsClient.php
  dev/tests/fixtures/docfx/NewClient/V1.Client.SecretManagerServiceClient.yml
  dev/tests/fixtures/docfx/Vision/V1.AddProductToProductSetRequest.yml
  dev/tests/fixtures/docfx/Vision/V1.AsyncBatchAnnotateFilesRequest.yml
  dev/tests/fixtures/docfx/Vision/V1.AsyncBatchAnnotateImagesRequest.yml
  dev/tests/fixtures/docfx/Vision/V1.BatchAnnotateFilesRequest.yml
  dev/tests/fixtures/docfx/Vision/V1.BatchAnnotateImagesRequest.yml
  dev/tests/fixtures/docfx/Vision/V1.Client.ImageAnnotatorClient.yml
  dev/tests/fixtures/docfx/Vision/V1.Client.ProductSearchClient.yml
  dev/tests/fixtures/docfx/Vision/V1.CreateProductRequest.yml
  dev/tests/fixtures/docfx/Vision/V1.CreateProductSetRequest.yml
  dev/tests/fixtures/docfx/Vision/V1.CreateReferenceImageRequest.yml
  dev/tests/fixtures/docfx/Vision/V1.DeleteProductRequest.yml
  dev/tests/fixtures/docfx/Vision/V1.DeleteProductSetRequest.yml
  dev/tests/fixtures/docfx/Vision/V1.DeleteReferenceImageRequest.yml
  dev/tests/fixtures/docfx/Vision/V1.GetProductRequest.yml
  dev/tests/fixtures/docfx/Vision/V1.GetProductSetRequest.yml
  dev/tests/fixtures/docfx/Vision/V1.GetReferenceImageRequest.yml
  dev/tests/fixtures/docfx/Vision/V1.ImageAnnotatorClient.yml
  dev/tests/fixtures/docfx/Vision/V1.ImportProductSetsRequest.yml
  dev/tests/fixtures/docfx/Vision/V1.ListProductSetsRequest.yml
  dev/tests/fixtures/docfx/Vision/V1.ListProductsInProductSetRequest.yml
  dev/tests/fixtures/docfx/Vision/V1.ListProductsRequest.yml
  dev/tests/fixtures/docfx/Vision/V1.ListReferenceImagesRequest.yml
  dev/tests/fixtures/docfx/Vision/V1.ProductSearchClient.yml
  dev/tests/fixtures/docfx/Vision/V1.PurgeProductsRequest.yml
  dev/tests/fixtures/docfx/Vision/V1.RemoveProductFromProductSetRequest.yml
  dev/tests/fixtures/docfx/Vision/V1.UpdateProductRequest.yml
  dev/tests/fixtures/docfx/Vision/V1.UpdateProductSetRequest.yml
  dev/tests/fixtures/docfx/Vision/toc.yml
  dev/tests/fixtures/phpdoc/clientsnippets.xml
  dev/tests/fixtures/phpdoc/newclient.xml
  dev/tests/fixtures/phpdoc/structure.xml
Labels: next release

#6717 chore(Firestore): Refactor Aggregation System Tests
  Firestore/tests/System/AggregateQueryTest.php
  Firestore/tests/System/FirestoreTestCase.php
  Firestore/tests/System/TransactionTest.php
Labels: api: firestore

#6731 feat(Storage): Enable Autoclass V2
  Storage/src/Bucket.php
  Storage/src/Connection/ServiceDefinition/storage-v1.json
  Storage/src/StorageClient.php
  Storage/tests/System/ManageBucketsTest.php
  Storage/tests/Unit/BucketTest.php
Labels: api: storage
