Repository googleapis/google-cloud-php, pull requests merged in 2023-02, with the labels that each got.

#5810 chore(Spanner): Throw session create exception correctly
  Spanner/src/Session/CacheSessionPool.php
  Spanner/tests/System/SessionTest.php
  Spanner/tests/Unit/Session/CacheSessionPoolTest.php
Labels: api: spanner

#5866 chore(datastore): update service discovery
  Datastore/src/Connection/ServiceDefinition/datastore-v1.json
Labels: api: datastore

#5870 chore(release): fix release script
  .github/workflows/release.yml
  dev/src/Split/Command.php
  dev/src/Split/ReleaseNotes.php
  dev/tests/fixtures/split/release-notes.md
  docs/manifest.json
Labels: release blocking

#5887 feat: introduce AdvisoryNotifications
  AdvisoryNotifications/.OwlBot.yaml
  AdvisoryNotifications/.gitattributes
  AdvisoryNotifications/.github/pull_request_template.md
  AdvisoryNotifications/.repo-metadata.json
  AdvisoryNotifications/CONTRIBUTING.md
  AdvisoryNotifications/LICENSE
  AdvisoryNotifications/README.md
  AdvisoryNotifications/VERSION
  AdvisoryNotifications/composer.json
  AdvisoryNotifications/metadata/V1/Service.php
  AdvisoryNotifications/owlbot.py
  AdvisoryNotifications/phpunit.xml.dist
  AdvisoryNotifications/samples/V1/AdvisoryNotificationsServiceClient/get_notification.php
  AdvisoryNotifications/samples/V1/AdvisoryNotificationsServiceClient/list_notifications.php
  AdvisoryNotifications/src/V1/AdvisoryNotificationsServiceClient.php
  AdvisoryNotifications/src/V1/Attachment.php
  AdvisoryNotifications/src/V1/Csv.php
  AdvisoryNotifications/src/V1/Csv/CsvRow.php
  AdvisoryNotifications/src/V1/Gapic/AdvisoryNotificationsServiceGapicClient.php
  AdvisoryNotifications/src/V1/GetNotificationRequest.php
  AdvisoryNotifications/src/V1/ListNotificationsRequest.php
  AdvisoryNotifications/src/V1/ListNotificationsResponse.php
  AdvisoryNotifications/src/V1/LocalizationState.php
  AdvisoryNotifications/src/V1/Message.php
  AdvisoryNotifications/src/V1/Message/Body.php
  AdvisoryNotifications/src/V1/Notification.php
  AdvisoryNotifications/src/V1/NotificationView.php
  AdvisoryNotifications/src/V1/Subject.php
  AdvisoryNotifications/src/V1/Text.php
  AdvisoryNotifications/src/V1/gapic_metadata.json
  AdvisoryNotifications/src/V1/resources/advisory_notifications_service_client_config.json
  AdvisoryNotifications/src/V1/resources/advisory_notifications_service_descriptor_config.php
  AdvisoryNotifications/src/V1/resources/advisory_notifications_service_rest_client_config.php
  AdvisoryNotifications/tests/Unit/V1/AdvisoryNotificationsServiceClientTest.php
  composer.json
Labels: next release

#5853 feat:[Spanner] CacheSessionPool::maintain deletes sessions older than 28d
  Spanner/src/Session/CacheSessionPool.php
  Spanner/tests/System/SessionTest.php
  Spanner/tests/Unit/Session/CacheSessionPoolTest.php
Labels: next release

#5897 chore: use correct actor name for release-please
  .github/conventional-commit-lint.yaml
  .github/workflows/backwards-compatibility-check.yaml
Labels: next release

#5895 chore: [AdvisoryNotifications] remove bc fixes from owlbot
  AdvisoryNotifications/owlbot.py
  AdvisoryNotifications/src/V1/Attachment.php
  AdvisoryNotifications/src/V1/GetNotificationRequest.php
  AdvisoryNotifications/src/V1/ListNotificationsRequest.php
  AdvisoryNotifications/src/V1/ListNotificationsResponse.php
  AdvisoryNotifications/src/V1/Message.php
  AdvisoryNotifications/src/V1/Message/Body.php
  AdvisoryNotifications/src/V1/Notification.php
  AdvisoryNotifications/src/V1/Subject.php
  AdvisoryNotifications/src/V1/Text.php
Labels: next release

#5869 fix!: [Build] purge google/devtools/build in favor of google/devtools/cloudbuild
  Build/.OwlBot.yaml
  Build/metadata/V1/BuildEvents.php
  Build/metadata/V1/BuildStatus.php
  Build/metadata/V1/PublishBuildEvent.php
  Build/owlbot.py
  Build/src/V1/Artifacts_ArtifactObjects.php
  Build/src/V1/BuildEvent.php
  Build/src/V1/BuildEvent/BuildComponentStreamFinished.php
  Build/src/V1/BuildEvent/BuildComponentStreamFinished/FinishType.php
  Build/src/V1/BuildEvent/BuildEnqueued.php
  Build/src/V1/BuildEvent/BuildFinished.php
  Build/src/V1/BuildEvent/ConsoleOutput.php
  Build/src/V1/BuildEvent/InvocationAttemptFinished.php
  Build/src/V1/BuildEvent/InvocationAttemptStarted.php
  Build/src/V1/BuildEvent_BuildComponentStreamFinished.php
  Build/src/V1/BuildEvent_BuildComponentStreamFinished_FinishType.php
  Build/src/V1/BuildEvent_BuildEnqueued.php
  Build/src/V1/BuildEvent_BuildFinished.php
  Build/src/V1/BuildEvent_ConsoleOutput.php
  Build/src/V1/BuildEvent_InvocationAttemptFinished.php
  Build/src/V1/BuildEvent_InvocationAttemptStarted.php
  Build/src/V1/BuildOptions_LogStreamingOption.php
  Build/src/V1/BuildOptions_LoggingMode.php
  Build/src/V1/BuildOptions_MachineType.php
  Build/src/V1/BuildOptions_SubstitutionOption.php
  Build/src/V1/BuildOptions_VerifyOption.php
  Build/src/V1/BuildStatus.php
  Build/src/V1/BuildStatus/Result.php
  Build/src/V1/BuildStatus_Result.php
  Build/src/V1/Build_Status.php
  Build/src/V1/CloudBuildGrpcClient.php
  Build/src/V1/ConsoleOutputStream.php
  Build/src/V1/Gapic/PublishBuildEventGapicClient.php
  Build/src/V1/Hash_HashType.php
  Build/src/V1/Network.php
  Build/src/V1/OrderedBuildEvent.php
  Build/src/V1/PublishBuildEventClient.php
  Build/src/V1/PublishBuildEventGrpcClient.php
  Build/src/V1/PublishBuildToolEventStreamRequest.php
  Build/src/V1/PublishBuildToolEventStreamResponse.php
  Build/src/V1/PublishLifecycleEventRequest.php
  Build/src/V1/PublishLifecycleEventRequest/ServiceLevel.php
  Build/src/V1/PublishLifecycleEventRequest_ServiceLevel.php
  Build/src/V1/PubsubConfig_State.php
  Build/src/V1/PullRequestFilter_CommentControl.php
  Build/src/V1/StreamId.php
  Build/src/V1/StreamId/BuildComponent.php
  Build/src/V1/StreamId_BuildComponent.php
  Build/src/V1/WorkerConfig.php
  Build/src/V1/WorkerPool/Region.php
  Build/src/V1/WorkerPool/Status.php
  Build/src/V1/WorkerPool_Region.php
  Build/src/V1/WorkerPool_Status.php
  Build/src/V1/resources/publish_build_event_client_config.json
  Build/src/V1/resources/publish_build_event_descriptor_config.php
  Build/src/V1/resources/publish_build_event_rest_client_config.php
  Build/tests/Unit/V1/PublishBuildEventClientTest.php
Labels: breaking change allowed, next release
