Repository googleapis/google-cloud-php, pull requests merged in 2024-06, with the labels that each got.

#6756 bug(BigQuery): Throw exception when reload function returns 499 status code
  BigQuery/src/JobWaitTrait.php
  BigQuery/tests/Unit/JobWaitTraitTest.php
Labels: api: bigquery

#7362 fix: pubsub version constant
  PubSub/src/PubSubClient.php
Labels: next release

#7373 feat(dev): add filter and sort to component-info command
  dev/src/Command/ComponentInfoCommand.php
  dev/src/ComponentPackage.php
  dev/tests/Unit/Command/ComponentInfoCommandTest.php
Labels: next release

#7372 chore: mark AccessContextManager stable
  .repo-metadata-full.json
Labels: next release

#7366 fix!: remove deprecated surfaces
  ShoppingMerchantInventories/src/V1beta/Gapic/LocalInventoryServiceGapicClient.php
  ShoppingMerchantInventories/src/V1beta/Gapic/RegionalInventoryServiceGapicClient.php
  ShoppingMerchantInventories/src/V1beta/LocalInventoryServiceClient.php
  ShoppingMerchantInventories/src/V1beta/RegionalInventoryServiceClient.php
  ShoppingMerchantInventories/tests/Unit/V1beta/LocalInventoryServiceClientTest.php
  ShoppingMerchantInventories/tests/Unit/V1beta/RegionalInventoryServiceClientTest.php
Labels: next release

#7364 feat: introduce BackupDr
  .repo-metadata-full.json
  BackupDr/.OwlBot.yaml
  BackupDr/.gitattributes
  BackupDr/.github/pull_request_template.md
  BackupDr/CONTRIBUTING.md
  BackupDr/LICENSE
  BackupDr/README.md
  BackupDr/VERSION
  BackupDr/composer.json
  BackupDr/metadata/V1/Backupdr.php
  BackupDr/owlbot.py
  BackupDr/phpunit.xml.dist
  BackupDr/samples/V1/BackupDRClient/create_management_server.php
  BackupDr/samples/V1/BackupDRClient/delete_management_server.php
  BackupDr/samples/V1/BackupDRClient/get_iam_policy.php
  BackupDr/samples/V1/BackupDRClient/get_location.php
  BackupDr/samples/V1/BackupDRClient/get_management_server.php
  BackupDr/samples/V1/BackupDRClient/list_locations.php
  BackupDr/samples/V1/BackupDRClient/list_management_servers.php
  BackupDr/samples/V1/BackupDRClient/set_iam_policy.php
  BackupDr/samples/V1/BackupDRClient/test_iam_permissions.php
  BackupDr/src/V1/Client/BackupDRClient.php
  BackupDr/src/V1/CreateManagementServerRequest.php
  BackupDr/src/V1/DeleteManagementServerRequest.php
  BackupDr/src/V1/GetManagementServerRequest.php
  BackupDr/src/V1/ListManagementServersRequest.php
  BackupDr/src/V1/ListManagementServersResponse.php
  BackupDr/src/V1/ManagementServer.php
  BackupDr/src/V1/ManagementServer/InstanceState.php
  BackupDr/src/V1/ManagementServer/InstanceType.php
  BackupDr/src/V1/ManagementURI.php
  BackupDr/src/V1/NetworkConfig.php
  BackupDr/src/V1/NetworkConfig/PeeringMode.php
  BackupDr/src/V1/OperationMetadata.php
  BackupDr/src/V1/WorkforceIdentityBasedManagementURI.php
  BackupDr/src/V1/WorkforceIdentityBasedOAuth2ClientID.php
  BackupDr/src/V1/gapic_metadata.json
  BackupDr/src/V1/resources/backup_dr_client_config.json
  BackupDr/src/V1/resources/backup_dr_descriptor_config.php
  BackupDr/src/V1/resources/backup_dr_rest_client_config.php
  BackupDr/tests/Unit/V1/Client/BackupDRClientTest.php
  composer.json
Labels: next release

#6658 feat(docs): add validation of xrefs to docfx command
  .github/workflows/docs.yaml
  .kokoro/docs/docker/Dockerfile
  dev/src/Command/DocFxCommand.php
  dev/src/DocFx/Node/ClassNode.php
  dev/src/DocFx/XrefValidationTrait.php
  dev/tests/Unit/DocFx/NodeTest.php
Labels: next release

#7375 chore(dev): ensure newline in repo-metadata-full.json
  dev/src/Command/AddComponentCommand.php
Labels: next release

#7406 chore(dev): remove unneeded copy_excludes
  dev/templates/owlbot.py.twig
  dev/tests/fixtures/component/CustomInput/owlbot.py
  dev/tests/fixtures/component/SecretManager/owlbot.py
Labels: next release

#7402 chore!: promote OrgPolicy to v1
  .repo-metadata-full.json
  OrgPolicy/README.md
  OrgPolicy/owlbot.py
  OrgPolicy/src/V2/AlternatePolicySpec.php
  OrgPolicy/src/V2/Client/OrgPolicyClient.php
  OrgPolicy/src/V2/Constraint.php
  OrgPolicy/src/V2/Constraint/BooleanConstraint.php
  OrgPolicy/src/V2/Constraint/ConstraintDefault.php
  OrgPolicy/src/V2/Constraint/ListConstraint.php
  OrgPolicy/src/V2/Constraint_BooleanConstraint.php
  OrgPolicy/src/V2/Constraint_ConstraintDefault.php
  OrgPolicy/src/V2/Constraint_ListConstraint.php
  OrgPolicy/src/V2/CreateCustomConstraintRequest.php
  OrgPolicy/src/V2/CreatePolicyRequest.php
  OrgPolicy/src/V2/CustomConstraint.php
  OrgPolicy/src/V2/CustomConstraint/ActionType.php
  OrgPolicy/src/V2/CustomConstraint/MethodType.php
  OrgPolicy/src/V2/DeleteCustomConstraintRequest.php
  OrgPolicy/src/V2/DeletePolicyRequest.php
  OrgPolicy/src/V2/Gapic/OrgPolicyGapicClient.php
  OrgPolicy/src/V2/GetCustomConstraintRequest.php
  OrgPolicy/src/V2/GetEffectivePolicyRequest.php
  OrgPolicy/src/V2/GetPolicyRequest.php
  OrgPolicy/src/V2/ListConstraintsRequest.php
  OrgPolicy/src/V2/ListConstraintsResponse.php
  OrgPolicy/src/V2/ListCustomConstraintsRequest.php
  OrgPolicy/src/V2/ListCustomConstraintsResponse.php
  OrgPolicy/src/V2/ListPoliciesRequest.php
  OrgPolicy/src/V2/ListPoliciesResponse.php
  OrgPolicy/src/V2/OrgPolicyClient.php
  OrgPolicy/src/V2/OrgPolicyGrpcClient.php
  OrgPolicy/src/V2/Policy.php
  OrgPolicy/src/V2/PolicySpec.php
  OrgPolicy/src/V2/PolicySpec/PolicyRule.php
  OrgPolicy/src/V2/PolicySpec/PolicyRule/StringValues.php
  OrgPolicy/src/V2/PolicySpec_PolicyRule.php
  OrgPolicy/src/V2/PolicySpec_PolicyRule_StringValues.php
  OrgPolicy/src/V2/UpdateCustomConstraintRequest.php
  OrgPolicy/src/V2/UpdatePolicyRequest.php
  OrgPolicy/tests/Unit/V2/Client/OrgPolicyClientTest.php
  OrgPolicy/tests/Unit/V2/OrgPolicyClientTest.php
Labels: next release

#7399 chore!: promote Ids to v1
  .repo-metadata-full.json
  Ids/README.md
  Ids/owlbot.py
  Ids/src/V1/Client/IDSClient.php
  Ids/src/V1/CreateEndpointRequest.php
  Ids/src/V1/DeleteEndpointRequest.php
  Ids/src/V1/Endpoint.php
  Ids/src/V1/Gapic/IDSGapicClient.php
  Ids/src/V1/GetEndpointRequest.php
  Ids/src/V1/IDSClient.php
  Ids/src/V1/IDSGrpcClient.php
  Ids/src/V1/ListEndpointsRequest.php
  Ids/src/V1/ListEndpointsResponse.php
  Ids/src/V1/OperationMetadata.php
  Ids/tests/Unit/V1/Client/IDSClientTest.php
  Ids/tests/Unit/V1/IDSClientTest.php
Labels: next release

#7398 chore!: promote EssentialContacts to v1
  .repo-metadata-full.json
  EssentialContacts/README.md
  EssentialContacts/owlbot.py
  EssentialContacts/src/V1/Client/EssentialContactsServiceClient.php
  EssentialContacts/src/V1/ComputeContactsRequest.php
  EssentialContacts/src/V1/ComputeContactsResponse.php
  EssentialContacts/src/V1/Contact.php
  EssentialContacts/src/V1/CreateContactRequest.php
  EssentialContacts/src/V1/DeleteContactRequest.php
  EssentialContacts/src/V1/EssentialContactsServiceClient.php
  EssentialContacts/src/V1/EssentialContactsServiceGrpcClient.php
  EssentialContacts/src/V1/Gapic/EssentialContactsServiceGapicClient.php
  EssentialContacts/src/V1/GetContactRequest.php
  EssentialContacts/src/V1/ListContactsRequest.php
  EssentialContacts/src/V1/ListContactsResponse.php
  EssentialContacts/src/V1/SendTestMessageRequest.php
  EssentialContacts/src/V1/UpdateContactRequest.php
  EssentialContacts/tests/Unit/V1/Client/EssentialContactsServiceClientTest.php
  EssentialContacts/tests/Unit/V1/EssentialContactsServiceClientTest.php
Labels: next release

#7396 chore!: promote DataFusion to v1
  .repo-metadata-full.json
  DataFusion/README.md
  DataFusion/owlbot.py
  DataFusion/src/V1/Accelerator.php
  DataFusion/src/V1/Client/DataFusionClient.php
  DataFusion/src/V1/CreateInstanceRequest.php
  DataFusion/src/V1/CryptoKeyConfig.php
  DataFusion/src/V1/DataFusionClient.php
  DataFusion/src/V1/DataFusionGrpcClient.php
  DataFusion/src/V1/DeleteInstanceRequest.php
  DataFusion/src/V1/Gapic/DataFusionGapicClient.php
  DataFusion/src/V1/GetInstanceRequest.php
  DataFusion/src/V1/Instance.php
  DataFusion/src/V1/ListAvailableVersionsRequest.php
  DataFusion/src/V1/ListAvailableVersionsResponse.php
  DataFusion/src/V1/ListInstancesRequest.php
  DataFusion/src/V1/ListInstancesResponse.php
  DataFusion/src/V1/NetworkConfig.php
  DataFusion/src/V1/OperationMetadata.php
  DataFusion/src/V1/RestartInstanceRequest.php
  DataFusion/src/V1/UpdateInstanceRequest.php
  DataFusion/src/V1/Version.php
  DataFusion/tests/Unit/V1/Client/DataFusionClientTest.php
  DataFusion/tests/Unit/V1/DataFusionClientTest.php
Labels: next release

#7395 chore!: promote CloudOptimization to v1
  .repo-metadata-full.json
  Optimization/README.md
  Optimization/owlbot.py
  Optimization/src/V1/AggregatedMetrics.php
  Optimization/src/V1/AsyncModelMetadata.php
  Optimization/src/V1/BatchOptimizeToursRequest.php
  Optimization/src/V1/BatchOptimizeToursRequest/AsyncModelConfig.php
  Optimization/src/V1/BreakRule/BreakRequest.php
  Optimization/src/V1/BreakRule/FrequencyConstraint.php
  Optimization/src/V1/CapacityQuantity.php
  Optimization/src/V1/CapacityQuantityInterval.php
  Optimization/src/V1/Client/FleetRoutingClient.php
  Optimization/src/V1/DistanceLimit.php
  Optimization/src/V1/FleetRoutingClient.php
  Optimization/src/V1/FleetRoutingGrpcClient.php
  Optimization/src/V1/Gapic/FleetRoutingGapicClient.php
  Optimization/src/V1/GcsDestination.php
  Optimization/src/V1/GcsSource.php
  Optimization/src/V1/InjectedSolutionConstraint/ConstraintRelaxation/Relaxation.php
  Optimization/src/V1/InputConfig.php
  Optimization/src/V1/Location.php
  Optimization/src/V1/OptimizeToursRequest.php
  Optimization/src/V1/OptimizeToursResponse.php
  Optimization/src/V1/OptimizeToursResponse/Metrics.php
  Optimization/src/V1/OptimizeToursValidationError.php
  Optimization/src/V1/OptimizeToursValidationError/FieldReference.php
  Optimization/src/V1/OutputConfig.php
  Optimization/src/V1/RouteModifiers.php
  Optimization/src/V1/Shipment.php
  Optimization/src/V1/Shipment/Load.php
  Optimization/src/V1/Shipment/VisitRequest.php
  Optimization/src/V1/ShipmentModel.php
  Optimization/src/V1/ShipmentModel/BreakRule/BreakRequest.php
  Optimization/src/V1/ShipmentModel/BreakRule/FrequencyConstraint.php
  Optimization/src/V1/ShipmentModel/DurationDistanceMatrix.php
  Optimization/src/V1/ShipmentModel/PrecedenceRule.php
  Optimization/src/V1/ShipmentRoute.php
  Optimization/src/V1/ShipmentRoute/Delay.php
  Optimization/src/V1/ShipmentRoute/EncodedPolyline.php
  Optimization/src/V1/ShipmentRoute/PBBreak.php
  Optimization/src/V1/ShipmentRoute/Transition.php
  Optimization/src/V1/ShipmentRoute/TravelStep.php
  Optimization/src/V1/ShipmentRoute/VehicleLoad.php
  Optimization/src/V1/ShipmentRoute/Visit.php
  Optimization/src/V1/ShipmentTypeIncompatibility.php
  Optimization/src/V1/ShipmentTypeRequirement.php
  Optimization/src/V1/SkippedShipment.php
  Optimization/src/V1/SkippedShipment/Reason.php
  Optimization/src/V1/TimeWindow.php
  Optimization/src/V1/TransitionAttributes.php
  Optimization/src/V1/Vehicle.php
  Optimization/src/V1/Vehicle/DurationLimit.php
  Optimization/src/V1/Vehicle/LoadLimit.php
  Optimization/src/V1/Vehicle/LoadLimit/Interval.php
  Optimization/src/V1/Waypoint.php
  Optimization/tests/Unit/V1/Client/FleetRoutingClientTest.php
  Optimization/tests/Unit/V1/FleetRoutingClientTest.php
Labels: next release

#7386 chore(Language): deprecate handwritten clients and classes
  Language/src/Annotation.php
  Language/src/LanguageClient.php
Labels: next release

#7422 chore: promote StorageControl to v1
  .repo-metadata-full.json
  StorageControl/README.md
  StorageControl/owlbot.py
  StorageControl/src/V2/Client/StorageControlClient.php
  StorageControl/src/V2/CreateFolderRequest.php
  StorageControl/src/V2/DeleteFolderRequest.php
  StorageControl/src/V2/Folder.php
  StorageControl/src/V2/GetFolderRequest.php
  StorageControl/src/V2/ListFoldersRequest.php
  StorageControl/src/V2/RenameFolderRequest.php
Labels: next release

#7424 chore: add back v1beta channel for AssuredWorkloads
  AssuredWorkloads/.OwlBot.yaml
  AssuredWorkloads/metadata/V1Beta1/Assuredworkloads.php
  AssuredWorkloads/metadata/V1Beta1/AssuredworkloadsService.php
  AssuredWorkloads/src/V1beta1/AnalyzeWorkloadMoveRequest.php
  AssuredWorkloads/src/V1beta1/AnalyzeWorkloadMoveResponse.php
  AssuredWorkloads/src/V1beta1/Client/AssuredWorkloadsServiceClient.php
  AssuredWorkloads/src/V1beta1/CreateWorkloadOperationMetadata.php
  AssuredWorkloads/src/V1beta1/CreateWorkloadRequest.php
  AssuredWorkloads/src/V1beta1/DeleteWorkloadRequest.php
  AssuredWorkloads/src/V1beta1/GetWorkloadRequest.php
  AssuredWorkloads/src/V1beta1/ListWorkloadsRequest.php
  AssuredWorkloads/src/V1beta1/ListWorkloadsResponse.php
  AssuredWorkloads/src/V1beta1/RestrictAllowedResourcesRequest.php
  AssuredWorkloads/src/V1beta1/RestrictAllowedResourcesRequest/RestrictionType.php
  AssuredWorkloads/src/V1beta1/RestrictAllowedResourcesResponse.php
  AssuredWorkloads/src/V1beta1/UpdateWorkloadRequest.php
  AssuredWorkloads/src/V1beta1/Workload.php
  AssuredWorkloads/src/V1beta1/Workload/CJISSettings.php
  AssuredWorkloads/src/V1beta1/Workload/ComplianceRegime.php
  AssuredWorkloads/src/V1beta1/Workload/FedrampHighSettings.php
  AssuredWorkloads/src/V1beta1/Workload/FedrampModerateSettings.php
  AssuredWorkloads/src/V1beta1/Workload/IL4Settings.php
  AssuredWorkloads/src/V1beta1/Workload/KMSSettings.php
  AssuredWorkloads/src/V1beta1/Workload/KajEnrollmentState.php
  AssuredWorkloads/src/V1beta1/Workload/ResourceInfo.php
  AssuredWorkloads/src/V1beta1/Workload/ResourceInfo/ResourceType.php
  AssuredWorkloads/src/V1beta1/Workload/ResourceSettings.php
  AssuredWorkloads/src/V1beta1/Workload/SaaEnrollmentResponse.php
  AssuredWorkloads/src/V1beta1/Workload/SaaEnrollmentResponse/SetupError.php
  AssuredWorkloads/src/V1beta1/Workload/SaaEnrollmentResponse/SetupState.php
  AssuredWorkloads/src/V1beta1/gapic_metadata.json
  AssuredWorkloads/src/V1beta1/resources/assured_workloads_service_client_config.json
  AssuredWorkloads/src/V1beta1/resources/assured_workloads_service_descriptor_config.php
  AssuredWorkloads/src/V1beta1/resources/assured_workloads_service_rest_client_config.php
  AssuredWorkloads/tests/Unit/V1beta1/Client/AssuredWorkloadsServiceClientTest.php
Labels: next release

#7414 feat(Bigtable): add bigtable-attempt header
  Bigtable/src/Exception/BigtableDataOperationException.php
  Bigtable/src/ResumableStream.php
  Bigtable/tests/Unit/SmartRetriesTest.php
Labels: api: bigtable, next release

#7463 chore(Spanner): add test for batchwrite, address review comments
  Spanner/src/Connection/Grpc.php
  Spanner/src/Database.php
  Spanner/tests/Unit/Connection/GrpcTest.php
Labels: api: spanner

#7420 feat(Spanner): Batch Write Feature
  Spanner/src/Connection/ConnectionInterface.php
  Spanner/src/Connection/Grpc.php
  Spanner/src/Database.php
  Spanner/src/MutationGroup.php
  Spanner/src/MutationTrait.php
  Spanner/src/Operation.php
  Spanner/src/Transaction.php
  Spanner/tests/Snippet/TransactionTest.php
  Spanner/tests/System/BatchWriteTest.php
  Spanner/tests/System/PgBatchWriteTest.php
  Spanner/tests/Unit/Connection/GrpcTest.php
  Spanner/tests/Unit/DatabaseTest.php
  Spanner/tests/Unit/MutationGroupTest.php
  Spanner/tests/Unit/MutationTraitTest.php
  Spanner/tests/Unit/TransactionTest.php
Labels: api: spanner, next release
