Repository googleapis/google-cloud-php, pull requests merged in 2024-01, with the labels that each got.

#6708 feat(Spanner): Inline Begin Transaction
  Spanner/src/Database.php
  Spanner/src/Operation.php
  Spanner/src/Result.php
  Spanner/src/Transaction.php
  Spanner/src/TransactionalReadInterface.php
  Spanner/src/TransactionalReadTrait.php
  Spanner/tests/Snippet/DatabaseTest.php
  Spanner/tests/System/PgQueryTest.php
  Spanner/tests/System/PgTransactionTest.php
  Spanner/tests/System/TransactionTest.php
  Spanner/tests/Unit/DatabaseTest.php
  Spanner/tests/Unit/InstanceTest.php
  Spanner/tests/Unit/ResultTest.php
  Spanner/tests/Unit/SnapshotTest.php
  Spanner/tests/Unit/TransactionTest.php
  Spanner/tests/Unit/TransactionTypeTest.php
Labels: api: spanner

#6078 feat(Spanner): Add directed read feature
  Spanner/src/Connection/Grpc.php
  Spanner/src/Database.php
  Spanner/src/Instance.php
  Spanner/src/Operation.php
  Spanner/src/Snapshot.php
  Spanner/src/SnapshotTrait.php
  Spanner/src/SpannerClient.php
  Spanner/src/TransactionConfigurationTrait.php
  Spanner/src/TransactionalReadTrait.php
  Spanner/tests/Snippet/ArrayTypeTest.php
  Spanner/tests/Snippet/BatchDmlResultTest.php
  Spanner/tests/Snippet/SpannerClientTest.php
  Spanner/tests/Snippet/StructTypeTest.php
  Spanner/tests/Snippet/StructValueTest.php
  Spanner/tests/System/TransactionTest.php
  Spanner/tests/Unit/DatabaseTest.php
  Spanner/tests/Unit/InstanceTest.php
  Spanner/tests/Unit/SnapshotTest.php
  Spanner/tests/Unit/SpannerClientTest.php
  Spanner/tests/Unit/TransactionConfigurationTraitTest.php
  Spanner/tests/Unit/TransactionTypeTest.php
Labels: api: spanner

#6953 chore: [AnalyticsData] update owlbot to include v1alpha
  AnalyticsData/.OwlBot.yaml
Labels: next release

#6974 chore: do not export-ignore samples in umbrella package
  .gitattributes
Labels: samples

#6945 chore: export-ignore changelog
  .gitattributes
Labels: next release

#6899 chore(tests): add CI for checking lowest version of dependencies
  .github/run-package-tests.sh
  .github/workflows/tests.yaml
  BigQuery/composer.json
  Bigtable/composer.json
  Config/composer.json
  Core/composer.json
  Datastore/composer.json
  Debugger/composer.json
  ErrorReporting/composer.json
  Filestore/composer.json
  Firestore/composer.json
  Language/composer.json
  Logging/composer.json
  PubSub/composer.json
  Spanner/composer.json
  Speech/composer.json
  Storage/composer.json
  Trace/composer.json
  Translate/composer.json
  Vision/composer.json
  VmwareEngine/composer.json
  composer.json
Labels: next release
