Repository googleapis/google-cloud-php, pull requests merged in 2025-04, with the labels that each got.

#8200 docs: remove CI title from readme
  README.md
  dev/tests/fixtures/docfx/ProductNeutralGuides/getting-started.md
Labels: next release

#8205 feat(storage): add MoveObject functionality
  Storage/src/Connection/ConnectionInterface.php
  Storage/src/Connection/Rest.php
  Storage/src/Connection/ServiceDefinition/storage-v1.json
  Storage/src/StorageObject.php
  Storage/tests/System/ManageObjectsTest.php
  Storage/tests/Unit/StorageObjectTest.php
Labels: api: storage

#8230 docs: [TextToSpeech] Update speech synthesis sample code
  TextToSpeech/README.md
Labels: samples

#8243 feat: add IAM v3
  Iam/.OwlBot.yaml
  Iam/metadata/V3/OperationMetadata.php
  Iam/metadata/V3/PolicyBindingResources.php
  Iam/metadata/V3/PolicyBindingsService.php
  Iam/metadata/V3/PrincipalAccessBoundaryPoliciesService.php
  Iam/metadata/V3/PrincipalAccessBoundaryPolicyResources.php
  Iam/samples/V3/PolicyBindingsClient/create_policy_binding.php
  Iam/samples/V3/PolicyBindingsClient/delete_policy_binding.php
  Iam/samples/V3/PolicyBindingsClient/get_policy_binding.php
  Iam/samples/V3/PolicyBindingsClient/list_policy_bindings.php
  Iam/samples/V3/PolicyBindingsClient/search_target_policy_bindings.php
  Iam/samples/V3/PolicyBindingsClient/update_policy_binding.php
  Iam/samples/V3/PrincipalAccessBoundaryPoliciesClient/create_principal_access_boundary_policy.php
  Iam/samples/V3/PrincipalAccessBoundaryPoliciesClient/delete_principal_access_boundary_policy.php
  Iam/samples/V3/PrincipalAccessBoundaryPoliciesClient/get_principal_access_boundary_policy.php
  Iam/samples/V3/PrincipalAccessBoundaryPoliciesClient/list_principal_access_boundary_policies.php
  Iam/samples/V3/PrincipalAccessBoundaryPoliciesClient/search_principal_access_boundary_policy_bindings.php
  Iam/samples/V3/PrincipalAccessBoundaryPoliciesClient/update_principal_access_boundary_policy.php
  Iam/src/V3/Client/PolicyBindingsClient.php
  Iam/src/V3/Client/PrincipalAccessBoundaryPoliciesClient.php
  Iam/src/V3/CreatePolicyBindingRequest.php
  Iam/src/V3/CreatePrincipalAccessBoundaryPolicyRequest.php
  Iam/src/V3/DeletePolicyBindingRequest.php
  Iam/src/V3/DeletePrincipalAccessBoundaryPolicyRequest.php
  Iam/src/V3/GetPolicyBindingRequest.php
  Iam/src/V3/GetPrincipalAccessBoundaryPolicyRequest.php
  Iam/src/V3/ListPolicyBindingsRequest.php
  Iam/src/V3/ListPolicyBindingsResponse.php
  Iam/src/V3/ListPrincipalAccessBoundaryPoliciesRequest.php
  Iam/src/V3/ListPrincipalAccessBoundaryPoliciesResponse.php
  Iam/src/V3/OperationMetadata.php
  Iam/src/V3/PolicyBinding.php
  Iam/src/V3/PolicyBinding/PolicyKind.php
  Iam/src/V3/PolicyBinding/Target.php
  Iam/src/V3/PrincipalAccessBoundaryPolicy.php
  Iam/src/V3/PrincipalAccessBoundaryPolicyDetails.php
  Iam/src/V3/PrincipalAccessBoundaryPolicyRule.php
  Iam/src/V3/PrincipalAccessBoundaryPolicyRule/Effect.php
  Iam/src/V3/SearchPrincipalAccessBoundaryPolicyBindingsRequest.php
  Iam/src/V3/SearchPrincipalAccessBoundaryPolicyBindingsResponse.php
  Iam/src/V3/SearchTargetPolicyBindingsRequest.php
  Iam/src/V3/SearchTargetPolicyBindingsResponse.php
  Iam/src/V3/UpdatePolicyBindingRequest.php
  Iam/src/V3/UpdatePrincipalAccessBoundaryPolicyRequest.php
  Iam/src/V3/gapic_metadata.json
  Iam/src/V3/resources/policy_bindings_client_config.json
  Iam/src/V3/resources/policy_bindings_descriptor_config.php
  Iam/src/V3/resources/policy_bindings_rest_client_config.php
  Iam/src/V3/resources/principal_access_boundary_policies_client_config.json
  Iam/src/V3/resources/principal_access_boundary_policies_descriptor_config.php
  Iam/src/V3/resources/principal_access_boundary_policies_rest_client_config.php
  Iam/tests/Unit/V3/Client/PolicyBindingsClientTest.php
  Iam/tests/Unit/V3/Client/PrincipalAccessBoundaryPoliciesClientTest.php
Labels: next release

#8242 feat: introduce DeviceStreaming
  .repo-metadata-full.json
  DeviceStreaming/.OwlBot.yaml
  DeviceStreaming/.gitattributes
  DeviceStreaming/.github/pull_request_template.md
  DeviceStreaming/CONTRIBUTING.md
  DeviceStreaming/LICENSE
  DeviceStreaming/README.md
  DeviceStreaming/VERSION
  DeviceStreaming/composer.json
  DeviceStreaming/metadata/V1/AdbService.php
  DeviceStreaming/metadata/V1/Service.php
  DeviceStreaming/owlbot.py
  DeviceStreaming/phpunit.xml.dist
  DeviceStreaming/samples/V1/DirectAccessServiceClient/adb_connect.php
  DeviceStreaming/samples/V1/DirectAccessServiceClient/cancel_device_session.php
  DeviceStreaming/samples/V1/DirectAccessServiceClient/create_device_session.php
  DeviceStreaming/samples/V1/DirectAccessServiceClient/get_device_session.php
  DeviceStreaming/samples/V1/DirectAccessServiceClient/list_device_sessions.php
  DeviceStreaming/samples/V1/DirectAccessServiceClient/update_device_session.php
  DeviceStreaming/src/V1/AdbMessage.php
  DeviceStreaming/src/V1/AndroidDevice.php
  DeviceStreaming/src/V1/CancelDeviceSessionRequest.php
  DeviceStreaming/src/V1/Client/DirectAccessServiceClient.php
  DeviceStreaming/src/V1/Close.php
  DeviceStreaming/src/V1/CreateDeviceSessionRequest.php
  DeviceStreaming/src/V1/DeviceMessage.php
  DeviceStreaming/src/V1/DeviceSession.php
  DeviceStreaming/src/V1/DeviceSession/SessionState.php
  DeviceStreaming/src/V1/DeviceSession/SessionStateEvent.php
  DeviceStreaming/src/V1/Fail.php
  DeviceStreaming/src/V1/GetDeviceSessionRequest.php
  DeviceStreaming/src/V1/ListDeviceSessionsRequest.php
  DeviceStreaming/src/V1/ListDeviceSessionsResponse.php
  DeviceStreaming/src/V1/Okay.php
  DeviceStreaming/src/V1/Open.php
  DeviceStreaming/src/V1/StatusUpdate.php
  DeviceStreaming/src/V1/StatusUpdate/DeviceState.php
  DeviceStreaming/src/V1/StreamData.php
  DeviceStreaming/src/V1/StreamStatus.php
  DeviceStreaming/src/V1/UpdateDeviceSessionRequest.php
  DeviceStreaming/src/V1/gapic_metadata.json
  DeviceStreaming/src/V1/resources/direct_access_service_client_config.json
  DeviceStreaming/src/V1/resources/direct_access_service_descriptor_config.php
  DeviceStreaming/src/V1/resources/direct_access_service_rest_client_config.php
  DeviceStreaming/tests/Unit/V1/Client/DirectAccessServiceClientTest.php
  composer.json
Labels: next release

#8182 feat: Add an Interval type to Spanner
  Spanner/src/Database.php
  Spanner/src/Interval.php
  Spanner/src/IntervalParsingState.php
  Spanner/src/ValueMapper.php
  Spanner/tests/System/PgQueryTest.php
  Spanner/tests/System/QueryTest.php
  Spanner/tests/System/WriteTest.php
  Spanner/tests/Unit/IntervalTest.php
  Spanner/tests/Unit/ValueMapperTest.php
Labels: next release

#8261 fix(cs): remove bleeding edge from phpstan, cleanup config
  phpstan.neon.dist
Labels: next release
