Repository googleapis/google-cloud-php, pull requests merged in 2025-01, with the labels that each got.

#7966 Feat(Storage): add ability to configure and utilize soft-delete and restore buckets
  Storage/src/Bucket.php
  Storage/src/Connection/ConnectionInterface.php
  Storage/src/Connection/Rest.php
  Storage/src/Connection/ServiceDefinition/storage-v1.json
  Storage/src/StorageClient.php
  Storage/tests/System/ManageBucketsTest.php
  Storage/tests/Unit/StorageClientTest.php
Labels: api: storage

#7963 fix: [Firestore] deprecation from autoloading deprecated class
  Firestore/src/DocumentReference.php
  Firestore/src/FirestoreClient.php
Labels: next release

#7949 chore!: migrate LifeSciences to new surface
  LifeSciences/owlbot.py
  LifeSciences/src/V2beta/Accelerator.php
  LifeSciences/src/V2beta/Action.php
  LifeSciences/src/V2beta/Client/WorkflowsServiceV2BetaClient.php
  LifeSciences/src/V2beta/ContainerKilledEvent.php
  LifeSciences/src/V2beta/ContainerStartedEvent.php
  LifeSciences/src/V2beta/ContainerStoppedEvent.php
  LifeSciences/src/V2beta/DelayedEvent.php
  LifeSciences/src/V2beta/Disk.php
  LifeSciences/src/V2beta/Event.php
  LifeSciences/src/V2beta/ExistingDisk.php
  LifeSciences/src/V2beta/FailedEvent.php
  LifeSciences/src/V2beta/Gapic/WorkflowsServiceV2BetaGapicClient.php
  LifeSciences/src/V2beta/Metadata.php
  LifeSciences/src/V2beta/Mount.php
  LifeSciences/src/V2beta/NFSMount.php
  LifeSciences/src/V2beta/Network.php
  LifeSciences/src/V2beta/PersistentDisk.php
  LifeSciences/src/V2beta/Pipeline.php
  LifeSciences/src/V2beta/PullStartedEvent.php
  LifeSciences/src/V2beta/PullStoppedEvent.php
  LifeSciences/src/V2beta/Resources.php
  LifeSciences/src/V2beta/RunPipelineRequest.php
  LifeSciences/src/V2beta/Secret.php
  LifeSciences/src/V2beta/ServiceAccount.php
  LifeSciences/src/V2beta/UnexpectedExitStatusEvent.php
  LifeSciences/src/V2beta/VirtualMachine.php
  LifeSciences/src/V2beta/Volume.php
  LifeSciences/src/V2beta/WorkerAssignedEvent.php
  LifeSciences/src/V2beta/WorkerReleasedEvent.php
  LifeSciences/src/V2beta/WorkflowsServiceV2BetaClient.php
  LifeSciences/src/V2beta/WorkflowsServiceV2BetaGrpcClient.php
  LifeSciences/tests/Unit/V2beta/Client/WorkflowsServiceV2BetaClientTest.php
  LifeSciences/tests/Unit/V2beta/WorkflowsServiceV2BetaClientTest.php
Labels: next release

#7947 chore!: migrate PrivateCatalog to new surface
  PrivateCatalog/owlbot.py
  PrivateCatalog/src/V1beta1/AssetReference.php
  PrivateCatalog/src/V1beta1/AssetReference/AssetValidationState.php
  PrivateCatalog/src/V1beta1/AssetReference_AssetValidationState.php
  PrivateCatalog/src/V1beta1/Catalog.php
  PrivateCatalog/src/V1beta1/Client/PrivateCatalogClient.php
  PrivateCatalog/src/V1beta1/Gapic/PrivateCatalogGapicClient.php
  PrivateCatalog/src/V1beta1/GcsSource.php
  PrivateCatalog/src/V1beta1/GitSource.php
  PrivateCatalog/src/V1beta1/Inputs.php
  PrivateCatalog/src/V1beta1/PrivateCatalogClient.php
  PrivateCatalog/src/V1beta1/PrivateCatalogGrpcClient.php
  PrivateCatalog/src/V1beta1/Product.php
  PrivateCatalog/src/V1beta1/SearchCatalogsRequest.php
  PrivateCatalog/src/V1beta1/SearchCatalogsResponse.php
  PrivateCatalog/src/V1beta1/SearchProductsRequest.php
  PrivateCatalog/src/V1beta1/SearchProductsResponse.php
  PrivateCatalog/src/V1beta1/SearchVersionsRequest.php
  PrivateCatalog/src/V1beta1/SearchVersionsResponse.php
  PrivateCatalog/src/V1beta1/Version.php
  PrivateCatalog/tests/Unit/V1beta1/Client/PrivateCatalogClientTest.php
  PrivateCatalog/tests/Unit/V1beta1/PrivateCatalogClientTest.php
Labels: next release

#7958 feat: Introduce ParameterManager
  .github/run-package-tests.sh
  .repo-metadata-full.json
  ParameterManager/.OwlBot.yaml
  ParameterManager/.gitattributes
  ParameterManager/.github/pull_request_template.md
  ParameterManager/CONTRIBUTING.md
  ParameterManager/LICENSE
  ParameterManager/README.md
  ParameterManager/VERSION
  ParameterManager/composer.json
  ParameterManager/metadata/V1/Service.php
  ParameterManager/owlbot.py
  ParameterManager/phpunit.xml.dist
  ParameterManager/samples/V1/ParameterManagerClient/create_parameter.php
  ParameterManager/samples/V1/ParameterManagerClient/create_parameter_version.php
  ParameterManager/samples/V1/ParameterManagerClient/delete_parameter.php
  ParameterManager/samples/V1/ParameterManagerClient/delete_parameter_version.php
  ParameterManager/samples/V1/ParameterManagerClient/get_location.php
  ParameterManager/samples/V1/ParameterManagerClient/get_parameter.php
  ParameterManager/samples/V1/ParameterManagerClient/get_parameter_version.php
  ParameterManager/samples/V1/ParameterManagerClient/list_locations.php
  ParameterManager/samples/V1/ParameterManagerClient/list_parameter_versions.php
  ParameterManager/samples/V1/ParameterManagerClient/list_parameters.php
  ParameterManager/samples/V1/ParameterManagerClient/render_parameter_version.php
  ParameterManager/samples/V1/ParameterManagerClient/update_parameter.php
  ParameterManager/samples/V1/ParameterManagerClient/update_parameter_version.php
  ParameterManager/src/V1/Client/ParameterManagerClient.php
  ParameterManager/src/V1/CreateParameterRequest.php
  ParameterManager/src/V1/CreateParameterVersionRequest.php
  ParameterManager/src/V1/DeleteParameterRequest.php
  ParameterManager/src/V1/DeleteParameterVersionRequest.php
  ParameterManager/src/V1/GetParameterRequest.php
  ParameterManager/src/V1/GetParameterVersionRequest.php
  ParameterManager/src/V1/ListParameterVersionsRequest.php
  ParameterManager/src/V1/ListParameterVersionsResponse.php
  ParameterManager/src/V1/ListParametersRequest.php
  ParameterManager/src/V1/ListParametersResponse.php
  ParameterManager/src/V1/Parameter.php
  ParameterManager/src/V1/ParameterFormat.php
  ParameterManager/src/V1/ParameterVersion.php
  ParameterManager/src/V1/ParameterVersionPayload.php
  ParameterManager/src/V1/RenderParameterVersionRequest.php
  ParameterManager/src/V1/RenderParameterVersionResponse.php
  ParameterManager/src/V1/UpdateParameterRequest.php
  ParameterManager/src/V1/UpdateParameterVersionRequest.php
  ParameterManager/src/V1/View.php
  ParameterManager/src/V1/gapic_metadata.json
  ParameterManager/src/V1/resources/parameter_manager_client_config.json
  ParameterManager/src/V1/resources/parameter_manager_descriptor_config.php
  ParameterManager/src/V1/resources/parameter_manager_rest_client_config.php
  ParameterManager/tests/Unit/V1/Client/ParameterManagerClientTest.php
  composer.json
Labels: next release

#7942 chore!: migrate BigQueryDataExchange to new surface
  BigQueryDataExchange/.OwlBot.yaml
  BigQueryDataExchange/metadata/Common/Common.php
  BigQueryDataExchange/owlbot.py
  BigQueryDataExchange/src/Common/Category.php
  BigQueryDataExchange/src/V1beta1/AnalyticsHubServiceClient.php
  BigQueryDataExchange/src/V1beta1/AnalyticsHubServiceGrpcClient.php
  BigQueryDataExchange/src/V1beta1/Client/AnalyticsHubServiceClient.php
  BigQueryDataExchange/src/V1beta1/CreateDataExchangeRequest.php
  BigQueryDataExchange/src/V1beta1/CreateListingRequest.php
  BigQueryDataExchange/src/V1beta1/DataExchange.php
  BigQueryDataExchange/src/V1beta1/DataProvider.php
  BigQueryDataExchange/src/V1beta1/DeleteDataExchangeRequest.php
  BigQueryDataExchange/src/V1beta1/DeleteListingRequest.php
  BigQueryDataExchange/src/V1beta1/DestinationDataset.php
  BigQueryDataExchange/src/V1beta1/DestinationDatasetReference.php
  BigQueryDataExchange/src/V1beta1/Gapic/AnalyticsHubServiceGapicClient.php
  BigQueryDataExchange/src/V1beta1/GetDataExchangeRequest.php
  BigQueryDataExchange/src/V1beta1/GetListingRequest.php
  BigQueryDataExchange/src/V1beta1/ListDataExchangesRequest.php
  BigQueryDataExchange/src/V1beta1/ListDataExchangesResponse.php
  BigQueryDataExchange/src/V1beta1/ListListingsRequest.php
  BigQueryDataExchange/src/V1beta1/ListListingsResponse.php
  BigQueryDataExchange/src/V1beta1/ListOrgDataExchangesRequest.php
  BigQueryDataExchange/src/V1beta1/ListOrgDataExchangesResponse.php
  BigQueryDataExchange/src/V1beta1/Listing.php
  BigQueryDataExchange/src/V1beta1/Listing/BigQueryDatasetSource.php
  BigQueryDataExchange/src/V1beta1/Listing/Category.php
  BigQueryDataExchange/src/V1beta1/Listing/State.php
  BigQueryDataExchange/src/V1beta1/Publisher.php
  BigQueryDataExchange/src/V1beta1/SubscribeListingRequest.php
  BigQueryDataExchange/src/V1beta1/UpdateDataExchangeRequest.php
  BigQueryDataExchange/src/V1beta1/UpdateListingRequest.php
  BigQueryDataExchange/tests/Unit/V1beta1/AnalyticsHubServiceClientTest.php
  BigQueryDataExchange/tests/Unit/V1beta1/Client/AnalyticsHubServiceClientTest.php
Labels: next release

#7943 chore!: promote GkeConnectGateway to V1
  .repo-metadata-full.json
  GkeConnectGateway/.OwlBot.yaml
  GkeConnectGateway/README.md
  GkeConnectGateway/metadata/V1Beta1/Gateway.php
  GkeConnectGateway/owlbot.py
  GkeConnectGateway/src/V1/Client/GatewayControlClient.php
  GkeConnectGateway/src/V1/GenerateCredentialsRequest.php
  GkeConnectGateway/src/V1/GenerateCredentialsRequest/OperatingSystem.php
  GkeConnectGateway/src/V1/GenerateCredentialsResponse.php
  GkeConnectGateway/src/V1beta1/Client/GatewayControlClient.php
  GkeConnectGateway/src/V1beta1/Client/GatewayServiceClient.php
  GkeConnectGateway/src/V1beta1/Enums/GenerateCredentialsRequest/OperatingSystem.php
  GkeConnectGateway/src/V1beta1/Gapic/GatewayControlGapicClient.php
  GkeConnectGateway/src/V1beta1/Gapic/GatewayServiceGapicClient.php
  GkeConnectGateway/src/V1beta1/GatewayControlClient.php
  GkeConnectGateway/src/V1beta1/GatewayServiceClient.php
  GkeConnectGateway/src/V1beta1/GatewayServiceGrpcClient.php
  GkeConnectGateway/src/V1beta1/GenerateCredentialsRequest.php
  GkeConnectGateway/src/V1beta1/GenerateCredentialsRequest/OperatingSystem.php
  GkeConnectGateway/src/V1beta1/GenerateCredentialsResponse.php
  GkeConnectGateway/src/V1beta1/resources/gateway_service_client_config.json
  GkeConnectGateway/src/V1beta1/resources/gateway_service_descriptor_config.php
  GkeConnectGateway/src/V1beta1/resources/gateway_service_rest_client_config.php
  GkeConnectGateway/tests/Unit/V1/Client/GatewayControlClientTest.php
  GkeConnectGateway/tests/Unit/V1beta1/Client/GatewayControlClientTest.php
  GkeConnectGateway/tests/Unit/V1beta1/Client/GatewayServiceClientTest.php
  GkeConnectGateway/tests/Unit/V1beta1/GatewayControlClientTest.php
  GkeConnectGateway/tests/Unit/V1beta1/GatewayServiceClientTest.php
Labels: next release

#7895 chore!: promote TextToSpeech to v2
  TextToSpeech/metadata/V1/CloudTts.php
  TextToSpeech/owlbot.py
  TextToSpeech/src/V1/AdvancedVoiceOptions.php
  TextToSpeech/src/V1/AudioConfig.php
  TextToSpeech/src/V1/AudioEncoding.php
  TextToSpeech/src/V1/Client/TextToSpeechClient.php
  TextToSpeech/src/V1/Client/TextToSpeechLongAudioSynthesizeClient.php
  TextToSpeech/src/V1/CustomPronunciationParams.php
  TextToSpeech/src/V1/CustomPronunciationParams/PhoneticEncoding.php
  TextToSpeech/src/V1/CustomVoiceParams.php
  TextToSpeech/src/V1/CustomVoiceParams/ReportedUsage.php
  TextToSpeech/src/V1/CustomVoiceParams_ReportedUsage.php
  TextToSpeech/src/V1/Gapic/TextToSpeechGapicClient.php
  TextToSpeech/src/V1/Gapic/TextToSpeechLongAudioSynthesizeGapicClient.php
  TextToSpeech/src/V1/ListVoicesRequest.php
  TextToSpeech/src/V1/MultiSpeakerMarkup/Turn.php
  TextToSpeech/src/V1/README.md
  TextToSpeech/src/V1/StreamingAudioConfig.php
  TextToSpeech/src/V1/StreamingSynthesizeConfig.php
  TextToSpeech/src/V1/StreamingSynthesizeResponse.php
  TextToSpeech/src/V1/SynthesisInput.php
  TextToSpeech/src/V1/SynthesizeLongAudioMetadata.php
  TextToSpeech/src/V1/SynthesizeLongAudioRequest.php
  TextToSpeech/src/V1/SynthesizeSpeechRequest.php
  TextToSpeech/src/V1/SynthesizeSpeechResponse.php
  TextToSpeech/src/V1/TextToSpeechClient.php
  TextToSpeech/src/V1/TextToSpeechGrpcClient.php
  TextToSpeech/src/V1/TextToSpeechLongAudioSynthesizeClient.php
  TextToSpeech/src/V1/TextToSpeechLongAudioSynthesizeGrpcClient.php
  TextToSpeech/src/V1/Voice.php
  TextToSpeech/src/V1/VoiceCloneParams.php
  TextToSpeech/src/V1/VoiceSelectionParams.php
  TextToSpeech/src/V1/resources/text_to_speech_descriptor_config.php
  TextToSpeech/src/V1/resources/text_to_speech_long_audio_synthesize_descriptor_config.php
  TextToSpeech/src/V1/resources/text_to_speech_long_audio_synthesize_rest_client_config.php
  TextToSpeech/src/V1/resources/text_to_speech_rest_client_config.php
  TextToSpeech/tests/System/V1/TextToSpeechSmokeTest.php
  TextToSpeech/tests/System/bootstrap.php
  TextToSpeech/tests/Unit/V1/Client/TextToSpeechClientTest.php
  TextToSpeech/tests/Unit/V1/Client/TextToSpeechLongAudioSynthesizeClientTest.php
  TextToSpeech/tests/Unit/V1/TextToSpeechClientTest.php
  TextToSpeech/tests/Unit/V1/TextToSpeechLongAudioSynthesizeClientTest.php
Labels: next release

#8020 fix(Bigtable): ensure appProfileId is sent in requests when set in options
  Bigtable/src/Table.php
  Bigtable/tests/Unit/TableTest.php
Labels: api: bigtable, next release

#8019 fix: add SERVICE_NAME constant to bigtable client
  Bigtable/src/BigtableClient.php
Labels: next release

#8012 docs: update analytics samples in README
  AnalyticsAdmin/README.md
  AnalyticsData/README.md
Labels: samples, next release
